### ISSUE TITLE
Rockbiter Weapon (Shaman Spell)

### ISSUE THREAD

**Issue by scotty0100** [classicdb/database#104]
This spell doesn't appear to raise attack power like it says, and it doesn't seem to give increased threat either.

I used a threat meter to test the latter so I don't know if it's accurate or not as I'm guessing it's not the true server side value but can't find a command to check threat.

**Comment by cala** [comment]
Thank you for this report. I'm not familiar with the shaman class, thus I don't know exactly how this spell should work. I remember seeing an issue regarding this spell in old mangos forum and a fix core side was proposed. However, I don't know if it was a good one or an ugly hack.
I will also look at it from database side.

**Comment by cala** [comment]
Could test the last build of CMaNGOS Classic, please ? It should fix this. https://github.com/cmangos/mangos-classic/commit/92fca21b0c76aceebbf4b8da71d32b3236e481ef

**Comment by cala** [comment]
@scotty0100 do you have some feedback in wowascension regarding this issue?

**Comment by PatSmuk** [comment]
Should be fixed and ultimately was not a DB issue. Closing.
