### ISSUE TITLE
Quest: Plagued Lands (2118)

### ISSUE THREAD

**Issue by scotty0100** [classicdb/database#106]
Quest objective: Place a trap and lay it on the ground.  Any Rabid Thistle Bear that crosses the light shall become docile for a short while, you must lead it back to Tharnarium.

What happens:  Bear does not become docile after walking over the trap and stays hostile.

Also if you fail to capture a bear and lose the trap you are supposed to be able to request another one from Tharnarium.  You have to abandon the quest and and reaccept to get it again, is that the only way it's possible?

Links: 
Quest of trap in action: http://www.youtube.com/watch?v=o2yV7Icy_Ao
WoWHead: http://www.wowhead.com/quest=2118/plagued-lands

**Comment by Schmoozerd** [comment]
https://github.com/scriptdev2/scriptdev2/pull/56

**Comment by cala** [comment]
Thank you for this report. Schmoozerd is right this issue belongs to SD2 where it is currently being handled. I close the issue here then. :)
