### ISSUE TITLE
Blasted lands - servants of Razelikh; Grol; Allistarj

### ISSUE THREAD

**Issue by stan84** [classicdb/database#107]
in Blasted lands - servants of Razelikh; Grol; Allistarj suld not be able to kill until player has quest for them and propper item in iventory. At low health they should become immune on attacks, ( something like banish phase). The wiki says about that:

The cannot be killed by normal means, to kill them you'll have to damage them down to about 5% of their hp, and then click the crystal near them (this can only be done if you have accetped the quest -  [57] The Stones That Bind Us).

**Comment by cala** [comment]
Thank you for spotting this one. I'm not sure it can be done via DB as this is typically an AI Event issue and X-Savior is more familiar with it than I am. However, the link with the quest and the gameobject makes me think also of SD2. I will look into it. :)

**Comment by cala** [comment]
Fixed by https://github.com/cmangos/classic-db/commit/e2e1fb24a953c04f2cfda8ea9fc32da49569bf86 and https://github.com/cmangos/classic-db/commit/f0ae5145811c3c555436d24be90556ab424361c9 and https://github.com/cmangos/classic-db/commit/adcf18487e207e777cd8dcffdc989316732e5093
