### ISSUE TITLE
Blasted Lands - servants of ....

### ISSUE THREAD

**Issue by stan84** [classicdb/database#108]
Servants of Razelikh; Servants of Allistarj , Servant of Sevine; Servant of Grol.

all above servants should not be able to kill without quest, at low hp they should be immune to attack.

Wiki expains:
They cannot be killed by normal means, to kill them you'll have to damage them down to about 5% of their hp, and then click the crystal near them (this can only be done if you have accetped the quest - Neutral 15 [57] The Stones That Bind Us).

**Comment by cala** [comment]
Related to issue #107 I close this one, all servants will be fixed together.
