### ISSUE TITLE
Quest: Captain's Chest Bug with Fix

### ISSUE THREAD

**Issue by scotty0100** [classicdb/database#109]
Area: STV - Booty Bay

NPC Captain Hecklebury Smotts offers you this quest twice, it can be done twice as I tested it.

The fix:

UPDATE `quest_template` SET `RequiredRaces`=77 WHERE  `entry`=614; -- Alliance Captain's Chest

UPDATE `quest_template` SET `RequiredRaces`=178 WHERE  `entry`=8551; -- Horde Captain's Chest

DELETE FROM `gossip_menu_option` WHERE  `menu_id`=3185 AND `id`=0; -- Fixes Lelanai's Gossip Menu

**Comment by cala** [comment]
Thank you for this report.
