### ISSUE TITLE
3 Fixes (Battlemaster Gossip Text, Strahad Farsan & Stormwind Guard Direction)

### ISSUE THREAD

**Issue by scotty0100** [classicdb/database#110]
Battlemaster Gossip Text: The orgrimmar battlemaster had "GOSSIP_OPTION_BATTLEFIELD" as his Gossip.

Strahad Farsan: This NPC was only appearing to GMs, if you toggle .gm on and .gm off he would disappear for normal players.

Stormwind Guard Directions: Stormwind Guards when asked about the Cooking Trainer,  direct the player to the Enchanting Trainer.

The fixes:

UPDATE `creature_template` SET `npcflag`=3 WHERE  `entry`=6251; -- Strahad Farsan

UPDATE `gossip_menu_option` SET `action_poi_id`=42 WHERE  `menu_id`=421 AND `id`=2; -- SW guard cooking trainer directions

UPDATE gossip_menu_option SET option_text= 'I wish to join the battle!' WHERE option_text= 'GOSSIP_OPTION_BATTLEFIELD'; -- Battlemaster Menu Fix

**Comment by cala** [comment]
Thank you, I've noticed this NPC being visible only to GM, like one of the Horde cooking trainers but I did not took the time to fix them.
Thanks for the two other fixes also.
