### ISSUE TITLE
Crumpled/Ripped/Torn notes

### ISSUE THREAD

**Issue by scotty0100** [classicdb/database#111]
These items are dropping from raptors in Arathi Highlands

How to replicate the bug: Kill Raptors in Arathi Highlands
What happens: They drop items that should be in bottles on the STV beach where the bloodsail are.

**Comment by cala** [comment]
Thank you for this report. This is not the first issue involving these items so they are probably wrongly scattered in other loot tables as well. I will look at it.

**Comment by cala** [comment]
Reference to issue #70 : note check that loot table were not inverted.

**Comment by cala** [comment]
Closed by https://github.com/classicdb/database/commit/0af5dcb111f43cd6e8bec85c454af3677bc049be
