### ISSUE TITLE
Darnall Vendor List || Defenders of Darrowshire Fix || Pet Trainer Gossip Menu

### ISSUE THREAD

**Issue by scotty0100** [classicdb/database#112]
Darnall Vendor List: In classic he had Runecloth patterns on him

Defender of Darrowshire Fix: It's not 100% Blizzlike but a makeshift workaround for now to make the quest completable. Hate Shriekers and Gibbering Ghouls will spawn the spirits now.

Pet Trainer Gossip fix: What happens at the moment: http://i.imgur.com/Y65P2Mp.png
What should happen: http://i.imgur.com/GstgiX0.png

Extra Information: You can still train pet spells, but you have to click right in the highlighted part."

INSERT INTO `dbscripts_on_creature_death` (`id`, `delay`, `command`, `datalong`, `datalong2`, `buddy_entry`, `search_radius`, `data_flags`, `dataint`, `dataint2`, `dataint3`, `dataint4`, `x`, `y`, `z`, `o`, `comments`) VALUES 
(8541, 0, 10, 11064, 5000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Hate Shrieker spawn Darrowshire Spirit'),
(8531, 0, 10, 11064, 5000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Gibbering Ghoul spawn Darrowshire Spirit');

INSERT INTO `npc_vendor` (`entry`, `item`, `maxcount`, `incrtime`) VALUES 
(7940, 14472, 1, 1200), -- adds Pattern: Runecloth Cloak to Darnalls item list
(7940, 14469, 1, 1200), -- Pattern: Runecloth Robe
(7940, 14488, 1, 1200); -- Pattern: Runecloth Boots

DELETE FROM `gossip_menu_option` WHERE  `menu_id`=4783; -- Fixes Pet Trainer Gossip Menu
INSERT INTO `gossip_menu_option` (`menu_id`, `id`, `option_icon`, `option_text`, `option_id`, `npc_option_npcflag`, `action_menu_id`, `action_poi_id`, `action_script_id`, `box_coded`, `box_money`, `box_text`, `condition_id`) VALUES 
(4783, 1, 3, 'How do I train my pet?', 5, 16, 0, 0, 0, 0, 0, NULL, 0),
(4783, 2, 0, 'I wish to untrain my pet.', 17, 16, 0, 0, 0, 0, 0, NULL, 0);

**Comment by cala** [comment]
Once again, thank you for your contribution. :+1: 

I had the [pet trainer gossip menu on my to do list](http://cmangos.net/thread-297.html) for a while and it is nice to see something.

The Darnall fix is ok. Thank you.

Can you explain why your Darrowshire fix is not "blizzlike", please?

**Comment by cala** [comment]
Some corrections regarding the script for spawning Darrowshire Spirits:
- according to [this old quest description](http://www.wowwiki.com/Quest:Defenders_of_Darrowshire?oldid=264870), the Hate Shrieker does not spawn the spirits. However, Cannibal Ghouls and Diseased Flayers do spawn them.
- the spirits are spawned for 5 seconds in your script but I remember them staying more longer than that and I suggest to increase this value to 20 seconds (I did not manage to find the exact value).
- I still do not see how this is not "blizzlike". If you are referring to the fact that the spirits will spawn every time when one of the related creature is killed, even if the killer do not have the quest, it was like that on retail. In fact, even NPCs could spawn the spirits when killing the ghouls/flayers. So `dbscripts_on_creature_death` seems a really good choice.

Does that sounds good to you?

**Comment by scotty0100** [comment]
Just saw this, yeah I meant about it spawning every time. So I guess it works out OK!

But yeah, 20 seconds sounds more reasonable.

**Comment by cala** [comment]
When testing this fix yesterday, I found out that the spirit spawning is already handled by ACID and that the quest is also completable. Thus, applying the fix we discussed would result in the spirits spawning twice.
Could you please confirm the spirits do not spawn when killing one of the three creatures above (entries 8530, 8531, 8532) when using Classic DB realease 1.2.0?

**Comment by scotty0100** [comment]
I created a second server with completely fresh db/code, acid & sd2 and they do spawn the spirits. With my current server they don't, a quick .server info on my main server shows that ACID is at 1.0.2 (but I generally apply the updates manually - I'm guessing I've missed one?)

**Comment by cala** [comment]
Current version of ACID is 1.0.3 and you can apply it safely. This is also the version that comes with the last release of Classic DB. :)

**Comment by cala** [comment]
Closed by https://github.com/classicdb/database/commit/f66b8587ea3de5e4d97300b184c0c8a6c06b8e44 and https://github.com/classicdb/database/commit/1444e3a344c3475278f15aa24a780d8cd6c20035 .
