### ISSUE TITLE
Pyrewood village residents not changing into worgens at night.

### ISSUE THREAD

**Issue by stan84** [classicdb/database#114]
Pyrewood village residents not changing into worgens at nigt. they should be at worgen form since 21:00 to 5:00. 

Like all residents of Pyrewood Village, changes into a Worgen at night and are affiliated with Stormwind during the daytime to make unattackable by Alliance players. 

could be easy done via game event, daily repeating. 
 I. pyrewood village - day; all human form , with friendly to alliance faction; 5:00 -> 21:00
 II. pyrewood village - worgen night; all worgen form, hostile to players. 21:00 -> 5:00

example for checking, it could be something like that: http://pastebin.com/k18DSJFQ

**Comment by cala** [comment]
Thank you for this report. I was indeed wondering if this feature was working or not and never took the time to check it.

Yes, a combination of event, and game event creature should do the trick, thank you for this suggestion.

**Comment by cala** [comment]
Fixed and in testing phase. Should be pushed in next updates batch push.
