### ISSUE TITLE
Missing Dark Iron Ambassador, rare elite in Gnomeregan

### ISSUE THREAD

**Issue by Neotmiren** [classicdb/database#125]
INSERT IGNORE INTO creature SET guid=590015, id=6228,
 map=90, position_x=-634.037, position_y=693.459, position_z=-327.057, orientation=2.9771,
 spawntimesecs=21600, spawndist=10, curhealth=4924, curmana=0, MovementType=1;

He even summons Fire Elementals when engaged in combat.

**Comment by cala** [comment]
Thanks for this report. Actually, the MovementType should be set to 2 as this NPC has waypoint movement (that I will add along your fix). It also seems that this creature should have about 1500 mana which are missing from its template.

The summons should already be handled by ACID.

**Comment by Neotmiren** [comment]
Do you create waypoints for Dark Iron Ambassador by yourself (he patrols the middle tunnel?) or they are already implemented in other DBs?

**Comment by cala** [comment]
Waypoints for Dark Iron Ambassador are already in YTDB, so they are easy to add in this case.
But adding waypoints manually is also an option when they are documented (maps, sniffs, videos). :)
