### ISSUE TITLE
Loot Fix for for Terrowulf Packlord, rare creature in Ashenvale

### ISSUE THREAD

**Issue by Neotmiren** [classicdb/database#127]
http://www.wowwiki.com/Terrowulf_Packlord?oldid=458508
[Ruffled Chaplet]
[Wolfpack Medallion]

INSERT IGNORE INTO creature_loot_template SET entry=3792, item=5753, ChanceOrQuestChance=40, groupid=2, mincountOrRef=1, maxcount=1, condition_id=0;
INSERT IGNORE INTO creature_loot_template SET entry=3792, item=5754, ChanceOrQuestChance=40, groupid=2, mincountOrRef=1, maxcount=1, condition_id=0;
DELETE FROM reference_loot_template WHERE item IN (5753, 5754);

**Comment by cala** [comment]
Thank you for all these reports. I have already reviewed some of them this WE and they will be added in the next batch of updates.
