### ISSUE TITLE
Class Trainers without gossip_menu_id. Rogue quest item via trainer's gossip option

### ISSUE THREAD

**Issue by Neotmiren** [classicdb/database#130]
The below SQL code, when invoked from HeidiSQL or the like, shows set of selected creatures (must be not too large set, or DB request will take forever) along with their respective gossip options and gossip texts.

Comparision between YTDB and ClassicDB reveals that virtually all Rogue Trainers (except unused creature templates) have gossips in YTDB. But there are about dozen Rogue Trainers without gossips in ClassicDB (Ian Strom in Booty Bay for example). The situation with other Class Trainers seems to be similar, but gossip_menu_id != 0 for all Rogue Trainers are more important because any Rogue trainer should be able to give special item that starts quest

http://www.wowwiki.com/Elegant_Letter?oldid=1514065
- after level 24 is reached by a Rogue. This letter should be obtained via gossip option, probably...

SELECT entry,name,subname,minlevel,npcflag,trainer_type,trainer_spell,trainer_class,trainer_race,gossip_menu_id,
 (SELECT group_concat(option_text separator ' \n ') FROM gossip_menu_option WHERE menu_id IN (creature_template.gossip_menu_id)) AS gossip_option_text,
 (SELECT group_concat(text_id separator ',') FROM gossip_menu WHERE entry IN (creature_template.gossip_menu_id)) AS text_id,
 (SELECT group_concat(text0_0 separator ' \n ') FROM npc_text WHERE id IN
   (SELECT text_id FROM gossip_menu WHERE entry IN (creature_template.gossip_menu_id))
 ) AS text0_0,
 (SELECT group_concat(text0_1 separator ' \n ') FROM npc_text WHERE id IN
   (SELECT text_id FROM gossip_menu WHERE entry IN (creature_template.gossip_menu_id))
 ) AS text0_1,
 (SELECT group_concat(text1_0 separator ' \n ') FROM npc_text WHERE id IN
   (SELECT text_id FROM gossip_menu WHERE entry IN (creature_template.gossip_menu_id))
 ) AS text1_0,
 (SELECT group_concat(text1_1 separator ' \n ') FROM npc_text WHERE id IN
   (SELECT text_id FROM gossip_menu WHERE entry IN (creature_template.gossip_menu_id))
 ) AS text1_1,
 (SELECT group_concat(text2_0 separator ' \n ') FROM npc_text WHERE id IN
   (SELECT text_id FROM gossip_menu WHERE entry IN (creature_template.gossip_menu_id))
 ) AS text2_0,
 (SELECT group_concat(text2_1 separator ' \n ') FROM npc_text WHERE id IN
   (SELECT text_id FROM gossip_menu WHERE entry IN (creature_template.gossip_menu_id))
 ) AS text2_1
FROM creature_template WHERE INSTR(subname,'Rogue Trainer')>0

**Comment by Neotmiren** [comment]
Currently, gossip option "Take the Letter" is implemented only for some of Rogue Trainers. "Osborne the Night Man" in Stormwind has it, but "Lord Tony Romano" - does not. Rogues can easily miss this letter if they learn abilities from unsuitable trainers.

**Comment by cala** [comment]
Thank you again for all your reports. Could you please do at least one pull request, so I could grab you Git ID and then be happy to grant you authorship for the fixes?

**Comment by cala** [comment]
Regarding this specific issue (my comment above was for every issue), it indeed looks like that more gossip menus are still missing even though I backport hundred of them from UDB...

**Comment by cala** [comment]
After checking, that are 482 missing gossip menus appearently (in YTDB, but not in Classic DB). It will take some time to check them all before inclusion.

**Comment by Neotmiren** [comment]
Honestly, at this moment I do not find great desire to look into github procedures. So maybe later, though I just play from time to time (multiclass, XP slowed greatly) and do appropriate fixes in the process, no other motivation actually.

There are much more gossips now, and this is very nice thing. In theory, any class trainer must have gossip menu because of Unlearn Talents option.
