### ISSUE TITLE
Priestess Josetta (Goldshire) offers invalid versions of Night Elf "Returning Home" quests.

### ISSUE THREAD

**Issue by Neotmiren** [classicdb/database#135]
DELETE FROM creature_questrelation WHERE id=377 AND quest IN (5630,5632,5633);
UPDATE quest_template SET QuestLevel=10 WHERE entry=5628;

These entries have empty OfferRewardText. Entry 5628 is valid but QuestLevel is too high (20 instead of 10).

**Comment by cala** [comment]
Thanks for this report. I guess quests 5630, 5632 & 5633 should be relinked to correct NPC quest givers that would more than probably be priest trainer in Kharanos and main priest trainer/high priest in Stormwind and Ironforge.

**Comment by Neotmiren** [comment]
There are three normal versions of this quest ("Returning Home") assigned to different NPCs (with correct correct ExclusiveGroup and other parameters). Though I did not test these versions - discovered wrong quests in Goldshire too late.

**Comment by Neotmiren** [comment]
Maybe the SQL template mentioned below could be useful. It displays quest titles and questgiver names - for selected set of quest titles AND selected set of creatures.

SELECT *, (SELECT CONCAT(Title,' ',MinLevel,' ',QuestLevel) FROM quest_template WHERE entry=quest) AS QuestTitle, (SELECT CONCAT(name,' ',minlevel) FROM creature_template WHERE entry=id) AS QuestGiver,(SELECT PrevQuestId FROM quest_template WHERE entry=quest) AS PrevQuestId, (SELECT Title FROM quest_template WHERE entry IN ((SELECT PrevQuestId FROM quest_template WHERE entry=quest))) AS PrevQuestTitle FROM `creature_questrelation` WHERE `quest` IN (SELECT entry FROM quest_template WHERE INSTR(Title,'Returning Home')>0) OR id IN (SELECT entry FROM creature_template WHERE INSTR(name,'Priestess Josetta')>0);

**Comment by cala** [comment]
After looking at the various 'Returning Home' quests in Classic DB and doing a bit of research about this quest, reading the quest texts, I think most of the related quests in DB have wrong levels/requirements and should all go into the same exclusive group and start next quest in chain 5627. The quest givers need to be spreaded amongst a few low level priest trainers who can easily guessed by the quest text.
