### ISSUE TITLE
Ammo for Rumbleshot (5541) - Quest End Script

### ISSUE THREAD

**Issue by PatSmuk** [classicdb/database#138]
Ammo for Rumbleshot is missing the scripted event on turn-in.

Video:
http://www.youtube.com/watch?v=VIeY1XU_3NI
http://www.youtube.com/watch?v=wCe_9PlTKsw

**Comment by scotty0100** [comment]
Hmm just created this as a SD2 bug https://github.com/scriptdev2/scriptdev2-classic/issues/30

Can we handle this in DB? It looked too complicated for DB so I raised as SD2..if not I will close down SD2 issue

**Comment by cala** [comment]
You'll be happy to hear that this is part of UDB 407 release, very nicely done by @Grz3s and will be backported very soon in Classic DB (I tested it yesterday evening and it looked awesome).

You can thus close the SD2 issue. Thank you. :)

The only thing that is not clear to me is if that event occurs on a regular basis (it was scripted that way in UDB) or if it should only start on quest end (if so, I have small adjustements to make firsthand).

**Comment by scotty0100** [comment]
Awesome news, this backport seems like it will fix a lot of stuff! Are we going to celebrate by a new DB version release? :+1:

**Comment by Grz3s** [comment]
hi all... 
yes .. I always wanted to do this event.... 
i recorded this event 2 Times..... once in 3.3.5 and another one... with 4.x.x .....
on both of tchem... noone finished any quest... also i spent few hours  to check, how often they repeat this event...  so im 100% sure that... what i made is correct... (maybe small details need to be fixed)....
And to be honest with u all ... i had no idea ... that event also "happens" as a quest_end_script..(had no idea about this quest at all) :D .... but yes ... it looks like event should happen there also.
.... so the question is ... 
- if there is any chance, that blizz changed smth... between classic and TBC/WOTLK...to make this event happen not only after q. (i know that q was removed with CATA - but u can go there and they still will be doing this event - checked it today)....
  ........
  defenetly i'll add this event for this q. soon..... and i need to make decision if im gona keep it ... as it is also...

**Comment by cala** [comment]
The script is now in Classic DB as it is in UDB. Thanks again @Grz3s for doing it, it really looks awesome!

In my opinion, their was no change between Classic and TBC and beyond. I think the event is on a schedule and can be triggered when completing the quest.

Currently, only the quest triggered part is missing. Can I help you on this matter @Grz3s ?

**Comment by Grz3s** [comment]
https://github.com/unified-db/Database/commit/e897dceaed43f540ab49726824774af5e1d5326e
done.

I decided ... to keep event as it is...+ added it as quest completed for his quest.
Pls check guids if they're complatible with your DB.
Thx for all your reports ... im happy to help ;)
