### ISSUE TITLE
Blastmaster Emi Shortfuse (Gnomeregan) has no gossip text

### ISSUE THREAD

**Issue by Neotmiren** [classicdb/database#139]
She says "Greetings, player_name", though she correctly offers option to start event.

INSERT IGNORE INTO npc_gossip SET npc_guid=(SELECT guid FROM creature WHERE id=7998 LIMIT 1), textid=1693

**Comment by Schmoozerd** [comment]
1) NEVER use npc_gossip table
2) She is scripted with SD2 - probably you installed something wrongly.

**Comment by Neotmiren** [comment]
Did you test before replying? Yes, she is scripted, and this is the reason why the gossip do not work.

bool GossipHello_npc_blastmaster_emi_shortfuse(Player\* pPlayer, Creature\* pCreature)
{
...
pPlayer->SEND_GOSSIP_MENU(pPlayer->GetGossipTextId(pCreature), pCreature->GetObjectGuid());

Function GetGossipTextId() uses npc_gossip.

**Comment by Schmoozerd** [comment]
Of course i did not test :)
I usually never test anything :P

yes, GetGossipTextId can use npc_gossip.
But you should NEVER use this fucking table. Infact it should have been removed in 2009...

Give her the gossip menu properly (table gossip_menu) and everything should be fine :)

**Comment by cala** [comment]
The required gossip menu (with this specific text_id) is already present in Classic DB, it just needs to be linked to the NPC:

``` SQL
UPDATE `creature_template` SET `gossip_menu_id` = 1080 WHERE `entry` = 7998;
```

**Comment by Neotmiren** [comment]
Emi's gossip text is displayed correctly without mangosscript.dll loaded.

Schmoozerd, you may be right only in one case: if it happens to be my local problem for some reason. This can only be tested in practice (for Classic, not WotLK).

Оn the other hand, YTDB for WotLK has almost empty npc_gossip and apparently things somehow work without them. However, ClassicDB has hundreds of entries in npc_gossip. Can Mangos Classic work without these entries?

@cala
It is already linked to NPC.

**Comment by cala** [comment]
> Emi's gossip text is displayed correctly without mangosscript.dll loaded.
> ...
> It is already linked to NPC.

So, I misunderstood the issue here. Though correctly linked, the gossip does not display when and only when SD2 is loaded? Am I right?

> Оn the other hand, YTDB for WotLK has almost empty npc_gossip and apparently things somehow work without them. However, ClassicDB has hundreds of entries in npc_gossip. Can Mangos Classic work without these entries?

That is precisely a thing I'm working on: moving `npc_gossip` entries to `gossip_menu`. I did this with TBC-DB and UDB as sources, I'm doing the same with YTDB now, but this is a tedious work because I have to ensure I do not backport some WotLK content.

**Comment by Neotmiren** [comment]
Yes, correctly linked from creature_template to gossip_menu and gossip_menu_options (although there are no gossip_menu_options for this NPC in YTDB). Аdding to npc_gossip TABLE fixes this issue. I never noticed npc_gossip TABLE before that, but now looked at Core code and found that it searches in values loaded from npc_gossip when called from SD2.

**Comment by Neotmiren** [comment]
The entry I add to npc_gossip previously was there, but removed from ClassicDB recently. So, other NPCs may had lost their gossip texts too - if they happen to be are script driven in the same manner as Blastmaster Emi.

**Comment by Schmoozerd** [comment]
hmm

one can argue whether the script is bad, or the core is bad that "GetGossipTextId" does not work correctly.

In any case using npc_gossip table is only a temporarily hack untill things are solved properly.
As i say: this crap table should have been deleted around 2009..

**Comment by cala** [comment]
Do we come to the conclusion that this is a SD2 or core issue and that this DB one can be closed?

I have a few small issues to open on SD2, I can also add an issue for this one.

**Comment by Schmoozerd** [comment]
I have urged the udb team recently to be ready to drop the npc_gossip table soonish, so i think we will do this one by core change.

**Comment by cala** [comment]
Thank you for the update. I will then close the issue here and wait for the usual update workflow wotlk -> tbc -> classic before dropping npc_gossip table. I should have finished the current gossips backport from YTDB in the meantime.
