### ISSUE TITLE
Quest 9422 should not autocomplete

### ISSUE THREAD

**Issue by cala** [classicdb/database#14]
The quest "Scouring The Desert" is bugged. As soon as you accept it you can turn it in for the reward. On top of that, the silithist spouts in the desert do not give the player the silithist dust to take bake to his or her camp, so they are bugged as well.

_original report by [The-Great-Sephiroth](https://github.com/The-Great-Sephiroth)_

I have committed a fix for the quest here: https://github.com/ProjectSilverpine/database/commit/ead6b044c89fc3698be2fbbf64e98d9f09fbf0c3 I'll commit it to this repository tomorrow if Salja hasn't done it by then. :)

If you mean Silithyst Geyser (http://www.wowhead.com/object=181598) by "silithist spouts", I don't think you're supposed to receive an item (dust) when you use the Geyser. You gain a buff/aura and then you run to back to the machine at the camp to "turn it in". That is currently how it works in mangoszero as well so they're not bugged.

_original report by [Ghurok](https://github.com/Ghurok)_

**Comment by Swater96** [comment]
Confirmed to not give an item. I have written a SD2 script for the object in the past and can confirm it is just a buff.
