### ISSUE TITLE
Matrix Punchograph 3005-D (Gnomeregan) has no option to obtain Schematic: Discombobulator Ray

### ISSUE THREAD

**Issue by Neotmiren** [classicdb/database#140]
Оne more issue of Gnomeregan instance (although I really do not like its technocratic theme, which is one of World of Warcraft original sins, that was progressing over time)

INSERT gossip_menu_option SET menu_id=1050, id=1, option_text='Use engineering to access hidden shematics!', option_id=1, npc_option_npcflag=1, action_menu_id=-1, action_script_id=50111, box_coded=0, box_money=0, box_text=NULL, condition_id=1769;
INSERT dbscripts_on_gossip SET id=50111, command=17, datalong=4413, datalong2=1, comments='Create Item - Schematic: Discombobulator Ray';
INSERT conditions (condition_entry, type, value1, value2) VALUES (1769, -1, 1413, 1768);
INSERT conditions (condition_entry, type, value1, value2) VALUES (1768, 7, 202, 160); -- Engineering 160
INSERT conditions (condition_entry, type, value1, value2) VALUES (1413, -1, 1023, 1121);
INSERT conditions (condition_entry, type, value1, value2) VALUES (1121, 2, 9327, 1); -- must have Security DELTA Data Access Card
INSERT conditions (condition_entry, type, value1, value2) VALUES (1023, 24, 4413, 1); -- does not already have Schematic: Discombobulator Ray

The numbers are taken from YTDB.

**Comment by cala** [comment]
Thank you for this report. A part of this hidden schematics was already added in https://github.com/classicdb/database/commit/905126df13898a646bed77e613628bbbd353ad33 and the other part will be added along with all the gossips I'm currently backporting from YTDB.
