### ISSUE TITLE
UBRS - Pyroguard Emberseer

### ISSUE THREAD

**Issue by scotty0100** [classicdb/database#141]
Map & Area: Hall of Binding - UBRS

How to replicate the bug: Use 3 characters to break the adds link with the Pyroguard

What happens: Once you kill the adds, Pyroguard Emberseer does not engage nor does the emotes he is gaining strength appear

What should happen: He should engage once he'll fully empowered

Extra Information: Could not get any further as the door won't open till he's killed.

I originally made this as a SD2 bug - however on second looks - it may be something to do with the unit_flags set  for the Pyroguard Emberseer.

On SD2 file boss_pyroguard_emberseer.cpp Line 117:

 m_creature->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);

Once the runes are active, however I believe the unit flags still have the Pyroguard as Passive etc.

**Comment by Schmoozerd** [comment]
Easiest is probably to compare unit flags to the ones set in UDB (which _should_ be correct and should be as expected)

**Comment by cala** [comment]
I will compare Classic DB to UDB data. But like Dire Maul, Blackrock Spire data of UDB need some improvements (I guess this is why you put an emphasis on _should_).

**Comment by Schmoozerd** [comment]
yes - though these flags are static data for which we have "good" information for both DM and BS.
(Though DM is pretty crazy what blizz does, hence the static data went only so far..)

**Comment by cala** [comment]
UDB `unit_flags = 33554752`
Classic DB `unit_flags = 33555264`
Which means Pyroguard Emberseer has flag 512 (Passive - unable to attack) in Classic DB and I guess it shouldn't.

I'm currently in the middle of numerous Blackrock Spire updates, so I will test this one soon. (I hope so).
