### ISSUE TITLE
Barrens wrong npc models

### ISSUE THREAD

**Issue by Metalica** [classicdb/database#143]
All guards in these towns:
- Camp taurajo
- Splintertree forest.
- Crrossroads.
- Morshan bae camp.
- Honor stand.
  
  Have wrong female and orc display models.

**Comment by cala** [comment]
Thank you for this report. Can you give some names of creatures with wrong model? It will help fixing them.

**Comment by Metalica** [comment]
Updated the main topic. I deleted display id's "12165 and 12166 "male and female" which fixed the issue.
