### ISSUE TITLE
AQ40 bugs

### ISSUE THREAD

**Issue by Metalica** [classicdb/database#144]
- Minerals are spawned 2 times, they should not be at all.
- Obsidian eradicator is missing on right stairs from the boss.
- All 3 Obsidian eradicator have no waypoints.
- Behind the 1st. boss, all 3 npc quest givers are at wrong location.
  
  Youtube video for reference:
- http://www.youtube.com/watch?v=3nDM0iePWtk

**Comment by cala** [comment]
Thank you for this report and the link.

**Comment by Tobschinski** [comment]
http://pastebin.com/95jgn0z8

**Comment by Tobschinski** [comment]
WPs done ...

**Comment by cala** [comment]
Closed by https://github.com/classicdb/database/commit/0c2d9c48a953ad3e3f5c0468eed93e0ee6773719
