### ISSUE TITLE
a20 bugs

### ISSUE THREAD

**Issue by Metalica** [classicdb/database#145]
Using october 11 or so db.
- summoning stone missing at start of aq20/aq40
- Qiraji gladiator is always double spawned.

**Comment by cala** [comment]
Thanks for the report. Qiraji gladiators will probably be fixed soon. Regarding the summoning stone, as the system is not yet implemented in core, there is no hurry.

**Comment by cala** [comment]
On a second thought, I'm not sure there ever was a summoning stone for _raid_ instances in Classic.

**Comment by PatSmuk** [comment]
There were no summoning stones for any instances. There were meeting stones, which obviously don't make sense for raids (imagine doing a PUG raid in vanilla XD).

**Comment by Metalica** [comment]
Hm.... this can be closed.
