### ISSUE TITLE
Brd arena and other minor bugs

### ISSUE THREAD

**Issue by Metalica** [classicdb/database#147]
Using octtober 11 / 2013 DB.
- BRD arena needs minor waypoint tweaking (dude walks 3x more then he should).
- Once you done the quest for the flag to summon the boss in arena, it does not work (needs double check).
- Keegs for destroying and baiting the boss are only 3 (should be at least 6-7) and they are spawned on each other. Also when you destroy the kegs, boss does not spawn!
- Beer kegs are only 5, but you need 6. Spawning around 4-5 more beer kegs, should do the trick.

**Comment by cala** [comment]
Thank you for these reports.

**Comment by TheTrueAnimal** [comment]
#3: After clicking on three gameobjects some npcs should spawn. But nothing happens.
This comment tells that you have to destroy ALL kegs: http://www.wowhead.com/npc=9541#comments and http://www.wowhead.com/quest=4134  (Just to clarify, the barrels that you break are off in an adjacent, smaller room to the main room where everyone is drinking. There are only three barrels and they're smaller as well.) https://web.archive.org/web/20060516141059/http://wow.allakhazam.com/db/quest.html?wquest=4134
I can't tell how many adds spawn. Seems like 3 or 4. https://web.archive.org/web/20060525212418/http://wow.allakhazam.com/db/mob.html?wmob=9537   http://de.wowhead.com/npc=9537#english-comments

Quest: http://www.wowhead.com/quest=4134
Gameobjekt: http://de.wowhead.com/object=16491
NPCs: http://de.wowhead.com/npc=9537 and 3x http://www.wowhead.com/npc=9541
Video: https://www.youtube.com/watch?v=GR_CQ-eC6ns (13:00)

**Comment by cala** [comment]
Kegs number and position fixed in https://github.com/classicdb/database/commit/2ae6c4efb250cf0a6225eefdc6be82b821575c76

**Comment by cala** [comment]
The kegs/Hurley event is SD2 stuff and is scripted here: https://github.com/scriptdev2/scriptdev2/pull/175/commits (third commit)
Waiting for merging and backport.

**Comment by cala** [comment]
All BRD related parts requiring SD2 are now scripted in this [pull request](https://github.com/scriptdev2/scriptdev2/pull/175) pending review and backport. So I'm closing this issue on the DB side. Thanks all. :smile:
