### ISSUE TITLE
naxxramass - small bugs

### ISSUE THREAD

**Issue by Metalica** [classicdb/database#150]
- Door to Anub'Rekhan should be closed, but is not.
- Deathkinght doesn't have shield.
- Sludge Betcher does not have green aura.
- At 7.17 - grobulus is re-spawning ozes.
- Archmage Tarsis is not in dead state - as shown in yt link.
  
  Youtube link for reference:
- http://www.youtube.com/watch?v=agWfYn0piY8

**Comment by PatSmuk** [comment]
Anub'Rekhan's should not be closed, he's the first boss.
The Sludge Belcher's aura should be part of ACID - have you installed it?
Grobulus spawning the oozes was something I didn't know of and should be done in its script.

**Comment by cala** [comment]
Thank you for this report.
To be more precise, Anub'Rekhan's door should be closed but not locked. And a text is yelled when the door is opened by players. I believed it was already like this.
I'm surprised by the Grobbulus report as I remember seeing it respawning the ooze. I will check this nonetheless along with the other points.
Thanks.

**Comment by Metalica** [comment]
To be more precise, Anub'Rekhan's door should be closed but not locked. And a text is yelled when the door is opened by players. I believed it was already like this. - This is correct, mistake on my part.

I'm surprised by the Grobbulus report as I remember seeing it respawning the ooze. I will check this nonetheless along with the other points. - Youtube link for refence, nothing to hide here.

 I did re-check and im using ACID 1.0.4 including sql which is in my db. Dudes dont have aura :)

**Comment by cala** [comment]
I'm pretty sure you are right about the Belchers. Maybe they are ok in ACID for wotlk, but used a different aura in Classic. I will look at it. Thanks again. :+1:

**Comment by Metalica** [comment]
- Anub'Rekhan script is totaly broke. Adds dont use skills, boss uses only one skill or two.
- Anub'Rekhan - when he dies, he says wrong thing.
- Anub'Rekhan is black for me (donno what is going on).
- Anub'Rekhan is to small and adds are to small. 02.17 - reference for size / http://www.youtube.com/watch?v=8t9ohvJava4
- Death lord, seems to respawn every few minutes.
  
  At phase 2 of Kel'Thuzad (http://www.youtube.com/watch?v=8t9ohvJava4 - 36.16 / reference), each add must come alone. Atm they are coming in masses.

**Comment by Schmoozerd** [comment]
the one slime respawned by grobbulus is done via waypoint movement.
possible there should have been slightly different behaviour in classic times.

about anub's door -- possible this was changed. atm his greetings yell is done by distance-check;

**Comment by cala** [comment]
Thank you for clarifying. I have many updates pending in Abomination/Construct Quarter of Naxxramas and I'll deal with those too.

**Comment by Metalica** [comment]
Found more info.
- Went to check  Anub'Rekhan script and found: "// spellId invalid
  // SPELL_SUMMONGUARD         = 29508,                   // Summons 1 crypt guard at targeted location - spell doesn't exist in 3.x.x"
  
  And i was wondering why he isnt using any skills :)
  
  Edit: I use classic scriptdev2 and found this in it, what is written above.

**Comment by cala** [comment]
Thank you for pointing.
@Xfurry and @Schmoozerd did an amazing job backporting WotLK Naxxramas scripts to TBC/Classic version, especially with all the changes that occured when the instance was updated to lvl 80 and 10/25 man.

However, there are still small fixes/improvements pending, like the one your are pointing above. I will see what can be done.

**Comment by cala** [comment]
I'm currently testing Anub'Rekan encounter and it is pretty close to what it should be. Only error I notice are the small scarab dealing damage with their WotLK stats at about 2k damage instead of the about 400 damage they had in classic. I will fix this in DB.

As for Anub door, it is indeed open while it should be closed as players were to open it by themselves (at least in Classic version). I tried to change the `data0` of the gameobject to make it close at spawn but with no effect. So I wonder if SD2 does not force it to open.

**Comment by xfurry** [comment]
The door state can be changed here https://github.com/cmangos/issues/wiki/Gameobject#state
You don't need to change anything in data0, but you should check the GO flags and faction so that the door is clickable

**Comment by cala** [comment]
Thanks Xfurry! I was so sure that state was only for chests, that I did not try it. :)
