### ISSUE TITLE
Omitted quest (Menethil Harbor) in "Missing Diplomat" quest chain

### ISSUE THREAD

**Issue by Neotmiren** [classicdb/database#151]
This is important quest, because it says that the "missing diplomat" is actually the King.

UPDATE `quest_template` SET `NextQuestId`=0 WHERE  `entry`=1249;
UPDATE `quest_template` SET `PrevQuestId`=1250 WHERE  `entry`=1264;

The questgiver is Tapoke Tapoke "Slim" Jahn. With just above changes to ClassicDB he will NOT offer quest directly after you defeat him AND turn-in "subdue" quest to Mikhail, although he will offer his quest after Mangos server has been reloaded. This erroneous behavior depends on SD2 code. Correct behavior requires adding 3 lines of code to SD2

m_creature->GetMotionMaster()->MoveTargetedHome();
m_creature->SetUInt32Value(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_QUESTGIVER);
Reset();

afrer call to SetRun(false);
to the function DamageTaken() 
in the file "src\bindings\ScriptDev2\scripts\eastern_kingdoms\wetlands.cpp"

**Comment by cala** [comment]
If I understand this correctly, the issue should be fixed both from DB (with the queries above) and in SD2?
I did not test this issue yet.

**Comment by Neotmiren** [comment]
Yes, both DB and SD2 should be fixed, but after server restart the quest should be available even without SD2 fix.

**Comment by cala** [comment]
Tested lately: with the DB fix only, the server has to be restarted (or creature forced to respawn) everytime a player complete the previous quest... Which is annoying.

I will test the SD2 code and push it to scriptdev2 repository.
