### ISSUE TITLE
[classic] blackrockdepth golems

### ISSUE THREAD

**Issue by jeeron** [classicdb/database#154]
Boss npc entry: 8983 (Golem Lord Argelmach)
how it works: the 2 golems next him doesnt "pop"
how should work: when you enter in combat with Lord Argelmach the 2 golems next to him must "pop" or "being alive"

Same with the golems in the room before
next to NPCs entry :

8920, 8900 ... (gnomes) I have NPC entry for a golem : 8906 (not sure)

**Comment by cala** [comment]
Thank you for the report. As you are probably aware, I already reply on the similar issue you open on cmangos core.
I'm still not sure if this issue is DB, script or core related.

**Comment by xfurry** [comment]
Maybe you can use creature link on aggro. Can you give it a try?

**Comment by TheTrueAnimal** [comment]
At the start of the fight the golem lord should immediately run into the room which lays before his room and pull some of the npcs there. The other two golems should also attack the players.

Angelmach: http://www.wowhead.com/npc=8983
Ragereaver golem: http://de.wowhead.com/npc=8906
Wrath Hammer Construct: http://de.wowhead.com/npc=8907
Video: from 3:55 on https://www.youtube.com/watch?v=4DaG11e-LNo

**Comment by cala** [comment]
Also requires ACID part: https://github.com/ACID-Scripts/Classic/pull/31
