### ISSUE TITLE
Non-circular waypoints for Kira Songshine (Elwynn Forest) leading to hers air walking

### ISSUE THREAD

**Issue by Neotmiren** [classicdb/database#156]
INSERT IGNORE creature_movement (id, point, position_x, position_y, position_z, waittime, emote, orientation) VALUES
(80283, 22, -9550.16, -68.9811, 57.4588,     0, 0, 1.3598 ),
(80283, 23, -9543.96, -40.0566, 56.5451,     0, 0, 1.11475),
(80283, 24, -9507.09,  35.1121, 56.517,      0, 0, 0.98909),
(80283, 25, -9492.11,  57.8834, 55.8784,     0, 0, 0.70321),
(80283, 26, -9483.7,   65.0161, 56.1693, 10000, 0,-0.05706),
(80283, 27, -9455.61,  63.4114, 55.8832,     0, 0, 0.58068),
(80283, 28, -9393.01,  104.486, 59.2978,     0, 0, 0.27909),
(80283, 29, -9363.17,  113.038, 61.4675,     0, 0, 0.54299),
(80283, 30, -9328.93,  133.697, 64.341,      0, 0, 0.47701),
(80283, 31, -9298.35,  149.504, 66.412,      0, 0, 0.28223),
(80283, 32, -9257.91,  161.229, 67.623,      0, 0, 0.86343),
(80283, 33, -9233.09,  190.265, 67.82,       0, 0, 0.80374),
(80283, 34, -9194.35,  230.449, 71.8101,     0, 0, 1.2467 ),
(80283, 35, -9184.62,  259.409, 73.981,      0, 0, 1.55144),
(80283, 36, -9183.56,  314.518, 79.2184,     0, 0, 1.42263),
(80283, 37, -9181.78,  326.43,  81.1904,     0, 0, 1.21529),
(80283, 38, -9175.93,  342.185, 84.2532,     0, 0, 0.85086),
(80283, 39, -9160.48,  359.541, 89.109,      0, 0, 0.79902),
(80283, 40, -9145.05,  375.98,  90.7306,     0, 0, 0.75897);

This simple addition creates exact "reverse waypoints" (orientation reversed) without unnecessary new wpguids for waypoint wisps
(use ".wp show on" command to see them in GM mode).

YTDB also may work correctly: it contains enough many waypoints, but I did not test them; no wpguids for waypoint wisps there at all.

Also text quotes in certain places along her path could be added:
http://www.wowwiki.com/Kira_Songshine
http://i60.fastpic.ru/big/2013/1106/d7/c695d18436235b0290ef4fbd26cd64d7.jpg

**Comment by cala** [comment]
Thank you for this report. This is not the only NPC with this behaviour as one of the Ironforge guard can be seen air jumping above the lava in the Great Forge.

Your additions will indeed fix this problem but I have first to check if she really had a circular path: some NPCs just teleport back to the first waypoint when reaching the end of their waypoint path (example: Rexxar).

**Comment by Neotmiren** [comment]
UPDATE creature SET position_x=-4875.47, position_y=-1109.89,position_z=502.212 WHERE guid=1895;

This seems to fix Ironforge Guard patrolling around the Great Forge. He is spawned too far from the first waypoint.

**Comment by cala** [comment]
Thank you, I did not check that.
