### ISSUE TITLE
Paladin's talent Benediction does not reduce mana cost of Seal of Crusader and Seal of Command

### ISSUE THREAD

**Issue by Neotmiren** [classicdb/database#157]
UPDATE spell_affect SET SpellFamilyMask=SpellFamilyMask|512|33554432 WHERE entry IN (20101,20102,20103,20104,20105); -- Paladin's talent Benediction (5 ranks) should affect Seal of the Crusader and Seal of Command

**Comment by cala** [comment]
Thank you for this report. `spell_affect` is one of the tables which are managed by the core developers. I will leave this issue open here for a while and make a dedicated pull request to core in the meantime.

**Comment by cala** [comment]
A pull request is in process core-side. I'm closing here. :)
