### ISSUE TITLE
Lots of reputation reward items are unavailable to buy from faction quartermasters

### ISSUE THREAD

**Issue by Neotmiren** [classicdb/database#158]
UPDATE item_template SET RequiredReputationFaction=890 WHERE RequiredReputationRank !=0 AND RequiredReputationFaction=0 AND 14753 IN (SELECT entry FROM npc_vendor WHERE item=item_template.entry); -- Silverwing Sentinels reputation for items sold by Illiyana Moonblaze
UPDATE item_template SET RequiredReputationFaction=889 WHERE RequiredReputationRank !=0 AND RequiredReputationFaction=0 AND 14754 IN (SELECT entry FROM npc_vendor WHERE item=item_template.entry); -- Warsong Outriders reputation for items sold by Kelm Hargunth
UPDATE item_template SET RequiredReputationFaction=730 WHERE RequiredReputationRank !=0 AND RequiredReputationFaction=0 AND 13216 IN (SELECT entry FROM npc_vendor WHERE item=item_template.entry); -- Stormpike Guard reputation for items sold by Gaelden Hammersmith
UPDATE item_template SET RequiredReputationFaction=729 WHERE RequiredReputationRank !=0 AND RequiredReputationFaction=0 AND 13218 IN (SELECT entry FROM npc_vendor WHERE item=item_template.entry); -- Frostwolf Clan reputation for items sold by Grunnda Wolfheart
UPDATE item_template SET RequiredReputationFaction=529 WHERE RequiredReputationRank !=0 AND RequiredReputationFaction=0 AND 10856 IN (SELECT entry FROM npc_vendor WHERE item=item_template.entry); -- Argent Dawn reputation for items sold by Argent Quartermaster Hasana
UPDATE item_template SET RequiredReputationFaction=59  WHERE RequiredReputationRank !=0 AND RequiredReputationFaction=0 AND 12944 IN (SELECT entry FROM npc_vendor WHERE item=item_template.entry); -- Thorium Brotherhood reputation for items sold by Lokhtos Darkbargainer
UPDATE item_template SET RequiredReputationFaction=576 WHERE RequiredReputationRank !=0 AND RequiredReputationFaction=0 AND 11555 IN (SELECT entry FROM npc_vendor WHERE item=item_template.entry); -- Timbermaw Hold reputation for items sold by Gorn One Eye
UPDATE item_template SET RequiredReputationRank=0 WHERE RequiredReputationRank !=0 AND RequiredReputationFaction=0 AND entry IN (15742,15754); -- Timbermaw Hold reputation not required for Pattern: Warbear Harness, Pattern: Warbear Woolies (are dropped, not sold)

WDB cache must be cleared after this fix, especially if the items were previously accessed from GM mode (it was possible for GM, but without reputation requirements displayed at client side).

**Comment by Neotmiren** [comment]
Not "Lost of" but "Lots of", as well as not "Paldain", but "Paladin". Please correct if it is possible.

**Comment by cala** [comment]
Corrected.
Issue added to the "Stand Your Ground" milestone.
