### ISSUE TITLE
Loot issues: Lady Vespira, Skhowl, Lo'Grosh, Mosh'Ogg Butcher  

### ISSUE THREAD

**Issue by Neotmiren** [classicdb/database#159]
-- Lady Vespira (rare naga, Darkshore)
INSERT IGNORE creature_loot_template SET entry=7016, item=6333, ChanceOrQuestChance=40, groupid=2; -- uncommon Spikelash Dagger
UPDATE creature_loot_template SET groupid=2 WHERE entry=7016 AND item=6332 AND groupid=0; -- mutually exclusive group for rare Black Pearl Ring
DELETE FROM reference_loot_template WHERE item IN (6333);

-- Skhowl (rare yeti, Alterac Mountains)
INSERT IGNORE creature_loot_template SET entry=2452, item=3011, ChanceOrQuestChance=50, groupid=2; -- uncommon Feathered Headdress
UPDATE creature_loot_template SET groupid=2 WHERE  entry=2452 AND item=6331 AND groupid=0; -- mutually exclusive group for rare Howling Blade
DELETE FROM reference_loot_template WHERE item IN (3011);

-- Lo'Grosh (rare ogre, Alterac Mountains)
INSERT IGNORE creature_loot_template SET entry=2453, item=4810, groupid=2, ChanceOrQuestChance=40; -- uncommon Boulder Pads
UPDATE creature_loot_template SET groupid=2, ChanceOrQuestChance=20 WHERE entry=2453 AND item=1678 AND groupid=0; -- mutually exclusive group for rare Black Ogre Kickers
UPDATE creature_loot_template SET groupid=2, ChanceOrQuestChance=20 WHERE entry=2453 AND item=6327 AND groupid=0; -- mutually exclusive group for rare The Pacifier
DELETE FROM reference_loot_template WHERE item IN (4810);

-- Mosh'Ogg Butcher (rare elite ogre, Stranglethorn Vale)
INSERT IGNORE creature_loot_template SET entry=723, item=1680, ChanceOrQuestChance=40; -- uncommon Headchopper IL 44 [39] 2H-Axe
DELETE FROM reference_loot_template WHERE item IN (1680);

All added items are mentioned in wowwiki as creature-specific drops.
Drop chances probably could be made more exact after additional investigation.

**Comment by Neotmiren** [comment]
Also many rare creatures have wrong rank in DB (rare, elite, rare elite). I already fixed all of them for myself in batch mode using Classic rare creatures list from wowwiki, so I cannot be aware about such misfits related to unmodified ClassicDB state.

**Comment by cala** [comment]
Thank you for this report. The loot issue is already slowly handled in issue #49 
The rank issue is new however. Thanks. :)

**Comment by Neotmiren** [comment]
Why rank issue is new? One of your latest commits fixes rare elite rank for Razorfen Kraul creatures. My scripted batch modifications result in

Illegal Rare rank removed from 69 creatures
Rare rank set to 346 classic rare creatures

These numbers include said Razorfen Kraul creatures.

**Comment by cala** [comment]
By "new" I was meaning that no issue was already open, even though I was aware some creatures rank need to be fixed, as you have already noticed. Sorry about the confusion. :)
