### ISSUE TITLE
Battlemaster status for Battleground Emissaries

### ISSUE THREAD

**Issue by Neotmiren** [classicdb/database#160]
If I understand correctly, emissaries should be able to teleport player to battlegrounds? Some of them have wrong flag 1048576 in DB (which is WotLK related value), must be 2048 for Classic.

UPDATE creature_template SET npcflag=npcflag&~1048576|2048 WHERE entry IN (14990,14991,15102); -- Defilers Emissary, League of Arathor Emissary, Silverwing Emissary

Also currently there are no gossip texts linked to emissaries.

**Comment by cala** [comment]
Thanks for pointing.
I added this report to the "Stand Your Ground" milestone, related to PvP and more specifically Battlegrounds. I have currently my hands full with the current milestone focused on dungeons updates, so PvP will be handled later unfortunately.

As for the missing gossip menus, issue #52 is already open and should be fixed shortly. :)
