### ISSUE TITLE
Holy Light - Heal Delay

### ISSUE THREAD

**Issue by cruzedyuni** [classicdb/database#162]
Hey guys,
alle ranks of the spell  "Holy Light" have a heal delay , which means that the animation is correct but the actually heal comes 2 or 3 seconds later.

**Comment by cala** [comment]
Thank you for this report. This is an [issue related to the CManGOS core](https://github.com/cmangos/issues/issues/281) and as such, cannot be fixed via the DB. Thus, I'm closing the issue here, waiting it is fixed core side.
