### ISSUE TITLE
The three epic quests NPC are misplaced

### ISSUE THREAD

**Issue by cala** [classicdb/database#167]
The three epic quests NPCs in the last room (after C'Thun room) are misplaced and should be inside the three magical blue circles.

**Comment by Tobschinski** [comment]
I know this is not directly related ...

Additional note: The magical blue circles expire after C'Thun has been defeated. 
Gossip of the three NPCs will be changing as well (!).

(I don't know if it is considered as a bug, but after a soft reset, the circles reappear, although C'Thun is dead)
