### ISSUE TITLE
Bugs spawns in Twin Emperors room are wrong

### ISSUE THREAD

**Issue by cala** [classicdb/database#168]
TO BE CHECKED
It looks like the bugs in Twin Emperors rooms are already the hostile ones (spawns via spell during the encounters) instead of the neutral and fast respawing ones that should be there in the first place.

**Comment by Tobschinski** [comment]
Indeed, Qiraji Scarabs (and Qiraji Scorpions, which are currently missing in DB) have a strange behavior.

Outside of the Twins Room (there should be some between Anubisath Defender and some more between the packs before Ouro), they seem to react on calls for assistance and attack the players, without turning hostile.

During the Twin Emps encounter, they only turn hostile after being targeted by http://www.wowhead.com/spell=804 or http://www.wowhead.com/spell=802.

By the way, the conditions need to be reviewed, but thats SD2 stuff. Believe me, you do not want to see a bug that got its size increased by 400% and then by another 300 ...

**Comment by Metalica** [comment]
https://www.youtube.com/watch?v=RrXUFgPSE6k - Reference for complete and every bug at Twin Emperors.

 Other note:

 Twin Emperors don't have immunity to melle or spell damage as shown in video.

**Comment by Tobschinski** [comment]
The only monster-faction I am aware of that is neutral to players is `634-Monster-8-0-0`

However, this faction will not react to CallForAssists from Trashmobs / packs, like they do on retail servers.

**Comment by cala** [comment]
Note: UDB uses faction 311 (Silithid) for creatures 15316 & 15317 (Qiraji Scorpions and Scarab). Not tested yet, but better than the current factions 14 (Monster = hostile to players) & 35 (Friendly = friendly to players (you don't say!)...)

**Comment by cala** [comment]
Faction fixed in 0571. The spell part will be dealt with in SD2. It "just" remains to fix the spawns. I will see if UDB/YTDB or else has better data than Classic DB on those creatures.

**Comment by cala** [comment]
@Tobschinski this closes the last open issue for AQ40/AQ20. Unless you see more things to fix for these 2 dungeons (aside from the things requiring SD2/core work), I think I will release the next version of Classic DB next week, once I test the DM East revamp from evil-at-wow (this WE).
