### ISSUE TITLE
Dark Iron Deposits not appearing.

### ISSUE THREAD

**Issue by scotty0100** [classicdb/database#169]
It appears Dark Iron Deposits aren't showing where they supposed to be.

Here is what WoWHead brings up for the current core/acid etc:

http://www.wowascension.com/wowhead/?object=165658

However; looking at the database a lot of this have "map=0" I'm guessing that's stopping them from spawning? Because they don't appear at these locations on the respective maps.

Additionally, spawn time seems to be just 1 minute.

Was going to go through and fix them all for the map ID but, theres a few different maps that they need to be set to, so didn't know how to figure out which mapID to be set to what.

**Comment by cala** [comment]
map = 0 means that the object or creature will be spawned on Eastern Kingdoms continent at position_x, position_y, position_z coordinates. The Burning Steppes being in Eastern Kingdoms, map = 0 is correct.

You are probably having a pool issue with the max spawns allowed. Try to into Classic DB the autopool SQL script located in the `utilities` directory of Classic DB and restart your server.

Regarding the spawn time of 1 minute, that sounds very low. Are you sure of it?

**Comment by scotty0100** [comment]
Ah I thought as much, but if you do:

SELECT \* FROM gameobject where id='165658';

(Using this query you will also see 60 secs for all the Dark Iron Deposits apart from the ones with the error in the mapID)

The map was 230/409 for the first few, so perhaps that's just an error with those ones.

I've run the script that you suggested and it said it affected 40 rows on the first query and 20 rows on the second, but unable to test to login to server and check until I'm done at work.

Are you able to find the deposits on your test server? I teleported to a couple but they seemed to be under the world or stuck in walls.

**Comment by cala** [comment]
map 230 is Blackrock Depths and map 409 is Molten Core, so Dark Iron Deposits are expected here.

I did not look for them in Burning Steppes or Searing Gorge yet, but don't expect to find lots of them. The pool system will only spawn some of them and only a very few outside of BRD and MC. It was likewise in retail.

**Comment by cala** [comment]
spawntime and animation should be fixed for the spawns on map = 0 with:

``` SQL
UPDATE `gameobject` SET `spawntimesecs` = 900, `animprogress` = 100 WHERE `map` = 0 AND `id` = 165658;
```

Regarding the spawns not showing, I looked into the database and they are in the pool system with a 5% spawn chance each, so it is not surprising at all that you do not see them all. I'll quickly roam throught Searing Gorge and Burning Steppes when I'll get the chance, but I strongly assume everything is as expected but for what is fixed by the query above. :)
