### ISSUE TITLE
Mangos will not import correctly

### ISSUE THREAD

**Issue by Swater96** [classicdb/database#171]
The latest full install of the db, z2401, will fail 100% of the time when importing on my server machine. I tried to import  z2392 and it completed successfully. 

Mysql version: 5.6.15.0

Here is the log:

[Err] 1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''Noblegarden egg, n' at line 3567
[Err] INSERT INTO `pool_gameobject` (`guid`, `pool_entry`, `chance`, `description`) VALUES
    (77022, 6294, 30, 'Mineral Spawn Point 87 - Tin'),
    (77023, 6294, 5, 'Mineral Spawn Point 87 - Silver'),
    (77024, 6295, 0, 'Mineral Spawn Point 88 - Copper'),
    (77025, 6295, 30, 'Mineral Spawn Point 88 - Tin'),
    (77026, 6295, 5, 'Mineral Spawn Point 88 - Silver'),
    (77027, 6296, 0, 'Mineral Spawn Point 89 - Copper'),
    (77028, 6296, 30, 'Mineral Spawn Point 89 - Tin'),
    (77029, 6296, 5, 'Mineral Spawn Point 89 - Silver'),
    (77030, 6297, 0, 'Mineral Spawn Point 90 - Copper'),
    (77031, 6297, 30, 'Mineral Spawn Point 90 - Tin'),
    (77032, 6297, 5, 'Mineral Spawn Point 90 - Silver'),
    (77033, 6298, 0, 'Mineral Spawn Point 91 - Copper'),
    (77034, 6298, 30, 'Mineral Spawn Point 91 - Tin'),
    (77035, 6298, 5, 'Mineral Spawn Point 91 - Silver'),
    (77036, 6299, 0, 'Mineral Spawn Point 92 - Copper'),
    (77037, 6299, 30, 'Mineral Spawn Point 92 - Tin'),
    (77038, 6299, 5, 'Mineral Spawn Point 92 - Silver'),
    (77039, 6300, 0, 'Mineral Spawn Point 93 - Copper'),
    (77040, 6300, 30, 'Mineral Spawn Point 93 - Tin'),
    (77041, 6300, 5, 'Mineral Spawn Point 93 - Silver'),
    (77042, 6301, 0, 'Mineral Spawn Point 94 - Copper'),
    (77043, 6301, 30, 'Mineral Spawn Point 94 - Tin'),
    (77044, 6301, 5, 'Mineral Spawn Point 94 - Silver'),
    (77045, 6302, 0, 'Mineral Spawn Point 95 - Copper'),
    (77046, 6302, 30, 'Mineral Spawn Point 95 - Tin'),
    (77047, 6302, 5, 'Mineral Spawn Point 95 - Silver'),
    (77048, 6303, 0, 'Mineral Spawn Point 96 - Copper'),
    (77049, 6303, 30, 'Mineral Spawn Point 96 - Tin'),
    (77050, 6303, 5, 'Mineral Spawn Point 96 - Silver'),
    (77051, 6304, 0, 'Mineral Spawn Point 97 - Copper'),
    (77052, 6304, 30, 'Mineral Spawn Point 97 - Tin'),
    (77053, 6304, 5, 'Mineral Spawn Point 97 - Silver'),
    (77054, 6305, 0, 'Mineral Spawn Point 98 - Copper'),
    (77055, 6305, 30, 'Mineral Spawn Point 98 - Tin'),
    (77056, 6305, 5, 'Mineral Spawn Point 98 - Silver'),
    (77057, 6306, 0, 'Mineral Spawn Point 99 - Copper'),
    (77058, 6306, 30, 'Mineral Spawn Point 99 - Tin'),
    (77059, 6306, 5, 'Mineral Spawn Point 99 - Silver'),
    (77060, 6307, 0, 'Mineral Spawn Point 100 - Copper'),
    (77061, 6307, 30, 'Mineral Spawn Point 100 - Tin'),
    (77062, 6307, 5, 'Mineral Spawn Point 100 - Silver'),
    (77063, 6308, 0, 'Mineral Spawn Point 101 - Copper'),
    (77064, 6308, 30, 'Mineral Spawn Point 101 - Tin'),
    (77065, 6308, 5, 'Mineral Spawn Point 101 - Silver'),
    (77066, 6309, 0, 'Mineral Spawn Point 102 - Copper'),
    (77067, 6309, 30, 'Mineral Spawn Point 102 - Tin'),
    (77068, 6309, 5, 'Mineral Spawn Point 102 - Silver'),
    (77069, 6310, 0, 'Mineral Spawn Point 1 - Iron'),
    (77070, 6310, 30, 'Mineral Spawn Point 1 - Mithril'),
    (77071, 6310, 10, 'Mineral Spawn Point 1 - Silver'),
    (77072, 6310, 7, 'Mineral Spawn Point 1 - Gold'),
    (77073, 6310, 3, 'Mineral Spawn Point 1 - Tin'),
    (77074, 6311, 0, 'Mineral Spawn Point 2 - Iron'),
    (77075, 6311, 30, 'Mineral Spawn Point 2 - Mithril'),
    (77076, 6311, 10, 'Mineral Spawn Point 2 - Silver'),
    (77077, 6311, 7, 'Mineral Spawn Point 2 - Gold'),
    (77078, 6311, 3, 'Mineral Spawn Point 2 - Tin'),
    (77079, 6312, 0, 'Mineral Spawn Point 3 - Iron'),
    (77080, 6312, 30, 'Mineral Spawn Point 3 - Mithril'),
    (77081, 6312, 10, 'Mineral Spawn Point 3 - Silver'),
    (77082, 6312, 7, 'Mineral Spawn Point 3 - Gold'),
    (77083, 6312, 3, 'Mineral Spawn Point 3 - Tin'),
    (77084, 6313, 0, 'Mineral Spawn Point 4 - Iron'),
    (77085, 6313, 30, 'Mineral Spawn Point 4 - Mithril'),
    (77086, 6313, 10, 'Mineral Spawn Point 4 - Silver'),
    (77087, 6313, 7, 'Mineral Spawn Point 4 - Gold'),
    (77088, 6313, 3, 'Mineral Spawn Point 4 - Tin'),
    (77089, 6314, 0, 'Mineral Spawn Point 5 - Iron'),
    (77090, 6314, 30, 'Mineral Spawn Point 5 - Mithril'),
    (77091, 6314, 10, 'Mineral Spawn Point 5 - Silver'),
    (77092, 6314, 7, 'Mineral Spawn Point 5 - Gold'),
    (77093, 6314, 3, 'Mineral Spawn Point 5 - Tin'),
    (77094, 6315, 0, 'Mineral Spawn Point 6 - Iron'),
    (77095, 6315, 30, 'Mineral Spawn Point 6 - Mithril'),
    (77

**Comment by cala** [comment]
I'm not sure to understand you: you are refering to install z2401 which is a core revision (Classic DB current revision is 0368) and you compare it to another core revision : z2392. It was then difficult for me to know where to look especially as the error log points to changes done several months ago in revision 0083 if my memory serves me.
Then I assumed you were refering to the single file in the Full_DB directory but I had no error when importing it either. So, I'm puzzled though I'd like to help. Could you try to describe again how the problem occurs, please ?

**Comment by Swater96** [comment]
![image](https://f.cloud.github.com/assets/540552/1843500/f6eb3cc2-74d3-11e3-8747-209a03c57cbe.png)
![image](https://f.cloud.github.com/assets/540552/1843502/0d3db964-74d4-11e3-98d8-494aafbd07a8.png)
![image](https://f.cloud.github.com/assets/540552/1843507/2cb3132a-74d4-11e3-9b7d-b6a3288d388a.png)
![image](https://f.cloud.github.com/assets/540552/1843509/429a9f28-74d4-11e3-98d0-b83b1d470b75.png)

**Comment by cala** [comment]
Thank you for the screenshot. It is as I feared: I have no error when importing the file that raises an error with your SQL client and I don't see any syntax error around the line prompted.
I suppose this is a small syntax change between two versions of MySQL and your client is sensible to it while mine is not. I'll see what I can do. :/

**Comment by Swater96** [comment]
What client for importing do you use and which mysql version?

**Comment by cala** [comment]
I use MySQL 5.5.17 for OS X (64 bits) and SQL clients: SequelPro on my Mac and HeidiSQL on my PC.

**Comment by cala** [comment]
Did you manage to import the last revision of the DB? If you still have error messages using a client for importing, can you run the `InstallFullDB.sh` script via GitBash or any command-line tool? It will help us point out if this is an SQL error or a client one (I sometime have errors from my PC client which fails to parse the queries when it is not in the mood to...).

**Comment by cala** [comment]
With the release of version 1.3 a new Full DB file has been created. Do you still have this issue with this new file?

**Comment by Swater96** [comment]
let me check for you real quick. Sorry for the late reply, the github message notification is very tiny!

**Comment by Swater96** [comment]
Looks like 1.3 solved my issue.
