### ISSUE TITLE
Quest 7838 - Arena Grandmaster bug

### ISSUE THREAD

**Issue by scotty0100** [classicdb/database#172]
This quest is not completable as the chest in Stranglethorn Vale only drops the trinket once. http://www.wowascension.com/wowhead/?item=18706

What should happen: You should be able to get it every time as its 100% droprate and 12 are needed for the Grandmaster Trinket quest.

Extra Information: Appears to be treating this as unique (it is not) as once you get one, you no longer see any more.

**Comment by Sinoxan** [comment]
This needs checking as I've looked into this and the item does have a 100% drop rate from the chest and isn't tagged as unique in the database so this might have been fixed.

**Comment by TheTrueAnimal** [comment]
You can always loot the item as long as you haven't started the quest Arena Grandmaster. Once you've started it you aren't able to loot the item any more. You can pick up the other items from the chest but don't see the trinket. The chest doesn't respawn until another player picks up the trinket.

**Comment by Lumber-Jack-2** [comment]
@cala on fire :D
