### ISSUE TITLE
[BlackRock Depths] General Angerforge fight mechanics

### ISSUE THREAD

**Issue by ghost** [classicdb/database#179]
- Adds spawn around him instead of up the ramp and running down to join the fight.
- Don't stop spawning if fight ends quickly. {don't ever stop spawning?}

**Comment by cala** [comment]
This should be mainly handled by SD2 and @Tobschinski proposed a fix here: https://github.com/scriptdev2/scriptdev2-classic/pull/45
I tested it and it works nicely. :+1:
 I think that DB side the only things that remain and that could be fixed DB side are the 4 Anvilrage Reservists in front of the General. I don't remember if they respawn when the general resets (aka after a while) or if they remain dead.
They also are on a 20 sec timer which should only be true for the ones in the Lyceum.

**Comment by Tobschinski** [comment]
They do re-spawn after a reset.

**Comment by cala** [comment]
Thank you!

**Comment by cala** [comment]
Closed by https://github.com/scriptdev2/scriptdev2-classic/commit/7707aa27789c11b59d43380147410ff5afbcd5c9
