### ISSUE TITLE
[BlackRock Depths] The Grim Guzzler - Ribbly Screwspigot

### ISSUE THREAD

**Issue by ghost** [classicdb/database#182]
- Has the proper chat function but it does not turn him and his crony's hostile and start the fight.

**Comment by scotty0100** [comment]
Tried fixing this using dbscripts_on_gossip to change his faction and attack the player..

Which works but his cronies don't assist - is there a way to change their faction as well?

Here's what I have so far to just get Ribbly to attack:

```
INSERT INTO `dbscripts_on_gossip` (`id`, `command`, `datalong`, `datalong2`, `comments`) VALUES ('1970', '22', '21', '5', 'Ribbly - Change Faction');
INSERT INTO `dbscripts_on_gossip` (`id`, `delay`, `command`, `search_radius`, `comments`) VALUES ('1970', '5', '26', '25', 'Ribbly - Attack Player');
UPDATE `gossip_menu_option` SET `action_script_id`='1970' WHERE (`menu_id`='1970') AND (`id`='1');
```

**Comment by cala** [comment]
Like many other similar quest "go find friendly npc, defeat/kill him and his friends", this is probably best handled by SD2 rather than DB.

**Comment by ghost** [comment]
That makes me wonder that if we could group the creatures(perhaps through _linking_) then maybe we could adjust adjust the faction of the group or alternatively make it an optional behaviour for creature linking to mirror the _master's_ faction over to the _members/"slaves"_.

**Comment by Schmoozerd** [comment]
In theory such a change could be done.

About using db-scripts: with the buddy system you should be able to change the faction of his friends.
Though quite possibly an SD2-solution is best choice

**Comment by TheTrueAnimal** [comment]
At the moment you can talk to him and the gossip menu exists but when you click on it nothing happens and the window is still open.

Quest: http://de.wowhead.com/quest=4136
NPC: http://de.wowhead.com/npc=9543
Friends: http://de.wowhead.com/npc=10043
Video: https://www.youtube.com/watch?v=pcIAd9cN9sY
