### ISSUE TITLE
[Scholomance] Quality of life

### ISSUE THREAD

**Issue by ghost** [classicdb/database#190]
- Lady Illucia Barov's silence gives "You are mounted" instead of "You are muted"

**Comment by cala** [comment]
I think all silence spells do the same and as such this is probably a core issue. I'll check this.

**Comment by cala** [comment]
@Nekoi : tested this morning and I had the correct error message "cannot do that while silenced". I tried with a priest either with friendly spells (healing myself) or offensive spells (casting shadow spells on Illucia).
Can you confirm that you still have this issue and if so, which class are you playing, which spell triggers this error message, are they some aura active? Thanks! :)

**Comment by cala** [comment]
This seems to be a core issue, see there: https://github.com/cmangos/issues/issues/395
So I'm closing it here.
