### ISSUE TITLE
[Stratholme]  The Unforgiven Rare Spawn

### ISSUE THREAD

**Issue by ghost** [classicdb/database#192]
- Rare spawn does not spawn ever on most servers. {Did not show up even once}

**Comment by cala** [comment]
Thank you. This creature (10516) is indeed missing in the DB.

**Comment by cala** [comment]
After a bit more research, it seems that The Unforgiven is spawned by script, with 3-4 adds Vengeful Phantoms (10387). At spawn, they start moving slowly toward the living part of the instance. The boss and adds are not linked (aside from normal assistance). The spawn is probably scripted with a nearby area trigger.

In summary, this should be handled by SD2 and not by DB. Closing here, will be handled by SD2.

**Comment by cala** [comment]
Possible way to spawn him (to investigate): NPC 14646 (Stratholme Trigger)
May also be related to Tier 0.5 event.
