### ISSUE TITLE
[Stratholme] Canon Master Willey Mechanics

### ISSUE THREAD

**Issue by ghost** [classicdb/database#193]
- Never spawns adds that shoot you from the end of the room requiring you to use the ammo to use the cannons and kill them.
- The canons shoot you every time you walk past the area the adds are meant to be spawned.

**Comment by TheTrueAnimal** [comment]
NPC: http://de.wowhead.com/npc=10997

Sources:
https://web.archive.org/web/20070123130802/http://wow.allakhazam.com/db/mob.html?wmob=10997
https://www.youtube.com/watch?v=ZmSRo8AUVrI
http://www.almarsguides.com/wow/instances/strathliving.cfm
