### ISSUE TITLE
[Stratholme] The slaughter House Baron room functionality

### ISSUE THREAD

**Issue by ghost** [classicdb/database#196]
- Menethil's gift is an intractable doodad {shouldn't be}
- Unholy aura does not appear on debuff bar {Not 100% it should}
- Ysida Harmon is not spawned for the 45 minute run as a part of the T 0.5 quest. She is to be there and then killed after       45 minutes {Or if everyone loses "The Baron Ultimatum" From death.}

**Comment by cala** [comment]
Closed by https://github.com/cmangos/mangos-classic/commit/cf63af912c3e7d2891903854d1ef6eca64c835a1
