### ISSUE TITLE
[Dire Maul East] Alzzin the Wildshaper Fight mechanics

### ISSUE THREAD

**Issue by ghost** [classicdb/database#197]
- Does not use Dire Wolf Form or Tree Form as a part of his fight.
- Alzzin's minions do not spawn in the cave and run out, instead spawn near the vine.

**Comment by cala** [comment]
Thank you for this report. I poke @X-Savior on this as the wolf/tree form are currently written in the ACID script of Alzzin (creature 11492) and should work. Yet, they do not.

**Comment by cala** [comment]
Fixed in a ACID pull request: https://github.com/ACID-Scripts/Classic/pull/16
