### ISSUE TITLE
[Dire Maul North] Traps required for tribute run

### ISSUE THREAD

**Issue by ghost** [classicdb/database#201]
- Broken traps do not activate after having the items and turning in the quest {required to skip Slip'kik for tribute run as 
   it freezes the mob that enters it

**Comment by TheTrueAnimal** [comment]
Quest: http://www.wowhead.com/quest=1193/a-broken-trap
Object: http://www.wowhead.com/object=179485/broken-trap
NPC: http://www.wowhead.com/npc=14323/guard-slipkik
Video: https://www.youtube.com/watch?v=AND-5oZBPc4

**Comment by cala** [comment]
Not fixed yet but first step done in https://github.com/classicdb/database/commit/94a05ca598dc32a62d531aa43f4ae831511afda4
