### ISSUE TITLE
[Dire Maul North] Gordok Ogre suit functionality

### ISSUE THREAD

**Issue by ghost** [classicdb/database#202]
- The Gordok Ogre Suit enables a lot of the "You are the new king" tribute run related dialogue. This should only be     readable and intractable if you do a tribute run and become king.
- Not all ogres become friendly once the suit is equipped.

**Comment by Tobschinski** [comment]
> Not all ogres become friendly once the suit is equipped.

This is the correct behavior, only Captain Kromcrush has the appropriate faction to interact with.

> The Gordok Ogre Suit enables a lot of the "You are the new king" tribute run related dialogue. This should only be readable and intractable if you do a tribute run and become king.

Lots of guards had Kromcrush's faction. This was changed. He is the only one left you can have a talk with while being suited.

**Comment by evil-at-wow** [comment]
> He is the only one left you can have a talk with while being suited.

... at least before you've talked to him and have sent him to Guard Fengus. He'll be red again once he's on his way to smack Fengus.

**Comment by cala** [comment]
Unless I'm mistaken, this could be closed since the factions were fixed and the issue was related to the interaction with NPCs having wrong faction while wearing the suit. Am I right?

**Comment by Tobschinski** [comment]
There is no script that could be performed but he will at least talk to you now. I'm on it. (I still think these unique events must not be done by db_scripting, but let's see ...)

**Comment by TheTrueAnimal** [comment]
Here are some videos:
https://www.youtube.com/watch?v=UbTubo90MiI
https://www.youtube.com/watch?v=AND-5oZBPc4

http://wow.gamepedia.com/Dire_Maul_tribute_run

**Comment by cala** [comment]
Closed by:
https://github.com/cmangos/classic-db/commit/2dbbee7649353124915e0f3e445aed999a998209
https://github.com/cmangos/classic-db/commit/4bc46cb25c3915f1d69793519f1a7396f4d83426
https://github.com/cmangos/classic-db/commit/c6cece0d7e350306902b9e9678c88e78b166982f
