### ISSUE TITLE
[Dire Maul North] King of the Gordok buff

### ISSUE THREAD

**Issue by ghost** [classicdb/database#204]
- King of the Gordok should make all the ogres friendly.

**Comment by TheTrueAnimal** [comment]
Some Ogres are friendly, others aren't. Some creatures seem to belong to a wrong fraction. All ogres outside of the instance are friedly and belong to faction 45, while the ones inside belong to faction 45. 

UPDATE `creature_template` SET `factionalliance` = 45, `factionhorde` = 45 WHERE `entry` IN (13160, 13036, 14326, 11441, 11444, 14322, 14321, 11448, 14385, 14386, 14323, 14351, 14325, 11445, 14324, 11446);

The Buff should disappear when you reset the instance but it doesn't. You can only get rid of it by dying.

**Comment by Tobschinski** [comment]
Coincidentally, I've done this yesterday.
https://github.com/classicdb/database/commit/1e0e535e9f0492d8138c7e4d39c2a04119ddfe77

**Comment by cala** [comment]
Nice, thank you. :+1:
