### ISSUE TITLE
[Upper Blackrock Spire] Hall of Binding room and boss 

### ISSUE THREAD

**Issue by ghost** [classicdb/database#208]
- Event seems no functioning. {starts the boss fight}
- You are to right click the pedestal and after some time the channelling mobs all charge you. Once they all die the boss rp's then slowly grows with some fire tornado's around him then become active.

**Comment by cala** [comment]
I'm surprised by this report. The event was fixed two months ago and tested successfully. Can you confirm that you can not start it when _three_ players click on the pedestral?

The visual effects (size increase and fire tornado) are indeed missing, IIRC, but this have to be handled via SD2 as an improvement of the current script.

**Comment by ghost** [comment]
I don't have my localhost any more, but I attempted starting it solo and thought it was possibly, my mistake.
