### ISSUE TITLE
[Upper Blackrock Spire] Finkle Einhorn spawn in The Furnace

### ISSUE THREAD

**Issue by ghost** [classicdb/database#209]
- Finkle Einhorn is double spawned. In the back of the cave, and when the beast dies.

**Comment by cala** [comment]
Thank you. I had noticed before it but forgot to fix it when I revamp Black Rock Spire two months ago. 
This query should fix it:

``` SQL
DELETE FROM `creature` WHERE `id` = 10776 and `map` = 229;
```

**Comment by ghost** [comment]
Should I close this then?

**Comment by cala** [comment]
No, wait until the fix is pushed (or it may be forgotten ;) )
