### ISSUE TITLE
Quest 1383 cannot be completed and should be revert to pre-TBC

### ISSUE THREAD

**Issue by cala** [classicdb/database#21]
Added previous questid to quest 1388 because it where available before you finished the first two quests of the line.

Correcting the Quest 1383 to pre TBC Questtext, got from waybackmachine-goblin workshop. Made Deepstrider tumor drop from deepstriders instead of dreaming whelps.

Submitted commit: https://github.com/Evildead666/database/commit/119662db68d9dca158857c5602ea7bf9fe21c923

_original report by [Evildead666](https://github.com/Evildead666)_

**Comment by Swater96** [comment]
This fix has been tested and should be implemented by next update!
- Swater96

**Comment by cala** [comment]
Thank you for testing. I'll push it soon(tm).

**Comment by cala** [comment]
Fixed in rev [0136] https://github.com/classicdb/database/commit/b20c685f135808e7d6ad97b95fddbcbc8453c6ee
