### ISSUE TITLE
Quest "Traitor to the Bloodsail" currently allows to gain unlimited REP with Booty Bay easily

### ISSUE THREAD

**Issue by Neotmiren** [classicdb/database#218]
UPDATE quest_template SET RequiredMaxRepValue=-1, RewRepFaction3=0, RewRepFaction4=0, RewRepFaction5=0, RewRepValue3=0, RewRepValue4=0, RewRepValue5=0 WHERE  entry=9259;

1) max REP should be limited to below Neutral.

2) this fix assumes that core automatically gives REP/2 with other Steamwheedle Cartel factions every time Booty Bay REP is gained (this is how my version of core works, but I am uncertain about unmodified Classic CMangos core).

**Comment by cala** [comment]
Thank you for this fix.

> 2) this fix assumes that core automatically gives REP/2 with other Steamwheedle Cartel factions every time Booty Bay REP is gained (this is how my version of core works, but I am uncertain about unmodified Classic CMangos core).

This is determined by the `reputation_spillover_template` table in the database and the core only looks up for the rate stored there. Classic DB should have the correct values for this, at least for Steamwheedle Cartel (checked just now).

**Comment by Neotmiren** [comment]
Yes, unmodified core probably correctly computes using reputation_spillover_template but it does not show +REP for allies if I remember correctly.
