### ISSUE TITLE
Missing questgiver NPC "Connor Rivers" (Stormwind)

### ISSUE THREAD

**Issue by Neotmiren** [classicdb/database#219]
INSERT creature SET id=5081, map=0, position_x=-9102, position_y=834.873, position_z=105.117, orientation=5.18, spawntimesecs=600, spawndist=0, curhealth=713, curmana=0, MovementType=0;

**Comment by cala** [comment]
Thank you. Shame on me: I spent some time recently in the Blue Recluse Inn in order to (unsuccessfully yet) fix a mage quest and I did not notice this NPC was missing.

**Comment by Neotmiren** [comment]
It would be nice to have Mage quest in Blue Recluse implemented. I checked it in various WoW cores / DBs but have never seen it fully working so far.

**Comment by cala** [comment]
That would be nice, indeed. Any input you can have regarding this quest would be welcome.
Currently, the only improvement I was able to do is:

``` SQL
-- Added missing spawns of creature 6492 (Rift Spawn) in Stormwind
-- for quest 1920 (Investigate the Blue Recluse)
-- Spawn positions based on: http://www.wowhead.com/quest=1920 and retail experience of the quest
DELETE FROM `creature` WHERE `guid` IN (34021, 34022, 34023, 34024);
INSERT INTO `creature` VALUES
(34021, 6492, 0, 0, 0, -9074.49, 822.55, 108.42, 5.26, 600, 11, 0, 356, 0, 0, 1),
(34022, 6492, 0, 0, 0, -9102.23, 836.88, 105.13, 4.15, 600, 11, 0, 356, 0, 0, 1),
(34023, 6492, 0, 0, 0, -9060.98, 837.11, 109.20, 5.28, 600, 11, 0, 356, 0, 0, 1),
(34024, 6492, 0, 0, 0, -9089.42, 827.14, 115.68, 1.16, 600, 11, 0, 356, 0, 0, 1);
```

Some spell relation/target are also probably missing, but I'm afraid the whole quest will require SD2 to be functionnal.

**Comment by Schmoozerd** [comment]
I took a short glimpse to wowhead related to this quest.
There is clearly some invisibility aura involved, this should be no problem.

Catching the npcs is likely to be done with some dummy spell, this might be doable with dbscripts_on_spellhit

From the comments it might also be the case that these npcs are actually summoned - well, it depends on the spells :)

**Comment by cala** [comment]
Thank you Schmoozerd for these inputs.

With all the recent issues reports (50+ o_O), the coming changes to `creature_template` table and the current work on Naxxramas, my hands are quite full but I'll see what I can do for this nice and easy quest. :)
