### ISSUE TITLE
Quest 652 is missing its complete script

### ISSUE THREAD

**Issue by cala** [classicdb/database#22]
Added spawn and attackscript for Thenan when quest 562 Breaking the Keystone is finished.

Submit commit: https://github.com/Evildead666/database/commit/234cf54a32be64a89cdee51c56cc85075e2994de

_original report by [Evildead666](https://github.com/Evildead666)_

**Comment by Swater96** [comment]
This fix has been tested and should be implemented by next update!
- Swater96

**Comment by cala** [comment]
Thank you for testing. I'll push it soon(tm).

**Comment by cala** [comment]
Fixed in rev [0137] https://github.com/classicdb/database/commit/51955208e8d6dab22255a5fcd3e7718a277db093
