### ISSUE TITLE
[BattleGrounds] Arathi Basin, Alterac Valley Flag Functionality

### ISSUE THREAD

**Issue by ghost** [classicdb/database#220]
- When capturing a flag if the flag turns over while you are channelling your channel should finish but not be successful.
   Alliance contest horde flag -> horde channels at 8 sec left -> turns over -> finishes cast and instantly turns back to          horde controlled skipping contesting.

**Comment by cala** [comment]
Should be working as intended now that BattleGrounds code in core was refactored in the past months.
