### ISSUE TITLE
[Scholomance] Lord Alexei loot table

### ISSUE THREAD

**Issue by scotty0100** [classicdb/database#226]
Source: http://www.wowwiki.com/Lord_Alexei_Barov

Patch 1.4.0 (2005-05-05): Lord Alexei Barov will now always drop at least one Rare item.

Currently is 1% drop rate.

Other mini bosses should potentially drop rares more commonly, but haven't found solid sources to back that up yet..

**Comment by ghost** [comment]
- Rattlegore, Jandice Barov, and Lord Alexei Barov will now always drop at least one Rare item.
  Ras Frostwhisper will always drop at least two Rare items.
  I believe all the others where still considered mini bosses where as Alexei was hard enough to warrant one rare every time.
  http://www.wowwiki.com/Patch_1.4.0

**Comment by cala** [comment]
Thank you for the report and comments.
Scholomance is my favorite 5-man dungeon and it is a pity I made only one commit about it since the first release of Classic DB. :(
There are many things to deal with currently, but I will bring special love to this instance when I can.

**Comment by Swater96** [comment]
Rattlegore, Jandice Barov, and Ras Frostwhisper are dropping correctly. Lord Alexei Barov seems to be dropping only mats and silver and rarely drops anything decent. 

Here is a corrected loot table that adds everything that is missing from him...

-- Lord Alexei Barov Loot --
INSERT INTO creature_loot_template (entry, item, ChanceOrQuestChance, groupid) VALUES ('10504', '14611', '0', '1');
INSERT INTO creature_loot_template (entry, item, ChanceOrQuestChance, groupid) VALUES ('10504', '14612', '0', '1');
INSERT INTO creature_loot_template (entry, item, ChanceOrQuestChance, groupid) VALUES ('10504', '14614', '0', '1');
INSERT INTO creature_loot_template (entry, item, ChanceOrQuestChance, groupid) VALUES ('10504', '14615', '0', '1');
INSERT INTO creature_loot_template (entry, item, ChanceOrQuestChance, groupid) VALUES ('10504', '14616', '0', '1');
INSERT INTO creature_loot_template (entry, item, ChanceOrQuestChance, groupid) VALUES ('10504', '14620', '0', '1');
INSERT INTO creature_loot_template (entry, item, ChanceOrQuestChance, groupid) VALUES ('10504', '14621', '0', '1');
INSERT INTO creature_loot_template (entry, item, ChanceOrQuestChance, groupid) VALUES ('10504', '14622', '0', '1');
INSERT INTO creature_loot_template (entry, item, ChanceOrQuestChance, groupid) VALUES ('10504', '14623', '0', '1');
INSERT INTO creature_loot_template (entry, item, ChanceOrQuestChance, groupid) VALUES ('10504', '14624', '0', '1');
INSERT INTO creature_loot_template (entry, item, ChanceOrQuestChance, groupid) VALUES ('10504', '14626', '0', '1');
INSERT INTO creature_loot_template (entry, item, ChanceOrQuestChance, groupid) VALUES ('10504', '14629', '0', '1');
INSERT INTO creature_loot_template (entry, item, ChanceOrQuestChance, groupid) VALUES ('10504', '14631', '0', '1');
INSERT INTO creature_loot_template (entry, item, ChanceOrQuestChance, groupid) VALUES ('10504', '14632', '0', '1');
INSERT INTO creature_loot_template (entry, item, ChanceOrQuestChance, groupid) VALUES ('10504', '14633', '0', '1');
INSERT INTO creature_loot_template (entry, item, ChanceOrQuestChance, groupid) VALUES ('10504', '14636', '0', '1');
INSERT INTO creature_loot_template (entry, item, ChanceOrQuestChance, groupid) VALUES ('10504', '14637', '0', '1');
INSERT INTO creature_loot_template (entry, item, ChanceOrQuestChance, groupid) VALUES ('10504', '14638', '0', '1');
INSERT INTO creature_loot_template (entry, item, ChanceOrQuestChance, groupid) VALUES ('10504', '14640', '0', '1');
INSERT INTO creature_loot_template (entry, item, ChanceOrQuestChance, groupid) VALUES ('10504', '14641', '0', '1');
INSERT INTO creature_loot_template (entry, item, ChanceOrQuestChance, groupid) VALUES ('10504', '18680', '0', '1');
INSERT INTO creature_loot_template (entry, item, ChanceOrQuestChance, groupid) VALUES ('10504', '18681', '0', '1');
INSERT INTO creature_loot_template (entry, item, ChanceOrQuestChance, groupid) VALUES ('10504', '18682', '0', '1');
INSERT INTO creature_loot_template (entry, item, ChanceOrQuestChance, groupid) VALUES ('10504', '18683', '0', '1');
INSERT INTO creature_loot_template (entry, item, ChanceOrQuestChance, groupid) VALUES ('10504', '18684', '0', '1');
INSERT INTO creature_loot_template (entry, item, ChanceOrQuestChance, groupid) VALUES ('10504', '23200', '0', '1');
INSERT INTO creature_loot_template (entry, item, ChanceOrQuestChance, groupid) VALUES ('10504', '23201', '0', '1');

**Comment by cala** [comment]
Thank you, but if you look at entry 35031 in `reference_loot_table` you will see the exact same list. Lord Alexei Barov is currently using that table, which is shared with the other five mini-bosses involved in popping Darkmaster Gandling. The error is that Lord Alexei Barov has 60% chance to drop something from that table while it should be 100%. I started working on this a few days below (not yet finished). Below is what I got for various Scholomance bosses until now:

``` SQL
-- Lord Alexei Barov (10504): added missing entries, increased chance to drop rare item (blue item) to 100%
-- Source: http://www.wowwiki.com/Lord_Alexei_Barov#Patch_changes
UPDATE `creature_loot_template` SET `ChanceOrQuestChance` = 100 WHERE `entry` = 10504 AND `item` = 35031;
INSERT INTO `creature_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `groupid`, `mincountOrRef`, `maxcount`, `condition_id`) VALUES 
(10504, 5759, 0.3419, 0, 1, 1, 0),
(10504, 8766, 1.9034, 0, 1, 1, 0),
(10504, 8932, 3.7725, 0, 1, 1, 0),
(10504, 13444, 0.4787, 0, 1, 1, 0), -- Major mana potion
(10504, 13446, 0.7864, 0, 1, 1, 0), -- Major healing potion
(10504, 24024, 10, 0, -24024, 1, 0); -- world loot reference table for similar bosses

-- Lady Illucia Barov (10502): added missing entries (some generic and some specific like dark rune)
-- Source: http://www.wowwiki.com/Lady_Illucia_Barov#Loot
INSERT INTO `creature_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `groupid`, `mincountOrRef`, `maxcount`, `condition_id`) VALUES 
(10502, 5759, 0.3419, 0, 1, 1, 0),
(10502, 7972, 4.1203, 0, 1, 1, 0),
(10502, 8766, 1.9034, 0, 1, 1, 0),
(10502, 8948, 3.7725, 0, 1, 1, 0),
(10502, 12808, 1.9921, 0, 1, 1, 0),
(10502, 13444, 0.4787, 0, 1, 1, 0), -- Major mana potion
(10502, 13446, 0.7864, 0, 1, 1, 0), -- Major healing potion
(10502, 18335, 1, 0, 1, 1, 0), -- Pristine black diamond
(10502, 20520, 51.4353, 0, 1, 1, 0), -- Dark runes
(10502, 24024, 10, 0, -24024, 1, 0); -- world loot reference table for similar bosses

-- Jandice Barov (10503)
-- Source: http://www.wowwiki.com/Jandice_Barov#Loot
INSERT INTO `creature_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `groupid`, `mincountOrRef`, `maxcount`, `condition_id`) VALUES 
(10503, 7972, 3.5331, 0, 1, 1, 0),
(10503, 8766, 1.4798, 0, 1, 1, 0),
(10503, 8948, 2.7747, 0, 1, 1, 0),
(10503, 12808, 2.2383, 0, 1, 1, 0),
(10503, 13444, 0.444, 0, 1, 1, 0), -- Major mana potion
(10503, 13446, 0.7584, 0, 1, 1, 0), -- Major healing potion
(10503, 14543, 0, 1, 1, 1, 0),
(10503, 18335, 1, 0, 1, 1, 0), -- Pristine black diamond
(10503, 24024, 10, 0, -24024, 1, 0); -- world loot reference table for similar bosses

-- Ras Frostwhisper (10508): updated reference table as some element in it shouldn't be in (like Alanna's Embrace)
-- added missing entries (mostly generic entries)
-- http://www.wowwiki.com/Ras_Frostwhisper#Loot
DELETE FROM `reference_loot_template` WHERE `item` = 13314;
INSERT INTO `creature_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `groupid`, `mincountOrRef`, `maxcount`, `condition_id`) VALUES 
(10508, 5760, 0.379, 0, 1, 1, 0), -- Eternium lock box
(10508, 7972, 3.596, 0, 1, 1, 0),
(10508, 8766, 1.56, 0, 1, 1, 0),
(10508, 8948, 3.358, 0, 1, 1, 0),
(10508, 12808, 2.3621, 0, 1, 1, 0),
(10508, 13314, 2, 0, 1, 1, 0), -- Alanna's Embrace
(10508, 13444, 0.4319, 0, 1, 1, 0),
(10508, 13446, 0.9607, 0, 1, 1, 0),
(10508, 18335, 1, 0, 1, 1, 0),
(10508, 24024, 10, 0, -24024, 1, 0); -- world loot reference table for similar bosses

-- Rattlegore (11622)
```

**Comment by kokeszko** [comment]
maybe a bit offtopic. do you accept http://web.archive.org/web/20060708184047/http://wow.allakhazam.com/db/mob.html?wmob=10508
as a source of percentage value of a "chance of dropping" of an item?
or maybe another way, is it acceptable source of information or there is another way to find that value?

**Comment by cala** [comment]
Tricky question... There are no real "valid source" for item drop chances because those values always stay on blizz servers side and are never sent to the clients. So every value known to allakhazam, wowhead and such are statistical estimations based on players reports (through addons). As such, their reliability relies mostly on how the statistics are computed (and if there is enough data to compute something meaningful)...

In my humble opinion:
- such sources as a reliable as one can be
- values could be safely rounded to the nearest half dozen (_i.e._ every drop chance should end by "0" or "5") except for drop chance below 10%
- having digits after the dot is irrelevant (except for drop chance below 1% though I don't think those truly exist but are probably a statistical interpretation of 1 item being picked in a large pool)
- if the drop chance for the same item in Classic DB is not very far from what the source says it is, keep the current Classic DB value (we want to try to keep as much compatibility as possible with other DBs projects like TBC-DB and UDB). When possible, check also UDB/TBC-DB.

I hope this answer your question. :)

**Comment by Schmoozerd** [comment]
Lastly - it has no impact on the game-feeling if a dropchance is 5, 7, or 8.3% ;)
Usually it appears blizz groups things in some estimation groups, sometimes weighted to reflect some kind of fairness (ie a Tier-token that is usable for 4 classes might drop more frequent than a tier-token that is usable only for 3 classes)

**Comment by Swater96** [comment]
So is boss loot handled in reference?

**Comment by Sinoxan** [comment]
Reference tables are for when multiple creatures drop similar things, usually whites and greys, so only items that are unique to that boss need to go in creature_loot_template.  Then multiple creatures share the same reference tables, mobs around the same level or area.

**Comment by PatSmuk** [comment]
With only a few exceptions (these bosses probably being one of them), no, boss loot should not be put in a reference.

**Comment by PatSmuk** [comment]
@cala You said you increased it to 100% but from looking at it:

``` sql
(10504, 24024, 10, 0, -24024, 1, 0); -- world loot reference table for similar bosses
```

That will only drop 10% of the time. Am I missing something?

**Comment by cala** [comment]
I was refering to the reference table 35051 which holds all the blue items shared by the six mini bosses in Scholomance. I update to 100% the drop chance of that table by Alexei Barov in the first query above.
Reference table 24024 is one of the tables holding generic world drops like some grey, green or recipes. This is one of the generic tables used by the mobs in Scholomance and currently missing from most of the bosses loot table. :)
