### ISSUE TITLE
Quest 3124 - 3127 are missing spell scripts

### ISSUE THREAD

**Issue by cala** [classicdb/database#23]
Added scripts for spells 11885, 11886, 11887, 11888, 11889
Despawning the corpse after the muisek Vessel got used.

Submitted commit: https://github.com/Evildead666/database/commit/d530fa1deb40039af7ece3aaf5984d3b41c72013

_original report by [Evildead666](https://github.com/Evildead666)_

**Comment by Swater96** [comment]
This fix has been tested and should be implemented by next update!
- Swater96

**Comment by cala** [comment]
Thank you for testing. I'll push it soon(tm).

**Comment by cala** [comment]
Fixed in rev [0138] https://github.com/classicdb/database/commit/18153dffd74a87522fa3152dbd9aeffa44467a13
