### ISSUE TITLE
[Model] Tauren Druid Travel/Cat form scale

### ISSUE THREAD

**Issue by ghost** [classicdb/database#231]
- The travel form is nearly two times the proper size.
- The cat for is about one and half times the proper size.

**Comment by cala** [comment]
Thanks for this report. At first glance, I don't know how druid forms are handled, so I think a bit of research will be needed on this one.

**Comment by ghost** [comment]
Well the way it worked in vanilla is; when you switched to the form you would then shrink down. So maybe it was a script blizzard made? Or is it possible for the form to have an independent scale from the humanoid form.

**Comment by PatSmuk** [comment]
Fixed: https://github.com/cmangos/mangos-classic/pull/51

**Comment by cala** [comment]
Thank you @Patman64 . One the Pull Request is accepted, we can close the issue here.

**Comment by cala** [comment]
Closing: core issue, nicely fixed by Patman64.
