### ISSUE TITLE
[GO] Too Much Milly's Harvest

### ISSUE THREAD

**Issue by PatSmuk** [classicdb/database#232]
The barrels of grapes in Northshire Valley called "Milly's Harvest" are overspawned. They need to be put into a spawn pool.

**Comment by cala** [comment]
Thank you. I also noticed that, long ago when I first tried mangos but as I lacked the skill to fix this at the time, this moved out of my mind.
Do you have any idea of what ratio would be good for the pool? My guess would be 1/3 (maybe 1/4).

**Comment by PatSmuk** [comment]
I counted 32 of them so I think having 8 up at a time would be more appropriate.
