### ISSUE TITLE
[Warrior] [Paladin] [Spellbook] - Skills show up once per rank

### ISSUE THREAD

**Issue by Tobschinski** [classicdb/database#233]
I have multiple 'Heroic Strike (Rank 2)' (and Rend) in my spellbook. 

![warrior spellbook visual - skills show up once per rank](https://f.cloud.github.com/assets/4753528/2059075/5c91bfba-8b95-11e3-9615-683b4f13b748.jpg)

There should be just one with the highest possible rank I have learned so far (as http://www.wowwiki.com/Downranking was not a valid option for warriors back in vanilla).

EDIT: After restarting, the redundant skills have been gone.

**Comment by Tobschinski** [comment]
Reopening it, since this bug is permanent on my paladin.

![paladinskillbook](https://f.cloud.github.com/assets/4753528/2062125/8b479a80-8c7d-11e3-9a7d-2702208cf4f8.png)

One tooltip contains more information.

![paldifftooltip](https://f.cloud.github.com/assets/4753528/2062151/73426f40-8c7e-11e3-9608-be9a4bba422c.jpg)

**Comment by cala** [comment]
Thanks for the report. I think this issue can only be handled by core also. Thus, I suggest you to re-open this issue here: https://github.com/cmangos/issues/ instead.
I'll probably close this one in a week or two.
