### ISSUE TITLE
[Looting] - How it should work / how it is working right now!

### ISSUE THREAD

**Issue by Tobschinski** [classicdb/database#235]
There are 5 different options a leader can choose to distribute http://www.wowwiki.com/Loot and one special procedure to quest-items.

![5lootingoptions](https://f.cloud.github.com/assets/4753528/2061875/d2d97a06-8c70-11e3-9e49-b64060e65128.png)

Right now, many loot options do not work as intended.

e.g. Group-looting, the standard option, is a mix between free for all and need before greed. Every single player that has been involved in killing the mob, is able to loot it. (gold, quest-items, items of all qualities). 

As the basics of looting are untouched, these following information are still valid for vanilla realms.

**Comment by Tobschinski** [comment]
Free-for-all

First-come, first-serve. All players that have been involved in killing the mob, are able to loot it. 

There is a glitter effect and changing cursor for everyone.

You will see every single item the mob has dropped. Gold (shared within the group after looting), quest-items (if you are on that certain quest), bop and boe items of all qualities. 

If the item you are trying to loot is bop, you will get the confirmation window.

**Comment by Tobschinski** [comment]
Round Robin

 Party members take turns looting corpses. Seems like it might be fair, "What drops, drops". The first player is allowed to loot the first mob, the second player the second mob and so on.

You will never see the loot of a mob, there won't be any glitter effect, no changed cursor, unless it is your turn to loot.

Additionally, this is regardless of the items that were dropped. If the second mob drops an epic item, only the second player is able to loot it or even see it. 
Same goes for gold, even though it is shared within the group after looting.

**Comment by Tobschinski** [comment]
Group Loot

Same as Round Robin, but the leader can choose a certain threshold 'uncommon', 'rare', 'epic' (uncommon is standard). 
Items that have a higher or even quality are distributed via rolling (need, greed, pass) and visible by any party member as an option to loot. (changed cursor, glitter effect)

**Comment by Tobschinski** [comment]
Master Looter

Same as Round Robin, but the leader can choose a certain threshold (uncommon, are, epic). Items that have a higher or even quality are distributed via master looting. (The leader decides which player will get the item).

**Comment by Tobschinski** [comment]
Need before Greed

Never used it, on retail, you pass automatically if you cannot use it. But I am something like 99% sure, this was not the case in vanilla. Yet to gather more information.

**Comment by Tobschinski** [comment]
Quest Loot

Quest loot is on a separate loot distribution and there are two common modes for this to occur. 

1) In quests where the party is to collect one of a specific item from a specific mob (Collect the head of (mob name here)) then regardless of loot setting, the mob will indicate lootable by every party member with the quest (and without the object). Each member may loot the quest item off the corpse. The other loot on the corpse is subject to the party loot setting.

 2) In other quests which require collecting several items of a type (harpy feathers for example), the quest items will drop on some mobs and be looted in the normal way, except that if the current looter can't collect the items (not on quest, already has full set) then the quest loot is ffa for those members who can still pick up the quest items. Other items on the corpse are governed by the party loot setting.

**Comment by Tobschinski** [comment]
No Loot

If a mob does not contain any item to loot, it will not show a glitter effect nor a cursor. No loot window will open on rightclicking it.

**Comment by cala** [comment]
Thank you for this report. Like some of the previous, I think this issue can only be handled by core. Thus, I suggest you to re-open this issue here: https://github.com/cmangos/issues/ instead. Like other issues opened here, you can add a link pointing to here to help keep track of the whole discussion.
I'll probably close this one in a week or two.

**Comment by Tobschinski** [comment]
https://github.com/cmangos/issues/issues/376
