### ISSUE TITLE
[Quest] [Westfall] - Captain Sander's Treasure Map set at 100% drop rate

### ISSUE THREAD

**Issue by Tobschinski** [classicdb/database#237]
http://web.archive.org/web/20071106055404/http://www.wowhead.com/?item=1357

The following mobs have Captain Sander's Treasure Map (ID 1357) incorrectly set at 100% drop rate:

Murloc Coastrunner (126)
Murloc Tidehunter (127)
Murloc Warrior (171)
Old Murk-Eye (391)
Murloc Minor Oracle (456)
Murloc Hunter (458)
Murloc Netter (513)
Murloc Raider (515)
Murloc Oracle (517)
Slark  (519)
Brack  (520)

It should be more like http://www.wowhead.com/item=1357 although values may be slightly different.

**Comment by cala** [comment]
Thank you for pointing this and providing improved values.
