### ISSUE TITLE
[Quest] [Mob] [Elwynn Forest] Princess' hostility.

### ISSUE THREAD

**Issue by Tobschinski** [classicdb/database#238]
Princess (http://old.wowhead.com/npc=330) and her followers should be neutral to both, alliance and horde, not hostile. 

http://www.youtube.com/watch?v=X4vPtdxOZyE#t=200

**Comment by cala** [comment]
Thank you for this report. I'll take this opportunity to also check that the bodyguards are also linked to Princess (entry 330).
