### ISSUE TITLE
Reward spell in quest 3567 has wrong source

### ISSUE THREAD

**Issue by cala** [classicdb/database#24]
Removing the you learn from quest window, and using dbscripts_on_quest_end for spellcasting so marli casts spell on player, otherwise player cast spell on himself/herself, which looks wrong

Submitted commit: https://github.com/Evildead666/database/commit/a15f4f7f5d7948c35910b24c283952e11ca0f17f

_original report by [Evildead666](https://github.com/Evildead666)_

**Comment by Swater96** [comment]
This fix has been tested and should be implemented by next update!
- Swater96

**Comment by cala** [comment]
Again: Thank you for testing. I'll push it soon(tm). :)

**Comment by cala** [comment]
Fixed in rev [0139] https://github.com/classicdb/database/commit/05f01ef53e43222d4a725da89191b7f42807d77c
