### ISSUE TITLE
[Quest] All Along the watchtowers

### ISSUE THREAD

**Issue by ghost** [classicdb/database#242]
- Western Plaguelands quest that has you place torches at the entrance of each tower in Andorhol. The quest doesn't not register placing the torch so it is not completable.
  ![untitled](https://f.cloud.github.com/assets/6431336/2076045/1141c486-8d9a-11e3-8d39-d738d3412f60.png)

**Comment by cala** [comment]
This quest is handled via SD2. I had a quick look at the code and I assume some NPCs are missing in the database.

**Comment by ghost** [comment]
NPCs? You are just suppose to fight your way to each and use the torch and it marks it. But the one thing is the torch does just spawn on your head and is smaller than it is suppose to me. You play a throwing animation. It is suppose to land in the doorway.

**Comment by cala** [comment]
Yes, the four lines "Tower marked 0/1" in your screenshot are in fact credits given by NPC killed via script. Gameobjects are also involved. I need to check if some of them (NPC, GO) are missing in the database.

**Comment by evil-at-wow** [comment]
I see the torch in the screenshot, so assuming this is a screenshot of your own server at least that part works (it's a summoned GO). The tower objects involved are indeed scripted in SD2 (go_andorhal_tower), but they need to be activated when using the Beacon Torch to get the quest credit. I'm guessing you're missing the spell_script_targets, because TBC-DB had the same issue long ago. @Nekoi should see warnings in the server logs if those are missing (spell 17016).

I fixed them in TBC-DB 1.2.1 with this data:
`
INSERT INTO `spell_script_target` VALUES 
(17016, 0, 176094),
(17016, 0, 176095),
(17016, 0, 176096),
(17016, 0, 176097);`

I did notice back then that the gameobject_template data for those four GOs said "UDB_First_Andorhal_Tower" and so on, so the GO data in TBC-DB is clearly coming from UDB.

**Comment by cala** [comment]
Thanks evil-at-wow. After checking, those script target entries are already in the database and the targets themselves are already spawned in DB. So, I think I will have to test the quest and dig into the error log to spot what is missing...

**Comment by Schmoozerd** [comment]
edit: hmm no - there should be no need for additional npcs
player cast spell and uses GO => GO Script is triggered

Check the effect of the related spell ;)

**Comment by cala** [comment]
```
**Advanced Info**
Spell Level = 0, BaseLevel 0, MaxLevel 0, MaxTargetLevel 0
Category = 0
DispelType = 0 (DISPEL_NONE)
Mechanic = 0 (MECHANIC_NONE)
SpellRange (Id 12) "Interact Range"
MinRange = 0
MaxRange = 5
CastingTime (Id 31) = 2.30
Duration: ID (22) 45000, 0, 45000
Interrupt Flags: 0x0000000F, AuraIF 0x00000000, ChannelIF 0x00000000
Requires Spell Focus 805
Chance = 101, charges - 0
**Effect 0:**
Id: 50 (SPELL_EFFECT_TRANS_DOOR)
BasePoints = 1
Targets (47, 0) (TARGET_DYNAMIC_OBJECT_FRONT, NO_TARGET)
EffectMiscValue = 176093
**Effect 1:**
Id: 86 (SPELL_EFFECT_ACTIVATE_OBJECT)
BasePoints = 1
Targets (40, 0) (TARGET_FOCUS_OR_SCRIPTED_GAMEOBJECT, NO_TARGET)
EffectMiscValue = 5
```

If I understand correctly, the first effect spawn the visual torch GO (seem to works), the second effect triggers GO and as the spell_script_target entries are there, this should also work.
I'd better have a look at the log. Unless there is a range error somewhere (spell range is very short: 5 yards)

**Comment by Schmoozerd** [comment]
you can always do a debug-session to the spell-effect or maybe even spell-targeting.
the spells' effect 1 should hit the already spawned GO (UDB_ANDORHAL_TOWER_X named i think)
And these GOs should have the SD2-script assigned, which then must be triggered and give the quest-credit.

**Comment by cala** [comment]
This also is what I thought after peering onto the script code and checking that GOs are already spawned (with script assigned). So, this _should_ be working and this is why I want to test this by myself. :)

**Comment by cala** [comment]
Tested yesterday and working. However, the credit was not always given after spell cast. If the player moves a bit and cast again, the credit is given. I assume there is some range issue here, but I remember this being that way back in Classic days.

**Comment by evil-at-wow** [comment]
Yes, positioning is crucial. The position as shown in the screenshot is not good enough. You really need to stand in the doorway to get credit.

**Comment by TheTrueAnimal** [comment]
I just started lighting the torch and it will give you a "must get closer" message, just inched forward until I torched it. https://web.archive.org/web/20070312121423/http://wow.allakhazam.com/db/quest.html?wquest=5098

**Comment by cala** [comment]
From a DB point of view, the quest is working. Error message should be handled in core. Thanks everyone.
