### ISSUE TITLE
[Quest] [Westfall] - Red Silk Bandanas - Missing requirements

### ISSUE THREAD

**Issue by Tobschinski** [classicdb/database#243]
![bandanarequirements](https://f.cloud.github.com/assets/4753528/2079835/6cd631da-8dcf-11e3-9e3c-2fc40b501cfc.png)

The selected quest 'Red Silk Bandanas'  (http://www.wowhead.com/quest=214) should only be available after you have completed the quest 'The Defias Brotherhood' (Escort the Defias Traitor) (http://www.wowhead.com/quest=155)

Right now, this is not the case.

![untitled](https://f.cloud.github.com/assets/4753528/2079971/b693b8f0-8dd0-11e3-897f-1a0040a8a811.png)

**Comment by cala** [comment]
Thank you for this report.

**Comment by cala** [comment]
Could tell me if the following query does fix this:

``` SQL
UPDATE `quest_template` SET `NextQuestId` = 214, `ExclusiveGroup` = -153, `NextQuestInChain` = 214 WHERE `entry` = 153;
UPDATE `quest_template` SET `NextQuestId` = 214, `ExclusiveGroup` = -153, `NextQuestInChain` = 214 WHERE `entry` = 155;
UPDATE `quest_template` SET `PrevQuestId` = 0 WHERE `entry` = 214;
```

You must also have completed the quest 153 before (http://www.wowhead.com/quest=153).

**Comment by Tobschinski** [comment]
If you meant me ...

Nope, I can still obtain both of them at the same time.

**Comment by cala** [comment]
Yes, sorry I was meaning you. :)

Pity it does not work. I'll look at that again.
