### ISSUE TITLE
[NPC] AI with spell casters

### ISSUE THREAD

**Issue by ghost** [classicdb/database#245]
- Spell casters seem to ignore 10 second school silence from counter spell and begin casting the same spell right away.

![capture](https://f.cloud.github.com/assets/6431336/2089362/e0b3f4b4-8e85-11e3-967c-1b368a9de493.PNG)

**Comment by PatSmuk** [comment]
Unit::ProhibitSpellSchool needs to be implemented for Creatures.

**Comment by cala** [comment]
Thank you for this report. Unfortunately, it can't be fixed via database because this is related to core, like Patman said. There is already an issue opened regarding this: https://github.com/cmangos/issues/issues/103

**Comment by ROKB** [comment]
still bug
