### ISSUE TITLE
[Molten Core] Trash mechanics and functionality

### ISSUE THREAD

**Issue by ghost** [classicdb/database#249]
- patrols seem to be missing, Lava surger mostly. Also Lava surger move speed way to low.
- Core hound packs do not revive one another if they do not die within 10 sec of each other. They should not have any loot,      or be lootable they simply despawn if they are all dead within 10 sec of the first.

**Comment by cala** [comment]
Thank you for those MC reports.
They seem to be a mix of DB issues and SD2 issues. I'll fix the DB ones and forward the scripts ones.

**Comment by Tobschinski** [comment]
DB issues were fixed.
