### ISSUE TITLE
Quest from Dalar Dawnweaver have wrong spell reward

### ISSUE THREAD

**Issue by cala** [classicdb/database#25]
fixing the "you learn spell" from quest windows, from 6 Quest of Dalar Dawnweaver, adding quest end scripts so dalar dawnweaver cast spell on Player, fixing the not enough mana bug.

Submitted commit: https://github.com/Evildead666/database/commit/e9b3c631fc390a1aa0588d0ec301471719b6d9b0

_original report by [Evildead666](https://github.com/Evildead666)_

**Comment by Swater96** [comment]
This fix has been tested and should be implemented by next update!
- Swater96

**Comment by cala** [comment]
Thank you for testing. I'll push it soon(tm).

**Comment by cala** [comment]
Fixed in rev [0140] https://github.com/classicdb/database/commit/1d92550bc7575ff4ab12acf9cfd2ea9e63f0f1b5
