### ISSUE TITLE
[Molten Core]  Lucifron

### ISSUE THREAD

**Issue by ghost** [classicdb/database#250]
- His guards patrol too far behind him, his patrol moves to far south. Should be able to stay back and not aggro him.
- The mind control does not put AI the player to attack friendlies. {No MC AI on server}
- Loot table issues, did not drop any epics.

Citation
http://www.wowwiki.com/Lucifron

**Comment by scotty0100** [comment]
Just noticed the Flamewaker Protector adds are holding flowers instead of Tridents as well. How did that happen? :P

**Comment by cala** [comment]
Probably long ago, someone either:
- modified an equipment template without checking if it was used by another creature
- added an equipment template to that creature without testing what he/she added

In Classic DB, we try to avoid pushing things without testing. (even though it happened and will happen again as nobody is perfect).

I will fix this NPC's equipment: there is no place for poesy in the fiery violence of Molten Core.

**Comment by cala** [comment]
After checking, Lucifron does drop at least 2 epic items. The only case he can drop less than 2 epic items is if one of the item (or the two of them) are specific for Horde and you are playing Alliance (or vice versa). For example, if Lucifron drops 2 epic paladin shoes while you are playing Horde, you won't see them. We are aware of this and this is related to core however and not to Lucifron.

Regarding the mind control effect, this is also related to core. So, from a DB point of view, this issue can now be closed.
