### ISSUE TITLE
[Molten Core] Magmadar

### ISSUE THREAD

**Issue by ghost** [classicdb/database#251]
- With all fears you often do not regain control even if you break it early. This bug is game breaking for this fight since you could often wipe if the tank got feared to long or at all.

**Comment by cala** [comment]
The duration of the fear effect is handled by core (there are other issue there regarding loss of control by players when facing a boss). I'm closing the issue here. Thank you.

**Comment by Tobschinski** [comment]
As an addition, I can only highly recommend to flame your tank. He should never be feared ...
