### ISSUE TITLE
[Molten Core]  Baron Geddon

### ISSUE THREAD

**Issue by ghost** [classicdb/database#253]
- I believe his patrol is near domo to shazzrah and he moves very fast, currently slow.
- Inferno only pulses once and lasts maybe 2 seconds.
- He does not; At 2% Health Baron Geddon will emote "Baron Geddon performs one last service for Ragnaros." You have 5 seconds    to kill him before he explodes like a living bomb, killing anyone in melee range (8500+ damage).

Citation
http://www.wowwiki.com/Baron_Geddon

**Comment by scotty0100** [comment]
Inferno only pulses once and lasts maybe 2 seconds.
<b>Raised a SD2 issue for this as I believe this is SD2 related</b> https://github.com/scriptdev2/scriptdev2-classic/issues/19

https://www.youtube.com/watch?v=Ofo5wkwd4s4#t=107

You can see how fast he paths there.

Walk Speed should probably be set to 5.

```
UPDATE `creature_template` SET `SpeedWalk`='5', `SpeedRun`='5' WHERE (`Entry`='12056');
```

**Comment by ghost** [comment]
This should be opened as Inferno pulses more than once if you simply read the Baron Geddon citation
Inferno — a PBAoE that increases in damage with each pulse. The pulses come about 1 second apart and last for 10 seconds. Damage starts at 500 damage per pulse and increases by 500 every other pulse (500, 500, 1000, 1000, 1500, etc.). Baron Geddon will not move while casting this and he will do 6-10 pulses.

**Comment by cala** [comment]
Inferno/Armaggedon spells cannot be fixed via DB. What could be fixed via DB was fixed, hence the closure of this issue.
As you can see above, a specific issue was open on SD2 to take care of the spells.
