### ISSUE TITLE
[Molten Core] MajorDomo Executus

### ISSUE THREAD

**Issue by ghost** [classicdb/database#257]
- The bubbles do seem to apply to every add but the effects don't occur. {No reflect, no damage on hit}
- Shadow bolts do double the proper damage
- fire pit damage about 300-500 damage low, also can't be partially resisted.

Citation
http://www.wowwiki.com/Majordomo_Executus

**Comment by cala** [comment]
Points 1 and 3 are working correctly in current state of the core.
Point 2 is fixed by https://github.com/cmangos/classic-db/commit/68b4588bf99594197c9fbafd41afb17f6eea9931
Thank you.
