### ISSUE TITLE
Quest 5156 has wrong race requirement

### ISSUE THREAD

**Issue by cala** [classicdb/database#26]
Should be accessible to every race and not only Horde as wrongly stated on wowhead.

Submitted commit: https://github.com/Evildead666/database/commit/07794eee9b900bd8f7436cbba594bdca9c549d98

**Comment by Swater96** [comment]
This fix has been tested and should be implemented by next update!
- Swater96

**Comment by cala** [comment]
Thank you. I'll push it when I can spare the time.

**Comment by cala** [comment]
Fixed in rev [0135] https://github.com/classicdb/database/commit/de855205d82a83fe88e5d1b0217c239cecd230c5
