### ISSUE TITLE
[NPC] Meven Korgal incorrectly positioned.

### ISSUE THREAD

**Issue by Neretz** [classicdb/database#261]
Currently Meven Korgal (Deathknell) is incorrectly positioned, he should stand at the entry of his tent.

**Comment by ghost** [comment]
Have cords?

**Comment by Dmzll** [comment]
http://wow.zamimg.com/uploads/screenshots/normal/23958.jpg
Do it by hand and push and update?

This is his x/y/z cords from TDB (tdb_full_335.46_2012_02_13)
-10829
-3048.59
47.1667

**Comment by cala** [comment]
@Neretz thank you for this report.
Does the position in the screenshot posted by Dmzll sounds OK? If so, could you please test the following updates and tell me if the NPC is now in the right place:

``` SQL
UPDATE `creature` SET `position_x` = -10829, `position_y` = -3048.59, `position_z` = 47.167 WHERE `id` = 1667;
```
