### ISSUE TITLE
Veron Amberstill doesn't sell his mounts.

### ISSUE THREAD

**Issue by scotty0100** [classicdb/database#265]
NPC: Veron Amberstill

Map & Area: Amberstill Ranch - Dun Morogh

Unable to buy mounts, with GM on the gossip menu is there. But should be visible to all players not just GMs.

**Comment by scotty0100** [comment]
Using info based of https://github.com/cmangos/issues/wiki/Conditions#wiki-value1

Gossip Menu for Veron Amberstill: 4001 -> Condition Entry is 1027.

1027 Condition: Type -1, value1 1025, value2 1026 (so requires both)

1025 Condition: Type 5 (Rep), value1 47, value 7. Rep is Ironforge

1026 Condition: Type 14 (Required Race/Class) value1 1097 .. should be dwarf I guess, is 1097 incorrect?

**Comment by cala** [comment]
Thanks for this report.

> Unable to buy mounts, with GM on the gossip menu is there. But should be visible to all players not just GMs

The gossip option should only be visible to
- dwarves
- alliance (not dwarves) players who are exalted with Ironforge

I cannot test this on a server right now, but from what I saw in the database, that should be the case. Also, the gossip text should change depending if the player is eligible or not to buying the mount.

Could you confirm that either dwarf players or any player with an exalted reputation with Ironforge can not see the gossip option, please?

**Comment by PatSmuk** [comment]
Logic in the database is incorrect. Right now it's set to 'Is a dwarf' **AND** 'Exalted with dwarves', when clearly it should be 'Is a dwarf' **OR** 'Exalted with dwarves'.

**Comment by cala** [comment]
Ok. I had another look at it.
Condition 14, 1097, 0  is "Every alliance race but dwarves", so it appears that dwarves can not have access to their own mounts. A shame.
However, the NPC is working fine for other races.

I'll fix this soon. Thanks both of you.
