### ISSUE TITLE
Suntara Stones [Broken Escort Quest & Broken Quest Chain]

### ISSUE THREAD

**Issue by scotty0100** [classicdb/database#267]
Map & Area: Grimsilt Dig Site - Searing Gorge

How to replicate the bug: accept the quest

What happens: nothing

What should happen: you should escort Dorius out of the site

Source:
http://db.vanillagaming.org/?quest=3367

Extra Info:

As this quest is broken you are unable to proceed with the quest chain.

**Comment by cala** [comment]
Thank you for reporting.
This one could only be handled by SD2 and an issue is already opened about it: https://github.com/scriptdev2/scriptdev2/issues/27
So, I'm closing the issue here.
