### ISSUE TITLE
Loot-table fixes - Deadmines #1

### ISSUE THREAD

**Issue by Tobschinski** [classicdb/database#269]
Hey Cala,

Marisa du'Paige  (rare spawn, outer Deadmines) does not drop any loot.

As being a rare, her common loot should be:

75% - Walking Boots  (uncommon Cloth Feet: 22 Armor, +3 INT, + 2 AGI) 
25% - Noble's Robe  (uncommon Cloth Chest: 21 Armor, +1 STR, +3 STA, +3 SPI)

(Source: Bradygames' Dungeon Companion, http://old.wowhead.com/npc=599#comments)

```
INSERT INTO creature_loot_template (entry, item, ChanceOrQuestChance, groupid, mincountOrRef, maxcount, condition_id)
VALUES (599, 4660, 75, 2, 1, 1, 0);

INSERT INTO creature_loot_template (entry, item, ChanceOrQuestChance, groupid, mincountOrRef, maxcount, condition_id)
VALUES (599, 3019, 25, 2, 1, 1, 0);
```

---

Brainwashed Noble (rare spawn, outer Deadmines) 

As being a rare, his common loot should be:

70% - Girdle of Nobles (uncommon Cloth Waist: 18 Armor, +2 STA, + 3 INT) 
30% - Staff of Nobles (uncommon Staff: 30 - 46 Damage, 3.2 Speed, +2 STA, +4 SPI) 

Notes: For now, Staff of Noble's chance is set to 0%.

(Source: Bradygames' Dungeon Companion, wowhead.com and wowwiki.com)

```
UPDATE creature_loot_template 
SET ChanceOrQuestChance=30
WHERE entry=596 AND item=3902;
```

**Comment by Tobschinski** [comment]
Feel free to correct me if I have done anything wrong.

By the way, I have seen abundant loot at entry 599, like tbc-gems and stuff. Is it wanted? Also, wouldn't it be better to add some sort of item-pools to each mob instead of fixed IDs with infinitesimal chances? 

And if I finally learn how to request, you will have less work!

**Comment by PatSmuk** [comment]
Yeah, the loot tables could probably use some heavy refactoring. Is there a reason you used group 2?

**Comment by Tobschinski** [comment]
Group 1 has already been taken by these gems. And one of these items should be a guaranteed loot, besides other.
Or am I misunderstanding the purpose of group-IDs?

By the way, since mobs should not drop more than one sort of cloth (not wool AND linen cloth at once, this would affect changes to every humanoid in azeroth), it would be great to add some sort of protected group-IDs, if this isn't the case already.

**Comment by cala** [comment]
Thank you for this report. I'll fix this soon.

**Comment by cala** [comment]
A note regarding this:

> Brainwashed Noble (rare spawn, outer Deadmines)
> 
> As being a rare, his common loot should be:
> 
> 70% - Girdle of Nobles (uncommon Cloth Waist: 18 Armor, +2 STA, + 3 INT) 
> 30% - Staff of Nobles (uncommon Staff: 30 - 46 Damage, 3.2 Speed, +2 STA, +4 SPI)
> 
> Notes: For now, Staff of Noble's chance is set to 0%.

Because Staff of Nobles is in a group, if Girdle of Nobles is not picked, then Staff of Noble will always be picked instead, which means it has _de facto_ a 30% drop chance. In this case 0 does not mean 0% drop chance but whatever % chance is left to reach 100% for the whole group.

**Comment by Tobschinski** [comment]
Oh, didn't know about that. Thanks for your information.

I guess I was just unlucky then, killed him quite a few times without ever receiving the staff.

**Comment by cala** [comment]
You wouldn't know how many times on retail I waited for a item to drop in BWL and yet never dropped against all odds... ;)
