### ISSUE TITLE
Unknown Maps / Missing graveyards

### ISSUE THREAD

**Issue by Tobschinski** [classicdb/database#270]
Reopened: https://github.com/cmangos/issues/issues/387

Classic version, not sure about others.

Notes: If you die in the outer Deadmines and release your corpse, you will not be moved to the graveyard next to Sentinel Hill. You will remain in place and can simply resurrect once the penalty timer is over.

I would assume this is the case for other dungeons as well, as I have noticed this on other projects too.

**Comment by cala** [comment]
Thank you for this report. Some graveyards are indeed missing. Temple of Ahn'Qiraj, Naxxramas and Ironforge (for Horde) are already fixed. Feel free to add any missing graveyard you notice. I'll fix the Deadmines one soon.

**Comment by Tobschinski** [comment]
**_Unknown Maps / Missing Graveyards for Alliance._**

---
- outer Ragefire Chasm _(not completely missing, but I was moved to Ashenvale)_
- outer Deadmines
- outer Wailing Caverns
- outer Blackfathom Deeps
- outer Gnomeregan
- outer Razorfen Kraul
- outer Razorfen Downs
- outer Scarlet Monastery
- outer Uldaman
- outer Maraudon
- outer Stratholme _(main entrance, side entrance is working)_
- outer Scholomance
- outer Dire Maul _(tricky one, there are many entrances, I wasn't moved to a graveyard at any of these)_

**Comment by Tobschinski** [comment]
_**Unknown Maps / Missing Graveyards for Horde.**_

---
- outer Deadmines
- outer Wailing Caverns
- outer Blackfathom Deeps
- outer Gnomeregan
- outer Razorfen Kraul
- outer Razorfen Downs
- outer Scarlet Monastery
- outer Uldaman
- outer Maraudon
- outer Stratholme _(main entrance, side entrance is working)_
- outer Scholomance
- outer Dire Maul _(tricky one, there are many entrances, I wasn't moved to a graveyard at any of these)_

(similar to Alliance, except for Ragefire Chasm)

**Comment by Tobschinski** [comment]
To reproduce, most likely, I used the **.tele** command to get to the dungeon. If I have been far away from its entrance, I ran there. If not, I used **.die**.

---

So far, every graveyard inside a dungeon is working.

---

The **.gps** command does not know the map, it is unknown.

e.g. (standing in front of the portal to Wailing Caverns will print x to chat.

_Map: 1 (Kalimdor) **Zone: 0 (< unknown >) Area: 0 (< unknown >)**X: -736.215942 Y: -2220.090820 Z: 17.141901 Orientation: 3.743045grid[30,27]cell[9,13] InstanceID: 0 ZoneX: 51.761768 ZoneY: 34.955280GroundZ: 157.213455 FloorZ: 17.142067 Have height data (Map: 1 VMap: 1)_

**Comment by cala** [comment]
Oh, that's a lot of dungeons, many more than I thought. Thank you for testing them.

**Comment by Tobschinski** [comment]
updated

**Comment by cala** [comment]
To be sure I understand correctly this issue:
- when a player dies _inside_ a dungeon (after going through the blue portal and being teleported inside the instance): his/her corpse is moved to the right graveyard
- when a player dies _before_ the dungeon (he/she has not gone through the blue portal but she/he is near it): his/her corpse is not moved to any graveyard and she/he is resurrected where he/she died?

Is this so?

**Comment by Tobschinski** [comment]
Yep!

**Comment by cala** [comment]
In this case, I wonder if this is not finally a core issue due to the fact that the core can not associate a zone/area with the current player position. Poke @Schmoozerd and @cyberium to get their opinion on this matter.

**Comment by PatSmuk** [comment]
This is indeed a core issue. It loses track of your zone/area when you enter a cave.

**Comment by cala** [comment]
Closing this issue as it is core related.

**Comment by Tobschinski** [comment]
At least "outer Ragefire Chasm (not completely missing, but I was moved to Ashenvale)" shouldn't, or am I wrong?

**Comment by cala** [comment]
No, you are right, I just missed that one.

**Comment by Tobschinski** [comment]
AQ20 - the area around Buru needs to be added to the list. The zone is known.
