### ISSUE TITLE
Miner Johnson, Deadmines

### ISSUE THREAD

**Issue by Tobschinski** [classicdb/database#271]
Hello there,

Miner Johnson (npc=3586) is a rare spawn in the Deadmines. His uptime should be 20 - 30 %.

In order to fix this, do I need some sort of placeholder, if he should not be there? I have checked your previous work on other rares, and you always use a second mob.

I am asking, because he never showed up if I used any chance other than 100.

**Comment by PatSmuk** [comment]
Can you post what you've tried?

**Comment by Tobschinski** [comment]
```
UPDATE mangos.creature_template SET rank=2 WHERE entry=3586;

INSERT INTO mangos.pool_template (entry, max_limit, description) 
VALUES (1182, 1, Miner Johnson (3586) Deadmines);

INSERT INTO mangos.pool_creature (guid, pool_entry, chance, description) 
VALUES (84079, 1182, 20, Miner Johnson);
```

Sadly, nothing more than that. I am also not sure about using pool_template over pool_creature_template.

**Comment by PatSmuk** [comment]
Unfortunately it's not possible to have only explicitly-chanced spawns that don't add to 100. The hack solution I suppose would be to find a random critter and make that part of the pool.

Maybe @Schmoozerd knows a better solution or how to make it work properly.

**Comment by Tobschinski** [comment]
Although it feels dirty ... 

```
-- set 'Miner Johnson' rank to Rare-Elite
UPDATE `mangos`.`creature_template` SET `rank`='2' WHERE `entry`='3586';

-- spawn additional NPC 'Rat'
INSERT INTO `mangos`.`creature` (`guid`, `id`, `map`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `DeathState`, `MovementType`) VALUES ('79147', '4075', '36', '1141', '0', '-152.545', '-526.434', '51.133', '1.73877', '604800', '10', '0', '120', '0', '0', '1');

--  pool 'Miner' Johnson and previously added 'Rat'
INSERT INTO `mangos`.`pool_template` (`entry`, `max_limit`, `description`) VALUES ('1182', '1', 'Miner Johnson (3586) Deadmines');
INSERT INTO `mangos`.`pool_creature` (`guid`, `pool_entry`, `chance`, `description`) VALUES ('84079', '1182', '20', 'Miner Johnson (3586) Deadmines'), ('79147', '1182', '80', 'Alternate creature to Miner Johnson (3586) Deadmines');
```

**Comment by Schmoozerd** [comment]
i think you can add pools with chances less than 100.
However this might result in nothing being spawned. In this case the pool will never be re-rolled and hence never be spawned.

This either requires a rework of the pool-system to create some dummy-spawns (which only trigger a time value)

Or you can use a system like ytdb does for special cases: wrap spawning of some random npcs into the same pool to get some respawn now and then triggered.

**Comment by cala** [comment]
> Or you can use a system like ytdb does for special cases: wrap spawning of some random npcs into the same pool to get some respawn now and then triggered.

After putting some thoughts and researches on that, I finally decided to go on that one too (and used it for some times now) because:
- there are some examples of rare mobs being replaced by a normal NPCs in instance (like Deathsworn Captain in Shadowfang Keep)
- number of mobs in a pack in low level instances is critical due to very few skills/abilities available to player, so adding a new NPC (especially one with special spells) would drastically increase the difficulty

Based on these, I decided to put the rare mob in the same pool than the closest (similar) mob. Unless correct % were known, I used the following: 30% for rare mob, 70% for normal mob. This usually match most of experience rate percieved by players where rare mob was spawn between 1 in 5 and 1 in 3.

**Comment by Tobschinski** [comment]
But removing close (hostile) NPC in order to spawn rares will effect difficulty as well, it will be lowered.

What is so bad about spawning additional critter to the same position. Or, like Patman suggested, use a random critter somewhere else. Most critter won't join the fight.

This is my solution to Miner Johnson ...
http://pastebin.com/AhgYK49a

**Comment by cala** [comment]
> But removing close (hostile) NPC in order to spawn rares will effect difficulty as well, it will be lowered

It is not removed, it is replaced by a slightly stronger one: players still have the same number of NPCs to encounter/crowd control, the group is just stronger

Yet your solution is quite good when no "eligible" NPC is near or when rare NPC is moving along waypoints or intended to be "aside from others".

Regarding this one, I think I'll go with your solution indeed. I was just giving generic guidelines above.

**Comment by Schmoozerd** [comment]
> i think you can add pools with chances less than 100.
> If this is not possible, maybe create a core patch to add this (Expected) feature
