### ISSUE TITLE
Creature 4949 has to few HP

### ISSUE THREAD

**Issue by cala** [classicdb/database#28]
Thrall currently has 40,000 HP. Isn't this supposed to be 400,000? I mean the king of Stormwind has over 525,000!

_original report by [The-Great-Sephiroth](https://github.com/The-Great-Sephiroth)_

**Comment by Swater96** [comment]
http://www.wowwiki.com/Talk:Thrall#Thrall.27s_HP

The best data I can find.. lol ;)

UPDATE `creature_template` SET `minhealth`='637000', `maxhealth`='637000' WHERE (`entry`='4949')

**Comment by cala** [comment]
I did also search for it but did not come with anything better. This value is definitely better than the current 40k HP and as long as it is in line with other faction leaders HP, we should go for it. I will however put a note when pushing this change that the value is not sure to be 100% blizzlike.
Thanks! :+1:

**Comment by cala** [comment]
Fixed in rev [0141] https://github.com/classicdb/database/commit/cbf153995dd20192c8f54c7dfb4d8bfe80a0fc3b
