### ISSUE TITLE
NPC ID 3455 in Northwatch  stay in an cannon

### ISSUE THREAD

**Issue by Dainara82** [classicdb/database#280]
NPC ID 3455 in Northwatch  stay in an cannon, so the NPC is not killable and don't attack the player
i delete the NPC and add it on the right position 
here is the sql

---

DELETE FROM creature WHERE guid=12166;
DELETE FROM creature_addon WHERE guid=12166;
DELETE FROM creature_movement WHERE id=12166;
DELETE FROM game_event_creature WHERE guid=12166;
DELETE FROM game_event_creature_data WHERE guid=12166;
DELETE FROM creature_battleground WHERE guid=12166;
DELETE FROM creature_linking WHERE guid=12166 OR master_guid=12166;
DELETE FROM creature WHERE guid=590012;
INSERT INTO creature VALUES (590012,3455,1,0,866,-2088.99,-3500.56,130.085,0.325127,25,0,0,500,0,0,0);
DELETE FROM creature WHERE guid=590012;
DELETE FROM creature_addon WHERE guid=590012;
DELETE FROM creature_movement WHERE id=590012;
DELETE FROM game_event_creature WHERE guid=590012;
DELETE FROM game_event_creature_data WHERE guid=590012;
DELETE FROM creature_battleground WHERE guid=590012;
DELETE FROM creature_linking WHERE guid=590012 OR master_guid=590012;
DELETE FROM creature WHERE guid=590013;
INSERT INTO creature VALUES (590013,3455,1,0,866,-2088.09,-3500.62,130.084,0.490059,25,0,0,500,0,0,0); 

---

**Comment by Tobschinski** [comment]
Indeed, this is correct. I have checked the other tower, and some correction is needed there as well.

I guess 

```
UPDATE `creature` SET `position_x`='-2088.859863', `position_y`='-3508.073975', `position_z`='130.084625', `orientation`='2.365365' WHERE `guid`='12166';
UPDATE `creature` SET `position_x`='-2221.687744', `position_y`='-3775.523193', `position_z`='130.862396', `orientation`='0.370675' WHERE `guid`='12165';
```

will fix them all.

**Comment by cala** [comment]
Thank you, it is nice to have testers on Horde side.

**Comment by Swater96** [comment]
@Dainara82 Remember when you add NPC's in game, the spawntime data (and possibly other values) are set to a default value, not necessarily what was there before. Ex. the respawn time of the new creature in your sql file will be the default (25?) seconds and that is not correct. This is especially important to remember for instances. Just FYI :).
