### ISSUE TITLE
Quest ID 4021  (Counterattack!)  Event don't start

### ISSUE THREAD

**Issue by Dainara82** [classicdb/database#281]
The Event don't start.
No enemys spawn

**Comment by Tobschinski** [comment]
Working for me, did you start it manually?
![untitled](https://f.cloud.github.com/assets/4753528/2314773/0e3d5a20-a31b-11e3-8784-5ccbe5b663a3.png)

**Comment by Dainara82** [comment]
ok  i test it again and it works, it was bevore DB 1.3  
thanks  and sorry 
Close
