### ISSUE TITLE
Quest ID 253 (Braut des Einbalsamierers) german ^^

### ISSUE THREAD

**Issue by Dainara82** [classicdb/database#283]
the grave can't be clicked

**Comment by Tobschinski** [comment]
I have had no problem with that quest.

I was even able to interact with the grave without being on quest 253. That should be removed.

Many GOs should not be interactable unless you are on a certain quest.

Have you completed this quest earlier? Because then, it is not usable anymore.

**Comment by cala** [comment]
I have no issue with that quest either. Can you confirm it is not working?

> Many GOs should not be only interactable unless you are on a certain quest.

This is a core issue, also reported here: #142

**Comment by Dainara82** [comment]
The player who send me the Bug Report tells me, that she had the quest in her questlog bevore i update the DB, she delete the quest and do it again and it works,
