### ISSUE TITLE
Quest ID 1960  (Untersuchungen im Alchemistenladen) german name ^^

### ISSUE THREAD

**Issue by Dainara82** [classicdb/database#285]
the event don't start after using the Roll
no adds spawning

**Comment by cala** [comment]
Thank you for this report. Instead of posting german name, could you use wowhead or the like to translate into english name, please?
Regarding this quest, it is currently broken like its alliance counterpart. I'm working on a fix, but this is tougher than expected at first glance.

**Comment by cala** [comment]
Now handled in #695
