### ISSUE TITLE
Quest ID 893  (ausgewählte waffen)

### ISSUE THREAD

**Issue by Dainara82** [classicdb/database#286]
Item ID 5094  should not drop or the droprate is very very bad,  after 70 kills no  drop

**Comment by Tobschinski** [comment]
![untitled](https://f.cloud.github.com/assets/4753528/2314449/048748b4-a317-11e3-9056-4b87a13a35ff.png)

I got mine out of the 5th Warfrenzy, guess you have been unlucky.

---

Incase that your DB is missing some entries ...

```
INSERT INTO `creature_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `groupid`, `mincountOrRef`, `maxcount`, `condition_id`) VALUES ('3459', '5094', '15.2174', '0', '1', '1', '0');
```

**Comment by cala** [comment]
Based on retail comments, this is completely normal behaviour: http://wowhead.com/item=5094#comments

I checked the drop rate in DB they are also ok.
