### ISSUE TITLE
Quest ID (Versäuchtes Land)

### ISSUE THREAD

**Issue by Dainara82** [classicdb/database#287]
NPC ID 32978
give a quest that you should capture an "Rabid Thistle Bear"  add ID 2164
if you captured it (Captured Rabid Thistle Bear)   add ID 11836
the quest don't be finished   it always stay "Captured Rabid Thistle Bear  0/1"
so the quest is not complete and you can't finished it by the questgiver
the add following and you cn go to the NPC  32978    and the Captured Rabid Thistle Bear  disappears
quest is not complete

**Comment by cala** [comment]
I will test this again, but last time I checked, it was working very well.

**Comment by Dainara82** [comment]
1 testet it and 2 other player, every player testet it 2-3 times
and the quest doesn't work for us

**Comment by PatSmuk** [comment]
The trap does nothing for me.

**Comment by cala** [comment]
After checking: the quest completion is not sent (it previously was). The trap does change the rabid bear to a captured rabid bear, the captured rabid bear does follow the player to quest giver, it does despawsn when in range of quest giver but quest completion is not sent when it should (after successfully using the trap).
I'll have to test it on other cores. It worked before.
