### ISSUE TITLE
Quest ID 1267  (Der vermisste Diplomat)

### ISSUE THREAD

**Issue by Dainara82** [classicdb/database#288]
the previouse quest  (quest ID) 1266  work, after you complet the Quest bei the NPC ID 4967 you got the following quest

with ID  1267    you should speak with Jaina Proudmoore
and this don't work every time
a group with 2 player  have the quest,  one player  can complete the quest  and by the other palyer it doesn't go and the quest is disappear

**Comment by cala** [comment]
Thank you for this report.
The quest 1266 is currently not 100% blizzlike because the end script is missing. This should be handled by SD2. As such I close the issue here.
