### ISSUE TITLE
Auctionhouse have an issues

### ISSUE THREAD

**Issue by Dainara82** [classicdb/database#289]
if i wan't to search for unknown recipes and i click on  useable items in the above 
the searchresult show me all recipes,  known and unknows recipes
and not only the unknown

**Comment by Tobschinski** [comment]
~~Afair, this is the correct behavior for classic. This was changed in later expansions.~~

EDIT: No way, I am never wrong!

**Comment by PatSmuk** [comment]
From http://www.wowwiki.com/Auction_House

> Patch 1.4.0 (2005-05-05):
> 
> Recipes you already know will not show up in the auction listing if "Usable Items" is checked.

Looks like a bug. But it's definitely a core issue. Reposted it here: cmangos/issues#394.
