### ISSUE TITLE
creature_equip_template & creature_equip_template_raw

### ISSUE THREAD

**Issue by scotty0100** [classicdb/database#290]
Perhaps not a bug per se, but just wondered if creature_equip_template is needed as it's empty in the current 1.3 version of the database.

However, creature_equip_template_raw has data. Just never noticed the error before - perhaps working as intended! But it does say it's using a deprecated format according to Server.log:

2014-03-04 13:04:18 Loading Equipment templates...
2014-03-04 13:04:18 ERROR:creature_equip_template table is empty!

2014-03-04 13:04:18 >> Loaded 0 equipment template
2014-03-04 13:04:18 
2014-03-04 13:04:18 >> Loaded 1950 equipment template (deprecated format)

**Comment by PatSmuk** [comment]
They should be converted, where possible, to creature_equip_template since it has less redundant information. But no one has undertaken this yet. From what I've heard from X-Savior the data is also a bit flawed so I'll probably be looking into redoing it in the future.

**Comment by cala** [comment]
I agree `creature_equip_template_raw` table should be moved to `creature_equip_template`.
However, as it is working like it is currently, I think this a low priority compared to other open issues.

**Comment by Tobschinski** [comment]
https://github.com/classicdb/database/commit/8ac5684f83bdf0193ca21a9426f09ca127814ebc https://github.com/classicdb/database/commit/850362e3a5098cc5e9cb8b8823b7a1b0d4fa40af https://github.com/classicdb/database/commit/c1e1b94cb638f5ac1e71c2d23919cfb5b66a9cf2 & https://github.com/classicdb/database/commit/e39b8188ecca3d893b4f0ea321cf2e2945343253

Done!

**Comment by cala** [comment]
Champagne !

**Comment by cyberium** [comment]
So we have to remove support in core of that raw one?

**Comment by Tobschinski** [comment]
No, not yet. (but soon)

**Comment by cala** [comment]
@cyberium be assured that as soon as we can drop the table (all entries moved and checks done), @Tobschinski will probably let you know with a rain of trouts. He hates this table more than me. ;)

**Comment by Tobschinski** [comment]
These are left ... lots of them shouldn't even use weapons ...

| ID | Name |
| --- | --- |
| 54 | Corina Steele |
| 80 | Kobold Laborer |
| 95 | Defias Smuggler |
| 167 | Morhan Coppertongue |
| 202 | Skeletal Horror |
| 222 | Nillen Andemar |
| 238 | Verna Furlbrow |
| 257 | Kobold Worker |
| 300 | Zzarc' Vul |
| 334 | Gath'Ilzogg |
| 372 | Karm Ironquill |
| 464 | Guard Parker |
| 486 | Tharil'zun |
| 599 | Marisa du'Paige |
| 641 | Goblin Woodcarver |
| 694 | Bloodscalp Axe Thrower |
| 696 | Skullsplitter Axe Thrower |
| 734 | Corporal Bluth |
| 773 | Krazek |
| 786 | Grelin Whitebeard |
| 794 | Matt |
| 808 | Grik'nir the Cold |
| 823 | Deputy Willem |
| 871 | Saltscale Warrior |
| 1019 | Elder Razormaw |
| 1035 | Dragonmaw Swamprunner |
| 1077 | Prospector Whelgar |
| 1134 | Young Wendigo |
| 1149 | Uthok |
| 1244 | Rethiel the Greenwarden |
| 1385 | Brawn |
| 1399 | Magosh |
| 1445 | Jesse Halloran |
| 1447 | Gimlok Rumdnul |
| 1460 | Unger Statforth |
| 1470 | Ghak Healtouch |
| 1474 | Rann Flamespinner |
| 1477 | Christoph Faral |
| 1478 | Aedis Brom |
| 1484 | Derina Rumdnul |
| 1487 | Splinter Fist Enslaver |
| 1560 | Yvette Farthing |
| 1682 | Yanni Stoutheart |
| 1684 | Khara Deepwater |
| 1776 | Magtoor |
| 1848 | Lord Maldazzar |
| 1889 | Dalaran Wizard |
| 1892 | Moonrage Watcher |
| 1893 | Moonrage Sentry |
| 1896 | Moonrage Elder |
| 2096 | Tarrel Rockweaver |
| 2108 | Garneg Charskull |
| 2211 | Captured Mountaineer |
| 2534 | Zanzil the Outcast |
| 2546 | Fleet Master Firallon |
| 2554 | Witherbark Axe Thrower |
| 2609 | Geomancer Flintdagger |
| 2639 | Vilebranch Axe Thrower |
| 2649 | Witherbark Scalper |
| 2694 | Highvale Ranger |
| 2784 | King Magni Bronzebeard |
| 2785 | Theldurin the Lost |
| 2805 | Deneb Walker |
| 2846 | Blixrez Goodstitch |
| 2849 | Qixdi Goodstitch |
| 2857 | Thund |
| 2951 | Palemane Poacher |
| 2952 | Bristleback Quilboar |
| 2953 | Bristleback Shaman |
| 2981 | Chief Hawkwind |
| 3051 | Supervisor Fizsprocket |
| 3083 | Honor Guard |
| 3104 | Makrura Shellhide |
| 3112 | Razormane Scout |
| 3181 | Fremal Doohickey |
| 3239 | Thunderhead |
| 3309 | Karus |
| 3318 | Koma |
| 3319 | Sana |
| 3320 | Soran |
| 3334 | Rekkul |
| 3359 | Kiro |
| 3365 | Karolek |
| 3375 | Bael'dun Foreman |
| 3444 | Dig Rat |
| 3468 | Ancient of Lore |
| 3529 | Moonrage Armorer |
| 3531 | Moonrage Tailor |
| 3533 | Moonrage Leatherworker |
| 3539 | Ott |
| 3649 | Thundris Windweaver |
| 3662 | Delmanis the Hated |
| 3692 | Volcor |
| 3693 | Terenthis |
| 3808 | Forsaken Dark Stalker |
| 3836 | Mountaineer Pebblebitty |
| 3840 | Druid of the Fang |
| 3875 | Haunted Servitor |
| 3922 | Thistlefur Totemic |
| 3936 | Shandris Feathermoon |
| 3943 | Ruuzel |
| 3945 | Caravaneer Ruzzgot |
| 3969 | Fahran Silentblade |
| 3970 | Llana |
| 3977 | High Inquisitor Whitemane |
| 3989 | Venture Co. Logger |
| 4054 | Laughing Sister |
| 4159 | Me'lynn |
| 4161 | Lysheana |
| 4175 | Vinasia |
| 4193 | Grondal Moonbreeze |
| 4225 | Saenorion |
| 4228 | Vaean |
| 4229 | Mythrin'dir |
| 4236 | Cyridan |
| 4242 | Frostsaber Companion |
| 4278 | Commander Springvale |
| 4309 | Gorm Grimtotem |
| 4310 | Cor Grimtotem |
| 4359 | Mirefin Murloc |
| 4455 | Red Jack Flint |
| 4507 | Daisy |
| 4550 | Ophelia Montague |
| 4616 | Lavinia Crowe |
| 4641 | Magram Windchaser |
| 4645 | Magram Mauler |
| 4646 | Gelkis Outrunner |
| 4663 | Burning Blade Augur |
| 4664 | Burning Blade Reaver |
| 4665 | Burning Blade Adept |
| 4666 | Burning Blade Felsworn |
| 4667 | Burning Blade Shadowmage |
| 4856 | Stonevault Cave Hunter |
| 4962 | Tapoke \"Slim\" Jahn |
| 5125 | Dolkin Craghelm |
| 5150 | Nissa Firestone |
| 5155 | Ingrys Stonebrow |
| 5156 | Maeva Snowbraid |
| 5224 | Murk Slitherer |
| 5239 | Gordunni Mage-Lord |
| 5317 | Jademir Oracle |
| 5327 | Coast Crawl Snapclaw |
| 5421 | Glasshide Petrifier |
| 5523 | War Party Kodo |
| 5598 | Atal'ai Exile |
| 5646 | Sandfury Axe Thrower |
| 5674 | Practice Target |
| 5697 | Theresa |
| 5734 | Apothecary Keever |
| 5809 | Watch Commander Zalaphil |
| 5841 | Rocklance |
| 5909 | Cazul |
| 6004 | Shadowsworn Cultist |
| 6010 | Felhound |
| 6033 | Lake Frenzy |
| 6194 | Spitelash Serpent Guard |
| 6222 | Leprous Technician |
| 6224 | Leprous Machinesmith |
| 6731 | Harlown Darkweave |
| 6738 | Innkeeper Kimlya |
| 6807 | Innkeeper Skindle |
| 7017 | Lord Sinslayer |
| 7048 | Scalding Broodling |
| 7207 | Doc Mixilpixil |
| 7778 | Doran Steelwing |
| 7804 | Trenton Lighthammer |
| 7858 | Southsea Swashbuckler |
| 7884 | Fraggar Thundermantle |
| 7885 | Spitelash Battlemaster |
| 7937 | High Tinker Mekkatorque |
| 7978 | Bimble Longberry |
| 7999 | Tyrande Whisperwind |
| 8096 | Protector of the People |
| 8147 | Camp Mojache Brave |
| 8154 | Ghost Walker Brave |
| 8155 | Kargath Grunt |
| 8161 | Harggan |
| 8196 | Occulus |
| 8199 | Warleader Krazzilak |
| 8216 | Retherokk the Berserker |
| 8308 | Alenndaar Lapidaar |
| 8359 | Ahanu |
| 8360 | Elki |
| 8402 | Enslaved Archaeologist |
| 8416 | Felix Whindlebolt |
| 8582 | Kadrak |
| 8664 | Saern Priderunner |
| 8897 | Doomforge Craftsman |
| 8917 | Quarry Slave |
| 9083 | Razal'blade |
| 9267 | Smolderthorn Axe Thrower |
| 9460 | Gadgetzan Bruiser |
| 9503 | Private Rocknot |
| 9525 | Freewind Brave |
| 9776 | Flamekin Spitter |
| 9777 | Flamekin Sprite |
| 9778 | Flamekin Torcher |
| 9779 | Flamekin Rager |
| 9984 | Ulbrek Firehand |
| 10036 | Brackenwall Enforcer |
| 10046 | Bethaine Flinthammer |
| 10060 | Grimestack |
| 10090 | Belia Thundergranite |
| 10181 | Lady Sylvanas Windrunner |
| 10262 | Opus |
| 10377 | Elu |
| 10456 | Prynne |
| 10540 | Vol'jin |
| 10579 | Kirtonos the Herald (Spell Visual) |
| 10600 | Thontek Rumblehoof |
| 10739 | Mulgris Deepriver |
| 10805 | Spotter Klemmy |
| 10840 | Argent Officer Pureheart |
| 11051 | Vhan |
| 11102 | Argent Rider |
| 11180 | Bloodvenom Post Brave |
| 11194 | Argent Defender |
| 11350 | Gurubashi Axe Thrower |
| 11442 | Gordok Mauler |
| 11753 | Gogo |
| 11754 | Meggi Peppinrocker |
| 11755 | Harlo Wigglesworth |
| 11757 | Umaron Stragarelm |
| 11829 | Fahrak |
| 11871 | Grinning Dog |
| 11911 | Grimtotem Mercenary |
| 11946 | Drek'Thar |
| 12150 | Riding Kodo (Purple) |
| 12496 | Dreamtracker |
| 13017 | Enthralled Deeprun Rat |
| 13158 | Lieutenant Sanders |
| 13776 | Corporal Teeka Bloodsnarl |
| 14229 | Accursed Slitherblade |
| 14277 | Lady Zephris |
| 14278 | Ro'Bark |
| 14402 | Seeker Cromwell |
| 14403 | Seeker Nahr |
| 14404 | Seeker Thompson |
| 14423 | Officer Jaxon |
| 14438 | Officer Pomeroy |
| 14439 | Officer Brady |
| 14490 | Rippa |
| 14499 | Horde Orphan |
| 14729 | Ralston Farnsley |
| 14822 | Sayge |
| 14849 | Darkmoon Faire Carnie |
| 14882 | Atal'ai Mistress |
| 14908 | Mogg |
| 15008 | Lady Hoteshem |
| 15617 | Orgrimmar Legion Axe Thrower |
| 15961 | Lunar Festival Sentinel |
| 16060 | Gothik the Harvester |
| 16125 | Unrelenting Deathknight |
| 16145 | Deathknight Captain |
| 16146 | Deathknight |
| 16148 | Spectral Deathknight |
| 16156 | Dark Touched Warrior |
| 16163 | Deathknight Cavalier |
| 16167 | Bony Construct |
| 16378 | Argent Sentry |
| 16505 | Naxxramas Follower |

**Comment by cala** [comment]
Those are the ones with equipment only in the `*_raw` table?

**Comment by Tobschinski** [comment]
si

**Comment by cala** [comment]
Then, we have two options:
- find out/create the `creature_equip_template` entries for those creatures based on the model IDs from `creature_equip_template_raw` entries
- import their `creature_equip_template` from other DBs

Both can be automated by a script if you want me to write one.

**Comment by Tobschinski** [comment]
A lot of models are unknown, which does not make it easier ...

**Comment by cala** [comment]
Et zut... :/

I'll what I can do anyway when I'm back.

**Comment by Tobschinski** [comment]
Okay, I just compared the model_ids in our item_template table with the item_dbc of 2.4 ...

380 not matching items (which should be good)
203 of them are recently added monster items ... (which killed me a bit inside)

... and of course all models exist in our vanilla client!

**Comment by Tobschinski** [comment]
I might redo this ...

**Comment by cala** [comment]
I did hope there would have been less of them... :(

> ... and of course all models exist in our vanilla client!

That's because Blizz started silently adding TBC content in the Classic client even before releasing Naxxramas.
And I _assume_ at some point they realize they did wrong choices or did things in a hurry and then fix/rationalize/level/balance/whatever-it-is-called them here and then. They are probably still doing this as for now, this is usual "continuous improvement" process. 

If you grow tired of this equipment template stuff, we can discuss this on IRC when I'm back to see how I can help.

**Comment by Tobschinski** [comment]
I will use the TBC data, it doesn't change anything visually, but I trust it more to be correct (for vanilla) than the 6.x data from wowhead (although all models are known). Two are less than ten years, afair.

**Comment by cala** [comment]
I agree: you are fully right.
