### ISSUE TITLE
Quest - Counting out Time 

### ISSUE THREAD

**Issue by Tobschinski** [classicdb/database#292]
After completing quest [Counting out Time #1](http://www.wowhead.com/quest=4972), you should be able to accept the infinitely repeatable quest [Counting out Time #2](http://www.wowhead.com/quest=4973) with less xp gain.

**Comment by Tobschinski** [comment]
```
UPDATE `quest_template` SET `SpecialFlags`='1' WHERE `entry`='4973';
```

**Comment by cala** [comment]
Thanks for this report. The second quest should reward 575 XP at level 60 (source: wowwiki). This means, you want to update `RewMoneyMaxLevel` to 345 (see quest_template documentation for more details if you need). :)

**Comment by Tobschinski** [comment]
Oh, nice to know.
I wasn't even sure if this quest is intended to give experience.
Earlier 2006 sources say 575, like you did, earlier 2007 sources say 0. 

Yet to find some sources taken out of late 2006.

By the way, as it seems, every quest has a false experience reward. I noticed this while I was doing Barov Family Fortune and some other's at Bulwark. This quest gave me 14,500 experience, a WotLK value. That's about 2.2 more than hte classic one.

**EDIT: I will take care of the experience somewhere else, pretty much every quest grants a false value.**
