### ISSUE TITLE
Argent Quartermaster Hasana - Vendor List

### ISSUE THREAD

**Issue by Tobschinski** [classicdb/database#293]
Incorrectly, [Argent Quartermaster Hasana](http://wowhead.com/npc=10856) sells unlimited amounts of [Major Healing Potions](http://wowhead.com/item=13446) and [Major Mana Potions](http://wowhead.com/item=13444).

I do highly recommend to remove these potions from her vendor list, as it would be a massive intervention in a server's economy.

**Comment by Tobschinski** [comment]
```
DELETE FROM `npc_vendor` WHERE `entry`='10856' AND (`item`='13444' OR `item`='13446');
```

**Comment by cala** [comment]
Thanks, indeed she shouldn't sell these.
