### ISSUE TITLE
Quest ID 4681 Washed Ashore (An Land gespült)

### ISSUE THREAD

**Issue by Dainara82** [classicdb/database#296]
the 1. quest ID 3524  with the same title   works greate.
but quest ID 4681   every skelet turtle i click, it says  Hello Dainara. so it don't work

**Comment by Tobschinski** [comment]
What do you mean by 'every turtle', isn't there just one at loc (31,46)?

For me, at least, the quest is working.

![turtle](https://f.cloud.github.com/assets/4753528/2351542/9578d69a-a57d-11e3-9f9e-3e5516b2e9ac.png)

**Comment by cala** [comment]
Like @Shubu, I had no issue with this quest either. Please, note that due to the core issue related [here](https://github.com/classicdb/database/issues/142), all turtle corpses should display the "Greetings Name" gossip, except the one related to the quest. Are you sure you tried the right one?

**Comment by Dainara82** [comment]
ok it was my mistake, i clicked every turtlebones on the beach not under water, i thinked every turtlebones have to work

**Comment by cala** [comment]
No worry, we are all here to learn. :)
 Closing the issue now.
