### ISSUE TITLE
Found 4 guard too near of their braserio in ironforge

### ISSUE THREAD

**Issue by cyberium** [classicdb/database#297]
So they take constant fire damage :)

entry 5595
guid 131, 106, 107, 1743

**Comment by cala** [comment]
Nice to see you coming to the classic side. ;)
It seems that players moving near the brasero also take the fire damage even though they are at a reasonnable and safe distance. So, I wonder if the spell used by those braseros has a two wide range (or wrong version of the spell).

**Comment by cyberium** [comment]
More info:
Brasero next to those guard seem not cause damage to player where the one near inn entrance does.

If i take another exemple, Dink (mage master in mysticplace) is extremly near of one brasero but take no damage. But playerget damage if they approach it.

**Comment by Swater96** [comment]
The bonfires at the naxxramas graveyard in WPL also strike the guards every tick.

**Comment by kokeszko** [comment]
Same thing in Orgrimmar. Guards standing near the way to the cleft of shadow (when you enter it from the drag) are also hit by brasero

**Comment by PatSmuk** [comment]
Maybe the guards are in the right place, and the brasero is wrong?

**Comment by kokeszko** [comment]
@Patman64 i don't know that

**Comment by DomGries** [comment]
I think the damage range of core has been incorrect for those gameobjects since for ever.

https://github.com/TrinityCore/TrinityCore/commit/6cd8d1286f48671cd2e782b3a6803d7e951cb0f5
https://github.com/TrinityCore/TrinityCore/commit/7e651ed72924b864111ea634dd98deed513e6847

No idea if that is the proper solution.

**Comment by Swater96** [comment]
@Patman64 since this happens in multiple different locations with multiple different objects I think the issue is more deep than NPC placement.

**Comment by cala** [comment]
The radius error pointed out by @stfx looks very promising to me, more than a placement error of a few NPCs/GOs

**Comment by cala** [comment]
Closed: this was a core issue where trap diameter was used instead of radius, resulting in an activation area four times what it should be.
