### ISSUE TITLE
Quest - Craftsman's Writ

### ISSUE THREAD

**Issue by Tobschinski** [classicdb/database#298]
- 3 (of 24) quests do have a wrong level requirement (instead of 55)
- some grant way to less or much reputation (instead of 25)
- some Sealed Craftsman's Writs are not repeatable

---

[Craftsman's Writ - Dense Weightstone](http://www.wowhead.com/quest=9178)
[Craftsman's Writ - Imperial Plate Chest](http://www.wowhead.com/quest=9179)
[Craftsman's Writ - Volcanic Hammer](http://www.wowhead.com/quest=9181)
[Craftsman's Writ - Huge Thorium Battleaxe](http://www.wowhead.com/quest=9182)
[Craftsman's Writ - Radiant Circlet](http://www.wowhead.com/quest=9183)
[Craftsman's Writ - Wicked Leather Headband](http://www.wowhead.com/quest=9184)
[Craftsman's Writ - Rugged Armor Kit](http://www.wowhead.com/quest=9185)
[Craftsman's Writ - Wicked Leather Belt](http://www.wowhead.com/quest=9186)
[Craftsman's Writ - Runic Leather Pants](http://www.wowhead.com/quest=9187)
[Craftsman's Writ - Brightcloth Pants](http://www.wowhead.com/quest=9188)
[Craftsman's Writ - Runecloth Boots](http://www.wowhead.com/quest=9190)
[Craftsman's Writ - Runecloth Bag](http://www.wowhead.com/quest=9191)
[Craftsman's Writ - Runecloth Robe](http://www.wowhead.com/quest=9194)
[Craftsman's Writ - Goblin Sapper Charge](http://www.wowhead.com/quest=9195)
[Craftsman's Writ - Thorium Grenade](http://www.wowhead.com/quest=9196)
[Craftsman's Writ - Gnomish Battle Chicken](http://www.wowhead.com/quest=9197)
[Craftsman's Writ - Thorium Tube](http://www.wowhead.com/quest=9198)
[Craftsman's Writ - Major Mana Potion](http://www.wowhead.com/quest=9200)
[Craftsman's Writ - Greater Arcane Protection Potion](http://www.wowhead.com/quest=9201)
[Craftsman's Writ - Major Healing Potion](http://www.wowhead.com/quest=9202)
[Craftsman's Writ - Potion of Petrification](http://www.wowhead.com/quest=9203)
[Craftsman's Writ - Stonescale Eel](http://www.wowhead.com/quest=9204)
[Craftsman's Writ - Plated Armorfish](http://www.wowhead.com/quest=9205)
[Craftsman's Writ - Lightning Eel](http://www.wowhead.com/quest=9206)

**Comment by Tobschinski** [comment]
```
UPDATE `quest_template` SET `MinLevel`='55', `SpecialFlags`='1', `RewRepValue1`='25', `RewRepFaction1`='529'  WHERE `entry` IN ('9178', '9179', '9181', '9182', '9183', '9184', '9185', '9186', '9187', '9188', '9190', '9191', '9194', '9195', '9196', '9197', '9198', '9200', '9201', '9202', '9203', '9204', '9205', '9206'); 
```

**Comment by cala** [comment]
Thanks for this work.
I agree with the change in repeatability, level and faction. However, according to http://www.wowwiki.com/Craftsman%27s_Writs?oldid=347898 the reputation gain should be 50 for each turn in (and 10 for acceptiong the initial writ). It was upgraded later in TBC.
