### ISSUE TITLE
quest ID 5821    Bodyguard for Hire

### ISSUE THREAD

**Issue by Dainara82** [classicdb/database#302]
NPC ID 11625   Cork Gizelton
Quest don't go, i tried it and 3 other player tried it
you get the quest, the npc still standing and do nothing, than the npc stay always on the same position, the kodo's walk to the end point from the quest, if you follow the kodos the quest will don't be finished
we got the quest from the half way not from beginning, i don't know if this is the trouble

**Comment by cala** [comment]
Thank you for this report. Like all escort quests, this one has to be handled by SD2. An issue there is already opened so I'm closing here. :)
https://github.com/scriptdev2/scriptdev2/issues/27
