### ISSUE TITLE
Quest - A Rogue's Deal #2

### ISSUE THREAD

**Issue by Tobschinski** [classicdb/database#303]
It seems, that Quest - [A Rogue's Deal #2](http://wowhead.com/quest=590) needs some improvements.
- nearby guards shouldn't assist you (if they defeat Calvin, which will most likely be the case, you will not be able to complete the quest)
- it takes a long time to recognize the defeat of Calvin
- Calvin does not use his rude emote after being defeated

**Comment by cala** [comment]
Thank you. This issue was already reported: https://github.com/classicdb/database/issues/66 
I tried to fixed it but was unsuccessful. So I'm closing this one and updating the previous one.
