### ISSUE TITLE
Players cannot enter BRD instance below level 60

### ISSUE THREAD

**Issue by cala** [classicdb/database#31]
Well you should be able to enter Black Rock Depths at level 48, seems to be a database error, I've deleted the following entry from areatrigger_teleport -> " id | name | required_level | required_item | required_item2 | required_quest_done | target_map | target_position_x | target_position_y | target_position_z | target_orientation
2890 | Molten Core Entrance, Inside | 60 | 0 | 0 | 0 | 230 | 1115.35 | -457.35 | -102.7 | 0.5 "

that seemed to have fixed it.

If you don't delete it, you get the message that "you have to level 60 to enter this instance" in an infinite loop even though you aren't even trying to enter anymore.

_original report by Herpaderp1_

Submitted commit by Titarion: https://github.com/mangoszero/database/commit/579e5d850e8c7a4a5879c9e7273820c4f6fa4ee0

**Comment by Swater96** [comment]
"-- Set The Molten Core -> BRD areatrigger to level 48
UPDATE `areatrigger_teleport` SET `required_level` = 48 WHERE `id` = 2890;" 

Tested out this fix from https://github.com/mangoszero/database/commit/579e5d850e8c7a4a5879c9e7273820c4f6fa4ee0 by Titarion on a fresh install of the classicdb and CMANGOS and SD2-classic, BRD entrance working as intended at level 48 when this script is applied.

**Comment by cala** [comment]
Thank you. Fixed in [0121] https://github.com/classicdb/database/commit/eeff222234bf9301409944b1f2c226801350a8b8
