### ISSUE TITLE
Quest 8446 and 8447 are not completable

### ISSUE THREAD

**Issue by cala** [classicdb/database#32]
Quest 8446 is missing completion data
source: [completion text](http://www.wowwiki.com/Quest:Shrouded_in_Nightmare)
Quest 8447 is missing almost everything, especially db_script.
sources: 
- [Quest text](http://www.wowwiki.com/Quest:Waking_Legends)
- [Video](http://www.youtube.com/watch?v=7S6_U8qNU2U)

**Comment by cala** [comment]
Update: quest 8446 is OK. Quest 8447 needs script.

**Comment by cala** [comment]
Research on possible spells used by the script in quest 8447 :
- Throw performed by Remulos: 25004 "Throw Nightmare Object"
- Possible aura spell of Malfurion: 24999 "Malfurion's Shade"

**Comment by scotty0100** [comment]
cala, does Waking Legends need DB script or do you think SD2 needs to be involved?

https://github.com/scriptdev2/scriptdev2-classic/issues/21

**Comment by Grz3s** [comment]
https://github.com/unified-db/Database/commit/8d6e23b090ea95e4230e9f431229b6c02efe1da3
