### ISSUE TITLE
Zone Overhaul - Shadowfang Keep - XP, minLVL, qLVL

### ISSUE THREAD

**Issue by Tobschinski** [classicdb/database#323]
Some 'experience' and 'min/qlevel' values in Shadowfang Keep (Zone: 209) are wrong, regarding Bradygames' Master Guide, web.archive.org/2006/wow.allakhazam.com and web.archive.org/2006/wowhead.com.

---

total experience
- ManGOS:   9,600
- Classic:  7,400
- Mismatch:-2,200

**Comment by Tobschinski** [comment]
```
UPDATE `quest_template` SET `RewMoneyMaxLevel`='1260' WHERE `entry`='1013';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='1200' WHERE `entry`='1098';
```

```
```

**Comment by cala** [comment]
Thanks for regrouping them. :+1:
