### ISSUE TITLE
Quest 8305 and 8519 are not completable

### ISSUE THREAD

**Issue by cala** [classicdb/database#34]
Quest 8305 should autocomplete when speaking with related GO

Quest 8519 is merely an event which gives automatically complete credits at end:
Source: [video of event](http://www.youtube.com/watch?v=kbK0_3NW280]

**Comment by Schmoozerd** [comment]
hmm, i am a bit unsue which quest is which, but i think the cinematic scene is implemented with SD2
So i kind of assumed this must work oO :)

**Comment by cala** [comment]
I did not last time I check: there was no cinematic after accepting quest. However, I'm not sure that I was testing on a DB with SD2 installed. Maybe it was one of the development DB I'm working on (with no SD2 usually).

I'll test again. Thank you for the input. :)

**Comment by cala** [comment]
After testing with the newly cleaned DB, quest 8519 does play its cinematic as intended. There are only a few modifications to do DB side (wrong factions and scale, mainly).

On three tests, quest 8305 worked once, did not complete twice. I'm trying to understand why.

**Comment by Schmoozerd** [comment]
hmm, maybe still some problem with targeting of the aoe quest-credit spell. I remember there had been quite some annoying issues with it in the past :(
