### ISSUE TITLE
Creatures 16194 and 16216 have wrong equipment model

### ISSUE THREAD

**Issue by cala** [classicdb/database#35]
Creature 16194 should have equipment like: http://www.wowwiki.com/Unholy_Axe?file=Unholy_Axe_old.jpg
Creature 16216 should have equipment like: http://www.wowwiki.com/Unholy_Swords?file=UnholySwords.JPG

**Comment by Swater96** [comment]
Alright I have researched this and here is what I have found.
- Unholy Staff (16215) has the sword modelid and should have the ID of the Headmaster's Charge (13937)
- Unholy Axe (16194) model is the Pendulum of Doom (9425) and the display ID of that weapon is (22220)
- Unholy Swords (16216) I cannot find an exact copy of the model..but the closest I can find in all of the MPQ's is the Haunting Blade (6641)

**Comment by cala** [comment]
Thank you for looking to the right or almost right models. I will test them soon(tm). :+1: 
Unholy staff model was previously fixed in https://github.com/classicdb/database/commit/b5a4ec40624c6462f79d7103ec412a32f8e1cebf

**Comment by cala** [comment]
Can someone test this update, please:

``` sql
DELETE FROM `creature_equip_template_raw` WHERE `entry` = 1003;
INSERT INTO `creature_equip_template_raw` (`entry`, `equipmodel1`, `equipmodel2`, `equipmodel3`, `equipinfo1`, `equipinfo2`, `equipinfo3`, `equipslot1`, `equipslot2`, `equipslot3`)
VALUES  (1003, 23539, 0, 0, 285346306, 0, 0, 2, 0, 0);
-- Fixes equipement with correct model for creature 16215 (Unholy Swords)
UPDATE `creature_equip_template_raw` SET `equipmodel1` = 20167, `equipmodel2` = 20167,`equipmodel3` = 0, `equipinfo3`= 0, equipslot1` = 781, `equipslot2` = 781,  `equipslot3` = 0 WHERE `entry` = 1726;
-- Fixes equipement with correct model for creature 16194 (Unholy Axe)
UPDATE `creature_equip_template_raw` SET `equipmodel1` = 22220, `equipmodel2` = 0,`equipmodel3` = 0 WHERE `entry` = 1725;
```

Even with cleared cache, I still see a placeholder for the offhand sword of Unholy Swords and I'm not sure this is due to the query being wrong.

**Comment by Swater96** [comment]
will test on my box asap for you

**Comment by Swater96** [comment]
There were some syntax errors preventing the code from running, fixed version is below

<code>DELETE FROM `creature_equip_template_raw` WHERE `entry` = 1003;
INSERT INTO `creature_equip_template_raw` (`entry`, `equipmodel1`, `equipmodel2`, `equipmodel3`, `equipinfo1`, `equipinfo2`, `equipinfo3`, `equipslot1`, `equipslot2`, `equipslot3`)
VALUES  (1003, 23539, 0, 0, 285346306, 0, 0, 2, 0, 0);
-- Fixes equipement with correct model for creature 16215 (Unholy Swords)
UPDATE `creature_equip_template_raw` SET `equipmodel1` = 20167, `equipmodel2` = 20167,`equipmodel3` = 0, `equipinfo3`= 0, `equipslot1` = 781, `equipslot2` = 781,  `equipslot3` = 0 WHERE `entry` = 1726;
-- Fixes equipement with correct model for creature 16194 (Unholy Axe)
UPDATE `creature_equip_template_raw` SET `equipmodel1` = 22220, `equipmodel2` = 0,`equipmodel3` = 0 WHERE `entry` = 1725;
</code>

![naxx](https://f.cloud.github.com/assets/540552/763077/ee46db22-e7f6-11e2-93fa-58de3e502b89.jpg)
Looks like one of the swords is working correctly and the other left side is not

**Comment by cala** [comment]
Thank you very much for testing this soon. It looks like you have the same issue than me. But I don't understand why and the MySQL table used here is specific to classic and thus documentation is missing... I'll try something else. :P
