### ISSUE TITLE
Zone Overhaul - Stockades - XP, minLVL, qLVL

### ISSUE THREAD

**Issue by Tobschinski** [classicdb/database#352]
Some 'experience' and 'min/qlevel' values in Stockades (Zone: 717) are wrong, regarding Bradygames' Master Guide, web.archive.org/2006/wow.allakhazam.com and web.archive.org/2006/wowhead.com.

---

total experience

ManGOS: 19600
Classic: 14800
Mismatch: -4800

**Comment by Tobschinski** [comment]
```
UPDATE `quest_template` SET `RewMoneyMaxLevel`='1650' WHERE `entry`='378';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='1260' WHERE `entry`='377';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='1200' WHERE `entry`='386';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='1590' WHERE `entry`='387';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='1590' WHERE `entry`='388';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='1590' WHERE `entry`='391';
```

```
UPDATE `quest_template` SET `MinLevel`='22' WHERE `entry`='378';
```

**Comment by Swater96** [comment]
Hmmm... The experience values in my dungeon champion for classic WoW do not compare with yours. For example quest 378 "The Fury Runs Deep" shows as max xp 2,750, where yours shows 1,650.

**Comment by Tobschinski** [comment]
Oh, you have to multiply that value with (5/3).

1650 \* (5/3) = 2750

[RewMoneyMaxLevel](https://github.com/cmangos/issues/wiki/Quest_template#wiki-rewmoneymaxlevel)

**Comment by Swater96** [comment]
Oh awesome. Really impressed with your work. Going to be doing every zone and instance?

**Comment by Tobschinski** [comment]
If I can keep myself motivated ... 

Strangle was painful.
