### ISSUE TITLE
NPC - Cloth Quartermaster - Miscellaneous

### ISSUE THREAD

**Issue by Tobschinski** [classicdb/database#364]
- the [Alliance Cloth Quartermaster](http://old.wowhead.com/npc=14725/raedon-duskstriker#starts) in Darnassus is missing 2 quests (they do not exist in DB) ...
  - [A Donation of Wool](http://wowhead.com/quest=10352)
  - [A Donation of Silk](http://wowhead.com/quest=10354) 
- some quests are missing their quest-requirements (runecloth only after completing lower tiers)
- some quests have different information texts
- some quests have a false min and qlvl
- some quests have a false experience gain
- some quests are missing emotes

**Comment by cala** [comment]
Those two quests were added after classic, that is why they are not in the DB. But their classic equivalent (I think availability was related to reputation with each city) should be in the DB but probably not linked to the NPC.

**Comment by Tobschinski** [comment]
There are only 7 quests named 'a donation of wool' and 'a donation of silk', but 8 for other tiers.
But thanks for pointing, wowhead.com may have messed up the quest-ids.

Regarding thottbot and allakhazam, http://wowhead.com/quest=10352 and http://wowhead.com/quest=10354 have existed in 2006, it may have been in TBC-beta, I do not know ...
AdditionalIy, I have found the quests http://wowhead.com/quest=7792 and http://wowhead.com/quest=7798
However, regarding wowhead.com, these quests should be linked to the exodar quest-giver, added in TBC.

This may have 2 causes ...
- wowhead has messed up the ids.
- Blizzard has changed something with their TBC-launch

Since all 4 quests are missing in DB, I do have to add at least 2.

Your call, which ones to choose .... :)
