### ISSUE TITLE
Cala, Spell training costs

### ISSUE THREAD

**Issue by Swater96** [classicdb/database#367]
Hey, I was looking through my WoW Master Guide, and noticed that just about every trained spell in-game does not match with what is in the guide. Would there be a reason for that? Like Ingame a spell costing 00,01,47 when in the guide it costs 00,01,60. 

If this is in-fact an inaccuracy of the classicdb values, I am willing to go through all class spells and change the values to match the guide.

**Comment by Swater96** [comment]
The classic one

**Comment by Sinoxan** [comment]
http://hydra-media.cursecdn.com/wowpedia.org/7/7a/WoWSG2Ed.jpg

This one?

**Comment by Swater96** [comment]
Yeah it's the second edition

**Comment by Sinoxan** [comment]
I've managed to download a copy and the values match those on Wowpedia.  I can help you out with it if you want.

**Comment by Swater96** [comment]
Yeah that'd be awesome. I'm going to start work tomorrow. I suppose since there's 9 classes I'll do 4 and you could do 4 if you want. Whoever wants the last can do it.

**Comment by Sinoxan** [comment]
Ok, I'll try and do what I can.

**Comment by Swater96** [comment]
I'll start with Druid Mage warlock and warrior

**Comment by cala** [comment]
Thank you for pointing this. Before you start such a long work it would be safer to ensure this is a database issue. This could also be a modifier in core wrongly set, a modifier in config file, one of the discounts players get for reputation or PvP rank... There are many things that affect the price of something between what is in DB and what players see in-game.

Thus, could you give us a few exemples of spells with wrong cost, possibly at least three classes and not always of first rank ? What you get in-game and what it should be according to your guide. Thank you. :)

**Comment by PatSmuk** [comment]
Yes, please check that the base values in the DB (npc_trainer/spellcost) do not match the book since there is a discount for exalted.

**Comment by Swater96** [comment]
Ingame: Druid - Rejuvenation (NE talking to Darn Trainer with friendly rep)
R1 - 95c
R2 - 2s85c
R3 - 17s10c

Ingame: Hunter - Immolation Trap (NE talking to Dwarf with SW faction listed with friendly rep)
R1 - 17s10c
R2 - 66s50c
R3 - 1g33s00c

Ingame: Priest - Renew (UD talking to Org trainer with neutral reputation)
R1 - 2s
R2 - 12s
R3 - 30s

WoW Master Guide - 
Druid - Rejuvenation R1 - 1s, R2 - 3s, R3 - 18s
Hunter - Immolation Trap R1 - 18s, R2 - 70s, R3 - 1g40s00c
Priest - Renew R1 - 2s, R2 - 12s, R2 - 30s.

All spells were not matching up except for the priest spells. In that case it was an Undead character speaking to an Orgrimmar trainer. Orgrimmar rep was at neutral and it gave the correct prices for the spells. So it looks like the base values are according to the master guide.

So my question now becomes should spell costs be modified by friendly reputation? And if so then it looks to me like the costs are blizzlike and working as intended.

**Comment by PatSmuk** [comment]
> So my question now becomes should spell costs be modified by friendly reputation? And if so then it looks to me like the costs are blizzlike and working as intended.

Yes, please see here: http://www.wowwiki.com/Reputation

I don't see any issues here. But if the reputation discounts are wrong then it's a core issue. Closing.

**Comment by Tobschinski** [comment]
Patch 2.3.0 (13-Nov-2007): Vendor Discounts: All vendors, flightmasters, and repairs with an associate faction now give discounts at all levels above neutral: (Friendly: 5%, Honored: 10%, Revered: 15%, Exalted: 20%).
            **Previously there was a flat 10% discount starting at honored.**
