### ISSUE TITLE
[Reputation] - Cenarion Circle / Brood of Nozdormu

### ISSUE THREAD

**Issue by Tobschinski** [classicdb/database#369]
#### Involved Factions:
- 609   - [Cenarion Circle](https://github.com/cmangos/issues/wiki/Faction.dbc)
- 910   - [Brood of Nozdormu](https://github.com/cmangos/issues/wiki/Faction.dbc)

---
#### Issues:
- [Qiraji's Lord Insignia](http://www.wowhead.com/item=21229/qiraji-lords-insignias) grants 500 **Circle of Cenarion** reputation instead of just 100. **[DONE]**
- ~~Trash in AQ40 grant 500 reputation with **Brood of Nozdormu** instead of just 100.~~ Vekniss Warrior, Stinger, Wasps, Hive-Crawler still need to be updated
- ~~Trash in AQ40 grant 25 **Cenarion Circle Reputation**, instead of 0.~~ see above
- Twin Emperors do not grant additional **Brood of Nozdormu** reputation. (7 x 30 = 210) 
    -> needs to be done by SD2, or not? you cannot add reputation for both of them, it would double the amount.
- C'thun does not grant additional **Brood of Nozdormu** (2500), nor **Cenarion Circle** reputation (500)
- Bugged quest at Kandrostrasz. (both 'Mortal Champions' are available, one is missing description and rewards) **[DONE]**
- Quests for T2.5-Set do not grant reputation (250 **Brood of Nozdormu**).

---
#### to-do:
- every related quest
- do retail run

---
#### Source:
- http://web.archive.org/web/20061117105309/http://www.wowwiki.com/Cenarion_Circle_Reputation_Guide
- http://web.archive.org/web/20061108193004/http://www.wowwiki.com/Brood_of_Nozdormu
- http://web.archive.org/web/20061115215023/http://www.worldofwarcraft.com/info/basics/factions/broodofnozdormu/

**Comment by Swater96** [comment]
also worth investigating the rep gained while progressing through the ranks Friendly>Honored>Revered...ect ect..

**Comment by cala** [comment]
@Tobschinski : With the recent commits you made to AQ40, I think some of the issues listed here can be checked.

**Comment by Tobschinski** [comment]
Oh yeah, this list. Let's see ...

**Comment by Tobschinski** [comment]
As it seems, I've been lazy, not really much to update ...

I'll do the rest [soon](http://wowpedia.org/Soon) :)

**Comment by cala** [comment]
Sorry, I think my previous comment was a bit pushy and it was not meant to be.

I'm currently thinking of slowly moving toward the next release of Classic DB and with all the nice work you did on AQ40, I think the main topic of this release is pretty obvious.
So, I was reviewing the current issues of AQ40 to estimate what is left to do.

Thanks for your recents changes! :+1:

**Comment by Tobschinski** [comment]
Oh, no, I'm not offended at all, no worries! 

> As it seems, I've been lazy, not really much to update ... 

I agree, this may be interpreted as such, my bad! I just made some fun of myself there ...
