### ISSUE TITLE
Some zones do not have pools for herbs resources

### ISSUE THREAD

**Issue by cala** [classicdb/database#37]
In Felwood (and other areas), herbs are not in the pool system and this results in too many gameobject spawns.

**Comment by Neotmiren** [comment]
Also there is extremely huge amount of resources in Barrens, especially Earthroot and Stranglekelp near Ratchet (and Stranglekelp is expensive - can be sold by low-level characters to vendors to gain easy gold).

On other side, amount of resources in Westfall are normal, but there are almost no Tin in Jangolode Mine which is known as the best source of Tin in World of Warcraft.

**Comment by cala** [comment]
The Barrens is also one of the area with no pool data, leading to huge amount of resources as you have noticed. Fixing this is part of the next milestone for classic DB.

I will have a look a tin mineral spawns in Jangolode Mine. However, keep in mind that some mineral spawns are shared with other ores, meaning that in some cases you must mine the copper mine before it can be respawned as a tin ore mine (with a 40% chance, I think). I don't know if there are such shared spawns in Jangolode Mine.

**Comment by Neotmiren** [comment]
Temporary solution to get rid of huge amounts of resources by creating pools automatically

http://pastebin.com/j9XfLg9R

Depending on $overwriteAllPools flag it can be applied to all resource nodes or only to non-pooled ones. It also spreads resources evenly If applied to all nodes.

**Comment by cala** [comment]
Closed by https://github.com/classicdb/database/commit/edcefbb52cec247e00d71c0623059368eb3c84be
Thank you.
