### ISSUE TITLE
[AQ40] - Buglist

### ISSUE THREAD

**Issue by Tobschinski** [classicdb/database#371]
Just for gathering information.

**Comment by Tobschinski** [comment]
... closing!

**Comment by Tobschinski** [comment]
##### Abundant Creatures
- remove Vekniss Borer (all) **[DONE]**
- remove Yauj Brood (all) **[DONE]**
- remove Vekniss Guardian (1 Pack) **[DONE]**
- remove Vekniss Warrior (all but 2 packs) **[DONE]**
- remove Brood of Fankriss (all) **[DONE]**
- remove Vekniss Hatcher (all) **[DONE]**
- remove Anubisath Defender (one) **[DONE]**
- remove Obsidian Eradicator (two) **[DONE]**
- remove Qiraji Lasher (all) **[DONE]**
- remove Anubisath Warrior (all) **[DONE]**
- remove Vekniss Stinger (if more than 1 per pack) **[DONE]**
- remove Vekniss Wasp (if more than 2 or 3 per pack) **[DONE]**
- remove Anubisath Swarmguard (all) **[DONE]**
- remove Vekniss Hive Crawler (all but 3 packs)  **[DONE]**
- remove Vekniss Soldier (one) **[DONE]**

---

#### Missing Creatures
- add Obsidian Eradicator (one) **[DONE]**
- add Qiraji Lasher
- add Vekniss Wasp
- add Vekniss Stinger
- add Qiraji  Scarab
- add Qiraji Scorpion
- add Qiraji Champion **[DONE]**
- add Qiraji Slayer
- add Qiraji Mindslayer
- add Obsidian Nullifier
- add Anubisath Warder 
- add Critter

---

#### Movement Creatures
- Obsidian Eradicator (three) **[DONE]**
- Vem (FFS, the guy that added movement to Vem must have been drunk) **[DONE]**
- Vekniss Warrior
- Battleguard Sartura
- Vekniss Soldier
- Vekniss Hive Crawler
- Vekniss Stinger
- Princess Huhuran (one) **[DONE]**
- Anubisath Defender (five)  **[DONE]**
- Qiraji Champion (eight) **[DONE]**
- Critter

---

#### Moving Creatures
- T2.5 NPCs (three) **[DONE]**
- The Prophet Skeram **[DONE]**
- Weapon NPCs (three)
- Bug-Trio  **[DONE]**
- Bug-Trio Trash
- Battleguard Sartura Trash
- The Prophet Skeram Trash
- C'Thun Trash

---

#### Gameobjects
- remove Small Obsidian Chunks **[DONE]**
- remove Large Obsidian Chunks **[DONE]**
- add Areatrigger Battleguard Sartura
- lock Greater Scarab Coffer **[DONE]**
- adjust Greater Scarab Coffer
- adjust Twin Emperor Door
- add idols to chest (removed Q-Chance) **[DONE]**
- remove barrier for 3 NPCs at C'Thun after his defeat

---

##### Quest
- T2.5 quest-requirements **[DONE]**
- Quest Mortal Champions **[DONE]**

---

#### Reputation
- add Qiraji Brainwasher-Rep
- change Trash-Rep
- add C'Thun-Rep
- add Twin Emps-Rep

---

#### Miscellaneous
- add Stealth-Detection Qiraji Mindwasher **[DONE]**
- add Stealth-Detection Qiraji Guardian **[DONE]**
- add Frenzy Aura to Qiraji Soldier **[DONE]** 
- change respawn timers
- add creature-linking
- change aggro-range 
- change movement speed
- change scale Bug-Trio **[DONE]**
- change scale Andorgos **[DONE]**

**Comment by Tobschinski** [comment]
Please, let me know if someone has something to add to the list. If I have any questions, I'll put them in this post.
- How do I make the Frenzy Aura of Vekniss Soldiers stackable with other Soldiers?
- Does someone remember if the visual effect of [Stealth Detection](http://www.wowhead.com/spell=8279) (blue eye) was already live in vanilla?

![180px-stealth_imunity 1](https://f.cloud.github.com/assets/4753528/2492180/98657de0-b216-11e3-8b48-996eb02ab021.jpg)
- How do I change the aggrorange of a creature? I have seen no dbfields that would match ...

**Comment by PatSmuk** [comment]
Have you checked if the doors in the Triangle Room (Twin Emps) exist and work?

**Comment by Tobschinski** [comment]
They do both, exist and work. There is just a small adjustment needed to match the frame. (orientation)

EDIT: After Twin Emps evaded, both door opens and will never be closed again! That should be changed.

EDIT 2: NVM, change it to they do work partially. I have managed to outsync the front door somehow. It is closed when I am out of fight and opens when I am fighting Emps ...
