### ISSUE TITLE
Western Plaguelands (WPL) mobs wrongly classified as elites

### ISSUE THREAD

**Issue by scotty0100** [classicdb/database#374]
Fix for the elites, I will paste below the bug report so you can make your decision whether to use it or not based on the sources provided.

UPDATE `creature_template` SET `rank` = 0 WHERE `entry` =  4475;      -- Blighted Zombie
UPDATE `creature_template` SET `rank` = 0 WHERE `entry` =  1794;      -- Soulless Ghoul 
UPDATE `creature_template` SET `rank` = 0 WHERE `entry` =  1795;      -- Searing Ghoul

**Comment by scotty0100** [comment]
Bug Report:

After a short trip to the Western Plaguelands I noticed numerous elite mobs which shouldn't be elites.

I haven't checked every single mob but the ones that I noticed:

Mobs around the cauldrons:
None of those should be elite, they were all normal non-elites back in vanilla. Example: Blighted Zombies around the 2nd cauldron. I haven't checked all 4 cauldrons but there shouldn't be any elites around them.

Most Andorhal mobs:
The only Andorhal mobs that should be elites are:

The patrolling Flesh Golems (Stitches type things)
The lone Skeletal Warlords inside the towers (for the All along the watchtowers quest - 1 in each tower)
The mobs guarding Araj (not sure if all of them, but I do know the Skeletal Warlords were elite)
And of course Araj himself
That's it, nothing else was elite in vanilla Andorhal - i.e. the skeleton/ghoul trash that's all over Andorhal were normal, non-elite mobs.
Even Feenix has this partly wrong because they classed the Searing Ghouls (one of the trash mobs) as elites when they weren't back in vanilla.

Source: Vanilla is my favourite state of the game, played it since launch and spent a lot of time on WoW back then so I remember a lot of things pretty well. But you can also check the old comments on WoWhead, their context clearly indicates these mobs weren't elite.

**Comment by scotty0100** [comment]
Bug Report Part 2:

Unfortunately I couldn't find a documented vanilla source yet, but here's a TBC video from before the big vanilla nerf of the 2.3 patch showing a lvl 57 mage AoE grinding the Dalson's Tears cauldron (where some mobs -Blighted Zombies- are currently marked as elite)

http://www.youtube.com/watch?v=gW7D7iKGDBg

A wowhead comment on Blighted Zombies from before 2.3 notes the area is good for AoE grinding. Also, the 1st and 3rd cauldrons (haven't checked the 4th one yet) have no elites around them. It wouldn't make sense to have plenty of elites around just the 2nd cauldron, making that sub-quest unfairly difficult and perhaps outright impossible for some classes when all the other cauldrons are perfectly soloable, just like they were in vanilla.

As for the Andorhal mobs, again vanilla sources are close to non-existent so I'm afraid you will have to rely on the memories of old-time vanilla players like myself on many of these issues.
The closest thing I could find to a digital source is a wowhead comment from 2.0.1 (the last patch before TBC, so it's actually still vanilla):

http://old.wowhead.com/npc=1795#comments

The commenter notes they have insane dps for their level, advising caution for when someone grinds Andorhal. This comment wouldn't make much sense if the mob had been elite, as something like this is only worth pointing out if it isn't obvious - i.e. the mob is non-elite and appears to be just another random trash. But the commenter is correctly surprised as I also remember those fire-casting zombies dealing extreme dps despite being non-elite and pulling 2 was often a lethal mistake.

Comments for the Soulless Ghoul don't mention anything about it being elite either - i.e. none of them refer to having any particular difficulties with the mob apart from its mana drain (which was indeed annoying).

The only elite mob (apart from Araj and his entourage) that you could encounter in the open areas of Andorhal were the Flesh Golems (big Stitches type abominations) which patrolled the streets. This mob has a lot of comments compared to the others and most of these are people bragging of how they soloed it and how easy it was to kill despite it being elite. If the above mentioned zombies had been elites as well, they'd probably have similar comments on their respective entries.

The Skeletal Warlords (inside the Andorhal towers and in Araj's bodyguard) were also elite and they too have people commenting on how they were soloed.

Some further information to confirm this:

The earliest Wowpedia entry for the Searing Ghouls, listing them as non-elite, dated April 2007 (TBC, but before the vanilla content nerf of 2.3.0):

http://wowpedia.org/index.php?title=Searing_Ghoul&oldid=606742

**Comment by cala** [comment]
Thank you for the report. As far as I remember, mobs around the cauldrons were not elite, not even the cauldron lords.

Regarding Andorhal, most of the mobs were not elite. Araj was elite and maybe the few abominations patrolling in the streets.

I'll check this when I'm back from holidays.

**Comment by Schmoozerd** [comment]
I think the rank is shipped with CREATURE_QUERY_RESPONSE.
So the correct rank must be included in the wdb files.

Hence old databases should usually have correct rank information, and maybe you also can get old wdb files from the old developers, or they might be lying around in some archieves.

Parsing wdb files is also much easier -- so you should be able to do large-scale development for stuff like ranks, which likely is a good idea.
