### ISSUE TITLE
Wrong stats on cloth item

### ISSUE THREAD

**Issue by zartor** [classicdb/database#376]
I've notice a few cloth items with strength stats bonus where they should have intel.

For exemple, the Blue Overalls from westfall plans  sold by Gina MacGregor state +4 Strength and +4 Stamina while it should be +4 Intel and + 4 stamina.
Ref: http://www.wowhead.com/item=6263/blue-overalls

**Comment by Swater96** [comment]
Thank you for your report. 

This does not apply to classic, a while back Blizzard pretty much changed every stat on any given piece of armor to make them somewhat viable to appropriate classes. This means 99% of wowhead data is now useless and cannot be trusted. Here is a link to the 2007 version of the same item that you have provided. (http://www.wowwiki.com/Blue_Overalls?oldid=556964)

As you can see it is really supposed to be str and stam given on a cloth item. That's just how it used to be. Think of holy paladins wearing nice colourful cloth robes...yeah...that happened. Scary, I know!

**Comment by PatSmuk** [comment]
Thanks for confirming. Closed.
