### ISSUE TITLE
Uniting the Shattered Amulet with fix.

### ISSUE THREAD

**Issue by scotty0100** [classicdb/database#381]
http://wowascension.com/wowhead/?quest=3627

Currently you can not slay Grol the Destroyer, Lady Sevine, and Archmage Allistarj.

As they all go immune at 1% which is correct, but the Ehchanted Weapon from the previous quest does not work. It says invalid target when you try to use it on them

The fix:

/\* Grol the Destroyer */
INSERT INTO spell_script_target VALUES ('12938', '1', '7665', '0');

 /\* Lady Sevine */
INSERT INTO spell_script_target VALUES ('12938', '1', '7667', '0');

/\* Archmage Allistarj */
INSERT INTO spell_script_target VALUES ('12938', '1', '7666', '0');

Then everything works fine.

**Comment by scotty0100** [comment]
Oh the one you closed cala was different I believe, I saw that when I was placing this one. The one you closed was referring to the Servants of Grol/Allistarj etc. Which I believe should drop down to 1%, and then you need to do something with them for a separate quest - this one is for the actual named bosses Grol the Destroyer, Lady Sevine, and Archmage Allistarj.

**Comment by cala** [comment]
Thanks for this report and fixes, I'll test them soon. :+1:
