### ISSUE TITLE
Quest: Cenarion Plant Salve

### ISSUE THREAD

**Issue by scotty0100** [classicdb/database#387]
## Original Bug Report:

Map & Area: Felwood

How to replicate the bug: Get Cenarion plant salve from Arathandris Silversky in southern Felwood. Find corrupted plants.

What happens: One of two things is happening, neither correct. Sometimes the dialogue window for the corrupted plan just says "Greetings, Name." Other times I am able to use the salve on the corrupted plants, but the plant is not cleansed and no reward is given.
What should happen: You should get one of four quest windows at the corrupted plants depending on the type of plant (Corrupted Windblossom, Corrupted Songflower, Corrupted Whipper Root, Corrupted Night Dragon). You use two Cenarion plant salves to complete the quest and cleanse the plant. The plant is cleansed, and you get a quest reward.

---

I've been trying to fix this using dbscripts_on_quest_end, which it looks like it already has setup but the issue is the gameobject doesn't despawn after the quest ends..so it's hard to see the cleansed flower underneath.

Is there a way to depop a gameobject on quest end?

I've been using https://github.com/cmangos/issues/wiki/DBScripts and looks like:

```
SCRIPT_COMMAND_DESPAWN_SELF = 18
    datalong: Despawn delay (MILLIESECONDS).
    Resulting source must be a creature.
```

Is just for creatures?

**Comment by cala** [comment]
Yes, this command is only for creatures and has no equivalent for gameobjects. But gameobjects can self despawn when used, I must check if gameobject with TYPE_QUESTGIVER can also self despawn.

Regarding the gossip menu saying "Greetings Name", this is a bug reported elsewhere and I'm curently looking at it.

**Comment by scotty0100** [comment]
Thanks for the information, cala.

It's a weird one - it's a flower that gives a quest. So can't actually 'use' the object. And there's no gossip menus either. Just the quest turn in if you have the correct items. So I think we will need a way to depop it on quest end somehow.

**Comment by cala** [comment]
I think that clicking on the gameobject to display the quest text (which is kind of a gossip) is using the object.

**Comment by TheTrueAnimal** [comment]
To be more precise:
Corrupted Flowers: http://db.vanillagaming.org/?item=11516 should be transform into cleansed flowers.
Cleansed Flowers: http://db.vanillagaming.org/?search=cleansed#objects Not all flowers transform.
Wildblossom, whipper root and night dragon should drop the following items after the cleansing:
http://db.vanillagaming.org/?item=11950
http://db.vanillagaming.org/?item=11951
http://db.vanillagaming.org/?item=11952
Songflower gives this spell: http://db.vanillagaming.org/?spell=15366
All flowers seem to have a respawntime of 1 sec which seems to be a little too fast.
When you use a cleansed flower a message appears (should be the message, that you're already doing something different - sry, i'm playing in german) and no loot window opens.

**Comment by cala** [comment]
Closed by https://github.com/classicdb/database/commit/edcefbb52cec247e00d71c0623059368eb3c84be
However, core needs update in order to despawn the quest GO after quest completion (plant cleansing).
Thank you.
