### ISSUE TITLE
Ring of Eternal Justice & Windcaller Yessendra [With proposed fix]

### ISSUE THREAD

**Issue by scotty0100** [classicdb/database#400]
Windcaller Yessendra in Silithis offers up quest rings from Ahn'Qiraj.

Currently the conditions are all over the place. As of right now, a paladin that hasn't finished the quest at the moment can talk to her, and request a replacement ring without finishing the quest line at all.

I was going to do this as a pull request; but as you probably have to check over what I've changed anyway. I figured I'd put it in a Google Doc to hopefully try and make it more readable. Hopefully it works and makes it easier.

https://docs.google.com/spreadsheets/d/1lxBKifhVhV1H3ZC5CFFQQwVVpxAX3yzDDg2-_5FluTA/edit?usp=sharing

The grey sections have not been modified, they are the current values as they stand in the database now.

The green is what I propose we change the conditions to. Just checking if they have completed the quest before hand.

The SQL for the proposed change is:

/\* Delete all existing conditions for the rings. */

DELETE FROM conditions WHERE condition_entry = 1020;
DELETE FROM conditions WHERE condition_entry = 1108;
DELETE FROM conditions WHERE condition_entry = 1109;
DELETE FROM conditions WHERE condition_entry = 1110;
DELETE FROM conditions WHERE condition_entry = 1111;
DELETE FROM conditions WHERE condition_entry = 1114;
DELETE FROM conditions WHERE condition_entry = 1117;
DELETE FROM conditions WHERE condition_entry = 1120;
DELETE FROM conditions WHERE condition_entry = 1123;

/\* Duplicate conditions we don't need. */

DELETE FROM conditions WHERE condition_entry = 1112;
DELETE FROM conditions WHERE condition_entry = 1115;
DELETE FROM conditions WHERE condition_entry = 1118;
DELETE FROM conditions WHERE condition_entry = 1121;

/\* Insert new conditions. */

INSERT INTO conditions (`condition_entry`, `type`, `value1`, `value2`) VALUES (1020,8,8700,0);
INSERT INTO conditions (`condition_entry`, `type`, `value1`, `value2`) VALUES (1108,8,8699,0);
INSERT INTO conditions (`condition_entry`, `type`, `value1`, `value2`) VALUES (1109,8,8701,0);
INSERT INTO conditions (`condition_entry`, `type`, `value1`, `value2`) VALUES (1110,8,8703,0);
INSERT INTO conditions (`condition_entry`, `type`, `value1`, `value2`) VALUES (1111,8,8697,0);
INSERT INTO conditions (`condition_entry`, `type`, `value1`, `value2`) VALUES (1114,8,8698,0);
INSERT INTO conditions (`condition_entry`, `type`, `value1`, `value2`) VALUES (1117,8,8702,0);
INSERT INTO conditions (`condition_entry`, `type`, `value1`, `value2`) VALUES (1120,8,8704,0);
INSERT INTO conditions (`condition_entry`, `type`, `value1`, `value2`) VALUES (1123,8,8556,0);

And out of curiosity, when editing this sort of stuff do you guys have a DB editor for these changes so viewing conditions is a bit easier?

Or do you literally just use SQL and refer to the types in DB structure wiki?

**Comment by cala** [comment]
Thank you! I'll review this soon. :+1:

**Comment by cala** [comment]
> And out of curiosity, when editing this sort of stuff do you guys have a DB editor for these changes so viewing conditions is a bit easier?
> 
> Or do you literally just use SQL and refer to the types in DB structure wiki?

SQL GUI + advanced text editor. I do it like a man. :tongue:

**Comment by cala** [comment]
I'm reviewing your update and the linked document was really helpful to understand what is going on and what you are doing. Thank you! :+1: 

On a general note, it is better to let untouched already existing conditions as they may be used by other gossip, script, loot... Instead create new ones and link them to what needs to be fixed. Unused conditions are harmless while broken conditions are very hard to spot sometime.

To avoid error messages like "You can only have one of this item", you need also to add a condition checking that the player does not already possess the related ring.

I would suggest the following code, based on what you proposed (and what already exists in DB):

``` SQL
SET @CID := 1126;

DELETE FROM `conditions` WHERE `condition_entry` BETWEEN @CID + 1 AND @CID + 15;
INSERT INTO `conditions` VALUES
(@CID + 1, 8, 8697, 0),
(@CID + 2, 8, 8703, 0),
(@CID + 3, 8, 8701, 0),
(@CID + 4, 8, 8699, 0),
(@CID + 5, 8, 8700, 0),
(@CID + 6, 24, 21411, 1),
(@CID + 7, 24, 21396, 1),
(@CID + 8, 24, 21405, 1),
(@CID + 9, 24, 21414, 1),
(@CID + 10, 24, 21408, 1),
(@CID + 11, -1, @CID + 10, @CID + 5),
(@CID + 12, -1, @CID + 9, @CID + 4),
(@CID + 13, -1, @CID + 8, @CID + 3),
(@CID + 14, -1, @CID + 7, @CID + 2),
(@CID + 15, -1, @CID + 6, @CID + 1);

UPDATE `gossip_menu_option` SET `condition_id` = @CID + 11 WHERE `menu_id` = 6928 AND `id` = 0;
UPDATE `gossip_menu_option` SET `condition_id` = @CID + 12 WHERE `menu_id` = 6928 AND `id` = 1;
UPDATE `gossip_menu_option` SET `condition_id` = @CID + 13 WHERE `menu_id` = 6928 AND `id` = 2;
UPDATE `gossip_menu_option` SET `condition_id` = @CID + 14 WHERE `menu_id` = 6928 AND `id` = 3;
UPDATE `gossip_menu_option` SET `condition_id` = @CID + 15 WHERE `menu_id` = 6928 AND `id` = 4;
UPDATE `gossip_menu_option` SET `condition_id` = 1114 WHERE `menu_id` = 6928 AND `id` = 5;
UPDATE `gossip_menu_option` SET `condition_id` = 1117 WHERE `menu_id` = 6928 AND `id` = 6;
UPDATE `gossip_menu_option` SET `condition_id` = 1120 WHERE `menu_id` = 6928 AND `id` = 7;
UPDATE `gossip_menu_option` SET `condition_id` = 1123 WHERE `menu_id` = 6928 AND `id` = 8;
```

Can you tell me if that sounds good to you?

**Comment by scotty0100** [comment]
Thanks cala.

Yes that makes sense to me. Glad the Google document helped. Figured it would help with all the conditions involved!

I'm quite tempted to make some sort of cMangos web-based DB editor in PHP that clearly shows the conditions and their relations.

Would speed up the bug fixes quite a lot I imagine!

**Comment by scotty0100** [comment]
Oh, guessing you tested the SQL? Or would you like me to give it a test?

**Comment by Schmoozerd** [comment]
@scotty0100 
quice,
http://cmangos.net/thread-222.html

from #cmangos 
<SAdraco> [05:56:32] any one know about VB scripting
<SAdraco> [05:56:45] i have a question about a project im working on
<SAdraco> [05:57:02] and this time google dont have the awnser
<SAdraco> [06:01:01] its a small db editor program simmilar to quice

https://github.com/vermie/MangosUtil

Better is to bundle the efforts. I cannot tell which place/ project is the best to start, but i think it was superior way to try to unify the efforts with the usability :)
