### ISSUE TITLE
Overlord Wyrmthalak small problems

### ISSUE THREAD

**Issue by Metalica** [classicdb/database#401]
Problem:
- Does not have any loot (loot tables "broken")

Complete youtube refences:
- Mob Spawnpoints.
- Difirent spawnpoints of difirent mobs (youtube links for reference).
- Waypoint of the mob.

https://www.youtube.com/watch?v=xdcU1rwKMHI
https://www.youtube.com/watch?v=Cqoq7kSGtjc

**Comment by cala** [comment]
Poke @Tobschinski : you were asking if BRS has some parts requiering updates, I think this issue describes a part of LBRS that was not revamp previously: Overlord Wyrmthalak place. Can you have a look at this, please?

**Comment by Tobschinski** [comment]
I will, but I've read that LBRS remains as it is, just UBRS and BFD are being revamped. So I will stick to these until WOD is released.

**Comment by cala** [comment]
/slaps @Tobschinski with a big large and shiny trout. :tongue: 

(yes, this is a bump)

**Comment by TheTrueAnimal** [comment]
We found out that he still spawns his adds when he is already dead.
