### ISSUE TITLE
Broken altars

### ISSUE THREAD

**Issue by Metalica** [classicdb/database#404]
Instead of using altar for 3 min or so. Your summoning for 5 hours.

Uldaman:
- Altar of keepers / https://www.youtube.com/watch?v=9KHA3olUQpA / 3.19 timer

Lrbs:
- Blackrock altar / https://www.youtube.com/watch?v=asKYQoMPbks / 1.49 timer

**Comment by cala** [comment]
Can you describe a bit more what is involved, please? A quest, a event, item used? Where? It is difficult for me to look what is wrong with so few informations. Thanks.

**Comment by Metalica** [comment]
Main topic updated :)

**Comment by cala** [comment]
Thanks for the update.

**Comment by cala** [comment]
> Instead of using altar for 3 min or so. Your summoning for 5 hours.

Are you saying that if you fail at the event, you must wait 5 hours before using altar again. And that you should only wait 3 minutes?

**Comment by Metalica** [comment]
No. You are summoning for 4 hours instead of 3 min or so.

**Comment by cala** [comment]
I looked at the database and the DBC files and everything looks OK. Last time I tested Pyroguard Emberseer event (blackrock altar) it was working fine also. So I'm puzzled, here.

Are you sure there were **3 players** clicking on the altars **at the same time**? If one of them was not channeling, the cast time would not really start making it look like it would take hours to complete.

**Comment by Metalica** [comment]
tested Pyroguard Emberseer event indeed needs 3 players. Found the info. last night. If that is all, this can closed.

**Comment by cala** [comment]
Thanks!
