### ISSUE TITLE
Whirling Invaders (and other event-based elementals)

### ISSUE THREAD

**Issue by Tobschinski** [classicdb/database#414]
In the north-west of Silithus, there are a couple spawns of Whirling Invaders. I was curious if they grant reputation with the Hydraxian Waterlords and checked them ...

As it seems, these are event-based spawns and should not be here unless http://www.wowwiki.com/Elemental_Invasions is active.

**Comment by cala** [comment]
Thanks. The Elemental Invasion event is currently missing in all cores. I don't think it can be 100% handle via DB. It is on my to do list at it was a fun event and greatly usefull when farming essences, but it will probably have to wait a bit more.

**Comment by cala** [comment]
Closed by : 
https://github.com/cmangos/mangos-classic/commit/c8017c63e072a401901d529a2875752d536d6c4f
and
https://github.com/cmangos/classic-db/commit/fa064790d0b5e2bc92328c517c8d7d74b1d622e8
https://github.com/cmangos/classic-db/commit/a3256eef060a56bd832b4b5839506eddfef17331
https://github.com/cmangos/classic-db/commit/9daa4f8676e5144fa66a629173a580f3de14f584
https://github.com/cmangos/classic-db/commit/8b630870b08c019ede422fbe781afa14e662838f
