### ISSUE TITLE
Ahn'Qiraj - Mounts

### ISSUE THREAD

**Issue by Tobschinski** [classicdb/database#422]
You should be allowed to use the Qiraji Resonating Crystals in AQ40. Currently, you are not.

**Comment by cala** [comment]
I don't think this one can be handled via DB. We should probably need to add an exception in core to allow the casting of the related spells if area is AQ40 or AQ20. I'll try to look at this later. My todo list is growing faster than I'm emptying it...

**Comment by Schmoozerd** [comment]
verify in DBCStructure.h bool IsMountAllowed() const  includes the exceptions for AQ.

**Comment by cala** [comment]
Classic core code:

``` c
    bool IsMountAllowed() const
    {
        return !IsDungeon() ||
               MapID == 309 || MapID == 209 || MapID == 509 || MapID == 269;
    }
```

The exception is here, but it is missing the AQ40 id (531) in all cores version. I'll push an update soon.

**Comment by cala** [comment]
On a second thought, I wonder if this is the right thing to do... In AQ40, players can not mount... except for the AQ40 mounts mentioned here. Adding AQ40's map ID in the code above will allow player to use any mounts there, not only the AQ40 mounts. Thus, the exception must probably be added somewhere else

**Comment by Schmoozerd** [comment]
hmm, might be.
Actually i am sure it works in wotlk-client. Also at the place where this IsMountAllowed function is used there is also some additional areaId check mentioned. Maybe the spell changed over the clients or such.

**Comment by Tobschinski** [comment]
Yep!

> Ahn'Qiraj
> Mounting is now permitted in Ahn'Qiraj.
> The Black Qiraji Resonating Crystal is now a normal mount.

http://www.wowwiki.com/Patch_3.0.2

**Comment by cala** [comment]
> Actually i am sure it works in wotlk-client. Also at the place where this IsMountAllowed function is used there is also some additional areaId check mentioned. Maybe the spell changed over the clients or such.

Not only the spells (and patch, as noted above). It seems that classic spells do not have m_spellInfo->AreaId which is probably used in TBC and later to allow disallow spell use/effect depending on area. As such, the issue reported here should only appear for Classic (not tested yet).

If so, I think the following patch should do the trick (still not tested yet):

``` diff
From d1b6c48585a0debbf9d6a46fcb4b4096577533d4 Mon Sep 17 00:00:00 2001
From: cala <calaftp@free.fr>
Date: Fri, 9 May 2014 11:15:47 +0200
Subject: [PATCH] Added exception to allow/restrict use of specific mounts

Changed SpellCastResult Spell::CheckCast(bool strict) by adding specific
case for AQ40 mounts making them unusable outside the instance and
defining them as the only mounts usable inside.
---
 src/game/Spell.cpp | 25 ++++++++++++++++++++++++-
 1 file changed, 24 insertions(+), 1 deletion(-)

diff --git a/src/game/Spell.cpp b/src/game/Spell.cpp
index f1492e3..648970a 100644
--- a/src/game/Spell.cpp
+++ b/src/game/Spell.cpp
@@ -4854,8 +4854,31 @@ SpellCastResult Spell::CheckCast(bool strict)
                 if (m_caster->GetTypeId() == TYPEID_PLAYER && ((Player*)m_caster)->GetTransport())
                     return SPELL_FAILED_NO_MOUNTS_ALLOWED;

+                /// Specific case for Temple of Ahn'Qiraj mounts as they are usable only in AQ40 and are the only mounts allowed here
+                /// TBC and above handle this by using m_spellInfo->AreaId
+                bool isAQ40Mounted = false;
+                
+                switch (m_spellInfo->Id)
+                {
+                    case 25863:    // spell used by ingame item for Black Qiraji mount (legendary reward)
+                    case 25953:    // spells of the 4 regular AQ40 mounts
+                    case 26054:
+                    case 26055:
+                    case 26056:
+                    case 26655:    // spells also related to Black Qiraji mount but use/trigger unknown
+                    case 26656:
+                    case 31700:
+                        if (m_caster->GetAreaId() == 531)
+                            isAQ40Mounted = true;                        
+                            break;
+                        else
+                            return SPELL_FAILED_NOT_HERE;
+                    default:
+                        break;
+                }
+                
                 // Ignore map check if spell have AreaId. AreaId already checked and this prevent special mount spells
-                if (m_caster->GetTypeId() == TYPEID_PLAYER && !sMapStore.LookupEntry(m_caster->GetMapId())->IsMountAllowed() && !m_IsTriggeredSpell) //[-ZERO] && !m_spellInfo->AreaId)
+                if (!isAQ40Mounted && m_caster->GetTypeId() == TYPEID_PLAYER && !sMapStore.LookupEntry(m_caster->GetMapId())->IsMountAllowed() && !m_IsTriggeredSpell) //[-ZERO] && !m_spellInfo->AreaId)
                     return SPELL_FAILED_NO_MOUNTS_ALLOWED;

                 if (m_caster->GetAreaId() == 35)
-- 
1.8.4.msysgit.0
```

**Comment by PatSmuk** [comment]
AFAIK you can use them outside of AQ40, so returning SPELL_FAILED_NOT_HERE when the area isn't AQ40 doesn't seem right.

**Comment by cala** [comment]
Only the legendary AQ mount was usable outside the instance, the regular ones can only be used inside (the tooltip is pretty clear about that). So, you are right, only the regular ones should return SPELL_FAILED_NOT_HERE and I will change that. Thanks.

**Comment by cala** [comment]
Closed by core update https://github.com/cmangos/mangos-classic/commit/5182ba3f649b534b873e79a9084701917bcf6d13
