### ISSUE TITLE
AQ20 - Lieutenant General Andorov & Kaldorei Elites

### ISSUE THREAD

**Issue by scotty0100** [classicdb/database#425]
Source for bug: 
http://www.dailymotion.com/video/x8s641_wow-raid-aq20-rashgarrot_videogames&start=150

What they look like currently:
<img src="http://i60.tinypic.com/2im8gbc.jpg"></img>

Equipment: Equip templates wrong for the elites and the General, they are missing their weapons.

Positions: They are not in line, and also when you walk into the Elites, they move. In the video they clearly stand still regardless of people running into them.

Scale: Lieutenant General Andorov is way too big, needs to be scaled down to 1.15 or so.

Flags: During the event, they are not healable and do not engage any of the NPCs in the General Rajaxx's courtyard. (SD2, or DB?)

**Comment by cala** [comment]
> Flags: During the event, they are not healable and do not engage any of the NPCs in the General Rajaxx's courtyard. (SD2, or DB?)

I need to check the SD2 script to see if flags are updated there, but I think this is a DB issue only.

**Comment by cala** [comment]
It seems that Andorov wields a unique pair of weapons which makes difficult for me to find the displayid of those weapons. It should probably be extracted from WotLK Item.dbc (weapon entry = 21465)

**Comment by evil-at-wow** [comment]
I can confirm the weapon entry. I just checked some AQ20 data from version 3.0.8 build 9506, and these are the item IDs I got:

| Name | Main hand | Off-hand | Ranged |
| --- | --- | --- | --- |
| Lieutenant General Andorov | 21465 | 21465 | NA |
| Kaldorei Elite | 4991 | NA | NA |

And while I was there, I checked that scale factor for Lieutenant General Andorov. The result was not unexpected I'd say: OBJECT_FIELD_SCALE_X = 0x3F800000 = 1.0  (interpreted as a float).

Edit:
Checking my TBC Item.dbc, the matching display IDs are as follows (untested):

| Item ID | Display ID |
| --- | --- |
| 4991 | 5175 |
| 21465 | 33835 |

**Comment by cala** [comment]
> And while I was there, I checked that scale factor for Lieutenant General Andorov. The result was not unexpected I'd say: OBJECT_FIELD_SCALE_X = 0x3F800000 = 1.0 (interpreted as a float).

Thank you for checking this. My in-game tests were giving me the same value. :)

**Comment by cala** [comment]
The positionning and movement of these NPCs is handled by SD2 and should be fixed from there.
