### ISSUE TITLE
AQ20 - Kurinnaxx Boss Fight

### ISSUE THREAD

**Issue by scotty0100** [classicdb/database#428]
Possible SD2 issue, let me know and I will open an issue there..

This fight works relatively well, the only flaw is that the 'Sand Trap' that spawns, doesn't really work properly.

It sort of just 'lands' at your feet and applies Sand Trap too quickly and also leaves the graphic there indefinitely (or a long time). 

As opposed to landing at your feet, giving you about 2-3 seconds to escape, and then explodes and fades away.

Sand Trap Example 1 Missing:
https://www.youtube.com/watch?v=LEXzX7w7TEU#t=201

Sand Trap Example 2 (Getting hit):
https://www.youtube.com/watch?v=LEXzX7w7TEU#t=340

How it looks right now:
https://www.youtube.com/watch?v=kkzlXMDB7Po#t=175

**Comment by cala** [comment]
The activation delay of the spell will be dealt with in SD2.

**Comment by cala** [comment]
https://github.com/cmangos/mangos-classic/commit/7fada45dd08859130c3ceb99f7f51fbd003feb45
