### ISSUE TITLE
Quest 1783: Tome of Divinity

### ISSUE THREAD

**Issue by scotty0100** [classicdb/database#43]
Pretty sure this is DB issue, possibly SD2.

You resurrect the npc Narm Faulk with Symbol of Life, but he remains dead, the quest is marked as complete, but you are supposed to turn in the quest to the newly resurrected Narm Faulk, but he's still dead :p

**Comment by cala** [comment]
I think this is rather a SD2 issue as the NPC Narm Faulk (ID 6177) and its counterpart in human quest line (quest 1786 - NPC Henze Faulk 6172) use a scriptname that is found nowhere else in SD2.
Could you please retry either of these two quests after running the following query and restarting mangos core?

```
UPDATE `creature_template` SET `ScriptName` = 'npc_redemption_target' WHERE `entry` IN (6177, 6172);
```

**Comment by scotty0100** [comment]
This has worked! Thanks

**Comment by cala** [comment]
Thus, it comes from SD2 (or old poor implementation of SD0 in classic DB). I close this issue here and I will speak with SD2 team about it.

**Comment by Schmoozerd** [comment]
Must be fine from SD2 side: https://github.com/scriptdev2/scriptdev2-classic/blob/master/sql/mangos_scriptname_full.sql#L98

**Comment by cala** [comment]
Thanks for the update. Then the error probably came from an old script from the sd0 area.
I think I should review all the open issues now that I have cleaned `creature_template.ScriptName` from various custom scripts.
