### ISSUE TITLE
Windcaller Yessendra (Silithus, Cenarion Hold) has wrong condition_id's in gossip_menu_option

### ISSUE THREAD

**Issue by Neotmiren** [classicdb/database#440]
...and because of this she offers Epic item for free.

(Windcaller Yessendra  is intended to offer multiple unique non-sellable quest rewards anytime in case if player disposed of these epics.)

First 5 (of 9) conditions that `gossip_menu_option` table refers are completely missing from `conditions` table. It seems that YTDB and UDB contain the same broken data (backported from there?). 

However, PSDB seems to contain full set of (QUEST REWARDED + HAS NOT ITEM) conditions. It is easy to copy numbers from there, create new five condition_id's in `conditions` and change reference numbers in `gossip_menu_option`.

**Comment by cala** [comment]
Hello,

I'm surprised by this issue because it is supposed to have been fixed two weeks ago in https://github.com/classicdb/database/commit/c2e4163426120ee6c25f3f71e9751fa19d81c6bc closing the previous similar issue #400 

Could you please check that: your database is up-to-date ?

**Comment by Neotmiren** [comment]
Ah sorry. My last DB patch is [511] and it is in [513]. Not very likely coincidence, but happens sometimes.

**Comment by cala** [comment]
No worries. :)
Thanks for the report anyway: duplicate issue report is always better than no report at all. :+1:

**Comment by Neotmiren** [comment]
In fact, I have many things that can be reported. Just listing from my log (only 'Fix' lines are fully blizzlike):

 ■ Fix Ensorcelled Parchment to always drop from Worn Wooden Chest: 1 loots
 ■ Fix respawn time of Worn Wooden Chest (3 min): 1 objects
 ■ Fix summoned Gazban to be hostile: 1 creatures
 ■ Fix Azshir the Sleepless to be hostile: 1 creatures
 ■ Fix missing Azshir the Sleepless (rare elite Human, Scarlet Monastery Graveyard): 1 creatures
 ■ Fix War Master Voone (LBRS) to drop 100-175 Flightblade Throwing Axes: 1 loots
 ■ Fix Lost Supplies (Unique) to always drop from Scattered Crate: 1 loots
 ■ The same Sell and Buy prices for tabards from vendors: 9 items
 ■ Make two Duskwood L40 Hordes agressive (but leave them non-PvP): 2 creatures
 ■ Make some more Alliance and Horde warriors agressive: 13 creatures
 ■ Correct dishonorable kill `Civilian` field according to UNIT_FLAG_PASSIVE: 2166 creatures
 ■ Fix Zaricotl (elite bird, Badlands) to drop Corroded Black Box: 1 loots
 ■ Fix "The Black Box" quest, make it non-repeatable: 1 quests
 ■ Fix/lower drop chance for scroll fragments of "The Lost Fragments" quest: 3 loots
 ■ Fix Baron Aquanis Summon while on Horde Quest 'Amongst the Ruins': 1 dbscripts
 ■ Fix underwater Bubbly Fissures to restore Breath: 13 gameobjects
 ■ Fix falsely neutral Faction template for some rare [elite] creatures: 49 creatures
 ■ Fix/add Mosh'Ogg Butcher: 1 guids
 ■ Remove condition to loot the Shaft of Tsol from Revelosh: 1 conditions
 ■ Custom Tuten'kash summoning (Razorfen Downs): 14 rows
 ■ Fix Children's Week quest chain and Watcher Callahan: 5 rows
 ■ Fix quest Electropellers (Fishing, Darkshore): 3 loots
 ■ Make combat dummies usable: 2 guids
 ■ Fix Leatherworking req.skill 250 for Rugged Leather, Cured Rugged Hide, Rugged Armor Kit: 8 rows
 ■ Fix/remove Everlook and Gadgetzan Transporters schematics from goblin Buzzek Bracketswing (Gadgetzan): 2 rows
 ■ Make prof. specializations mutually non-exclusive: 18 quests
 ■ Fix mana of Fire Roc (Tanaris) so it could cast Flamespit: 1 creatures
 ■ Fix InhabitType for some water creatures: 3 creatures
 ■ Fix loot from Stonearm (rare Centaur, The Barrens): 2 rows
 ■ Fix loot from Razormaw Matriarch (rare Raptor, Wetlands): 4 rows
 ■ Fix loot from Lord Sakrasis (rare Naga, Stranglethorn Vale): 4 rows
 ■ Fix loot from Ma'ruk Wyrmscale (rare Orc, Wetlands): 4 rows
 ■ Fix loot from Pridewing Patriarch (rare wyvern, Stonetalon Mountains): 4 rows
 ■ Fix loot from Rathorian (rare Felguard, Barrens): 4 rows
 ■ Fix loot from Rot Hide Bruiser (rare Gnoll, Silverpine Forest): 4 rows
 ■ Fix loot from Scale Belly (rare Basilisk, Stranglethorn Vale): 4 rows
 ■ Fix loot from Leech Widow (rare Spider, Wetlands): 4 rows
 ■ Fix loot from Dalaran Spellscribe (rare Human, Silverpine Forest): 4 rows
 ■ Fix loot from Boss Galgosh (rare Trogg, Loch Modan): 4 rows
 ■ Fix loot from Grizlak (rare Kobold, Loch Modan): 4 rows
 ■ Fix loot from Magosh (rare Trogg, Loch Modan): 4 rows
 ■ Fix loot from Brokespear (rare Centaur, Barrens): 2 rows
 ■ Fix loot from Deeb (rare Murloc, Tirisfal Glades): 2 rows
 ■ Fix loot from Digger Flameforge (rare Dwarf, Barrens): 2 rows
 ■ Fix loot from Geopriest Gukk'rok (rare Quilboar, Barrens): 2 rows
 ■ Fix loot from Goraluk Anvilcrack (rare elite Orc, Upper Blackrock Spire): 1 rows
 ■ Fix loot from Hammerspine (rare Trogg, Dun Morogh): 3 rows
 ■ Fix loot from Heggin Stonewhisker (rare Dwarf, Barrens): 2 rows
 ■ Fix loot from Rohh the Silent (rare Gnoll, Redridge Mountains): 1 rows
 ■ Fix loot from Silithid Ravager (rare Silithid, Thousand Needles): 2 rows
 ■ Fix loot from Snarlmane (rare undead Gnoll, Silverpine Forest): 2 rows
 ■ Fix loot from Skarr the Unbreakable (rare Ogre, Dire Maul): 2 rows
 ■ Fix loot from Digmaster Shovelphlange (rare elite Goblin, outside Uldaman): 2 rows
 ■ Remove UDB dbscripts from Sayge (Darkmoon Faire), use SD2 patch: 1 creatures
 ■ Fix too high drop chance for Essence of Undeath: 1 creatures
 ■ Fix waypoints for Azurous (rare elite dragon, Winterspring): 41 rows
 ■ Fixed broken gossip_menu_option conditions for Windcaller Yessendra (Silithus): 20 rows
