### ISSUE TITLE
Missing creature Zekkis (rare Troll, outside Temple of Atal'Hakkar)

### ISSUE THREAD

**Issue by Neotmiren** [classicdb/database#444]
YTDB has 3 guids in `creature` table (probably pooled), PSDB has one location, ClassicDB/HGC-DB/UDB/TC-DB have no locations.

**Comment by Neotmiren** [comment]
Veyzhak the Cannibal (rare Troll, Temple of Atal'Hakkar) is missing too. Again, only PSDB and YTDB have guids in `creature` table, but YTDB wrongly locates him outside of Instance.

**Comment by cala** [comment]
Closed: will be handled with #449
