### ISSUE TITLE
Stormwind City Guard drops quest item called 'Shipment of Boots'

### ISSUE THREAD

**Issue by Neotmiren** [classicdb/database#455]
DELETE FROM creature_loot_template WHERE item=5076 AND entry=68;

**Comment by ghost** [comment]
Why not just create pull requests? :)

**Comment by Neotmiren** [comment]
I think this is easiest and the most "unpretending" way. From time to time I just play long singleplayer multiclass game with modified CMangos core (the link is in my profile) and make quick fixes that just suit my needs, which means they are not fully correct or blizzlike every time.
