### ISSUE TITLE
Scourge Warder - too high drop chance for Essence of Undeath

### ISSUE THREAD

**Issue by Neotmiren** [classicdb/database#456]
UPDATE creature_loot_template SET ChanceOrQuestChance=0.013 /_YTDB_/ WHERE entry=8525 AND item=12808 AND ChanceOrQuestChance > 5; -- Scourge Warder had absurdly high 85% chance

**Comment by cala** [comment]
Thank you for the recent issues you opened and the fixes you proposed.
