### ISSUE TITLE
Some water+ground creatures cannot be enagaged into combat because of wrong InhabitType

### ISSUE THREAD

**Issue by Neotmiren** [classicdb/database#460]
mmaps enabled

UPDATE creature_template SET InhabitType=3 WHERE entry IN (4821,4822,4823, 4686,4687, 5467); -- Skittering/Snapping/Barbed Crustacean (BFD), Deepstrider Giant/Searcher (Desolace), Deep Dweller (Tanaris)

(And moreover, with mmaps enabled I see the same problem with all underwater creatures in Blackfathom Deeps (BFD) regardless of their InhabitType. It seems to be core issue with water in this specific map.)

**Comment by cala** [comment]
Thank you for this report. I don't remember having an issue with underwater creatures in BFD. I will test it again, but maybe there was an error in your liquid maps extraction for this map.

**Comment by Neotmiren** [comment]
Yes, please check BFD with mmaps enabled (without them all works well).

In my version of core only two (known to me) movement issues are left: all underwater creatures in BFD and certain small area inside Render's Rock cave (orc with (Entry: 435 Guid: 17573) and other nearby orcs). The problem is the same: "Leaving Combat" immediately after "Entering Combat". Pathfinder seems to fail.

**Comment by Neotmiren** [comment]
I have tested BFD once more with mmaps... Liquid levels seems to be correct (.gps command). Аnd to be more precise, underwater combat works sometimes, it depends on player's position. The worst case is Moonshrine Ruins, the part with "Deep Pool Threshfin" creatures. Being attacked from distance they leave combat nearly in any case.
