### ISSUE TITLE
Defias Enchanter has wrong Elite rank

### ISSUE THREAD

**Issue by Neotmiren** [classicdb/database#461]
I have refreshed ClassicDB to latest version so now can post some old issues being sure (from non-zero log results) that they do not duplicate any resolved issues.

UPDATE creature_template SET rank=0 WHERE entry=910;

**Comment by cala** [comment]
Thank you for all the issues you reported. :)

Regarding the Defias Enchanter, I'm not sure about it. I removed their elite rank long ago (as they obviously have normal stats), but someone gave me a source proving they were indeed elite back in Classic (or at least flagged as elite).

Following you report, I just did a new research and found nothing proving they were elite, but the source provided in the commit giving them back the elite rank was a comment in **old**.wowhead.com which is now gone.

So, I'm unsure about changing this NPC rank for a third time.

**Comment by Neotmiren** [comment]
L26 Defias Enchanter has less health than nearby L26 non-Elite Defias Night Blade. Enchanter's spell damage seems to be regular (not tested and compared, though). But there is one strange thing in ClassicDB -  quite "elite" amount of melee damage, not very useful thing for spellcaster.

Dropped amount of gold is regular. But I have old classic database called 'sdb' with high melee damage and increased amount of gold. Unclear case.

**Comment by Neotmiren** [comment]
Feenix Classic 1.12 server changed Defias Enchanter to non-elite in their database (compare to elite Defias Taskmaster)

http://database.wow-one.com/?npc=910
http://database.wow-one.com/?npc=4417

**Comment by cala** [comment]
I agree 100% that this NPC has "normal" stats and not "elite" stats. I'm just pointing out that I previously reverted it to elite after someone provided me a source. I assume the source was credible enough for me to change the NPC's rank back to elite. Unfortunately, that source is no longer available and I'm wondering what to do.

**Comment by cala** [comment]
This is the third time I "fix" this NPC's rank. I hope this is the last. :tongue:
