### ISSUE TITLE
Eitrigg's Wisdom with fix

### ISSUE THREAD

**Issue by scotty0100** [classicdb/database#473]
The quest Eitrigg's Wisdom is the 2nd quest for the Onyxia Key Chain for the Horde. The quest says to "seek wisdom from Eitrigg" who is in Orgrimmar near Thrall.

His chat bubbles are there in the dialogue window, but when you click them all, you instead "learn how to make Polar Bracers" rather than completing the quest to next talk to Thrall.

Below is the fix:

```
INSERT INTO `dbscripts_on_gossip` (`id`, `command`, `datalong`, `comments`) VALUES ('6444', '7', '4941', 'Quest Complete - Eitrigg\'s Wisdom');
UPDATE `gossip_menu_option` SET `action_script_id`='6444' WHERE (`menu_id`='2908');
```

**Comment by cala** [comment]
Thank you for pointing. It was previously working (fixed long ago) but was broken again in rev 0396 when I did not take the time to test 100% of someone else work. I'll do a proper fix for both soon(tm).

In the meantime, your code will do the trick if you want to use it as a hot fix.

**Comment by scotty0100** [comment]
Hmm, did this work for you cala after that SQL?

Just had a report saying it was still broken - at work so can't double check ATM. But will do later.

**Comment by scotty0100** [comment]
He doesn't complete the quest still. There's no action script set in gossip_menu_option

UPDATE `gossip_menu_option` SET `action_script_id`='244031' WHERE (`menu_id`='2907');
