### ISSUE TITLE
Scarlet Diversions

### ISSUE THREAD

**Issue by scotty0100** [classicdb/database#476]
"Quest "Scarlet Diversions" does not work.

It is impossible to plant "Scourge Banner", it always says "Requires Scarlet Crusade Forward Camp". 

It seems this Game Object doesn't exist?

**Comment by Schmoozerd** [comment]
This is posisble - such spells often require a spell-focus-go, which sometimes are not sent to the clients.
Hence these needs to be inventend manually to the database.
UDB adds them with go-entry > 300000 i think, sometimes with UDB_ added to the name.
