### ISSUE TITLE
Flame Imps in MC

### ISSUE THREAD

**Issue by scotty0100** [classicdb/database#478]
Flame Imps in MC are currently casting 'Cone of Fire' spell ID: 19630.

Should be Fire Nova
http://www.wowhead.com/npc=11669/flame-imp

```
UPDATE `creature_ai_scripts` SET `action1_param1`='20602' WHERE (`creature_id`='11669');
UPDATE `creature_template_spells` SET `spell1`='20602' WHERE (`entry`='11669');
```

**Comment by scotty0100** [comment]
Forgot to mention about their respawn time also. They should be 7 minutes. I believe they are currently set to 2 hours.

Some sources:

http://www.blizzardguides.com/wow_molten_core_guide.html

```
---IMPS---

+7 minute respawn.

-hits tanks for about 200.
-small AE fire attack that stacks up quite quickly.

=warriors fight for aggro.
=mages use blizzard, if they get agro, use frost nova, then more AEs.
=move on quickly cause these guys respawn fast!
```

http://webcache.googleusercontent.com/search?q=cache:BY5Q-PyAgsQJ:www.bellumaeternus.com/wiki.php%3Ftitle%3DFlame_Imp%26feed%3Datom%26action%3Dhistory+&cd=3&hl=en&ct=clnk&gl=uk

```
 AoE/Technical/Groups of 7+ (7 minute static re-spawn)<br /> <br /> '''Attacks''': Melee attack is very weak, about 400 damage to a rogue, but they all do a 600 damage fire AoE that when not kept out of the main group will rip everyone apart very quickly.
```

http://z8.invisionfree.com/Ardelans_Zone/ar/t10.htm

**Comment by scotty0100** [comment]
Made a report on Acid about this as once I updated to the newest Acid, I lost this fix.

Should we be updating to the newest Acid @cala , or rely on classicDB's ACID only to avoid these issues?

Or any creature_ai_ should be pushed to Acid as well to fix on both sides?

**Comment by cala** [comment]
Thanks! I usually make a batch pull request to ACID on a regular basis, grouping all the few updates made here. Since ACID changed their release schedule, I'll now make a PR every commit touching ACID stuff to keep both projects more in sync.

I made a pull request for the Flame Imps (and Scarshield Infiltrator/Valean script) along with a few other updates. Expect things to be OK shortly.
