### ISSUE TITLE
[Molten Core] Flamewaker (Gehennas adds)

### ISSUE THREAD

**Issue by scotty0100** [classicdb/database#481]
Currently they are CCable, I don't see any guides/sources online to show this. Only strategy guides and videos where they are off tanked. I feel if they were CCable the information would be more widely known.

They are Humanoid creatures so are also able to be polymorphed ATM.

**Comment by Tobschinski** [comment]
Currently testing all mechanic_immune_masks ...

**Comment by cala** [comment]
You should have a look at #161 where Neotmiren created a query based on immunities taken from UDB, TBC-DB and YTDB. I had this in the pipe for a long time but never took the time to work on it. You could probably pick there some missing immunities.

**Comment by cala** [comment]
> Currently testing all mechanic_immune_masks ...

@Tobschinski I would like to have your opinion on this matter: there are some immunities we know are wrong, like these above and that could easily be fixed. But I'm afraid it would not fix 100% of the missing immunities for that creature. Would it be better to fix only what we are sure of and fix again those NPC later ? Or wait to have 100% sure missing immunities and then fix them?

**Comment by Tobschinski** [comment]
It shouldn't last longer than a few days, although the World Cup is keeping me busy. I think, a temporary solution isn't worth the effort, although I don't mind editing a freshly edited value.

But I might need some help if I want to refer all of these immune_mechanics to spells.

**Comment by cala** [comment]
Damned World Cup which prevents people from paying their tribute to the almighty WoW Emu God. :P

Alright, so let's fix this and push the other immunities update to later (in a bigger immunities revamp for instance).
