### ISSUE TITLE
Missing in Action Quest with fix

### ISSUE THREAD

**Issue by scotty0100** [classicdb/database#483]
This currently auto completes as it was broken before now it's scripted can remove the auto complete.

```
UPDATE `quest_template` SET `SpecialFlags`='2' WHERE (`entry`='219');
```

Also noticed that the Corporal doesn't auto attack the Blackrock Orcs - meaning you could avoid/stealth out completely without fighting anything if you was a rogue.

It's faction related, and I used the same EventAI/Faction as Kinelory - a similar Escort NPC that attacks NPCs.. I believe these are right?

```
 UPDATE `creature_template` SET `AIName`='EventAI' WHERE (`Entry`='349');
 UPDATE `creature_template` SET `FactionAlliance`='231', `FactionHorde`='231' WHERE (`Entry`='349');
```

**Comment by cala** [comment]
For this one, the eventAI change will only raise error. The faction change might be good, but all other DB have the same value than Classic DB thus I think it is good. Changing it to 231 (Escortee) may result in the NPC being chain-killed by nearby ennemies NPCs on spawn. I think, the right way to do it is to improve the SD2 script to enforce the faction change when the escort starts.

**Comment by scotty0100** [comment]
Sounds good, I didn't see many NPCs roaming around him, but you never know with these caves could have stuff aggroing through the walls etc. I'll raise a SD2 issue to get the faction changed to 231 on Event Start.

Quest Auto Completion can be turned off for this quest and then issue can be closed :+1:
