### ISSUE TITLE
Foe Reaper(ID 573) lacks spawndist data

### ISSUE THREAD

**Issue by ghost** [classicdb/database#486]
**Current Behaviour:**
Appears static, although movement type is set to _random_.

**Intended Behaviour:**
Foe Reaper should move around randomly within a relatively(to his size) small radius. 

``` sql
UPDATE creature SET spawndist = 7 WHERE id = 573;
```

**Comment by cala** [comment]
Except one of the entries, this NPC already has movement type set to random with a radius of 5 yards.
The same radius is set in all other DBs. Are you sure of the 7 yards radius value?
