### ISSUE TITLE
Incorrect spawn distance data for creatures in Lordamere Interment Camp

### ISSUE THREAD

**Issue by ghost** [classicdb/database#489]
**Current Behaviour:**
Inhabitants of the said area are currently static or behaves incorrectly when it comes to random movement.

**Intended Behaviour:**
Moves around randomly within a small distance which is variable depending on their environment.

I attempted to correct all faulty spawns in the area, this is a copy from the output SQL log file. Sorry for the bad and redundant formatting.

``` sql
UPDATE creature SET spawndist=5.000000, MovementType=1 WHERE guid=17303;
UPDATE creature SET spawndist=4.000000, MovementType=1 WHERE guid=17302;
UPDATE creature SET spawndist=5.000000, MovementType=1 WHERE guid=17306;
UPDATE creature SET spawndist=5.000000, MovementType=1 WHERE guid=17340;
UPDATE creature SET spawndist=5.000000, MovementType=1 WHERE guid=17355;
UPDATE creature SET spawndist=4.000000, MovementType=1 WHERE guid=17301;
UPDATE creature SET spawndist=7.000000, MovementType=1 WHERE guid=17109;
UPDATE creature SET spawndist=5.000000, MovementType=1 WHERE guid=17293;
UPDATE creature SET spawndist=5.000000, MovementType=1 WHERE guid=17294;
UPDATE creature SET spawndist=6.000000, MovementType=1 WHERE guid=17289;
UPDATE creature SET spawndist=5.000000, MovementType=1 WHERE guid=16853;
UPDATE creature SET spawndist=7.000000, MovementType=1 WHERE guid=16984;
UPDATE creature SET spawndist=6.000000, MovementType=1 WHERE guid=16816;
UPDATE creature SET spawndist=5.000000, MovementType=1 WHERE guid=16873;
UPDATE creature SET spawndist=6.000000, MovementType=1 WHERE guid=16859;
UPDATE creature SET spawndist=5.000000, MovementType=1 WHERE guid=16791;
UPDATE creature SET spawndist=5.000000, MovementType=1 WHERE guid=18031;
UPDATE creature SET spawndist=5.000000, MovementType=1 WHERE guid=16806;
```

**Comment by cala** [comment]
Thank you for this update. Like the Foe Reaper one, could you detail what source you used for the spawndist value? Thanks ! :)

**Comment by ghost** [comment]
Unfortunately I had no source to go from with one, all I knew for certain was that they originally did not have their intended movement behaviour, so I tried to use my _"game design intuition"_ and gut feeling to its best extent. 

I am sorry some of these issues/PRs are really badly formatted. They were partially made so I could familiarize my self with working with various parts of the database. I will make sure to provide PRs in a much more compatible format in the future with better documentation.
