### ISSUE TITLE
Unsupported backported WotLK conditions (related to NPC Andorgos, Temple of Ahn'Qiraj)

### ISSUE THREAD

**Issue by Neotmiren** [classicdb/database#499]
Server.log errors

``` text
ERROR:Condition (31) reserved for later versions, skipped
ERROR:ObjectMgr::LoadConditions: invalid condition_entry 717, skip
ERROR:Condition (31) reserved for later versions, skipped
ERROR:ObjectMgr::LoadConditions: invalid condition_entry 718, skip
```

**Comment by cala** [comment]
As commented in the commit introducing those gossip options: these errors are expected and will disappear when the conditions are backported from WotLK to Classic.

**Comment by Neotmiren** [comment]
But how could CONDITION_COMPLETED_ENCOUNTER be backported while it refers DungeonEncounter.dbc which is non-existent in Classic?

``` text
■ CONDITION_COMPLETED_ENCOUNTER (31) 
   ■ value1: encounter_id (DungeonEncounter(dbc).id) 
   ■ value2: encounter_id2 (DungeonEncounter(dbc).id)
Returns if encounter_id is complete (if encounter_id2 provided it will return if encounter_id is completed OR if encounter_id2 is completed) 
```

**Comment by cala** [comment]
In a nutshell, we intend to move from a DBC based system to a SQL based one, thus enabling the backport.

**Comment by Neotmiren** [comment]
I always wondered why developers have not converted .dbc (very inconvenient format) to .sql long ago.

In that case, maybe you already have 2.4.3 and/or 3.3.5a .dbc converted to .sql? Or know the link?

I have only 1.12 dbc->sql and could not find anything higher in internet. I am aware of how to convert .dbc to .sql (did it for 1.12), but it requires some extra files with names and data types for each field of each DBC table. Self-making all this data from structs in .cpp/.h source code is not a simple and quick work.

**Comment by Schmoozerd** [comment]
best ask via irc somebody - these dbc files are relevant to copyright issues, hence they should not be shipped here.

**Comment by Neotmiren** [comment]
It could be the reason why .dbc were not converted to .sql long ago.

But with such requirements what is the purpose of all this? .sql dbc data cannot be included into database, yes? So, end user should run extractor, extractor should create .sql from .MPQ, and this .sql should be used as intermediate (not final) step in assembly of database, and then other modifications should be applied? (without further modifications to dbc data there is no big advantage in .sql format instead of .dbc)

How could binary repacks be possible in this case?

**Comment by Schmoozerd** [comment]
Binary Repacks: No.

Aside from we have currently no motivation of converting dbcs to sql and use the data via sql in our system.
This here is  a special case, where we need parts of the wotlk dbc (toggling ID <-> encounter-index, map, difficulty) for older clients as well, hence we will replace one dbc store with a (crippled) sql-store.

As this (bijective) function is pretty trivial and without intrinsic information, it should be at most a toe above a drawn line, so the projects should have no problem. Including classicDB when shipping this data.

**Comment by cala** [comment]
My reply above was misleading, sorry.

Schmoozerd is right: I was refering to encounters _only_.
_Some_ of the data will be moved to SQL in order to make them available to previous expansions.
