### ISSUE TITLE
Some Paladin/Shaman/Mage/Rogue trainers have extra 'null' gossip option

### ISSUE THREAD

**Issue by Neotmiren** [classicdb/database#500]
Paladin trainers in Stormwind Cathedral are example of this.

``` sql
DELETE FROM gossip_menu_option WHERE id=2 AND option_text IS NULL AND option_id=16 AND npc_option_npcflag=16 AND action_menu_id=0 AND condition_id=0;
```

**Comment by Schmoozerd** [comment]
I just noticed: Cheers for issue 500 :)

(And 400 issues fixed is also a great progress!)

**Comment by cala** [comment]
Thanks! I got many help and reports lately, which is very nice. Also, fixing DB is easier/quicker than fixing core issues. The hardest part here is getting reliable data about Classic content. :)
