### ISSUE TITLE
[AQ20] 10th Scarab Coffer is missing

### ISSUE THREAD

**Issue by Tobschinski** [classicdb/database#502]
The 10th Scarab Coffer in AQ20 is currently missing. I do not have any data for this one yet.

![10thscarab](https://cloud.githubusercontent.com/assets/4753528/3593469/e48d9426-0c86-11e4-8ab6-6e80c7acb9b2.jpg)

**Comment by cala** [comment]
Well, unless you can easily managed to get good retail source for that one, manually adding it based on the screeshot above should also be ok.

**Comment by evil-at-wow** [comment]
I'll check my archives and report back.

[edit]
I'm sorry, but no luck so far. I seem to only have those at Kurinnaxx, Rajaxx and Ayamiss:
Scarab Coffer at position x y z = -9541.15 1585.01 26.5581 orientation = -2.23402
Scarab Coffer at position x y z = -9694.64 1653.44 22.4991 orientation = -0.418879
Scarab Coffer at position x y z = -9090.66 1500.96 24.4341 orientation = 0.977383
Scarab Coffer at position x y z = -8713.44 1543.34 32.2034  orientation = 0.767944
