### ISSUE TITLE
[MC] Humanoids - Missing Equipment

### ISSUE THREAD

**Issue by Tobschinski** [classicdb/database#506]
The following Humanoids in MC are missing their weapons.

Flamewaker Protector
Gehennas
Flamewaker
Shazzrah
Sulfuron
Flamewaker Priest
Majordomo Executus
Flamewaker Elite

(Flamewaker Healer - not sure if they should use something)

I have no idea which IDs should be used here.

**Comment by cala** [comment]
Equipment IDs in Classic are a real nightmare. Until #290 is fixed (core side and DB side), I will do the job for the missing NPC's equipment. I'm starting to get the hang on this, as tedious as it is.

**Comment by Tobschinski** [comment]
Nope, for the Healers.
![executus](https://cloud.githubusercontent.com/assets/4753528/3657403/82991426-1194-11e4-8720-7f66b32f26d6.png)

**Comment by cala** [comment]
Nice. The less equipment IDs I have to check, the better I am. ;)

**Comment by evil-at-wow** [comment]
Does it help you if you get the correct item entries (not display IDs)? I can just get them from a sniff for you then.

**Comment by ghost** [comment]
You can just look up the entries on WoWhead by entering the entry ([like this](http://www.wowhead.com/item=2023/monster-spear-rusty)) and retrieve the DisplayID from the source in the 3D viewer. :)

**Comment by cala** [comment]
@evil-at-wow If you have the correct item IDs that would be very helpful, thank you :)

@efonius you are right and the DBC file also contains the display ID. What is sometimes hard to get is the correct item IDs or the right slot flags (specific for classic). The display ID is easy to get once you kown where to look.

**Comment by evil-at-wow** [comment]
Ok, here are the item entries (data from client version 3.0.8, build 9506).

| Name | Main hand | Off-hand | Ranged |
| --- | --- | --- | --- |
| Flamewaker Protector | 15910 | NA | NA |
| Gehennas | 13698 | NA | NA |
| Flamewaker | 5746 | NA | NA |
| Shazzrah | 2177 | NA | NA |
| Sulfuron Harbinger | 3433 | NA | 5870 |
| Flamewaker Priest | 2176 | NA | NA |
| Majordomo Executus | 12063 | NA | NA |
| Flamewaker Elite | 13632 | NA | NA |
| Flamewaker Healer | NA | NA | NA |

I'm assuming that @Tobschinski actually meant Sulfuron Harbinger where he said Sulfuron :smile:

**Comment by cala** [comment]
Thanks a lot ! :)

**Comment by Tobschinski** [comment]
Sulfuron Harbinger is throwing cubes at me. This happened somewhere else, but I do not remember who fixed this.

**Comment by cala** [comment]
My mistake. I'll fix this soon.

**Comment by evil-at-wow** [comment]
I verified my item entries, and they are correct (at least for WoTLK).

The commit has this data:

> INSERT INTO `creature_equip_template_raw` VALUES
> (2413, **7480**, 0, **8927**, 33490434, 0, 419500034, 529, 0, 25);

The first value, 7480, matches the displayid mentioned on the [wowhead page for item 3433](www.wowhead.com/item=3433), but the second value does not. If we blindly follow [wowhead](http://www.wowhead.com/item=5870) that should be 98910 instead of 8927. That value seems high compared to the others, though, and that can't be a coincidence...

**Comment by cala** [comment]
The display ID of the throwing weapon was taken in the item DBC file (WotLK version, but it is similar in Classic). 
ID = 98910 is probably a new model ID added in cata or MoP. I don't think there was such high number in WotLK, so the current value should be correct for Classic.

The error here probably lies in the item slot flags that I did not set properly.
