### ISSUE TITLE
Blood of Heroes

### ISSUE THREAD

**Issue by Zingzah** [classicdb/database#507]
The Blood of Heroes (http://www.wowhead.com/object=176213) is an object found in eastern and western Plaguelands. They are supposed to randomly spawn at various locations like gathering nodes. When looting it spawns 1-3 fallen heroes (http://www.wowhead.com/npc=10996) at a short distance to allow enough time to loot the blood of heroes item. The object gives the correct loot (tested in gm mode) but spawns fallen heroes right on top of the player who gets an immediate knockback preventing looting.  Is there a DB entry where the distance from a spawn point can be specified?  That would be a fix for this problem.

Fallen heroes also don't have weapons and shield equipped -
The shield as far as I can tell from screenshots is the Shield_Crest_A_01Gold - ModelID 2333
and the sword Sword_1H_Long_B_02_Gold

Let me know if you need anymore info
I forgot some additonal info
The sword_1H_Long_B-02Gold should correspond to modelID 3735 for the equipment template for that NPC (10996)

**Comment by cala** [comment]
Thank you for this report and all the data. The equipment should be easy to fix.

Making the Fallen Heroes spawn at some distance from the gameobject may be tricky.

**Comment by cala** [comment]
> The object gives the correct loot (tested in gm mode) but spawns fallen heroes right on top of the player who gets an immediate knockback preventing looting. Is there a DB entry where the distance from a spawn point can be specified? That would be a fix for this problem.

After checking how this is done actually and reading comments, I think everything work as intended. When looting, the spell 17200 is casted and it summons the fallen heroes in a range of 3 yards. Players are not supposed to loot freely the blood but there should be a 5 sec delay before the NPCs engage.
