### ISSUE TITLE
Ironforge Guards Issues x3

### ISSUE THREAD

**Issue by Zingzah** [classicdb/database#508]
There are several Ironforge guards not patrolling as they should.  The guards are creature id 5595 and the Guid of the non-patrolling guards are as follows:
121,105,57,97,1889,1759,1760,1894.

The 2nd issue is there are several IF guards placed next to braziers in too close proximity and getting the fire burning effect animation.  The guids of these guards are 1743,131,106,107,2023.

The 3rd issue is with IF guard guid 1895.  This npc patrols but with shield stowed and no weapon equipped.

**Comment by cala** [comment]
Thank you for your report.

For the first issue, could you provide a bit more detail about the paths they should follow? Thank you.

The second issue is already discussed in #297 
We are not sure if this is DB related or if this is a bug in core.

**Comment by Zingzah** [comment]
Just had a look at the new patrolling ironforge guards, fantastic work! Ironforge guard guid 1894 still has no waypoints and movement type=0.  He's the only one I can see that needs some waypoint lovin'.
