### ISSUE TITLE
IF Thiefcatchers No Weapons

### ISSUE THREAD

**Issue by Zingzah** [classicdb/database#509]
The three IF Thiefcatchers - Shadowdelve, Thunderbrew and Farmountain all are lacking equipped weapons. Weapon modelID 1383 (Axe_1H_Hatchet_A_03Red) seems to be the right one required in each hand.

**Comment by evil-at-wow** [comment]
My parser says the thief catchers are wearing a pair of [these](http://www.wowhead.com/item=11763) (client version 3.0.3, build 9183).

**Comment by Zingzah** [comment]
Yeah, Thungrim's axe is the right item but db needs a modelID number hence 1383.

**Comment by evil-at-wow** [comment]
Yes, I'm aware the Classic DB needs model IDs and not item entries. I was just confirming with retail data because "seems to be the right one" suggested to me you weren't entirely sure yet.

**Comment by cala** [comment]
"Thungrim's axe" indeed looks like what the NPCs are holding, but evil-at-wow has the right object ID.
Whatever, the three NPCs already had the right equipment but it was sheathed. Try visiting Ironforge with a Horde character, you will see that the thief catchers will draw their axes and chop-chop you happily.
With https://github.com/classicdb/database/commit/2ff48db99c6a54bea60da2c963e846296e82c06a they will now wield their weapons out of their sheath.
