### ISSUE TITLE
WSG Healer Bugged

### ISSUE THREAD

**Issue by Swater96** [classicdb/database#51]
Only revives players 1 time out of 2 countdowns.

Example: A player dies and is sent to the spirit healer. The timer counts down and the player is revived. The player dies again and is sent back to the spirit healer. This time the timer will count down, the healer will cast the res, but the player will stay dead. After the next countdown the player is revived 100% of the time. Seems to not be random, and can be exactly recreated on command.

**Comment by cala** [comment]
Yes, spirit healers have/had several issues. I'm not sure this one is related to DB though.

**Comment by Swater96** [comment]
I remember fixing the issue on a private server project..and i'm pretty sure that the problem was an NPC flag in the DB. Ill research the problem in a few days.

**Comment by cala** [comment]
Later, many time later... Well, I tested this issue and was not able to reproduce it.
From the start, it looks like a core issue and I can only assume that the various core updates in the past two years did fix this.
Thank you. :+1:

**Comment by Lumber-Jack-2** [comment]
much love to all the classicupdates <3
as a person who never played on patch 1.x it's woundful to see how you get datas for all these tiny event and script them

**Comment by Swater96** [comment]
Holy crap @cala that was 2 years ago? Time flies man!
