### ISSUE TITLE
NPC 11488 Illyanna Ravenoak

### ISSUE THREAD

**Issue by time-out** [classicdb/database#513]
She is spawned twice: https://github.com/time-out/database/commit/ad72aa84a85d7dc69d7051fc0dbd8a2f2e0efa44

http://www.wowhead.com/npc=11488
In the link here: http://www.wowhead.com/npc=14308 ... you can see her next to the bear.

**Comment by cala** [comment]
Thank you for those issues & fixes. :+1:
