### ISSUE TITLE
Caledra Dawnbreeze bow display

### ISSUE THREAD

**Issue by Zingzah** [classicdb/database#515]
This NPC (1752) is equipped with dagger and a bow but only displaying(wielding) the dagger.  Post vanilla model screenshots show her wielding the bow but I couldn't find any vanilla screenies showing this.

**Comment by evil-at-wow** [comment]
I didn't play the game during Classic times, so I can't confirm nor deny that she had weapons back then. 

@cala If you need the item IDs and (WoTLK) info, I posted it [here](https://github.com/cmangos/issues/issues/436).

**Comment by cala** [comment]
Caledra Dawnbreeze already wears the correct equipment. Her weapons are sheathed like they should be Classic. Thanks for the report, I'm closing the issue.
