### ISSUE TITLE
Ammo Crate Respawn

### ISSUE THREAD

**Issue by Zingzah** [classicdb/database#518]
This object (176785) is looted for Rumbleshot's Ammo for the quest Ammo for Rumbleshot.  It gives the correct loot but takes about 18 mins to respawn.  Is this intended behaviour or too excessive a wait time?

**Comment by cala** [comment]
DB value is 15 min. Sounds a bit long, (same value in all other DB but YTDB which has 10 min). I could not find a reliable respawn time. But I don't think it should be lowered below 10 min.
