### ISSUE TITLE
Quest 4921 bug...

### ISSUE THREAD

**Issue by The-Great-Sephiroth** [classicdb/database#519]
Mankrik in Crossroads is supposed to offer quest 4921, "Lost in Battle", once a player reaches level 14. After the player found his wife, Mankrik would then offer quest 899, "Consumed by Hatred", presumably for revenge. However, both are being offered at the same time now, instead of in order. I know that sometime during BC or LK they shortened this to prevent all the running back and forth and made him offer both at once, but in Vanilla (heck, in the beta) they were offered one after the other.

**Comment by Tobschinski** [comment]
The Master Guide [rel. 2006] does not list Lost in Battle as a prerequisite of Consumed by Hatred.

**Comment by cala** [comment]
> but in Vanilla (heck, in the beta) they were offered one after the other.

It seems logical that they would and they possibly had at a time in Vanilla, but keep in mind that Vanilla stretched from late 2004 to january 2007. Many changes occured during that period of time. Our reference patch is 1.12.1 and at that time, both quests were no longer linked as the Master Guide (and other sources) tells us.

Thanks for the report. I close the issue.
