### ISSUE TITLE
Improper loot table...

### ISSUE THREAD

**Issue by The-Great-Sephiroth** [classicdb/database#520]
In Thunderbluff on Lower Rise there is a small pool of water one can fish from. As I was doing this last night, I pulled out a lesser mana potion. I never recall doing so on an official server, and I played from the beta through LK, quitting when Cata came out.

**Comment by Tobschinski** [comment]
You can do this on the official servers. http://www.elsanglin.com/fish/mulgore.html

And, as it seems, you could do so during TBC. http://web.archive.org/web/20070513144507/http://www.thottbot.com/i2455

That, of course, has no evidence for classic, but getting Mana Potions out of these waters is nothing that would surprise me. Even in classic.

**Comment by cala** [comment]
Tobschinski is right: potions can be fished by players. Closing this issue. Thank you.
