### ISSUE TITLE
Quest 881 bug...

### ISSUE THREAD

**Issue by The-Great-Sephiroth** [classicdb/database#521]
At the end of the quest "Echeyakee", you are supposed to be blessed with "Echeyakee's Grace". This does not happen. In fact, the text claims that you will LEARN the buff, but you do not.

**Comment by cala** [comment]
Thank you for this report. This looks more like a core issue (at least in Classic). The database seems correct for that part. I'm closing here, the discussion will continue on the similar issue you opened core side.
