### ISSUE TITLE
Anvilrage Warden wrong equipment

### ISSUE THREAD

**Issue by stan84** [classicdb/database#523]
Anvilrage Warden id 8890 have bugged equipment templateID=1806.
1806 points to nonexistent in 1.12 item, so mobs have "chess cube" in hand, according to LK database they should have sword and shield.
I propose update for db like:

UPDATE `mangos`.`creature_equip_template_raw` SET `equipmodel1`='7488', `equipmodel2`='1685' WHERE `entry`='1806';

http://www.wowhead.com/npc=8890

**Comment by cala** [comment]
Thank for this report.
