### ISSUE TITLE
Sagefish pool location incorrect...

### ISSUE THREAD

**Issue by The-Great-Sephiroth** [classicdb/database#524]
In 1.x, sagefish did not spawn in the ocean around Ratchet. Sagefish only spawned in mountainous areas. Hillsbrad Foothills, Silverpine Forest, Stonetalon Mountains, a few in Loch Modan, and a few in Ashenvale are all I ever remember from Vanilla for sagefish. Greater sagefish were in other locations.

**Comment by cala** [comment]
Thank you for this report.

**Comment by Zingzah** [comment]
Further to this report I have noticed Sagefish Pools along the Darkshore shoreline.  These should be only found in freshwater. Els Anglin has them listed as being caught in Darkshore http://www.elsanglin.com/fish/sagefish_school.html but that site only started 2008+.  Wowwiki doesn't mention sagefish being caught at all http://web.archive.org/web/20071201204806/http://www.wowwiki.com/Raw_Sagefish so I'm assuming these schools shouldn't be in Darkshore at all in vanilla.

**Comment by cala** [comment]
Closed by https://github.com/classicdb/database/commit/edcefbb52cec247e00d71c0623059368eb3c84be
Thank you.
