### ISSUE TITLE
Only One Deeprun Tram Operating

### ISSUE THREAD

**Issue by Zingzah** [classicdb/database#527]
Only one side (closest to portal) of the deeprun tram is working atm.  The carriage for the other side isn't present.

**Comment by Zingzah** [comment]
On further investigation, it seems that when at the IF side, the tram closest to the portal is operational.  When the carriage is used to travel to SW and leaves, the far side track (furthest from the portal at SW end) carriage periodically arrives, then leaves and the track closest to the portal doesn't have any carriages arrive.  Most peculiar behaviour.

**Comment by Sinoxan** [comment]
So both sides are working but only in one direction? The back track only goes from Stormwind to Ironforge and the front track only goes from Ironforge to Stormwind?  Did you wait long enough for them to have a chance to come back again?

**Comment by Swater96** [comment]
Ironforge side: Both trams are working.
Stormwind side: Farthest tram from the portal is the only one coming in, and it takes a LONG time to come again if you miss it.

Weird huh? 
Tested on the latest db, with scripts and core compiled same day.

**Comment by Sinoxan** [comment]
That is really strange, is there anything in mangos that stops objects from loading if there isn't anyone in the vicinity?

**Comment by cala** [comment]
Thanks. @Swater96 when you performed your test and got those specific results, can you tell me on which side you entered the deeprun tram? IF side or SW side?

**Comment by Swater96** [comment]
If you enter on the IF side both will work. If you enter on the SW side only one will work and it takes forever and ever for it to come again. I set my char speed to 8 and ran down the tram from the IF side, and I could see the tram that doesn't show up in SW actually headed to SW... it just never arrived.

**Comment by cala** [comment]
I run a few tests on this matter : 
- entering IF side : only one tram is working back and forth
- boarding the working tram and waiting on SW side: first tram still working, second tram starts working after a while, back and forth
- boarding on either tram back to IF : both trams are working
- entering SW side : symmetrical results

So, my conclusions are : 
- both trams are working
- this is a core/config issue : 
  - when player enters one end of the zone, the nearest tram is activated and starts moving to the other end
  - the other tram is too far away to be loaded and/or activated
  - when a player enters/goes to the opposite side : the second tram is activated, but is not in sync with the first one : it needs one round or two to get in sync
- to fix this : either increase values in config file / have a more populated server
- issue is the same than the core issue about wandering NPC not starting to move until player get near them

As a conclusion, the database is OK on this matter. I'm closing here. Thanks to everyone for testing and reporting back.
