### ISSUE TITLE
Hammerspine Rare

### ISSUE THREAD

**Issue by Zingzah** [classicdb/database#528]
I encountered this rare and apparently is the only source for Icepane Warhammer (2254) and Ice-covered bracers(763).  He also emotes "I smell a <race>." but not sure whether it's triggered on aggro or within a certain distance. The bracers are present butIcepane Warhammer doesn't appear to be in the loot table

**Comment by Tobschinski** [comment]
Can you obtain both items with just one kill, or just one OR the other?

**Comment by Zingzah** [comment]
The bracers are in the loot table(1119) with many other entries that form a chance to be the one drop.  The warhammer is not listed.  There are also reference loot entries which form a second drop but I don't think it's part of that.

**Comment by Tobschinski** [comment]
I was more interested in the loot-table on the official servers. Could you loot both there, or just one of those two items per kill?

**Comment by Sinoxan** [comment]
The two rares items need to be in their own group and should be drop rates of 20% for the Icepane Warhammer (2254) and 80% for the Ice-covered Bracers (763).

I started correcting the loots for rares (66f4d6c26dd4d6ea2a07f1c98a9fcaa407feb1c9) but only managed to do a few zones before I was busy with other things again, I can do the rares in Dun Morogh for you when I get chance.

**Comment by Tobschinski** [comment]
Alright, thank you.
