### ISSUE TITLE
Jarven Thunderbrew

### ISSUE THREAD

**Issue by Zingzah** [classicdb/database#529]
Not sure whether this issue is DB or Core related but during the Bitter Rivals (310) quest when Jarven goes upstairs and back down again his movement is not walking but rather a teleport type motion every 5 or so yards which looks very odd.

**Comment by cala** [comment]
Thank you for your last reports. They will be handled in the next update batch.

**Comment by scotty0100** [comment]
I have been told by people in regards to the Bitter Rivals quest that the 'Guarded Barrel' should despawn and the 'Unguarded Barrel' spawn in its place, instead of one spawning next to it and having both a 'Guarded' and 'Unguarded' barrel up..but have no sources to prove this.

I can not recall this myself.

It makes more logical sense to despawn it, do you know @cala?

**Comment by evil-at-wow** [comment]
I've done this quest back in TBC with my gnome, and indeed, the Guarded Thunder Ale Barrel turns into an Unguarded one. I don't know how it's technically done though - I have no sniffs of the quest unfortunately - but it looks very smooth so visually it's like a morph.

What happens is this: you complete the previous quest in the chain, and that makes Jarven Thunderbrew walk away and turns the Guarded Thunder Ale Barrel into an Unguarded one. It is the Unguarded one, and only that one, that will complete 'Bitter Rivals' and offer you 'Return to Marleth'. After a while, Jarven comes back and the Unguarded Thunder Ale Barrel becomes a Guarded one again.

I even found a (bad quality) video with some proof [here](http://www.youtube.com/watch?v=Qq4rjleLF6Y) (fast forward to around 8:40).

**Comment by cala** [comment]
There is already an issue open regarding this (#137). I did not take the time to fix it yet, but it is on my short list.
My guess is to use dbscripts_on_quest_end to make the guarded barrel untargetable, and spawn the ungarded one at the same spot. Then, when the ungarded one despawns, the script turns the garded barrel back to targetable.
