### ISSUE TITLE
SQL error caused by UNIQUE prefix before KEY in the definition of table `conditions`

### ISSUE THREAD

**Issue by Neotmiren** [classicdb/database#53]
I updated Classic database to the latest version and found out that additional Pusillin (Dire Maul) quest DBScript cannot be applied correctly because of collision between

INSERT INTO conditions (condition_entry, TYPE, value1, value2) VALUES
(719, 33, 1, 0),

from this additional .sql update and 

INSERT INTO conditions VALUES
(389, 33, 1, 0), -- wp == 1

from 0129_SD2_updates.sql

Maybe this triad (33, 1, 0) `unique_conditions` (`type`,`value1`,`value2`) must be unique only for the same `condition_entry`?

By the way, Pusillin DBScript worked very well with previous version of ClassicDB, and probably must be commited. It can be found here

https://github.com/mangoszero/database/blob/master/_develop/_developer_files/salja.sql

**Comment by cala** [comment]
Of course, you are free to use updates from other projects, but you understand that we do not provide support for them.

About your questions:
- Pusillin is scheduled to be added properly in a futur backport from UDB 406 along with other fixes
- (`type`, `value1`, `value2`) is constraint to unique in `conditions` table

**Comment by cala** [comment]
The Pusillin script was added in revision 0148 https://github.com/classicdb/database/commit/e28eb027129bf90354705f0103903e56ba6625c5 along with many backports from UDB 406.

**Comment by Neotmiren** [comment]
This is good. It seems that UNIQUE prefix is not really necessary (it is possible to remove it and all works), but is intended to prevent appearance of duplicate conditions; so, the condition entries should be reused.
