### ISSUE TITLE
Mo'grosh Stronghold

### ISSUE THREAD

**Issue by Zingzah** [classicdb/database#531]
The cave system in this area that contains Chok'sul has very few mobs inside.  It needs to be populated more densely than it is atm.

**Comment by Sinoxan** [comment]
Screenshots or videos from classic would greatly help in knowing how many mobs there were and where they were.

**Comment by Zingzah** [comment]
Some screenshots of the area to help:
![screen shot 08-18-14 at 01 14 pm 001](https://cloud.githubusercontent.com/assets/5461014/3947270/50a2a88a-2687-11e4-9cd8-6c61b4b3b4b4.PNG)
![screen shot 08-18-14 at 01 14 pm 002](https://cloud.githubusercontent.com/assets/5461014/3947273/50a8466e-2687-11e4-96eb-6170ddb31617.PNG)
![screen shot 08-18-14 at 01 14 pm](https://cloud.githubusercontent.com/assets/5461014/3947272/50a63be4-2687-11e4-8aba-6e2f44c149e0.PNG)
![screen shot 08-18-14 at 01 15 pm 001](https://cloud.githubusercontent.com/assets/5461014/3947269/509ea3fc-2687-11e4-8ea8-8da1ca09e3f2.PNG)
![screen shot 08-18-14 at 01 15 pm 002](https://cloud.githubusercontent.com/assets/5461014/3947274/50ab0bb0-2687-11e4-8e8e-1668e64d5606.PNG)
![screen shot 08-18-14 at 01 15 pm 003](https://cloud.githubusercontent.com/assets/5461014/3947271/50a4d4d4-2687-11e4-9cbc-16ae488dd997.PNG)
![screen shot 08-18-14 at 01 15 pm 004](https://cloud.githubusercontent.com/assets/5461014/3947277/50d22c72-2687-11e4-91b3-d88e778d82df.PNG)
![screen shot 08-18-14 at 01 15 pm 005](https://cloud.githubusercontent.com/assets/5461014/3947275/50cffb82-2687-11e4-8810-900d690daaa4.PNG)
![screen shot 08-18-14 at 01 15 pm](https://cloud.githubusercontent.com/assets/5461014/3947276/50d1f608-2687-11e4-91ef-de81f8bc9fa0.PNG)
![screen shot 08-18-14 at 01 16 pm 001](https://cloud.githubusercontent.com/assets/5461014/3947278/50d3580e-2687-11e4-9a0d-5d9c6a68f640.PNG)
![screen shot 08-18-14 at 01 16 pm](https://cloud.githubusercontent.com/assets/5461014/3947279/50d8e06c-2687-11e4-89c0-7adf46c737ee.PNG)
