### ISSUE TITLE
starting zone creates neutral instead of hostile

### ISSUE THREAD

**Issue by lorilith** [classicdb/database#532]
patch 3.3.0 turned the wolves in elwynn forest (and other starting zone creatures) neutral instead of hostile.  Previous to this (patch 2.X and 1.X) these creates were hostile to players.

The Database currently has them as neutral, which mirrors current WoW but not vanilla/classic WoW

**Comment by Tobschinski** [comment]
What wolves are we talking about, the Young Wolves?

http://web.archive.org/web/20070808200801/http://www.wowwiki.com/Young_Wolf

**Comment by Swater96** [comment]
If I recall correctly all the hostilities are correct. Now the damages...those are all wrong.

**Comment by lorilith** [comment]
I seem to be incorrect on the wolves but the underlying problem is still valid.  Kobold Laborers are currently neutral and they were hostile (in the cave at human start).

**Comment by Sinoxan** [comment]
I thought the same as @Swater96 , I thought someone went through and changed all the wotlk neutrals back to classic hostiles a while back, maybe it got lost or a few were missed out.

Does anyone know where the neutral/hostile flag is in the database?

**Comment by Tobschinski** [comment]
FactionAlliance + FactionHorde

https://github.com/cmangos/issues/wiki/FactionTemplate.dbc

I have no source to check their faction, prior or post 3.3.

**Comment by Swater96** [comment]
Workers should be passive: http://www.wowwiki.com/Quest:Investigate_Echo_Ridge?oldid=199718

Laborers per (Patch 3.3.0 (08-Dec-2009): They are no longer aggressive.) http://www.wowwiki.com/Kobold_Laborer

**Comment by Tobschinski** [comment]
Oh wait, there are just 2 factions for Kobolds, 25 & 26. Since 25 are the neutral ones, I'll simply use 26.
