### ISSUE TITLE
Jenn Langston + Elly Langston

### ISSUE THREAD

**Issue by Zingzah** [classicdb/database#537]
Jenn Langston (npc 3626) is one of those interesting npcs that you find walking around from time to time.  She interacts to a range of different emotes as listed in http://www.wowhead.com/npc=3626#comments and even goes back to being in the beta.  She just pats around old town but at the moment she doesn't have any movement or interaction abilities at all.

**Comment by Tobschinski** [comment]
The part of ACID will be addressed when I've managed to get a full list of emotes.

**Comment by cala** [comment]
I already have a script that _should_ work. But, currently only the first emote is caught and have a response. The others ones are just ignored. I suspect this is a core issue (though I also can have some of the emotes wrong). Marcus Jonathan has the same issue, for example.

So I did not yet make a pull request to ACID. If you want to use this as a starting basis, you are welcome to. Try to swap the scripts order to try them. A complete list of emotes can be found in `/src/game/ShareDefines.h` of your core sources files directory.

``` SQL
DELETE FROM `creature_ai_scripts` WHERE `id` BETWEEN 362602 AND 362608;
INSERT INTO `creature_ai_scripts` VALUES
(362603, 3626,
22, 0, 100, 1, 41, 6, 469, 0,
5, 11, 0, 0,
0, 0, 0, 0,
0, 0, 0, 0, 'Jenn Langston - laugh on flex emote'),
(362602, 3626,
22, 0, 100, 1, 34, 6, 469, 0,
5, 34, 0, 0,
0, 0, 0, 0,
0, 0, 0, 0, 'Jenn Langston - dance on dance emote'),
(362604, 3626,
22, 0, 100, 1, 84, 6, 469, 0,
5, 58, 0, 0,
0, 0, 0, 0,
0, 0, 0, 0, 'Jenn Langston - blow a kiss on shy emote'),
(362605, 3626,
22, 0, 100, 1, 17, 6, 469, 0,
5, 17, 0, 0,
0, 0, 0, 0,
0, 0, 0, 0, 'Jenn Langston - bows on bow emote'),
(362606, 3626,
22, 0, 100, 1, 58, 6, 469, 0,
5, 84, 0, 0,
0, 0, 0, 0,
0, 0, 0, 0, 'Jenn Langston - shy on kiss emote'),
(362607, 3626,
22, 0, 100, 1, 77, 6, 469, 0,
1, @ENTRY, 0, 0,
5, 77, 0, 0,
0, 0, 0, 0, 'Jenn Langston - rude text on rude emote'),
(362608, 3626,
22, 0, 100, 101, 101, 6, 469, 0,
1, @ENTRY - 1, @ENTRY - 2, @ENTRY - 3,
1, @ENTRY - 4, @ENTRY - 5, 0,
0, 0, 0, 0, 'Jenn Langston - random text on wave emote');

DELETE FROM `creature_ai_texts` WHERE `entry` BETWEEN @ENTRY - 5 AND @ENTRY;
INSERT INTO `creature_ai_texts` VALUES
(@ENTRY, '%s returns the rude gesture to $n', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 2, 0, 0, 'Jenn Langston rude'),
(@ENTRY - 1, 'Well hello, $n, what can I get you today?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 'Jenn Langston random text'),
(@ENTRY - 2, 'Been a tough day? A nice ale should loosen those worries right up.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 'Jenn Langston random text'),
(@ENTRY - 3, 'Do you think I need more pieces of flair?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 'Jenn Langston random text'),
(@ENTRY - 4, 'What do you fancy, sir?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 'Jenn Langston random text'),
(@ENTRY - 5, 'Hi, what would you like?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 'Jenn Langston random text');
```

**Comment by Tobschinski** [comment]
Oh thanks, I'll have a look at this.

Just noticed that Elly Langston <Barmaid> should have exactly the same behavior. Let's hope this family is not as big as I am afraid of it is ...

**Comment by cala** [comment]
Fixed by a pull request in ACID repo: https://github.com/ACID-Scripts/WOTLK/pull/20. 
There was indeed a core issue that I fixed last week. So, the AI script is 100% working on WotLK but still partially broken on TBC/Classic until core fix is backported (everything will be fine then).
