### ISSUE TITLE
Protecting the Shipment - Quest #309

### ISSUE THREAD

**Issue by Zingzah** [classicdb/database#539]
There are two issues with this quest, it works pretty well all round though.  Firstly at the ambush, the dark iron ambushers appear on Darnassian mounts.  I've been trying to look up screenshots/videos of the escort but couldn't find any.  I just don't ever remember the dark iron ambushers being on mounts at all.  Secondly, when the quest successfully completes, Miran does not reset back to his original start position with Huldar.

**Comment by cala** [comment]
Thank you for this report. The resest of Miran is handle by SD2. You need to wait a while for the script to reset. If it still does not reset, then please open an issue on SD2 repository.
