### ISSUE TITLE
Kobold Workers in Echo Ridge Mines

### ISSUE THREAD

**Issue by scotty0100** [classicdb/database#556]
Kobold Workers outside Echo Ridge Mines emote when low on health "Yieeeeee! Me run!" but don't actually flee.

**Comment by cala** [comment]
Thanks. The question is: should they flee? (in my opinion: no, this too early in the game for new player to handle fleeing NPCs)
If yes, then we need to had that part in ACID. If no, we need to remove the text.

**Comment by Sinoxan** [comment]
They did used to flee and it was incredibly annoying at low level back when you couldn't kill them in 3 hits and had to start chasing after them instead.

**Comment by Tobschinski** [comment]
I don't know if this is old enough (2008) to be not taken on any private server, but https://www.youtube.com/watch?v=faN11hsdWjE#t=154

**Comment by Sinoxan** [comment]
I definitely remember some Kobolds fleeing but having had another look into it I might be thinking of the Kobolds outside the Fargodeep Mine.

**Comment by cala** [comment]
In my opinion: the video linked is on retail server, wotlk client. We see that the NPC does say "Yeee me run" but does not actually flee. Moreover, it does it on aggro, meaning, the change from hostile to neutral NPC (that was already pushed to Classic DB a few commits ago) would have no effect on this strangely timed emote. In my opinion, this emote is blizzlike as illogical as it is.
So I close this issue.
