### ISSUE TITLE
Deadmines chest

### ISSUE THREAD

**Issue by Metalica** [classicdb/database#559]
When you enter the deadmines, wait for them to load. There will be a chest spawns, which i never so on offical. 

 Kinda wrong spawn or something ?

**Comment by Sinoxan** [comment]
There were a few chests in Deadmines, where exactly is this one?

There is also one that should only be visible if you are on a quest from a Darkmoon Faire fortune card, if this isn't implemented correctly it might just be showing up to everyone.  I'm not sure where in the instance it is but there is a picture of it here.

http://wowpedia.org/Mysterious_Deadmines_Chest

**Comment by Tobschinski** [comment]
http://wow.zamimg.com/uploads/screenshots/resized/61330.jpg

But this one is just up if you're in GM mode or on the quest.

**Comment by Metalica** [comment]
This one im talking about: http://wow.zamimg.com/uploads/screenshots/resized/61330.jpg is it correct, should be there ?

**Comment by Tobschinski** [comment]
Probably, comments on wowhead are like:

'The chest spawns just around the corner from the instance portal. I ran half the instance before I realized something was wrong and doubled back, and there it was, waiting.'

'Once you enter the instance...dont panic if you dont see it right away. It takes some time to spawn. '

**Comment by Metalica** [comment]
Then this report can be closed, as i thought it was a bug.
