### ISSUE TITLE
Goblin Captain Greenskin (Deadmines) may use undead pirate model

### ISSUE THREAD

**Issue by Neotmiren** [classicdb/database#56]
"The Deadmines boss Captain Greenskin has the incorrect model. Instead of being his usual goblin self, he is an undead pirate"
https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/711

UPDATE `creature_template` SET `modelid_2`=0 WHERE  `entry`=15373 AND modelid_1=3494 AND modelid_2=7113;
UPDATE `creature_model_info` SET `modelid_other_gender`=0 WHERE  `modelid`=3494 AND modelid_other_gender=7113;
UPDATE `creature_model_info` SET `modelid_other_gender`=0 WHERE  `modelid`=7113 AND modelid_other_gender=3494;

**Comment by cala** [comment]
Thank you. I had also spotted it a few weeks ago but did not open a issue. Your fix looks good. I'll test it soon(tm). Thanks ! :+1:

**Comment by joelmatheny** [comment]
Just ran Deadmines and Captain Greenskin was an undead model....doesn't look like it was completely fixed.

**Comment by Neotmiren** [comment]
@joelmatheny, do you play current CMaNGOS + ClassicDB assembled by yourself? Did not you run some other 1.12 server (local or not) version before current CMaNGOS and enter Deadmines? In such case WoW Classic client Cache folder must be taken into account. If the cached data files were not deleted manually, they will keep wrong creature models, ranks etc. sent by previous server.
