### ISSUE TITLE
Ysida Harmon is missing 

### ISSUE THREAD

**Issue by Metalica** [classicdb/database#560]
Ysida Harmon is missing. Has a 45 timer to save her before Baron Rivendare kills her. She shoud be in kneeling position in cage.

 Atm cage is turned opositive way.

 Start from 2.39: https://www.youtube.com/watch?v=suxK69L_2fI

http://www.wowwiki.com/Ysida_Harmon

**Comment by cala** [comment]
Thank you for the report. There is already an issue about this: https://github.com/classicdb/database/issues/196
Closing this one.
