### ISSUE TITLE
Atiesh partly Broken

### ISSUE THREAD

**Issue by Metalica** [classicdb/database#561]
Atiesh Damage, hp, armor: http://db.valkyrie-wow.ru/?npc=16387
Weilding two swords: http://www.wowwiki.com/Atiesh

 Fight 1: https://www.youtube.com/watch?v=ZNHCkd5AvKI
 Fight 2, where he drops the sword: https://www.youtube.com/watch?v=D5wP695sdao

Sword: Andonisus, Reaper of Souls

"This sword is a drop off of Atiesh (a demon) after you complete the Atiesh, Greatstaff of the Guardian questline. Only the person who completes the quest can loot it (as far as I know), and it only lasts while you're in Stratholme (where the last part of the chain takes you)."

"The demon seems to be holding a legendary sword which you somehow use in order to finish the questline.
Teasing melee classes, he drops the sword which gives +600 AP, however the item is conjured and will disappear after a few minutes or when you leave Stratholme. ^^"

**Comment by cala** [comment]
@Tobschinski, since you are one of the few lucky to ever see the event on retail, do you have inputs on that event, please?

**Comment by Tobschinski** [comment]
Not really ... I'm afraid.

**Comment by cala** [comment]
Oh. No more fishes for you then...
