### ISSUE TITLE
DM North: Courtyard doors

### ISSUE THREAD

**Issue by Metalica** [classicdb/database#563]
Before the revamp of DM North, doors where working awesome. Know... they are gone, permanently. 

 I used:
- 1.12.1 client.
- Reseted instance.
- Deleted WDB, just to make sure.

**Comment by cala** [comment]
I'm unsure what you are talking about:
- DM North was never revamped. The only wing that was revamped, is DM East thanks to @evil-at-wow but the North and West wings are still waiting to be revamped, though a few things were already fixed
- there are several doors in DM North, which ones are you talking about, please?

**Comment by Metalica** [comment]
Courtyard doors (as in topic). They where there before dm update, know they are gone.
