### ISSUE TITLE
Naxxramas mobs missing

### ISSUE THREAD

**Issue by Metalica** [classicdb/database#565]
Before naxxramas updates from clasicdb, these mobs where there. No idea why there where deleted.

 Go to 3.26 for proff.: https://www.youtube.com/watch?v=1QximOcF5T8

**Comment by cala** [comment]
Are you speaking of the NPCs near the meat wagons when entering the big room where Patchwerk patrols?

**Comment by Metalica** [comment]
Correct, forgot to add :)
