### ISSUE TITLE
Gnarled Thistleshrub & Ironfur Patriarch Armor Value

### ISSUE THREAD

**Issue by scotty0100** [classicdb/database#566]
Using this SQL Query

```
SELECT Entry, Name, MinLevel, MaxLevel, ArmorMultiplier, Armor, MaxLevelHealth, Rank  FROM `creature_template` WHERE `MinLevel` BETWEEN '46' AND '49' AND `MaxLevel` BETWEEN '46' AND '49' ORDER BY `Armor` DESC LIMIT 0, 1000
```

Both Gnarled Thistlethrub and Ironfur Patriarch have very high armor values for creatures in this range. I think it should be closer the ~3,000 range.

They currently have armor similar to Snapjaw Turtles and Stone Golems. Making it hard for melee to kill these with such high armor values.

**Comment by Tobschinski** [comment]
I don't know, the Bestiary states 4302 - 4385 armor for the Ironfur Patriarchs (3125 - 3342 for Ironfor Bears)and Ironfur is a reference for me to have abnormal armor values.

Same goes for Treants, most of them have a higher armor rating than other types with the same level.

**Comment by cala** [comment]
I agree with Tobschinski. As surprisingly high those armors values can be, they seem to be OK.
