### ISSUE TITLE
Taming the Beast - Taming Rod

### ISSUE THREAD

**Issue by scotty0100** [classicdb/database#567]
To replicate: Make an Orc Hunter, level it to level 10.

.go creature Sian'Dur accept Quest The Hunter's Path (there were 2 quests here? not sure if that's a bug or not, had GM mode off as well)
.go creature Thotar and accept Taming the Beast
.go creature Dire Mottled Boar and start using your Taming Rod on it, and then interrupt the spell, it 'Completes' without the full cast.

Tested Night Elf version of this and the same thing happens.

**Comment by cala** [comment]
Thanks. This one is already open in core and I think this is not related to DB.
https://github.com/cmangos/issues/issues/30
