### ISSUE TITLE
Trinket items with Mail Armor requirement

### ISSUE THREAD

**Issue by Neotmiren** [classicdb/database#57]
Related to few Trinkets (Gnomish Universal Remote as example)

UPDATE item_template SET subclass=0 WHERE class=4 AND subclass=3 AND InventoryType=12;

If game client cache already contains these items it is necessary to clear cache.

**Comment by cala** [comment]
Fixed in revision 0149 https://github.com/classicdb/database/commit/01fb2508d545698d2f607caad74c992b178f3308 Thank you!
