### ISSUE TITLE
Silithus pvp

### ISSUE THREAD

**Issue by Metalica** [classicdb/database#570]
When you pick up the geyser and go the machine with red glow: http://www.wowwiki.com/The_Silithyst_Must_Flow?file=Silithysthorde.jpg .It gives you 0 honor points and 20 Reputation with the Cenarion Circle faction.

 It shoud give you:
 19 Honor points PER geyser (missing).
 20 Reputation with the Cenarion Circle faction (correct).

More information: http://www.wowwiki.com/The_Silithyst_Must_Flow

**Comment by cala** [comment]
The honor points are handled by the core. I had a look at the code and the correct value is awarded. Maybe the server does not inform back the client to display it or something similar (I think the honor points calculation is not 100% functionnal in core). In conclusion, this is not a database issue.
