### ISSUE TITLE
Quest 4763 - The Blackwood Corrupted

### ISSUE THREAD

**Issue by Zingzah** [classicdb/database#572]
This quest works pretty well, is able to be completed but has some missing elements.  They're all listed in this entry http://www.wowwiki.com/Quest:The_Blackwood_Corrupted .  Firstly, when looting the grain, nut and fruit samples a Blackwood Warrior should be summoned to attack the player.  Secondly when the purifying bowl is placed  all Furbolgs within the camp (or set distance) turn friendly and rush the bowl, (despawning or turning hostile (I'm not sure which) after a set time).  Thirdly, when Xabraxxis is summoned he should emote (yell?) "What the... nobody cleanses a furbolg in MY camp! Face the wrath of Xabraxxis!"

**Comment by cala** [comment]
Thank you for this report. I had a quick look at that and most of this could be done by DB. Only the NPCs faction changed and move to the puryfing bowl looks tricky depending on what the related spell does.

**Comment by cala** [comment]
After checking: the spell starts an event (3938) that has a DB script attached to it. This makes spawn the satyr but nothing more. There is a faction "Uncorrupted Furbolg": 934 that might be what we are looking for. But changing faction of a whole bunch of NPCs is not doable (at least not without using the evil GUID). And having all those NPCs moving toward a single point with undefined coordinates (the players do not place the bowl at the same place) is not doable.

We may need SD2 for this.

**Comment by cala** [comment]
Closed by https://github.com/cmangos/mangos-classic/commit/183dc2b37b1cba35511da162dce2ebc0be11d3d5
