### ISSUE TITLE
Moonstalker Runts in Darkshore Incorrect Level

### ISSUE THREAD

**Issue by Zingzah** [classicdb/database#573]
Most of the Moonstalker Runts I've seen in Darkshore are lvl16-17 which is too high.  http://web.archive.org/web/20070808195837/http://www.wowwiki.com/Moonstalker_Runt lists these as lvl 10-11 which is what I remember them as.  They are only lvl 18-19 when accompanying Moonstalker Matriarchs which right at the southern most part of Darkshore.

**Comment by Metalica** [comment]
Fix: UPDATE `creature_template` SET `MinLevel`='10', `MaxLevel`='11' WHERE (`Entry`='2070')
