### ISSUE TITLE
Missing Bubbly Fissures

### ISSUE THREAD

**Issue by Zingzah** [classicdb/database#574]
This object needs to be placed near the Strange Lockbox off the coast of Westfall and Silverpine to aid druids in their Trial of the Sea Lion quests.  It's mentioned in the wowwiki entry for quests http://www.wowwiki.com/Half_Pendant_of_Aquatic_Endurance.  I'm not sure which DB object in the database would be used for this as it needs (i'm just guessing) to have a water breathing aura (spell 11789 perhaps).

**Comment by Grz3s** [comment]
pls check here:
https://github.com/unified-db/Database/commit/291970792f348c444680042baf6bcb9b2e4dfe2c
