### ISSUE TITLE
Quest #250 A Dark Threat Looms

### ISSUE THREAD

**Issue by Zingzah** [classicdb/database#577]
This quest involves investigating (opening) a suspicious barrel.  Currently Two Dark Iron Sappers are spawned near this object.  Comments from http://www.wowhead.com/quest=250 indicate that these two sappers spawn and attack similar to Benedict's chest (Obj 3239).  I clearly remember this behaviour when doing this quest on live.

**Comment by cala** [comment]
Based on the comments you linked, it is unclear if the NPCs spawn before or after using the barrel.
[wowwiki](http://www.wowwiki.com/A_Dark_Threat_Looms_quest_chain) and the quest text also suggest that the two NPCs are already there when player arrives.

**Comment by cala** [comment]
From old comments about that quest: http://web.archive.org/web/20071015115245/http://wow.allakhazam.com/db/quest.html?wquest=250
is it clear that the two dwarves are already spawned. Maybe the comment on wowhead was from someone who arrived at the same time those two dwarves were respawning?
I'm closing this issue, thank you.
