### ISSUE TITLE
Tharlendris seeds purchase option

### ISSUE THREAD

**Issue by Zingzah** [classicdb/database#578]
These seeds are available for purchase after completing the quest Morrowgrain research (Q#3785) but appears as an option even if the quest hasn't been completed. http://www.wowwiki.com/Mathrengyl_Bearwalker

**Comment by Grz3s** [comment]
thx for your report:
https://github.com/unified-db/Database/commit/b0c4fd2fa6ec587a05cd0497f09b30c2f547944b
