### ISSUE TITLE
Greatly wrong MinLevel requirements for most Darkmoon Faire quests

### ISSUE THREAD

**Issue by Neotmiren** [classicdb/database#58]
http://www.wowwiki.com/Darkmoon_Faire_(old)

UPDATE `quest_template` SET MinLevel=1  WHERE entry IN (7881,7889,7894,7899);
UPDATE `quest_template` SET MinLevel=10 WHERE entry IN (7882,7890,7895,7900, 7905,7926);
UPDATE `quest_template` SET MinLevel=20 WHERE entry IN (7883,7891,7896,7901);
UPDATE `quest_template` SET MinLevel=30 WHERE entry IN (7884,7892,7897,7902);
UPDATE `quest_template` SET MinLevel=40 WHERE entry IN (7885,7893,7898,7903,7939,7941,7942,7943,8222,8223);

**Comment by cala** [comment]
Fixed in revision 0150 https://github.com/classicdb/database/commit/f4c09b1d86ef2b1a021901210da2db3e30f81809
Thank you!
