### ISSUE TITLE
NPC #2080 Denalan Movement issue

### ISSUE THREAD

**Issue by Zingzah** [classicdb/database#581]
This npc whenever he moves from his position to the planter and back during quest 997 (Denalan's Earth), 930 (The Glowing Fruit), and 931 (The Shimmering Frond) his movement is very "choppy", similar to that of Jarven Thunderbrew that has been since fixed.  Also after planting the shimmering frond (after completing the shimmering frond quest) he resumes his original position and continues the planting emote(he looks like he's chopping wood) continuously.

**Comment by cala** [comment]
This was fixed at the same time that Jarven Thunderbrew. I tested all 3 quests again, just in case and they are still fixed. I suggest that you make a clean install of Classic DB and delete the content of your WDB directory.
