### ISSUE TITLE
Blackthorn ridge graveyard missing link

### ISSUE THREAD

**Issue by Metalica** [classicdb/database#582]
When you die in instance:
- Razorfen kraul
- razorfen downs

What is atm doing, when you die:
 It teleports to thousand needles spirit healer under the great lift.

 When you die in general at south part of barrens:
It teleports you to camp taurajo spirit healer.

What it shoud do, when correctly working:
From both instances and when you die in south region. It should teleport you to blackthron ridge spirit healer.

 Also graveyard as object is missing at blackthorn ridge.

**Comment by cala** [comment]
I'm sorry but I found nothing about this spirit healer or cemetary (and I don't remember it). Could you provide screens, videos or whatever, so I can find out its precise location and thus I can look for it in the DBC files, please? Thank you.

**Comment by Tobschinski** [comment]
> Patch 0.7 (15 June 2004): - Graveyards have been added to Camp Taurajo and Ratchet for a total of three graveyards in The Barrens.
> Patch 2.2.0 (25-Sep-2007): - Added a new graveyard to the Southern Barrens.

This is what I got for graveyards in the Barrens, plus this information specially for Razorfen Downs.

> Patch 2.2.0 (25-Sep-2007): Additional graveyards were added.
>             Previously, the closest graveyard was at Camp Taurajo, quite a long run.

**Comment by Metalica** [comment]
Ticket can be closed.
