### ISSUE TITLE
Q#990 Trek to Ashenvale Questgiver Missing

### ISSUE THREAD

**Issue by Zingzah** [classicdb/database#583]
The questgiver for this quest Sentinel Selarin(npc #3694) is currently not available to offer this quest which is the intro quest to ashenvale from darkshore.  She only spawns after completing the 2nd Lost Master ie. completing either Escape through stealth (#995) or Escape through force(#994).  The db currently only has the completion of #994 as a requirement for quest #990 so needs to have a either/or between #994 and #995 added.

**Comment by Zingzah** [comment]
http://web.archive.org/web/20070808195837/http://www.wowwiki.com/Sentinel_Selarin

**Comment by cala** [comment]
Good catch, we will need some DBscripts there.

**Comment by Grz3s** [comment]
almost forgot about this npc :)  [missing in WotLK also]
yes... this npc is on my "to do" list.... looooong time already :)....
i know where she spawns... know her path... got my own *avi - where she stands... and then i know where she runs out and despawns...
what is still missing.... "her chat with Terenthis" ...
maybe i'll brake my own rule "not 100% = not added" ... and ill update her without chat? what do u guys think?

**Comment by ghost** [comment]
I think you should, it's better to have it working without the dialogue than what not working at all. Maybe someone here could help research the dialogue, I've tried but didn't find anything off the bat, maybe we can find it in some _"Let's Play"_ video or something.

**Comment by Grz3s** [comment]
https://github.com/unified-db/Database/commit/09f4781abd245e4831191ef0c8e332822bd1a42c
;)

**Comment by Zingzah** [comment]
I found one reference to this from a two other db sources:
https://github.com/decrypt/Arcemu-2.4.3/blob/master/Core/sql/WhyDB%20-%202.4.3/development/ascent_world/npc_monstersay.sql
and
https://xp-dev.com/sc/63284/HEAD/%2FCraDB%2Ftrunk%2Fdb%2Fnpc_monstersay.sql
both with the same entry
INSERT INTO `npc_monstersay` VALUES (3694, 0, 50, 7, 11, 'Sentinel Selarin', 'Terenthis, Raene sent me to find you. The Sentinels are in need of help in Ashenvale.', NULL, NULL, NULL, NULL);
I have looked through alot of the other entries and they seem quite accurate.  I can't remember whether there was more to the dialogue than one entry though.

**Comment by Grz3s** [comment]
Nice one.... 
Also i spend few mins with this and ive found ..this avi:
https://www.youtube.com/watch?v=KrRQxM-UIkk <--- look from 2:42 .. (poor quality)... but after few seconds we can see text from our npc.... it was hard to read it... but with your text it looks that its the one...
So i made an update.... and added it into UDB.
https://github.com/unified-db/Database/commit/f3c98b4a703e03598c4f08b4a53ce530fee5bf8d
;)

**Comment by evil-at-wow** [comment]
Nice find Grz3s! Too bad the player in the video runs away from the conversation, because he's missing a part actually.

I seem to have the entire conversation in my archives (sniffs from version 3.3.0a):

> Sentinel Selarin says: Terenthis, Raene sent me to find you. The Sentinels are in need of help in Ashenvale.
> Terenthis says: Hello, Selarin. I'm afraid I cannot help you at the moment, but perhaps some of the adventurers here in Auberdine can...
> Sentinel Selarin says: Thank you, Terenthis. I shall remain here for as long as I can.
> Sentinel Selarin says: Hopefully I can send a worthy few to help Ashenvale and the Sentinels.

Apparently I've done that quest, so there's a good chance I even have a screenshot around somewhere then...

**Comment by Grz3s** [comment]
https://github.com/unified-db/Database/commit/8356fe145b6b5319b98b0dfd7a5eb0091066a922
thank you.
