### ISSUE TITLE
Demoralizing Roar offered/learned twice

### ISSUE THREAD

**Issue by Zingzah** [classicdb/database#587]
My druid reached level 20, went to train and was offered Demoralizing Roar (Rank 2) twice.  I accepted both and ended up with two copies of the ability in my spell book.

**Comment by cala** [comment]
This is a core issue where some spells are added twice in spell book. It has been already reported, though I did not find where.
As it has zero impact on gameplay aside from visual duplicate in spell book, this issue has a very low priority as you can imagine.
