### ISSUE TITLE
Razormane Wolfs & Hunters [With fix]

### ISSUE THREAD

**Issue by scotty0100** [classicdb/database#588]
There are lots of Razormane Wolfs in the Barrens spawned on top off Razormane Hunters, ACID already summons a wolf on spawn of Razormane Hunters which makes it look like Razormane Hunters have two pets.

Can just delete all Razormane Wolf spawns I believe as they are summoned.

Razormane Wolf ID = 3939

```
DELETE FROM creature WHERE id=3939;
```

**Comment by cala** [comment]
Good catch, thanks. There are probably many similar issues elsewhere.
If you are sure that Razormane wolfs are always summoned (with such a name, I guess they should), then your fix is okay.
