### ISSUE TITLE
Gnarlpine Vengeance Spell #5628

### ISSUE THREAD

**Issue by Zingzah** [classicdb/database#589]
Just transferring this from a post I opened on the forums about this spell.  It's a spell that currently incorrectly buffs a player instead of the casting gnarlpine mob.  There were several suggestions as to which area this bug should be raised in including the core, acid and finally Xfurry said this would be a DB issue and suggested a solution which is:
This is DB issue. Target pair:
Code:
Targets (22, 7) (TARGET_CASTER_COORDINATES, TARGET_AREAEFFECT_INSTANT)
require a script target.

The solution is simple:
Code:
INSERT INTO spell_script_target VALUES (5628, 1, 2011, 0),(5628, 1, 2010, 0);

**Comment by cala** [comment]
Checked right now: those entries are already in the database. But this is only for two type of Gnarlpine: Gnarlpine Defender (2010) and Gnarlpine Augur (2011). The others Gnarlpine are not in the DB, though some of them can cast this spell. Can you check that the following code fixes it?

``` SQL
INSERT INTO `spell_script_target` VALUES
(5628, 1, 2006, 0),
(5628, 1, 2007, 0),
(5628, 1, 2008, 0),
(5628, 1, 2009, 0),
(5628, 1, 2012, 0),
(5628, 1, 2013, 0),
(5628, 1, 2014, 0);
```

**Comment by cala** [comment]
@Zingzah : Did you have the opportunity to test the above fix?

**Comment by Zingzah** [comment]
Apologies for taking so long to get back on this one.  I have tested this fix and it does work.  Gnarlpine Vengeance is also correctly applied to Augurs(2011), Pathfinders(2012), Avengers(2013) and Totemics(2014).  I had a look through both wowhead and wowwiki and there was a bit of conflicting information about which creature cast what spells.  Wowwiki was the only resource which had these four having this ability wowhead didn't mention any gnarlpine casting the vengeance spell.

A weird thing though is when I first came across this issue and the player had this cast on them, they received the buff icon displayed in the player buff area and the size increase.  I'm not sure about the attack speed and run speed increase.  However when both the creature and player cast this on themselves (I learnt the spell and cast it to test it's effect)  only the display effect (black angry face with red outline and accompanying sound effect) was executed.  No buff icon, size increase or other benefits from the spell were received.  Might this spell behave differently when self cast from cast on a target?

**Comment by cala** [comment]
Thanks for you feedback.
This spell is bit complicated: it is a NPC designed spell, self casted, with 3 range effects (increase size, increase speed, increase attack speed). But the all the eligible targets must be described in DB. Only two of them were there. So, with all these elements, it is very likely that the spell casted by players have different behaviour than when casted by NPCs, and this behaviour can also change depending on what are the nearby NPCs.
