### ISSUE TITLE
Rogue Class Quest "Horns of Nez'ra" (Lakeshire) cannot be accepted

### ISSUE THREAD

**Issue by Neotmiren** [classicdb/database#59]
Teleport to questgiver
.go creature Arantir

Erroneous behaviour is caused by Repeatable flag set in quest_template SpecialFlags. To fix it:

UPDATE `quest_template` SET `SpecialFlags`=0 WHERE `entry`=2358 LIMIT 1;

Also XP reward (1800 XP in-game) is slightly different from what is found on wowiki (1750 XP, but article is WotLK related)
http://www.wowwiki.com/Quest:Horns_of_Nez'ra?oldid=2201960

so maybe the fix should look like that

UPDATE `quest_template` SET `SpecialFlags`=0, `RewMoneyMaxLevel`=1050 WHERE `entry`=2358 LIMIT 1;

**Comment by cala** [comment]
Thank you for the report and the fix (along with the other issues you've opened). That seems pretty good and will be pushed as soon as I got the time to do so. :+1: 

However, I'm not sure about the XP reward and I think we should keep it as it is (this is only a 50XP difference over a 1750XP total). The value is the same in TBC-DB and as we don't have reliable source of what the value was in classic, I prefer to keep the two DB with the same value.
