### ISSUE TITLE
Quest chain 3181: The Horn of the Beast

### ISSUE THREAD

**Issue by Metalica** [classicdb/database#591]
Quest does not work from Curator Thorius. I get Proof of Deed and take it to Mountaineer Pebblebitty. Nothing happens. I should able to give her the proff and get:
- Key to Searing Gorge / ID: 5396
- Reputation.
- Expirience.
  
  Doors ID:
  ID 6943:  All working correctly.
  ID 30084: Does not have option to open it with key.

Link for refence where the quest part is broken: http://www.wowwiki.com/Quest:At_Last!

**Comment by Tobschinski** [comment]
If you have still problems with the quest, I would like to have more information. For me, it is working as it should be.
