### ISSUE TITLE
Hezrul Bloodmark No Waypoints in the Barrens

### ISSUE THREAD

**Issue by scotty0100** [classicdb/database#593]
Map & Area: Barrens, Lushwater Oasis

What happens:
Hezrul and his two linked mobs (Kolkar Bloodchargers) stand still where they spawn.

What should happen:
Hezrul and his two linked mobs (Kolkar Bloodchargers) patrol clockwise around the Lushwater Oasis.

Source:
http://www.wowhead.com/quest=852#comments:id=1986

**Comment by Grz3s** [comment]
can be backported from UDB407
