### ISSUE TITLE
Taunt should be 30yd and not 5yd

### ISSUE THREAD

**Issue by S-Marais** [classicdb/database#594]
the taunt spell is aimed to recover the aggro on a distant mob, a taunt at 5yd is useless :) it should be 30yd

**Comment by Tobschinski** [comment]
Hello Sir, unfortunately, lots of things were different in vanilla. The game evolved somehow. :)

Taunt:
Patch 3.0.8 (2009-01-20): Range increased to 30 yards, from 20 yards.
Patch 3.0.2 (2008-10-14): Range increased to 20 yards, from 5 yards. Cooldown reduced to 8 sec.

**Comment by S-Marais** [comment]
I had completely forgot about that. Thanks :)
