### ISSUE TITLE
Covert Ops Alpha (Q#1079) + Beta (Q#1080) Issues

### ISSUE THREAD

**Issue by Zingzah** [classicdb/database#595]
There are a few issues with these two quests, the 1st one being eligibility:
I was able to obtain these after completing only quest #1074 Ineptitude + Chemicals = Fun but also needs to be completed quest #1077 Special Delivery for Gaxim. 
http://www.wowwiki.com/Quest:Covert_Ops_-_Alpha
http://www.wowwiki.com/Quest:Covert_Ops_-_Beta
The second issue involves the explosive wagons for both alpha and beta quest.  The alpha(red) explosives fail to set at the red explosives wagon (setting countdown but fails at the end) and when trying to set the blue explosives at the blue wagon a "Requires Blue explosives wagon" message is displayed.
When setting off the wagons via GM mode, Venture Co. mobs nearby do not move to investigate, failing to give the player the opportunity to loot either the documents or engineering plans.

**Comment by cala** [comment]
Will now be handled there. Thanks.
