### ISSUE TITLE
Razormane Wolf

### ISSUE THREAD

**Issue by S-Marais** [classicdb/database#598]
Acid does handle well the spawn of the Razormane Hunter's pet but the level of the pet matches the hunter's level where it should be 4 level below.

Razormane Hunter level 11 should have a Razormane Wolf level 7
Razormane Hunter level 12 should have a Razormane Wolf level 8

Maybe I should report this to ACID though

**Comment by cala** [comment]
No, this is a core issue. We are aware of it. Thank you for reporting.
