### ISSUE TITLE
Quest "Garments of darkness" cannot be completed

### ISSUE THREAD

**Issue by S-Marais** [classicdb/database#599]
QuestID 5650
You have to heal Deathguard Kel and then buff him with Fortitude to complete the quest, but nothing happens when you do so.

**Comment by Tobschinski** [comment]
![untitled](https://cloud.githubusercontent.com/assets/4753528/4512487/e508dee4-4b40-11e4-9939-bc1b5c71f419.png)

Working fine for me. I think the order is important, you have to heal him before you buff him.
Lesser Heal Rank 2, Fortitude Rank 1.

**Comment by cala** [comment]
This quest is handled by SD2. You can also check that it is correctly installed and working if the issue persists.

**Comment by S-Marais** [comment]
I just retried with a new character but still the same issue. I am using the latest SD2. Also I did it in the specific order to be sure. and with the two lesser heal available at the time.

**Comment by cala** [comment]
I confirm this quest is working. I suggest you check that SD2 is well installed along with its database and is correctly loaded by the core. Chances are good this is a configuration issue on your side.
