### ISSUE TITLE
Quest "Winterfall Activity" rewards too much XP

### ISSUE THREAD

**Issue by cala** [classicdb/database#6]
The quest "Winterfall Activity" rewarded me 90,000 exp when I turned it in. I believe it should have been 9,000 exp instead. It gave me half a level or close to it at level 58.

Quest ID: 8464

_original report by [The-Great-Sephiroth](https://github.com/The-Great-Sephiroth)_

**Comment by Swater96** [comment]
http://www.wowwiki.com/Quest:Winterfall_Activity

Confirmed to give 90,000 XP upon completion.. looked through Quest_template and couldn't find a XP Reward field so maybe Cala knows where it is?

**Comment by cala** [comment]
Thank you for confirming this.
The XP reward is stored in `quest_template` in `RewMoneyMaxLevel` field. When rewarding player, core adjusts this value depending on player level and quest level mainly. This is why you did not find the 90,000 value in the fields.
This issue should be fixed by commit https://github.com/Evildead666/database/commit/ca937eb1a3197ebaccf496f27b75d39bbead9c6a by @Evildead666 if you want to test it as I didn't have the time until now.

**Comment by Swater96** [comment]
This fix has been tested and should be implemented by next update!
- Swater96

**Comment by cala** [comment]
Fixed in rev [0142] https://github.com/classicdb/database/commit/c252b03ea5c6ea0d78218c316fcd48344594fee6
