### ISSUE TITLE
Non-pooled Midsummer Celebrants

### ISSUE THREAD

**Issue by Neotmiren** [classicdb/database#60]
In some remote places Midsummer Celebrants are non-pooled (near Gadgetzan, not far from Booty Bay etc). Two of them (different races) stand overlapped in each place. I solved this issue via php script which is variation of the script that automatically creates pools for minerals and herbs (for NPCs it uses very small map cell size).

Script results in

Midsummer Celebrants: 50 creatures assigned to 25 pools

It is possible to generate SQL code from this script if there are no other methods.

**Comment by cala** [comment]
Thanks. Game events also need a lot of love. I'm note sure if we need to pool the NPCs here or remove one of them are they seem to be duplicates.

I've just created a specific milestone for game events and added this issue to it.
