### ISSUE TITLE
Rites of the Earthmother

### ISSUE THREAD

**Issue by S-Marais** [classicdb/database#601]
This quest (ID 755) have the following objectives: Travel to Seer Graytongue who lives in the hills directly south of Camp Narache.

When you validate the quest to Seer Graytongue you are supposed to receive the buff Mark of the Wild. When you play a character with mana you actually buff yourself using your own mana, but if you play a warrior you receive the error message "Not enough mana"

**Comment by cala** [comment]
Thank you for reporting.
This is probably a core issue. There may even be already an issue open about this. I need to check that when I can spare the time.

**Comment by cala** [comment]
Related to core issue: https://github.com/cmangos/issues/issues/438
Closing here. Thank you.
