### ISSUE TITLE
Alaindia NPC #3562 Waypoints

### ISSUE THREAD

**Issue by Zingzah** [classicdb/database#603]
This npc currently has no waypoints.  She also waits at certain points for about 5 mins according to
http://www.wowhead.com/npc=3562/alaindia#comments
With that in mind I have created some waypoints for this npc which look pretty close to the above post.  I wasn't sure to add to the creature_movement or creature_movement_template tables given much talk about "evil" guids on the forums.  
Updating creature table:

UPDATE `creature` (`guid`, `id`, `map`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `DeathState`, `MovementType`) VALUES (49525, 3562, 1, 0, 85, 9696.2, 2571.05, 1335.68, 4.25791, 300, 0, 0, 1605, 0, 0, 2);

Adding Waypoints to creature_movement:

INSERT INTO `creature_movement` (`id`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, 

`script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `wpguid`, 

`orientation`, `model1`, `model2`) VALUES (49525, 1, 9692.93, 2575.03, 1335.68, 0, 0, 0, 0, 0, 0, 0, 

0, 0, 0, 0.728785, 0, 0);
INSERT INTO `creature_movement` (`id`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, 

`script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `wpguid`, 

`orientation`, `model1`, `model2`) VALUES (49525, 2, 9750.89, 2627.87, 1334.05, 300000, 0, 0, 0, 0, 

0, 0, 0, 0, 0, 3.84289, 0, 0);
INSERT INTO `creature_movement` (`id`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, 

`script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `wpguid`, 

`orientation`, `model1`, `model2`) VALUES (49525, 3, 9692.43, 2574.6, 1335.68, 0, 0, 0, 0, 0, 0, 0, 

0, 0, 0, 5.45577, 0, 0);
INSERT INTO `creature_movement` (`id`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, 

`script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `wpguid`, 

`orientation`, `model1`, `model2`) VALUES (49525, 4, 9708.03, 2554.65, 1335.68, 0, 0, 0, 0, 0, 0, 0, 

0, 0, 0, 4.94134, 0, 0);
INSERT INTO `creature_movement` (`id`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, 

`script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `wpguid`, 

`orientation`, `model1`, `model2`) VALUES (49525, 5, 9714.24, 2525.85, 1335.68, 0, 0, 0, 0, 0, 0, 0, 

0, 0, 0, 4.92563, 0, 0);
INSERT INTO `creature_movement` (`id`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, 

`script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `wpguid`, 

`orientation`, `model1`, `model2`) VALUES (49525, 6, 9709.41, 2496.51, 1335.68, 0, 0, 0, 0, 0, 0, 0, 

0, 0, 0, 4.49367, 0, 0);
INSERT INTO `creature_movement` (`id`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, 

`script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `wpguid`, 

`orientation`, `model1`, `model2`) VALUES (49525, 7, 9693.82, 2473.83, 1335.68, 0, 0, 0, 0, 0, 0, 0, 

0, 0, 0, 5.61285, 0, 0);
INSERT INTO `creature_movement` (`id`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, 

`script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `wpguid`, 

`orientation`, `model1`, `model2`) VALUES (49525, 8, 9759.13, 2422.9, 1334.18, 300000, 0, 0, 0, 0, 0, 

0, 0, 0, 0, 2.42414, 0, 0);
INSERT INTO `creature_movement` (`id`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, 

`script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `wpguid`, 

`orientation`, `model1`, `model2`) VALUES (49525, 9, 9693.75, 2473.47, 1335.68, 0, 0, 0, 0, 0, 0, 0, 

0, 0, 0, 2.45948, 0, 0);
INSERT INTO `creature_movement` (`id`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, 

`script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `wpguid`, 

`orientation`, `model1`, `model2`) VALUES (49525, 10, 9709.45, 2495.78, 1335.68, 0, 0, 0, 0, 0, 0, 0, 

0, 0, 0, 1.41852, 0, 0);
INSERT INTO `creature_movement` (`id`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, 

`script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `wpguid`, 

`orientation`, `model1`, `model2`) VALUES (49525, 11, 9714.2, 2525.76, 1335.68, 0, 0, 0, 0, 0, 0, 0, 

0, 0, 0, 0.036222, 0, 0);
INSERT INTO `creature_movement` (`id`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, 

`script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `wpguid`, 

`orientation`, `model1`, `model2`) VALUES (49525, 12, 9927.83, 2531.24, 1319.3, 300000, 0, 0, 0, 0, 

0, 0, 0, 0, 0, 3.16603, 0, 0);
INSERT INTO `creature_movement` (`id`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, 

`script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `wpguid`, 

`orientation`, `model1`, `model2`) VALUES (49525, 13, 9714.13, 2525.69, 1335.68, 300000, 0, 0, 0, 0, 

0, 0, 0, 0, 0, 0.004804, 0, 0);
INSERT INTO `creature_movement` (`id`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, 

`script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `wpguid`, 

`orientation`, `model1`, `model2`) VALUES (49525, 14, 9707.99, 2554.98, 1335.68, 0, 0, 0, 0, 0, 0, 0, 

0, 0, 0, 2.03899, 0, 0);

**Comment by cala** [comment]
Great! This one was one my to do list, thanks for taking care of it.
I tested your fix and I agree with the pathway, waiting position (and orientations). Could you please make a pull request so we could merge it?
In case you need it: [How to make a pull request](https://help.github.com/articles/using-pull-requests)

Being picky, I still have a few enhancements that can be brought to your fix:
- your `UPDATE` query should only update the `MovementType` field, not all the field. This makes clearer for others what your are changing
- this NPC being unique, it is preferable to use `creature_movement_template` instead, as you already guessed. You need to also set `MovementType` to 2 in `creature_template` table
- the pathway along the Temple of Elune is a bit too polygonal in my opinion. I suggest that you add two or three waypoints to make the pathway follow more closely the circular pink carpet around the Temple walls
- though the pathway is right, I remember it being in the reverse order (Tower with the two herbalism NPCs -> wait -> Other tower -> wait -> Temple entrance -> wait -> Bank -> wait -> back to the tower with the two NPCs). Your fix make the NPC moves in the reverse order. I'm not 100% sure to be right, though. If you are sure of your order, then don't change it.

If you don't feel/know how to add these changes to your current fix, just do a pull request, I'll add them after.

**Comment by cala** [comment]
Closed by https://github.com/classicdb/database/commit/e1d07833ac336b15b81b9150baab46773e66d21d
