### ISSUE TITLE
Crushridge Ogres Fix

### ISSUE THREAD

**Issue by Metalica** [classicdb/database#604]
Crushridge Ogres are mini Ogres instead of normal size Ogres :)

UPDATE `creature_template` SET `Scale`='2' WHERE (`Entry`='2416')
UPDATE `creature_template` SET `Scale`='2' WHERE (`Entry`='2287')
UPDATE `creature_template` SET `Scale`='2' WHERE (`Entry`='2256')
UPDATE `creature_template` SET `Scale`='2' WHERE (`Entry`='2255')
UPDATE `creature_template` SET `Scale`='2' WHERE (`Entry`='2253')
UPDATE `creature_template` SET `Scale`='2' WHERE (`Entry`='2252')
UPDATE `creature_template` SET `Scale`='2' WHERE (`Entry`='2254')

**Comment by cala** [comment]
Thanks for this report and fix proposal.
I agree Crushridge ogres are smaller than Gordunni or Gordok ogres. But after checking what size they have on TBC and WotLK cores (that don't have as much scale issues than Classic), I think that a scale of 1.7 would be better that 2.
If you agree (or have a better value to argue), could you make a pull request with this fix (including the one for Grel'Borg: https://github.com/classicdb/database/issues/605), please?
In case you need it: [How to make a pull request](https://help.github.com/articles/using-pull-requests/)

**Comment by Metalica** [comment]
UPDATE creature_template SET Scale='1,7' WHERE (Entry='2416')
UPDATE creature_template SET Scale='1,7' WHERE (Entry='2287')
UPDATE creature_template SET Scale='1,7' WHERE (Entry='2256')
UPDATE creature_template SET Scale='1,7' WHERE (Entry='2255')
UPDATE creature_template SET Scale='1,7' WHERE (Entry='2253')
UPDATE creature_template SET Scale='1,7' WHERE (Entry='2252')
UPDATE creature_template SET Scale='1,7' WHERE (Entry='2254')
UPDATE creature_template SET Scale='1,7' WHERE (Entry='2417')

 I dont agree with these value, but ok. As for github. Svn was less complicated then github. Need to get my head around it.

**Comment by cala** [comment]
> I dont agree with these value, but ok

I understand. As I said, I used TBC core and WotLK along with a few screenshots gathered here and there to get some idea of the correct scale for those NPCs. Based on these sources, I tried a few values in Classic and 1.7 seemed better to me than 2.0, which looked quite big, especially when ogres are indoor. But I may be wrong.
If you have screenshots, videos or others sources with a better scale showing that 2.0 is indeed a more suitable value, then I'm willing to change it of course.

Regarding the pull request, this would allow me to give you authorship of the commit when pushed to the repository. But if you don't want it or don't care about it, I can also push it by myself and add in the commit message that you are the author, like I do with Neotmiren fixes for example. As you wish. :)

**Comment by Metalica** [comment]
Refence: https://www.youtube.com/watch?v=IyWdCSGjP7Q

 What i did:

 I took human warrior and and went to the boss and checked out the size. That's where i got the 2.0 size from. Also a side note, youtube link is ~6 years old.

 Please do as you said. Yust added me as auto and it's done :) Easyer.

**Comment by cala** [comment]
Thanks. Your video however is only for the ogre boss which may be taller than the others. I found this one: https://www.youtube.com/watch?v=KcB201DV73I where you clearly see that normal ogres are not that tall. Only the named ones are a bit taller.

Once we agreed on the value, I'll push your fix as mentioned above. :)

**Comment by Metalica** [comment]
Ok value is 1.7 for normal mob, boss 2.0 ( both videos as proff).

**Comment by Tobschinski** [comment]
Careful, a Crushridge Mage in particular is as big as a tauren female on retail.

![ogresize](https://cloud.githubusercontent.com/assets/4753528/4524277/418d96a2-4d42-11e4-9713-594eea767fe9.png)

Grel'borg the Miser would no longer fit through the door to the basement.

--> I don't know, they all look fine as they are.

**Comment by Tobschinski** [comment]
I am more concerned about the ogres trying to play musical chairs in that fortress. Why would they do that. (ClassicDB) This looks like a unique case where there's actually too much movement going on.
![muschair](https://cloud.githubusercontent.com/assets/4753528/4527612/7ad44ffc-4d68-11e4-9f0c-ca4448ddbbbe.png)

**Comment by cala** [comment]
Looks like duplicate to me.

**Comment by Tobschinski** [comment]
They are missing elsewhere, I'll take care of it.
