### ISSUE TITLE
Grel'borg the Miser

### ISSUE THREAD

**Issue by Metalica** [classicdb/database#605]
He does not move atm.

http://www.wowhead.com/npc=2417/grelborg-the-miser#comments

"Patrols between the basement of the Keep(36,55) to in front of the Town Hall(40, 47), and back. He takes 2 minutes, 10 seconds to walk from the Keep's Basement to Town Hall, and 2 minutes to return to the basement, for those interested in the details of timing. He spends 30 seconds in the basement before he leaves, if he isn't attacked."

 He is mini ogre, i added fix.

UPDATE `creature_template` SET `Scale`='2' WHERE (`Entry`='2417')

**Comment by Tobschinski** [comment]
@Cala - could you please push http://pastebin.com/3m0DWWPW  - I am not able to do this myself right now, somehow

**Comment by Tobschinski** [comment]
Thank you, still don't know why things aren't working over here ...
