### ISSUE TITLE
Masters eye

### ISSUE THREAD

**Issue by Metalica** [classicdb/database#606]
Masters eye in temple of anuari at twin emperors respawns in 25 seconds.

 I could provice fix, but have no idea how long the hours/days should be. Hint's welcome.

**Comment by Tobschinski** [comment]
Probably in a soft reset.

The Eye should also not be affected by gravity and fly somewhere higher.

**Comment by cala** [comment]
The script involving the Master's Eye is played only once per instance. So, yes a soft reset only should make it respawn. Then, you can change its respawn time to 7 days, like all bosses in the instance.

**Comment by Metalica** [comment]
You ladies can put the timer yourself. I kinda don't want to add wrong timer.

**Comment by Tobschinski** [comment]
Just because I wear pink jerseys on the pitch ...

**Comment by Metalica** [comment]
Yust becouse you.

**Comment by cyberium** [comment]
@Tobschinski as i see everyone know about your sweet body now :/

**Comment by cala** [comment]
Oh no. Can't be unseen.

**Comment by Tobschinski** [comment]
COME AT ME, BRO!

![](http://waltsense.com/storage/articles/20090330_fat_flex_500px.jpg?__SQUARESPACE_CACHEVERSION=1238440958317)
