### ISSUE TITLE
Durotar copper mines

### ISSUE THREAD

**Issue by S-Marais** [classicdb/database#611]
In durotar, all mines are on a the same time. I didn't set the pools to pop more often. So when I travel from Sen'jin to Razor Hill for example I can have my bags full of copper just by minning there. Problem in scriptdev2?

**Comment by cala** [comment]
This is a pool issue, database side. Those mineral nodes are not in a pool (or its max limit is way too high). I started working on these issues in 2013 as you can see [here](https://github.com/classicdb/database/issues/91), [here](https://github.com/classicdb/database/issues/37) and [there](https://github.com/classicdb/database/issues/38). I even had a fix for the missing herbs pools, but I was told that was not needed. But as reports keep coming in, I think I should resume my work on these. Anyway, I'm closing this issue as it is already covered by #92 
Thanks for reporting.
