### ISSUE TITLE
Lashtail Raptor - Dropped Weapon Spell

### ISSUE THREAD

**Issue by scotty0100** [classicdb/database#613]
Lashtail Raptors proc a spell called 'Dropped Weapon' that procs on you as a buff and disarms you, you can click off the buff and get your weapon back.

Should not get the option to click off disarm.

**Comment by cala** [comment]
Thanks for the report. I will look at this, but it may be a DBC issue which means we may need to add an exception in core for this specific spell.

**Comment by cala** [comment]
Like: https://github.com/classicdb/database/issues/640 this is not fixable by DB. Either wrong DBC attributes ou wrong handling by core. I believe there is already a similar issue open in core repository. Thank you. :)
