### ISSUE TITLE
Eternal Quintessence - Duke Hydraxis

### ISSUE THREAD

**Issue by scotty0100** [classicdb/database#614]
Map & Area: Azhara
How to replicate the bug: Once completing quest Hands of the Enemy (ID 6824) Speak to the Duke
What happens: nothing
What should happen: at Revered rep he should have the option to give you the Eternal Quintessence, at Honored rep Aqual Quintessance

Source: http://www.wowhead.com/item=22754/eternal-quintessence#comments

I can not find the missing gossip option for this..

**Comment by cala** [comment]
Thanks, I was sure that Duke Hydraxis was fine and without you report I would probably not have check him in a long time.

Assuming we find the right data (gossip option texts and gossip id), this is easy to fix.

**Comment by scotty0100** [comment]
Yeah I had trouble finding the gossip menu to go along with it, wasn't a lot of data on the interwebs about this quest!

**Comment by Tobschinski** [comment]
This is used on Valkyrie-WoW, but I have absolutely no idea if it's a custom thing. (nor am I willing to farm reputation to get to revered :) )

![essence](https://cloud.githubusercontent.com/assets/4753528/4611573/85a60c46-52bc-11e4-854d-e7552a50a9ef.png)

**Comment by scotty0100** [comment]
Had another 40 minute or so Google/YouTube session with no luck so far :(

Not sure if we can ever get the Blizzard data for this, he has been taken out of the game now as well.

**Comment by cala** [comment]
Thank you. I'm afraid we won't easily find reliable source on the matter. I have a high numbers of screenshots back from Classic days, with many gossips in them, but I doubt this one will be in.
I'm also pretty sure that the one on valkyrie-wow is a custom one: "Gimme" is familiar language and if it would have been use on a gossip I used several times while farming MC, I would have remembered it.

I'm afraid we will need to use a placeholder text here.

**Comment by scotty0100** [comment]
Well..after another 30 minutes of Googling obscure areas where this might appear (Feat of Strength Achievment - The Fifth Element) I had some success!!

Before taking the Quintessence:
<img src="http://img.photobucket.com/albums/v672/Xandier/Forums/WoWScrnShot_052106_111828.jpg">

After taking the Quintessence:
<img src="http://img.photobucket.com/albums/v672/Xandier/Forums/WoWScrnShot_052106_111856.jpg">

Aqual Quintessence..I'm still not sure - but it's a good place to start! :)

Source a blog from 2006: http://thulf.blogspot.co.uk/2006_05_01_archive.html you can find this picture under the hyperlink "Eternal Quintessence"

The other picture I found by going through his image bucket account after I found the first image, lol.

**Comment by ghost** [comment]
@scotty0100  you're a research prodigy!

**Comment by Tobschinski** [comment]
The eternal quintessence was gone forever if you delete it, right?

**Comment by evil-at-wow** [comment]
@Tobschinski You mean on live servers now? Yes, it'll be gone forever because you won't be able to get another one.

**Comment by Tobschinski** [comment]
No, back in the glory days or WoW.

**Comment by cala** [comment]
This was an option based on reputation and not on quest reward. I'm pretty sure you could get it again if deleted.
