### ISSUE TITLE
Grawmug / Gnasher / Brawler trio in Stonesplinter Valley

### ISSUE THREAD

**Issue by scotty0100** [classicdb/database#616]
These 3 creatures are for the quest In defense of a Kings Lands and they seem to all be 'rooted' on the spot and not move at all

Which should not happen as theres comments on WoWHead that say that if your not careful you can aggro all 3 from underneath the ledge

Source: http://www.wowhead.com/npc=1205#comments

**Comment by cala** [comment]
Thanks for the report. This is a mmaps issue (the NPCs cannot find a path, so they evade), we are dealing with it core-side: https://github.com/cmangos/issues/issues/303
I'm closing this here.
