### ISSUE TITLE
Cenarion Raiment bug

### ISSUE THREAD

**Issue by Metalica** [classicdb/database#617]
Set does not have correct skill:  Set: Reduces the cooldown of your Tranquility spell by 50% and increases the damage done by your Hurricane spell by 15%.

 Reference: http://vanilla-wow.wikia.com/wiki/Cenarion_Raiment

 Correct skill ID: 23556

**Comment by Tobschinski** [comment]
This spell did only grant a reduced cooldown in Vanilla and TBC, for both, Hurricane and Tranquility. Because Hurricane lost its cooldown in WotLK (3.0.2), the set bonus was changed a few patches later.

> (3.2.0) Cenarion Set: No longer reduces the (nonexistent) cooldown on Hurricane. Instead, the set bonus increases the damage done by Hurricane by 15%.

**Comment by cala** [comment]
As stated by Tobschinski, in your bug report you are refering to a set bonus that was introduced in WotLK.
Yes, that vanilla-wow.wikia.com website does say that this was also the case in Classic, but this website is wrong. The bonus in Classic was slightly different.

Your initial message is a bit misleading regarding what you are reporting as an issue. If you were telling that the whole bonus is missing, than yes, we need to look at that. But if you were telling than it should be "Set: Reduces the cooldown of your Tranquility spell by 50% and increases the damage done by your Hurricane spell by 15%.", then you used a wrong source. vanilla-wow and other private servers wiki or database _are not_ reliable sources. Most of them were built on leeched content (mostly from mangos project) years ago and they still carry on the bugs that were there at that time.

If we are closing an issue and you think that we should not, please do not open a new one: keep the discussion in the first one instead. We can still review it again and reopen it if needed.
