### ISSUE TITLE
Quest #1059 Needs quest ending script added

### ISSUE THREAD

**Issue by Zingzah** [classicdb/database#618]
This quest, Reclaiming the Charred Vale ends small quest chain at Falfindel Waywarder in Feralas.  I remember doing this a few times on live and it's only a small little script in which Falfindel does a cast animation (looks like swiftmend) and a number of wisps appear head in a particular direction for a little bit then disappear. Some details are in
http://www.wowhead.com/quest=1059/reclaiming-the-charred-vale#comments
http://www.wowwiki.com/Quest:Reclaiming_the_Charred_Vale_%282%29
Would love to find a clip of the event, I'll keep searching.

**Comment by cala** [comment]
Thanks for reporting. A DBscript should do the trick... once we know what spell is casted.

EDIT:
NPC to be summoned: Forest wisp 4059
Spell to summon them : call of forest 6537 (source: http://www.wowhead.com/spell=6537#comments http://www.wowhead.com/spell=6537#screenshots:id=87812)
