### ISSUE TITLE
Cenarion Raiment bug 

### ISSUE THREAD

**Issue by Metalica** [classicdb/database#619]
Set does not have correct skill: Set: Reduces the cooldown of your Tranquility spell by 50% and increases the damage done by your Hurricane spell by 15%.

Reference: http://vanilla-wow.wikia.com/wiki/Cenarion_Raiment

Correct skill ID: 23556

EDIT by cala: I **do not** accept bad language here.

**Comment by Tobschinski** [comment]
See https://github.com/classicdb/database/issues/617 - you are still referring to a patched spell.
Just to be fair, if you think this is a misunderstanding, please provide more information.
