### ISSUE TITLE
Fix: Mithril Ore in Durotar

### ISSUE THREAD

**Issue by scotty0100** [classicdb/database#62]
Replaces two mithril ore's found in Durotar with Copper Nodes, and fixes one of the Copper Ore nodes that's half way in the world.

UPDATE gameobject SET id = 1731 WHERE guid=7321;
UPDATE gameobject SET id = 1731 WHERE guid=7304;
UPDATE gameobject SET position_z = -8.4 WHERE guid=5455;

**Comment by cala** [comment]
Thank you, there are indeed no mithril spawns in Durotar.
