### ISSUE TITLE
Forest Song Population Incorrect

### ISSUE THREAD

**Issue by Zingzah** [classicdb/database#621]
This area in Ashenvale currently has 3 Npcs as its home.  However, in vanilla (prior to patch 2.0.1) there is supposed to be only Kayneth Stillwind.
http://web.archive.org/web/20061108183108/http://www.wowwiki.com/Forest_Song
The other two npcs currently there atm (Sentinel Frostshadow #npc3880 and Illiyana #3901) were originally at the Shrine of Aessina.  The only location I could find for Sentinel Frostshadow was from this vanilla wedding clip which shows her positioning at the time.
http://www.youtube.com/watch?v=dKN-LcT67A4
I haven't found any original coords(positioning) for Illiyana as yet but will keep searching.

**Comment by cala** [comment]
Nice catch again. I already had a run through ashenvale one year ago and I did not notice those NPCs were at the wrong place.
