### ISSUE TITLE
Issue running 0765_UDB_407_updatepack_mangos.sql

### ISSUE THREAD

**Issue by Galatean** [classicdb/database#622]
When doing the initial DB import according to the cmangos wiki, running 0765_UDB_407_updatepack_mangos.sql gives me the following error:
ERROR 1136 (21S01) at line 19: Column count doesn't match value count at row 1

Anything I can do to resolve this?

**Comment by cala** [comment]
Thank you.
This is a mismatch between the core structure of the database and the one used by Classic DB. There is already a pull request regarding this here: https://github.com/cmangos/mangos-classic/pull/91
While I'm reviewing it, you can fix this by running this code before installing Classic DB:

``` SQL
ALTER TABLE `gameobject_template` DROP COLUMN `castBarCaption`;
```

Note this is a temporary solution.

**Comment by Galatean** [comment]
It worked! Thanks for the quick response!
