### ISSUE TITLE
Presence of Might Enchant Don't Stack Together

### ISSUE THREAD

**Issue by scotty0100** [classicdb/database#623]
How to replicate the bug: enchant warrior's both helm and pants with Presence of Might

What Happens: you get +10 stamina and +7 defense, the equivalent of 1 enchant

What should happen: you should get +20 stamina and +14 defense, half that from pants, half that from helm.

Extra Information:

Presence of Might http://db.vanillagaming.org/?item=19782

My enchanted gear:
Enchanted Thorium Helm http://db.vanillagaming.org/?item=12620
Deathbone Legguards http://db.vanillagaming.org/?item=14623

I noticed some weird behavior when I had only one of them, on my pants. When I died or logged out, then came back, enchant stopped working, and I had to unequip and re-equip pants for it to work again.

Not sure if it's solvable through DB spell fields..or is a core issue?

**Comment by cala** [comment]
Thank you for reporting this. From my point of view, this is a core issue where bonus from enchant are not calculated as they should.
Closing here.
