### ISSUE TITLE
Raene's Cleansing Questline

### ISSUE THREAD

**Issue by Zingzah** [classicdb/database#625]
I came across a few issues while doing this questline so I thought it easiest to group them all into one post.  So here goes:
1.  The first one I came across was to do with Raene's greeting text.
You have completed Teronis' mission, and I appreciate all you have done, $N. (npc_text 6555)
 is presented on first meeting Raene even before any quests have been completed.  and then after Dartol's rod has been reconstructed the greeting changes to 
I know these forests as if they were a part of me... But know that there is still much to be learned from them, and much danger still hidden. (npc_text 6553)
These are presented in the wrong order.

2.1 In quest #1027 the required item is #5519 (Iron Pommel). This was lootable from a Rusty Chest (object #19021) which spawned from every Rotting Slime I killed.
According to comments
http://www.wowhead.com/object=19021#comments and
http://www.wowhead.com/item=5519#comments this isn't supposed to be 100% on live.
Also some players commented the pommel being in the slimes' loot table which I could not find to be the case in the db.

2.2  While on this quest I found some Ghostpaw runners (npc #3823 lvl 19) in this area which they should not be (should only be in the Zoram Strand area)
1. Finally when doing quest #1045 I became a bit confused by Ran Bloodtooth's Skull (item #5388).  It is not required for the completion of the quest and did appear in the loot from Ran Bloodtooth.  Yet it is a provided item in the following quest #1046 (the final in the questline).  It is listed in #1046 as a SourceItemId and ReqItemId and I couldn't find out whether it's supposed to drop off Ran or not.  Any thoughts on this would be appreciated.
   A great defining Ashenvale questline all in all and executed well for the majority.

**Comment by cala** [comment]
Thank you for this complete report.
I did a cleanup of Ashenvale alliance side some times ago, with special care to Raene's quest line but I obviously missed a few things.

For the gossip text, we probably need to swap the condition id between the two texts in Raene's gossip menus.

For the rusty chest, this spawn on death is probably handled by ACID. We need to check the probability of the event to trigger and do a pull request accordingly to ACID.

For the ghostpaw runners, can you precise where you found them (or give GUID), please ?

For the Ran Bloodtooth's Skull, this is intended. The item is known to drop from Ran. It is also required for the last part of the quest line but provided by quest giver (was previously missing, forcing players to kill Ran a second time). So as strange as it may seems, this is working as expected.

**Comment by Zingzah** [comment]
These are the Ghostpaw Runners that I believe are out of place.  Maybe they should be either the Howlers(#3824 lvl23-24) or Alphas(#3825 lvl27-28) instead.
Fallen Sky Lake Area
35001,35004,35000,34952,35002,34986,34999,35003,34976,35005,34995,34988(fell through world when .go creature to this one)
Fire Scar Shrine/Shrine of Aessina Area
34956,34944,34947,34998,34981,34954(fell through world again),34955,34939,34946,34963,34937,
34938,34940,34949,34950,34941,34951,34943,34979,34997,34942,34977,34980,34982,34973,34969,34961,34983,34953,34957,34936,34059,34945.34962,34948
The remaining Runners are in the Zoram Strand region and ok.
