### ISSUE TITLE
Quest #1022 Additional Incorrect text emotes

### ISSUE THREAD

**Issue by Zingzah** [classicdb/database#626]
In this quest, The Howling Vale, the Tome of Mel'Thandris is read and starts a little script with Velinde Starsong spawning and emoting some text.  However in addition to the text from this quest she also emotes text from Rise Obsidian which is emoted by Dorius
from creature_ai_texts:
-658  Fools. I knew that if I played upon my brother's feeble emotions, he would send 'rescuers.'
-659 How easy it was to manipulate you into recovering the last Suntara stone from those imbeciles of the Twilight's Hammer..
-660 When I stumbled upon the Suntara stones at the Grimesilt Digsite, the power of Ragnaros surged through my being. It was Ragnaros that gave me a purpose.
Just these need to be removed, the others are correct.

**Comment by cala** [comment]
Thanks for your report. This looks like an ACID issue but when looking at ACID code, I don't see the error. Could you reapply ACID from official repository and tell if this issue is still there, please?

**Comment by Zingzah** [comment]
I think I may have found the problem here.  There are two things happening here.  Firstly, when the Tome is used a db event (663) is triggered with the correct text emotes.  Secondly, when Velinde is spawned EventAI executes scripts 394601-04 which contains the incorrect text that is being shown from the Rise Obsidian quest.  So it's just a question of removing the eventAI and/or creature_ai_scripts pertaining to Velinde (#3946)

**Comment by Zingzah** [comment]
Just checked this with latest ACID and this issue seems to have corrected.

**Comment by cala** [comment]
Thanks. As I did both the DB scripts and the ACID removal, I was expecting this. What is most disturbing is that the ACID script is only partly removed on Classic DB though I applied the latest ACID version (including the full removal) when releasing v1.4.1.
Anyway, since the official ACID does not contains the error, we can close this issue.
