### ISSUE TITLE
Lupos NPC 521

### ISSUE THREAD

**Issue by TheTrueAnimal** [classicdb/database#627]
Since Patch 1.9.2 Lupos shouldn't deal shadow damage any more. At mangos zero he still does although it's patch 1.12.1.

NPC: http://www.wowhead.com/npc=521
Source: https://web.archive.org/web/20070614002029/http://wow.allakhazam.com/db/mob.html?wmob=521

**Comment by Tobschinski** [comment]
Are we talking about Lupos as a pet or Lupos as a creature?

**Comment by TheTrueAnimal** [comment]
Lupos as pet.

**Comment by cala** [comment]
@Phatcat Just to be sure: this issue should be closed by this line https://github.com/cmangos/mangos-classic/commit/c018db951028b9a2e45ed6f137791f836f82164c#diff-4f14a67c343c24da132bdf3c8706b7c4R1076 am I right?

**Comment by Phatcat** [comment]
@cala yes. This is why I referenced it.

If you would consider letting me onto the db team I could help do some housekeeping as well ;)

**Comment by cala** [comment]
I was already considering it. ;-)

Thanks for confirming the issue closure, this is as I thought.
