### ISSUE TITLE
Enraged Silverback Gorilla

### ISSUE THREAD

**Issue by TheTrueAnimal** [classicdb/database#629]
The gorillas should use some kind of enrage when they're at 10% life.

NPC: http://de.wowhead.com/npc=1511
Spell: http://de.wowhead.com/spell=8599
Video: https://www.youtube.com/watch?v=cO671tvyeiQ

**Comment by Swater96** [comment]
@cala @Tobschinski This had been fixed. I tried to follow the SD2 naming guidelines, please doublecheck for me. 1511(NPC)01(First script)

UPDATE creature_template SET AIName='EventAI' WHERE (Entry='1511');
DELETE FROM `creature_ai_scripts` WHERE id=151101;
INSERT INTO `creature_ai_scripts` (`id`, `creature_id`, `event_type`, `event_flags`, `event_param1`, `event_param2`, `action1_type`, `action1_param1`, `comment`) VALUES ('151101', '1511', '2', '1', '10', '0', '11', '8599', 'Enraged Silverback Gorilla - Enrage');

**Comment by cala** [comment]
Thank you for the report, the research and the pull request. There are some small adjustements to be made, but this is mostly ok.
This is ACID stuff and I will push it to ACID soon.

**Comment by cala** [comment]
Pull requests were made to ACID. Thank you.
