### ISSUE TITLE
Mobs & Stealth

### ISSUE THREAD

**Issue by scotty0100** [classicdb/database#63]
A lot of mobs aren't using their stealth abilities to name a few:

Rohh the Silent, Source: http://www.wowhead.com/npc=947/rohh-the-silent#comments:id=117974

Razormane Stalker, Source: http://www.wowhead.com/npc=3457#comments:id=328513

Shadowmaw Panther, Source: http://www.wowhead.com/npc=684/shadowmaw-panther#comments:id=71387

Probably lots more out there but those 3 for sure.

**Comment by cala** [comment]
Those creatures are probably missing their addon entry in `creature_addon`. I can add them for the three creatures listed above.

I suggest you and everyone keep on updating this issue everytime you see a mob that is missing its stealth aura.

**Comment by cala** [comment]
The creatures listed above were fixed in revision 0214. I let this issue open: please, feel free to add here any NPC you found in the game that is missing its stealth aura.

**Comment by cala** [comment]
I fixed a lot more of creatures today. The update will be pushed later along with the next batch of updates.

**Comment by cala** [comment]
Closed by https://github.com/classicdb/database/commit/0d0afb0b45dc75d3d6f21c1e76f81cfad2d2ebda
