### ISSUE TITLE
Aurius' Reckoning 

### ISSUE THREAD

**Issue by TheTrueAnimal** [classicdb/database#630]
After taking the quest the npc should help players defeating baron rivendale by spawning during the fight. After having defeated him a little event should start after which the quest is completed. At the moment the npc does not spawn during the fight. You can directly take the quest which is autocompleting.

Prequest: http://aowow.wow-castle.de/?quest=5122
Quest: http://www.wowhead.com/quest=5125
NPC: http://www.wowhead.com/npc=10917
Baron: http://www.wowhead.com/npc=10440
Video: https://www.youtube.com/watch?v=ceahrMKY1CA [^](from 1:35 on)

**Comment by cala** [comment]
Closed by https://github.com/cmangos/mangos-classic/commit/0519a1da7381e1c26c49ab56e4b12026895f707c
