### ISSUE TITLE
Stratholme Rats Event

### ISSUE THREAD

**Issue by TheTrueAnimal** [classicdb/database#631]
When you enter one of the gates in Stratholme some rats should spawn and attack. I've seen 10 at the video.

Rat: http://www.wowhead.com/npc=10441
Video: https://www.youtube.com/watch?v=opFRb4Y0WzM (from 1:08 on)

**Comment by cala** [comment]
Missing data for this one: what is the trigger for the trap? No suitable GO spotted nor spell.
NPC 14646 (Stratholme Trigger) candidate?

**Comment by Tobschinski** [comment]
Nope, the Stratholme trigger is spawned somewhere in the living part.

**Comment by cala** [comment]
In the Scarlet Bastion for one of the spawning event, I guess?
Then how the rat traps and the Unforgiven are spawned/triggered is still a mystery to me...

**Comment by evil-at-wow** [comment]
It's probably scripted. You have to open a gate first, so it could be triggered by that gate closing again or so. 

I have noticed that the rat traps are on a timer too. The first time you're trying to pass through the gates you'll have rats, but after a few minutes you can open the gates  again and pass through a few more times without getting rats. Then after a good while, you try once more and suddenly you'll get rats again. At least that's what I remember. I might have some notes about this... somewhere...

**Comment by Tobschinski** [comment]
The doors are open and will only close if you move through the underpass.

I'd say this is just another trap-go that is never sent to the client, like the ones guarding the eggs in LBRS or Onyxia's lair.

The Unforgiven could just be invisible ...

**Comment by cala** [comment]
Thanks both of you for your answers.

> I'd say this is just another trap-go that is never sent to the client, like the ones guarding the eggs in LBRS or Onyxia's lair.

That's what I'm afraid of though I found no related spell in the DBCs. I will need SD2 here, then.

> The Unforgiven could just be invisible

If that was the case, it would be seen in the sniffs, I think and more importantly, it would not trigger on stealth. Yet, stealthed characters make it spawn but not aggro.

**Comment by cala** [comment]
Dear @evil-at-wow I hope you will forgive me to bother you again but the quickness of your answers and their reliability gave me bad habits as I was afraid they would. I'm now addicted. Please, do not take advantage of this.

By any chance, do you have any information about the GO 175534, please? Spawn location (if any) would be nice, but I'm especially interested in the template data of that GO like flags and faction. If you can't find any data of this GO in your Stratholme sniffs, this is also a worthy info.

**Comment by evil-at-wow** [comment]
You know you can just ask, @cala, though It might take a little while before I manage to get back to you, depending on what you're asking for and my own schedule.

But you're lucky, because I still have the data from a Stratholme run around (the failed 45m run from the Ysida issue). Unfortunately for you, I don't see any GO with that entry in the list of GOs...

My TBC-DB tells me that this entry is supposed to be a `Supply Crate`. I see many `Supply Crate` GOs in that one run, but they all have a different entry: 176224, 176304, 176307, 176308 or 176309. Not a single one with entry 175534. I'll check some more Stratholme data I have later, to see if that results in anything useful.

And what must you give in return? Everything! :smiling_imp:

**Comment by cala** [comment]
Thank you for this answer. :+1: 

Unfortunately, this is as I feared: the 5 chest GOs are there (176224, 176304, 176307, 176308 and 176309) but not the 4 related trap GOs. GO entry 175534 is the one that is used to spawn the rats for this very issue but also for the crates.

It is assumed that the GOs existed in Classic but were removed later and replaced by server-side traps/effects. But we will never know for sure. That GO is casting spell 16371 which summons the rat (NPC 10441) but the spell is in Classic DBC but not the WotLK ones.

I hope you will find something usefull in your next check of your data because I'm a bit at lost with that issue.

**Comment by cala** [comment]
@xfurry May I ask for your help and opinion on the matter?
Here is a quick summary. There are two issues in Stratholme, probably related.

**https://github.com/cmangos/issues/issues/468**
Is about various GO (crates) that players must open. There are five kinds of them, one with loot and 4 spawning a GO trap. The spells for the traps are in Classic DBC but @Schmoozerd said they were removed in WotLK. So for Classic, it's only a matter of spawning the GOs at the right places but for WotLK (and possibly TBC), we may need to code the spells or have another approach.

**This current issue**
Is about the two places in Stratholme where players enter a corridor with two gates/grid closing at each end and numerous plagued rats spawning and attacking the players (see https://youtu.be/opFRb4Y0WzM?t=1m4s). After a timer expires, the gates open again. This issue is possibly linked with the above one because the spawned NPCs are also spawned by one of the four GO traps (NPC 10411, spawned by spell 16371, used by GO trap 175534). The main issue here is how to trigger the whole trap event. I found in the DB no GO/NPC trigger that would make sense, @evil-at-wow and @Tobschinski seem to find none in their sniffs either.

So, I have two approaches:
1. spawn the related GO trap in the middle of the corridor and script them in DBScripts to make the event work. But it does not seem proper as we can't script single GO traps, only their template and as seen in the first issue, they are spawned elsewhere too (though we can probably stop the script execution in those cases because the gate GOs are not nearby).
2. script the event in SD2, triggering it when a player is between the two gate or in range of a specific location to emulate a trigger/trap. Maybe you have a better suggestion for that @xfurry ? 

Which one do you think is best suited?

**Comment by cala** [comment]
Poke @xfurry for your advice on this topic, please. :)

**Comment by xfurry** [comment]
Sorry, didn't see this topic before.
I need to see how this looks in a real server environment, in order to understand what is going on.
So let me run a few testes on my side and I will get back to you asap. (hope UDB and @Grz3s  are on the same page with  you guys on this topic)

**Comment by cala** [comment]
> Sorry, didn't see this topic before.

No worries, I'm sure you get far more notifications than me.
Any input you can have on the matter would be of great help, thanks! :smile:

**Comment by cala** [comment]
Kind poke @xfurry if you had the time to gather some data. :)
This is the last issue remaining for the next Classic DB milestone and I would like to close this properly.

**Comment by Phatcat** [comment]
You can bypass the 'gate' traps: (possibly only in tbc and wrath version)
TBC: https://youtu.be/M78WS50Mcvk?t=2m51s
Wrath: https://youtu.be/nGr8IxEG3g0?t=3m1s

https://youtu.be/9QsftBBXd1o?t=6m1s (this is not really a good quality source, but nevertheless a fine video to study the baron run)

It's not only rats that spawn at the gates or even in the crates; it's also insects and magots, perhaps chosen at semi-random?. and lots of them in between the gates.... not 10.. more like 20 (possibly a random number given my other comment on this thread) - This player has 'show mob health bars' - 'Plagued insect')
https://youtu.be/--IiC_Wuxfg?t=6m50s

I'm pretty sure the crates worked by letting you start opening it, and if it works then you open it like a normal crate and can loot stuff (most notably holy water of course) - if it doesn't work (infected) it will break as soon as the opening timer is done and the maggots will spawn.. Is how I remember it.

(both the last 2 links are best viewed at 0.5 speed)

.. I honestly don't know why I mixed in the crates with this, I guess I thought they were sort of related -.-

**Comment by Phatcat** [comment]
(both of the last 2 links are best viewed at 0.5 speed)

**Comment by Phatcat** [comment]
Oh my, would you look at that:

https://youtu.be/--IiC_Wuxfg?t=7m3s

Pay attention to the rogue; the gate has to be manually opened in vanilla.

also if you go back to about 6:45 in the video you will see that the gate trap is actually not filled with rats but rather with those big maggot things and those small... darker.. maggot things... This player has show mob health bars on so the names should be able to be made out .

It looks like this trap thing chaged quite a bit between vanilla and wrath.

**Comment by Phatcat** [comment]
also in vanilla, it wasn't just 10 maggots.. it looks more like 15 - 20 of each of the 2 types..

**Comment by Phatcat** [comment]
> No suitable GO spotted nor spell.

@cala What about these?

Id: 16369
Name: Bugs
General info
Category = 0, SpellIconId = 1, ActiveIconId = 0, SpellVisual = (0, 0)
SpellFamilyName = SPELLFAMILY_GENERAL, SpellFamilyFlags = 0x0000000000000000
SpellSchool = 0 (SPELL_SCHOOL_NORMAL)
DamageClass = 0 (SPELL_DAMAGE_CLASS_NONE)
PreventionType = 0 (SPELL_PREVENTION_TYPE_NONE)
Attributes
Attributes: 0x00000190 (SPELL_ATTR_UNK4, SPELL_ATTR_UNK7, SPELL_ATTR_UNK8)
Advanced info
Spell Level = 0, BaseLevel 0, MaxLevel 0, MaxTargetLevel 0
Category = 0
DispelType = 0 (DISPEL_NONE)
Mechanic = 0 (MECHANIC_NONE)
SpellRange (Id 1) "Self Only"
MinRange = 0
MaxRange = 0
CastingTime (Id 1) = 0.00
Duration: ID (5) 300000, 0, 300000
Interrupt Flags: 0x00000000, AuraIF 0x00000000, ChannelIF 0x00000000
Chance = 101, charges - 0
Effects
Effect 0:
Id: 41 (SPELL_EFFECT_SUMMON_WILD)
BasePoints = 2 to 6
Targets (18, 0) (TARGET_EFFECT_SELECT, NO_TARGET)
EffectMiscValue = 10461
Effect 1:
NO EFFECT
Effect 2:
NO EFFECT

Id: 16370
Name: Maggots
General info
Category = 0, SpellIconId = 1, ActiveIconId = 0, SpellVisual = (0, 0)
SpellFamilyName = SPELLFAMILY_GENERAL, SpellFamilyFlags = 0x0000000000000000
SpellSchool = 0 (SPELL_SCHOOL_NORMAL)
DamageClass = 0 (SPELL_DAMAGE_CLASS_NONE)
PreventionType = 0 (SPELL_PREVENTION_TYPE_NONE)
Attributes
Attributes: 0x00000190 (SPELL_ATTR_UNK4, SPELL_ATTR_UNK7, SPELL_ATTR_UNK8)
Advanced info
Spell Level = 0, BaseLevel 0, MaxLevel 0, MaxTargetLevel 0
Category = 0
DispelType = 0 (DISPEL_NONE)
Mechanic = 0 (MECHANIC_NONE)
SpellRange (Id 1) "Self Only"
MinRange = 0
MaxRange = 0
CastingTime (Id 1) = 0.00
Duration: ID (5) 300000, 0, 300000
Interrupt Flags: 0x00000000, AuraIF 0x00000000, ChannelIF 0x00000000
Chance = 101, charges - 0
Effects
Effect 0:
Id: 41 (SPELL_EFFECT_SUMMON_WILD)
BasePoints = 2 to 6
Targets (18, 0) (TARGET_EFFECT_SELECT, NO_TARGET)
EffectMiscValue = 10536
Effect 1:
NO EFFECT
Effect 2:
NO EFFECT

Id: 16371
Name: Rats
General info
Category = 0, SpellIconId = 1, ActiveIconId = 0, SpellVisual = (0, 0)
SpellFamilyName = SPELLFAMILY_GENERAL, SpellFamilyFlags = 0x0000000000000000
SpellSchool = 0 (SPELL_SCHOOL_NORMAL)
DamageClass = 0 (SPELL_DAMAGE_CLASS_NONE)
PreventionType = 0 (SPELL_PREVENTION_TYPE_NONE)
Attributes
Attributes: 0x00000190 (SPELL_ATTR_UNK4, SPELL_ATTR_UNK7, SPELL_ATTR_UNK8)
Advanced info
Spell Level = 0, BaseLevel 0, MaxLevel 0, MaxTargetLevel 0
Category = 0
DispelType = 0 (DISPEL_NONE)
Mechanic = 0 (MECHANIC_NONE)
SpellRange (Id 1) "Self Only"
MinRange = 0
MaxRange = 0
CastingTime (Id 1) = 0.00
Duration: ID (5) 300000, 0, 300000
Interrupt Flags: 0x00000000, AuraIF 0x00000000, ChannelIF 0x00000000
Chance = 101, charges - 0
Effects
Effect 0:
Id: 41 (SPELL_EFFECT_SUMMON_WILD)
BasePoints = 2 to 6
Targets (18, 0) (TARGET_EFFECT_SELECT, NO_TARGET)
EffectMiscValue = 10441
Effect 1:
NO EFFECT
Effect 2:
NO EFFECT

Creature IDs fit:

'Bugs' - 10461: 'Plagued Insect'
'Maggots' - 10536: 'Plagued Maggot'
'Rats' - 10441: 'Plagued Rat'

the base points are probably the amount to summon on trap, then a bunch of them are just spread out in between the two gates, grouped together so triggering one triggers them all? (In the video they seem to be spawned in multiple places)

**Comment by Phatcat** [comment]
Something like this for the trigger? 

Id: 16378
Name: Temperature Reading
Description: Take a reading of the temperature at a hot spot.
General info
Category = 0, SpellIconId = 1, ActiveIconId = 0, SpellVisual = (215, 0)
SpellFamilyName = SPELLFAMILY_GENERAL, SpellFamilyFlags = 0x0000000000000000
SpellSchool = 0 (SPELL_SCHOOL_NORMAL)
DamageClass = 0 (SPELL_DAMAGE_CLASS_NONE)
PreventionType = 0 (SPELL_PREVENTION_TYPE_NONE)
Attributes
Attributes: 0x00000180 (SPELL_ATTR_UNK7, SPELL_ATTR_UNK8)
Advanced info
Spell Level = 0, BaseLevel 0, MaxLevel 0, MaxTargetLevel 0
Category = 0
DispelType = 0 (DISPEL_NONE)
Mechanic = 0 (MECHANIC_NONE)
SpellRange (Id 7) "Very Short Range"
MinRange = 0
MaxRange = 10
CastingTime (Id 5) = 2.00
Interrupt Flags: 0x0000001F, AuraIF 0x00000000, ChannelIF 0x00000000
Requires Spell Focus 723
Chance = 101, charges - 0
Effects
Effect 0:
Id: 3 (SPELL_EFFECT_DUMMY)
BasePoints = 1
Targets (38, 0) (TARGET_SCRIPT, NO_TARGET)
Effect 1:
NO EFFECT
Effect 2:
NO EFFECT

?

It's right next to this fella, looks very much like he's stratholme related;

Id: 16381
Name: Summon Rockwing Gargoyles
Description: Summons $s1 $lRockwing Gargoyle:Rockwing Gargoyles; to accompany the caster until dismissed.
General info
Category = 0, SpellIconId = 150, ActiveIconId = 0, SpellVisual = (4080, 0)
SpellFamilyName = SPELLFAMILY_GENERAL, SpellFamilyFlags = 0x0000000000000000
SpellSchool = 5 (SPELL_SCHOOL_SHADOW)
DamageClass = 0 (SPELL_DAMAGE_CLASS_NONE)
PreventionType = 1 (SPELL_PREVENTION_TYPE_SILENCE)
Attributes
Attributes: 0x00000100 (SPELL_ATTR_UNK8)
AttributesEx2: 0x00000004 (SPELL_ATTR_EX2_CANT_REFLECTED)
Advanced info
Spell Level = 1, BaseLevel 1, MaxLevel 0, MaxTargetLevel 0
Category = 0
DispelType = 0 (DISPEL_NONE)
Mechanic = 0 (MECHANIC_NONE)
SpellRange (Id 13) "Anywhere"
MinRange = 0
MaxRange = 50000
CastingTime (Id 7) = 10.00
Duration: ID (21) -1, 0, -1
Interrupt Flags: 0x0000000F, AuraIF 0x00000000, ChannelIF 0x00000000
Chance = 101, charges - 0
Effects
Effect 0:
Id: 42 (SPELL_EFFECT_SUMMON_GUARDIAN)
BasePoints = 2, Multiple = -99999998430674944.00
Targets (46, 0) (TARGET_SCRIPT_COORDINATES, NO_TARGET)
EffectMiscValue = 10408
Effect 1:
NO EFFECT
Effect 2:
NO EFFECT

In between these we find this invisibility, which may be related to the eye of naxxramus or how it's called (https://youtu.be/--IiC_Wuxfg?t=42s) - or unforgiven?;

Id: 16380
Name: Greater Invisibility
Description: Turns the caster invisible until the effect is cancelled.
ToolTip: Invisible.
General info
Category = 0, SpellIconId = 30, ActiveIconId = 0, SpellVisual = (72, 0)
SpellFamilyName = SPELLFAMILY_MAGE, SpellFamilyFlags = 0x0000000080000000
SpellSchool = 6 (SPELL_SCHOOL_ARCANE)
DamageClass = 1 (SPELL_DAMAGE_CLASS_MAGIC)
PreventionType = 1 (SPELL_PREVENTION_TYPE_SILENCE)
Attributes
Attributes: 0x10110000 (SPELL_ATTR_NOT_SHAPESHIFT, SPELL_ATTR_STOP_ATTACK_TARGET, SPELL_ATTR_CANT_USED_IN_COMBAT)
AttributesEx1: 0x00000100 (SPELL_ATTR_EX_NOT_IN_COMBAT_TARGET)
Advanced info
Spell Level = 1, BaseLevel 1, MaxLevel 0, MaxTargetLevel 0
Category = 0
DispelType = 6 (DISPEL_INVISIBILITY)
Mechanic = 0 (MECHANIC_NONE)
SpellRange (Id 1) "Self Only"
MinRange = 0
MaxRange = 0
CastingTime (Id 1) = 0.00
Duration: ID (21) -1, 0, -1
Interrupt Flags: 0x00000000, AuraIF 0x00003C07, ChannelIF 0x00000000
Chance = 101, charges - 0
Effects
Effect 0:
Id: 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 300
Targets (1, 0) (TARGET_SELF, NO_TARGET)
Aura Id 18 (SPELL_AURA_MOD_INVISIBILITY), value = 300, misc = 0 (0), periodic = 0
Effect 1:
NO EFFECT
Effect 2:
NO EFFECT

**Comment by Phatcat** [comment]
@cala 

> The main issue here is how to trigger the whole trap event.

area_trigger perhaps? like we do with stuff like instance portals?

**Comment by cala** [comment]
@Phatcat thanks for the research you've made. :+1: 

Thanks for the videos, they are instructive.

Regarding the crates that are randomly scattered across Stratholme, there are indeed several on them: one normal chest (the one the players want) and four trapped ones when opened (three that spawn NPCs and one that casts a disease on players).
The NPCs are indeed the ones you've mentioned and they are spawned by the spells you linked _in Classic_ (the spells are no longer in the WOTLK client). Basically, I already have a 100% DB fix for those as discussed in https://github.com/cmangos/issues/issues/468.

But before pushing it, I want to have a better view of the gate trap. They seem to be closely related. At least, it uses the same NPCs and thanks to your videos, we know now that the trap not only spawn rats, but also maggots and insects. So before pushing the crate fix, I want to ensure it won't collide with the trap gate.

Still the same question remains: how to trigger this... All videos show the same: a player enters the open gates and when he reaches the middle, they closes around him and then the NPC spawn. So, it looks like a range/on sight trigger

I already looked at the area_triggers (you can find the list in the [wiki](https://github.com/cmangos/issues/wiki/AreaTrigger.dbc)) but none of the area_triggers on the Stratholme map is located near the trap gates unfortunately.

Maybe @xfurry have seen something similar in another script?

**Comment by Phatcat** [comment]
Perhaps Blizzard handled some area_triggers server-side? It wouldn't make sense to handle this area-trigger client-side anyways given how it functions. Also it seems that a lot of stuff was handled server side in Straholme, and that Blizzard moved even more of it during TBC. Maybe this was one of those things?

It would very much seem like this trap was perhaps handled in the script; it feels very much as if it does periodic checks (which may be why you are able to skip it if you move fast enough, as well as have to wait for it a bit after you've killed all.

Would a 'custom' area_trigger in the stratholme script (one for each gate trap of course) handled periodically (with a few flags, like, a flag called 'trapTriggered1' and 2 flagged false by default and a flag called 'trapKilled1' and 2, also false by default, where you flip trapTriggered when a trap triggers, and once all the vermin has been dealt with you flip trapKilled to true and triggered to false.

That way you can have 4 active states for each trap;

TK - Where T is for 'triggered' and K is for 'killed'
00 - Trap is not triggered but can be triggered
01 - Trap is not triggered, but the spawn has been killed so don't trigger the trap if player walks through
10 - Trap is triggered but minions have not been killed 
11 - This state would maybe be kind of redundant and so would most likely just a transistion to know to open the gates again.

**Comment by cala** [comment]
Closed by https://github.com/cmangos/mangos-classic/commit/eb8bf25673d6b19c0207c16cb5f2a6fdd60cbc31
Thanks to everyone for their help, research, inputs, insights on this mysterious one! :laughing:
