### ISSUE TITLE
Nothing but the truth

### ISSUE THREAD

**Issue by TheTrueAnimal** [classicdb/database#632]
The quest description says that you have to collect this:
http://www.wowhead.com/item=6082

In reality you have to collect this:n:
http://db.vanillagaming.org/?item=6082

The item "Green Whelp Blood" isn't named correctly. The correct name would be: "Deepstrider Tumor". The item "Green Whelp Blood" does also have a wrong name at the description of the quest. It should be "Deepstrider Tumor".  The quest text should explain that you can get deepstrider tumor from deepstrider searchers and deepstrider giants in desolace. Although the text is wrong at the moment, the item gets really dropped by them.

Source: http://www.wowhead.com/quest=1383  comments

**Comment by Tobschinski** [comment]
I am sorry, but I don't get the error here.

![untitled](https://cloud.githubusercontent.com/assets/4753528/4689484/6fc99eba-56bd-11e4-85cd-caeb323201d9.png)

If I did not see the obvious, please give me a hint.

**Comment by TheTrueAnimal** [comment]
Maybe it's just an german bug.

**Comment by TheTrueAnimal** [comment]
I don't know where to post the german fix. This is it:

UPDATE `locales_quest` SET `Details_loc3` = 'Mir schwebt genau das richtige Serum vor. Es wird die Wahrheit genau so behandeln, wie die Wahrheit behandelt werden sollte.$B$BFür dieses Gebräu brauche ich mehrere Schattenpantherherzen aus dem Sumpf. Außerdem brauche ich den verzauberten Fungus des Morastlords, der dort haust. Ich bin sicher, jemand, der so tüchtig ist wie Ihr, $N, kann ihn überreden, sich von einigen zu trennen.$B$BDer schwierige Teil wird sein, einen Tiefenschreitertumor im weit entfernten Desolace zu finden. Diese Giganten werden nur selten krank und bilden Tumore.$B$BUnd jetzt fort mit Euch!', `Objectives_loc3` = 'Apotheker Faustin im Bettlerschlupfwinkel braucht 5 Schattenpantherherzen, Morastlordfungus und einen Tiefenschreitertumor.' WHERE `entry` = 1383;
UPDATE `locales_item` SET `name_loc3` = 'Tiefenschreitertumor' WHERE `entry` = 6082;
