### ISSUE TITLE
Reanimated Corpse Scholomance

### ISSUE THREAD

**Issue by TheTrueAnimal** [classicdb/database#633]
When you try to kill these npcs they should not go under 1 hp and suddenly revive with full health. Then you can really kill them.

Bug: They die just like other npcs.

NPC: http://www.wowhead.com/npc=10481 [^]
Quellen:
http://www.wowwiki.com/Reanimated_Corpse [^]
http://wowpedia.org/Reanimated_Corpse [^]
https://www.youtube.com/watch?v=CtZftE1lUPU [^](ab 5:55)

**Comment by cala** [comment]
Fixed in ACID pull request: https://github.com/ACID-Scripts/Classic/pull/12
