### ISSUE TITLE
Unstable Corpse

### ISSUE THREAD

**Issue by TheTrueAnimal** [classicdb/database#634]
The npcs should explode when they die and make damage. At the moment they don't.

NPC: http://www.wowhead.com/npc=10480
Spell: http://www.wowhead.com/spell=17689

**Comment by Tobschinski** [comment]
I'd be interested if http://www.wowhead.com/spell=17690 is used here.

**Comment by cala** [comment]
I would think that these NPCs should cast 17690 on death which would trigger 17689. But current ACID script casts 17689.

**Comment by Tobschinski** [comment]
Proc flag 0x00000028, chance = 40, charges - 0
03 Taken damage from melee strike hit
05 Taken damage by Spell that use melee weapon

I don't know, on death could be too late, on spawn too soon.

**Comment by cala** [comment]
The current AI code sounds OK. I need to test it, but that may be a core issue where offensive spells casted on NPC death can't deal damages since caster is dead.

**Comment by cala** [comment]
Very likely a core issue. Tracking the script in debug mode shows that it is indeed casted with right source and targets but no damage is done.
https://github.com/cmangos/issues/issues/429

**Comment by cala** [comment]
Tested with latest ACID: everything is fine from DB side (spell cast at the right time, with visual effect) but no damage is applied. This is a core issue. Thanks.
