### ISSUE TITLE
The Battle of Darrowshire

### ISSUE THREAD

**Issue by TheTrueAnimal** [classicdb/database#636]
After placing the item at the darrowshire town square nothing happens. Some mobs should spawn.

Quest: http://www.wowhead.com/quest=5721
Item: http://de.wowhead.com/item=15209
Videos: https://www.youtube.com/watch?v=9UxpoAyr10s
https://www.youtube.com/watch?v=hLFDJuiEtbk
https://www.youtube.com/watch?v=zW3wB-jzbvM 
(there are many "Battle of Darrowshire" videos at youtube)

**Comment by cala** [comment]
Thank you for reporting. This issue is to be handled by SD2 and is already open there: https://github.com/scriptdev2/scriptdev2-classic/issues/7 .
