### ISSUE TITLE
Loch Modan quest "Wanted: Chok'Sul" - missing reward item (ring) and MinLevel is too high

### ISSUE THREAD

**Issue by Neotmiren** [classicdb/database#64]
UPDATE `quest_template` SET `MinLevel`=15 WHERE `entry`=256 AND `MinLevel`=17 LIMIT 1;
UPDATE `quest_template` SET `RewChoiceItemId3`=1449, `RewChoiceItemCount3`=1 WHERE `entry`=256 LIMIT 1;

Source: http://questkeep.koderi.dk/printpage.php?id=766

This site declares on its main page:
"All rights reserved (c) QuestKeep Team 2004-2005"

The information is surely related to Classic, because all ogres are described as Elite. TBC trivialized much of Classic Azeroth world by converting many Elite creatures to Normal. Probaly exactly at that moment MinLevel was lowered from 15 to 9, although there is minor possibility that MinLevel was lowered some time in 2006, before TBC (the reason could be Wanted poster quest status; such quests are usually accessible at low levels; if player checked the poster and found it empty why he would check it once more, given the fact that there is no exclamation mark over "Wanted" posters in Classic client). MinLevel 9 would be much more interesting, because of reward items.

**Comment by cala** [comment]
According to the link you've provided and http://www.wowwiki.com/Quest:WANTED:_Chok%27sul?direction=next&oldid=815824 , item 1449 (Minor Channeling Ring) is rewarded to everyone. Player only have to choice between the two other items. When I look at the database, this is already that way. I assume you still did not get the item for some reason. I will test it ingame.

Regarding quest level, wowd also gives it to level 15 for accepting the quest, though 'true' quest level is 22 Elite. You are right, level 9 seems _very_ low. I don't think Wanted posters were giving you quest that soon in classic, 13 level gap sounds ridiculous. As you've mentioned, it was probably changed during TBC.

For now, I suggest the following update:

``` SQL
UPDATE `quest_template` SET `MinLevel` = 15, `QuestLevel` = 22 WHERE `entry` = 256;
```

**Comment by Neotmiren** [comment]
You are right with reward. I began to play using MangosZero repack from 2011 with old database and the Ring was definitely missing there. My patch implemented the same reward (separate from choices, of course) other way, and it reported YES (affected rows in table) after transition to CMangos so I wrongly assumed that this reward issue is not corrected in CMangos Classic.

I see the QuestLevel is already 22 in DB, so only MinLevel need to be changed.

**Comment by Neotmiren** [comment]
And now I see that even for MangosZero it was not correct - really I added it as a choice reward and forgot that.

**Comment by Neotmiren** [comment]
Tested both MangosZero and CMangos and both seems to have the same issue with what "Wanted" poster shows.

.tele Thelsamar
.quest remove 256
click at "Wanted" poster

Only Boots and Shoulders (choice) are shown. There is no Ring on poster. If quest is accepted all three are shown in Quest Log.

**Comment by cala** [comment]
Thank you for completing this issue. From what you said, it looks more like a core issue, than a DB one. If @schmoozerd shares this view, I'll close the issue here (after updating `MinLevel`) and open one in cmangos core repository.

**Comment by cala** [comment]
Note that this can also be a limitation from client and not related to core since I think gossips are handled in a different way between gameobjects and creatures.

**Comment by Schmoozerd** [comment]
Possible that in this case data is sent incorrectly to the client. also possible that this simply was a bug in classic, in which case we could not do anything about it.

Probably someone needs to examine the code before the gossip-menu changes a few years ago and now, such minor things often got backported with slight errors.

**Comment by cala** [comment]
@Schmoozerd Thank you for confirming my thoughts on this issue. I understand you are very busy right now and I appreciate that you took time to reply. See you soon.
