### ISSUE TITLE
Bat Costume

### ISSUE THREAD

**Issue by TheTrueAnimal** [classicdb/database#640]
The spell should be a buff but it's a debuff, so you can't click it away. The debuff prevents you from casting. It tells that you are silenced.

Spell: http://www.wowhead.com/spell=24733

Content Version: Classic DB version 1.4.1 'Toward the Fiery Heart'. For CMaNGOS z2525 and Scriptdev2 z2703 (update 0786_quest_template applied to mangos db)
Creature AI: ACID 1.12.x (Classic) for CMaNGOS-CLASSIC (1.12.X Client)

**Comment by cala** [comment]
Thank you for reporting. Unfortunately, this is not fixable by DB : either the DBC for this spell (and its child spell) is wrong or the core does not handle it properly. I think there is already a similar issue open in core repository. Closing here.
