### ISSUE TITLE
Hallow's End Treats for Jesper / Spoops!

### ISSUE THREAD

**Issue by TheTrueAnimal** [classicdb/database#641]
You have to collect sweets by doing different emotes to several NPCs but they do not react.

Meta-Quests:
http://www.wowhead.com/quest=8312
http://www.wowhead.com/quest=8311

Quests:
http://www.wowhead.com/quest=8353
http://www.wowhead.com/quest=8354
http://www.wowhead.com/quest=8355
http://www.wowhead.com/quest=8356
http://www.wowhead.com/quest=8357
http://www.wowhead.com/quest=8358
http://www.wowhead.com/quest=8359
http://www.wowhead.com/quest=8360

**Comment by cala** [comment]
Closed by https://github.com/cmangos/classic-db/commit/11fdf818663ed31dbb598aa6fb7aec5d25c8d8bf
