### ISSUE TITLE
The Videre Elixir

### ISSUE THREAD

**Issue by TheTrueAnimal** [classicdb/database#643]
You have to lay down an item in front of an NPC who opens a door after that. At the moment he doesn't react.

Quest: http://www.wowhead.com/quest=3909
Item: http://www.wowhead.com/item=11141
NPC: http://www.wowhead.com/npc=9467
Door: http://www.wowhead.com/object=164729

**Comment by cala** [comment]
Thank you very much. Will be tracked there from now: https://github.com/cmangos/issues/issues/2361
