### ISSUE TITLE
Campfire missing buff

### ISSUE THREAD

**Issue by TheTrueAnimal** [classicdb/database#644]
Campfires don't give a spirit buff.

http://www.wowwiki.com/Basic_Campfire
http://wowpedia.org/Campfire

Content Version: Classic DB version 1.4.1 'Toward the Fiery Heart'. For CMaNGOS z2525 and Scriptdev2 z2703 (update 0786_quest_template applied to mangos db)
Creature AI: ACID 1.12.x (Classic) for CMaNGOS-CLASSIC (1.12.X Client)

**Comment by cala** [comment]
Thanks for reporting. This is a core issue. A pull request was already open here: https://github.com/cmangos/mangos-classic/pull/103
