### ISSUE TITLE
Forlorn Spirit

### ISSUE THREAD

**Issue by TheTrueAnimal** [classicdb/database#645]
The ghost should be hostile. It's neutral at the moment.

NPC: http://www.wowhead.com/npc=2044

Sources: 
http://www.wowhead.com/quest=67
https://web.archive.org/web/20060107190512/http://wow.allakhazam.com/db/quest.html?wquest=67

Content Version: Classic DB version 1.4.1 'Toward the Fiery Heart'. For CMaNGOS z2525 and Scriptdev2 z2703 (update 0786_quest_template applied to mangos db)
Creature AI: ACID 1.12.x (Classic) for CMaNGOS-CLASSIC (1.12.X Client)

**Comment by cala** [comment]
Wowhead is wrong on this matter. The forlorn spirit uses its own faction which is neutral to players.

It is forced by script to attack players completing the quest and only those. So, unless the script is no longer working, I close this issue. Thank you.

**Comment by ghost** [comment]
@cala I really beg you, take a look at this thread, http://cmangos.net/thread-6615-post-42435.html#pid42435 31 and 32 post. And then all are silent. And these two opening event could help. I have an idea to create a new table creature_ai_movepoint(special for POINT_MOTION_TYPE. 
@xfurry in thread https://github.com/cmangos/issues/issues/427
Said there is a dbscripts_on_creature_movement, But db script can only work with WAYPOINT_MOTION_TYPE. I did not know what to say.
Thanks advance.
It's time to EventAI already become independent from SD2.

**Comment by cala** [comment]
@Ulduar I don't see how this is related to the current issue, especially as I'm not working on EventAI code. Regarding NPC 2044, everything can be handled finely and easily with DBscripts.

**Comment by ghost** [comment]
Okay, I've realized that the wrong address. Thanks and at this. Well, it'll hack. Me have left no other choice.
