### ISSUE TITLE
Incorrect Quest Text for Beached Sea Creature/Beached Sea Turtle Quests

### ISSUE THREAD

**Issue by Galatean** [classicdb/database#647]
These quests are all in Darkshore.

Basically, the texts when interacting with the dead sea beasties in question is swapped around between quests 4722, 4723, 4725, 4727, 4728, 4730, 4731, 4732, and 4733.

The end result is that one of the sea turtles mentions a wheelbarrow, when the wheelbarrow sea creature is very much not a turtle. Another one mentions having some form of transport on its shell when the model its attached to isn't one with the wooden structures on its back.

**Comment by ghost** [comment]
I did my best to try and get the gameobjects to offer the correct quest as correctly on retail as I could, but feel free to double check for me.

UPDATE `gameobject_questrelation` SET `quest` = '4728' WHERE `id` = '175226';
UPDATE `gameobject_questrelation` SET `quest` = '4730' WHERE `id` = '175227';
UPDATE `gameobject_questrelation` SET `quest` = '4722' WHERE `id` = '176190';
UPDATE `gameobject_questrelation` SET `quest` = '4732' WHERE `id` = '176191';
UPDATE `gameobject_questrelation` SET `quest` = '4727' WHERE `id` = '176196';
UPDATE `gameobject_questrelation` SET `quest` = '4725' WHERE `id` = '176197';
UPDATE `gameobject_questrelation` SET `quest` = '4731' WHERE `id` = '176198';
UPDATE `gameobject_questrelation` SET `quest` = '4733' WHERE `id` = '175230';
UPDATE `gameobject_questrelation` SET `quest` = '4723' WHERE `id` = '175233';

_Updated: Noticed I made a mistake on a gameobject/quest last night. (11-10-14 @ 9:11 AM)_
