### ISSUE TITLE
Strength of Isha Awak - Spell 5325

### ISSUE THREAD

**Issue by TheTrueAnimal** [classicdb/database#648]
You get should get this buff as reward of a quest and in comparison with the database you get it but nothing happens.

Quest: http://www.wowhead.com/quest=873
Spell: http://www.wowhead.com/spell=5325

Mangos Zero. 
@cala Already reportet here: https://github.com/cmangos/issues/issues/482#issuecomment-60568513

**Comment by ghost** [comment]
It actually does "something", it gives you 2 spirit (hidden aura).

Now wowhead referring to retail does state that it also give's spirit when it says it should be giving stamina. So which is more logical, when blizzard implemented this aura did they simply picked the wrong stat to apply, or was the description a typo as it can be common?

~Wowhead Information~
Effect  Apply Aura: Mod Stat (Spirit)
Value: 2

**Comment by Phatcat** [comment]
> Id: 5325
> Name: Strength of Isha Awak (Rank 1)
> Description: Increases the Stamina of the target by $s1 for $d.
> General info
> Category = 99, SpellIconId = 47, ActiveIconId = 0, SpellVisual = (297, 0)
> SpellFamilyName = SPELLFAMILY_GENERAL, SpellFamilyFlags = 0x0000000000000000
> SpellSchool = 3 (SPELL_SCHOOL_NATURE)
> DamageClass = 1 (SPELL_DAMAGE_CLASS_MAGIC)
> PreventionType = 1 (SPELL_PREVENTION_TYPE_SILENCE)
> Attributes
> Attributes: 0x08000080 (SPELL_ATTR_UNK7, SPELL_ATTR_CASTABLE_WHILE_SITTING)
> Advanced info
> Spell Level = 10, BaseLevel 0, MaxLevel 0, MaxTargetLevel 0
> Category = 99
> DispelType = 1 (DISPEL_MAGIC)
> Mechanic = 0 (MECHANIC_NONE)
> SpellRange (Id 4) "Medium Range"
> MinRange = 0
> MaxRange = 30
> CastingTime (Id 1) = 0.00
> RecoveryTime: 0 ms, CategoryRecoveryTime: 1000 ms
> StartRecoveryCategory = 0, StartRecoveryTime = 0.00 ms
> Duration: ID (30) 1800000, 0, 1800000
> Interrupt Flags: 0x00000009, AuraIF 0x00000000, ChannelIF 0x00000000
> Chance = 101, charges - 0
> Effects
> Effect 0:
> Id: 6 (SPELL_EFFECT_APPLY_AURA)
> BasePoints = 2
> Targets (21, 0) (TARGET_SINGLE_FRIEND, NO_TARGET)
> Aura Id 29 (SPELL_AURA_MOD_STAT), value = 2, misc = 4 (UNIT_MOD_STAT_SPIRIT), periodic = 0
> Effect 1:
> NO EFFECT
> Effect 2:
> NO EFFECT

## 

> Description: Increases the Stamina of the target by $s1 for $d.
> (...)
> Aura Id 29 (SPELL_AURA_MOD_STAT), value = 2, misc = 4 (UNIT_MOD_STAT_SPIRIT), periodic = 0

So what do we do about this? - we got conflicting info here; how will we ever get the correct answer for this?

**Comment by Tobschinski** [comment]
Nothing, even Blizzard does mistakes.

**Comment by Phatcat** [comment]
Yeah, it very much seems like a mistake on Blizzards side, Old thottbott thinks so as well: https://web.archive.org/web/20071112103155/http://thottbot.com/s5325
Should we not just close this issue then, maybe?

**Comment by Tobschinski** [comment]
Your will, my hands.

**Comment by Phatcat** [comment]
Hah, I just thought I'd help a bit with cleanup; this is one of those very issues that could be left open for eternity as we can do nothing about this without making an either or decision, and we will never get an answer from Blizzard which was supposed to be the right stat.

**Comment by Lumber-Jack-2** [comment]
you can ask in then offical forum for it (some time ago they even gave me information about the battle for the undercity stuff)

**Comment by Phatcat** [comment]
You serious? Now that I do not understand why they'd ever do that..

**Comment by Lumber-Jack-2** [comment]
you need an active retail account in order to post in the forum - that's why :D

**Comment by Phatcat** [comment]
Okay so I posted in the forum and they just straight up deleted my post without answering...  I should have maybe asked a bit more subtly than I did, but I doubt they would have given me a useful answer anyway, especially if the spell no longer exists in the game (does it?)

**Comment by Lumber-Jack-2** [comment]
you are not allowed to refer to any privat server xD

you can ask it like : 

"and friend and me are guessing that spell xy should work like x and i think it had worked like y back in the days in vanilla. could you give me a clear answer how it was?"

**Comment by Phatcat** [comment]
Oh, I did not refer to private servers or reverse engineering, but they just seem to have deleted my post anyways. I just said it had conflicting data on sites like wowhead and the like and I was curious as to what was the right answer. Guess they don't even support the sniffing these db sites did back in the day.
