### ISSUE TITLE
Brambleweed Leggings should be personal loot from NPC Boahn

### ISSUE THREAD

**Issue by Neotmiren** [classicdb/database#65]
Currently this item is a world drop via reference_loot_template, but it only should be dropped by NPC Boahn (in the caves outside Wailing Caverns instance).

http://www.wowwiki.com/Brambleweed_Leggings?oldid=691064
http://www.wowhead.com/item=5422

Another item that drops from NPC Boahn is "Boahn's Fang". It drops directly from him and does not present in reference_loot_template TABLE. This is correct.

**Comment by cala** [comment]
Thank you for reporting. I'll fix this today.

**Comment by Neotmiren** [comment]
And thank you for all your work on ClassicDB.

**Comment by cala** [comment]
My pleasure! :)
