### ISSUE TITLE
Shellfish Trap

### ISSUE THREAD

**Issue by TheTrueAnimal** [classicdb/database#650]
When clicking on them one of these two things should happen:
- you get an item (works)
- a creature spawns and attacks you (does not work)

GOB: http://www.wowhead.com/object=176582
NPC: http://www.wowhead.com/npc=11562

Sources: 
https://web.archive.org/web/20060313064114/http://wow.allakhazam.com/db/quest.html?wquest=5386
http://www.wowhead.com/quest=5421#english-comments
https://web.archive.org/web/20060515025218/http://wow.allakhazam.com/db/quest.html?wquest=5421
http://www.wowhead.com/object=176582#english-comments

**Comment by cala** [comment]
There are two kinds of GO here:
176635 that is a trap spawning the hostile NPC and wielding no loot
176582 that is the chest-like object with loot in it (and it spawns nothing)

Both are now working correctly and are spawned in world. Closing this, now.
