### ISSUE TITLE
Sand Sharks not spawned

### ISSUE THREAD

**Issue by TheTrueAnimal** [classicdb/database#651]
Sand Sharks are not spawned.

http://www.wowhead.com/npc=5435/sand-shark
https://web.archive.org/web/20070527004201/http://wow.allakhazam.com/db/mob.html?wmob=5435

Content Version: Classic DB version 1.4.1 'Toward the Fiery Heart'. For CMaNGOS z2525 and Scriptdev2 z2703 (update 0786_quest_template applied to mangos db)
Creature AI: ACID 1.12.x (Classic) for CMaNGOS-CLASSIC (1.12.X Client)

**Comment by Tobschinski** [comment]
I got you some sharks, please go out and play with them! I don't know if I got all of them though.
