### ISSUE TITLE
Old Treasure Chest is empty

### ISSUE THREAD

**Issue by TheTrueAnimal** [classicdb/database#652]
The Old Treasure Chest in Scholomance doesn't drop anything.
http://www.wowhead.com/object=176944

Content Version: Classic DB version 1.4.1 'Toward the Fiery Heart'. For CMaNGOS z2525 and Scriptdev2 z2703 (update 0786_quest_template applied to mangos db)
Creature AI: ACID 1.12.x (Classic) for CMaNGOS-CLASSIC (1.12.X Client)

**Comment by ghost** [comment]
From what I can tell (on current build) it does contain items, but there is a chance to get nothing as well.

**Comment by Metalica** [comment]
I tested out and there are items in chest's.

**Comment by cala** [comment]
Tested and working: there are 84 items lootable inside the chest ranking from 0.5 to 6% drop chance. So there is a chance that you don't get any item, but there is also a chance that you get 16 of them (max number of items the core can generate).
Closing the issue, thank you everyone.
