### ISSUE TITLE
Hive'Ashi Drone 

### ISSUE THREAD

**Issue by TheTrueAnimal** [classicdb/database#653]
When tortured druids and sentinels die two hive'ashi drones should spawn. I'm not sure if it is possible that they spawn with a chance of 75%. At the moment they don't spawn.
Drone: http://www.wowhead.com/npc=13136
Druid: http://www.wowhead.com/npc=12178
Sentinel: http://www.wowhead.com/npc=12179

Similar and working correctly:
http://www.wowhead.com/npc=10383 spawns if http://www.wowhead.com/npc=10381 dies.

Mangos Zero.

**Comment by Metalica** [comment]
Fix for Druid.

UPDATE `db`.`creature_ai_scripts` SET `id`='1038191', `creature_id`='12178', `event_type`='6', `event_inverse_phase_mask`='0', `event_chance`='100', `event_flags`='0', `event_param1`='0', `event_param2`='0', `event_param3`='0', `event_param4`='0', `action1_type`='11', `action1_param1`='21327', `action1_param2`='0', `action1_param3`='7', `action2_type`='1', `action2_param1`='-1321', `action2_param2`='0', `action2_param3`='0', `action3_type`='0', `action3_param1`='0', `action3_param2`='0', `action3_param3`='0', `comment`='Tortured Druid - Summon Hive\'Ashi Drone and Emote on Death' WHERE (`id`='1038191');

UPDATE `db`.`creature_ai_texts` SET `entry`='-1321', `content_default`='Tortured Druid\'s death cry has stirred the nearby silithid hive', `content_loc1`=NULL, `content_loc2`=NULL, `content_loc3`=NULL, `content_loc4`=NULL, `content_loc5`=NULL, `content_loc6`=NULL, `content_loc7`=NULL, `content_loc8`=NULL, `sound`='0', `type`='2', `language`='0', `emote`='0', `comment`='Tortured Druid death' WHERE (`entry`='-1321');

UPDATE `creature_template` SET `AIName`='EventAI' WHERE (`Entry`='12178')

 Fix for Sentinel:

INSERT INTO `creature_ai_texts` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `sound`, `type`, `language`, `emote`, `comment`) VALUES ('-1322', 'Tortured Sentinel\'s death cry has stirred the nearby silithid hive', '', '', '', '', '', '', '', '', '0', '2', '0', '0', 'Tortured Sentinel death')

UPDATE `db`.`creature_ai_scripts` SET `id`='1038192', `creature_id`='12179', `event_type`='6', `event_inverse_phase_mask`='0', `event_chance`='100', `event_flags`='0', `event_param1`='0', `event_param2`='0', `event_param3`='0', `event_param4`='0', `action1_type`='11', `action1_param1`='21327', `action1_param2`='0', `action1_param3`='7', `action2_type`='1', `action2_param1`='-1322', `action2_param2`='0', `action2_param3`='0', `action3_type`='0', `action3_param1`='0', `action3_param2`='0', `action3_param3`='0', `comment`='Tortured Sentinel - Summon Hive\'Ashi Drone and Emote on Death' WHERE (`id`='1038192');

UPDATE `creature_template` SET `AIName`='EventAI' WHERE (`Entry`='12179')

 @cala 

 If some fine tunning is to be made. Go on :)

**Comment by cala** [comment]
Thank you everyone of you for your contribution. A pull request has been made to ACID: https://github.com/ACID-Scripts/Classic/pull/8
I'm closing the issue here.
