### ISSUE TITLE
Resistances on low level mobs

### ISSUE THREAD

**Issue by 249CAAFE40** [classicdb/database#656]
Kobolds (NPC 40, 475, 476, 1236 and 4111) have fire resistance. I cannot find a source saying they shouldn't, but it seems wrong given that they are low level mobs and made them difficult to kill on my mage in elwynn forest.

For that matter, there seems to be a lot of low level mobs that have resistances in the db. Can list them with this query

select entry, name, resistancefire, resistancefrost, resistancenature, resistanceshadow, resistanceholy, resistancearcane, minlevel, maxlevel from creature_template where (resistancefire > 0 or resistancefrost > 0 or resistanceholy > 0 or resistancenature > 0 or resistancearcane > 0 or resistanceshadow > 0) and maxlevel < 30;

Some of those i recognize as elites or rares which makes sense, but common mobs? Where is the source for this info.

**Comment by cala** [comment]
> Where is the source for this info.

We have no more source stating this info is wrong than source stating it is right.

I agree these resistances are weird, especially on common mobs but without more infos on this, I prefer let the DB untouched.

**Comment by 249CAAFE40** [comment]
Here's all the info I was able to find. Resistances seem to follow themes where certain types of mobs have resistances to certain types of magic, in general. But how the exact values were ever determined I have no idea.

wowhead commments:

http://www.wowhead.com/npc=6073/searing-infernal#comments - Despite their name, these guys don't have any fire-based attacks, and their swings cause physical damage. However, they seem to be resistant to most forms of magic, including frost, fire (they're immune), and shadow damage. They are also immune to Fear. These guys have weakness for Arcane Magic, or at least for Arcane Explosion (Rank 1 gives about 70 dmg per hit)

http://www.wowhead.com/npc=10202/azurous#comments - Blue dragons in general are highly resistant to magic of all schools. Rare elites are often immune to slowing effects.

http://www.wowhead.com/npc=10363/general-drakkisath#comments - General Drakkisath comes with two Elite Adds. Take note that the adds have high magic resistance due to them being of the chromatic flight.

http://www.wowhead.com/npc=6109/azuregos#comments - he is IMMUNE to ARCANE dmg.

wowpedia:

Mobs known to have base Resistance

Although Spell Resistance was removed from players in Patch 5.0.4, it was not removed from NPCs. A very few mobs in the game have a base Resistance to one or more spell schools.

Note that this is an incomplete list, and always will be, since few mobs have Resistance and tools to gather this data are either rare or nonexistent.

```
Doomwarder (level 35-36 in Mannoroc Coven): Fire Resistance
Suffering Highborne (level 51-52 in Winterspring): Arcane Resistance
Ice Thistle yetis (level 51-52 in Winterspring): Frost Resistance
```

**Comment by ghost** [comment]
All resistance values for monster as for patch 1.0 is available in one of the Brady Games Strategy books. There are clear templates to how resistances works for cases like dragonflight and elementals, which should be able to be found through bruteforcing them via retail.

**Comment by Tobschinski** [comment]
As a first proposal, I am going to remove any resistances to holy damage, these should have been removed from the game at some point during the beta.

**Comment by X-Savior** [comment]
I am helping Tobi on this also.

We need to remove Holy and also we will remove ALL resistances and then I will import all Resistances from Bestiary book (as should be same for TBC and Classic) and then we will see where we are at.

**Comment by 249CAAFE40** [comment]
I took a look at the book, and it seems fairly complete, but missing dungeon bosses. For example, Ragnaros is not listed as having any fire resistance or negative frost resistance. Non-dungeon bosses do not seem to be listed, i.e. I can't find any reference to Azuregos. There's also some disagreement between the book and wowhead comments, i.e. the book does not list searing infernals as having any frost resistance or arcane weakness. Still, it's certainly better than what we have now, and bosses are small enough in number to do manually.

**Comment by X-Savior** [comment]
I agree... I mean we need to start somewhere.

**Comment by Tobschinski** [comment]
Well, Ragnaros (and other elementals) should be immune to fire damage (their own element), not resistant. That are different things.

**Comment by 249CAAFE40** [comment]
True, but the book does list immunities as well for mobs like evolving ectoplasm. And Ragnaros should still be listed as having a negative frost resistance. Also, not every elemental is immune to their own element, e.g. molten core Firelord elementals are only listed as having -93 frost resist, but Lava Surgers are listed as having 93 fire and 93 nature resist.

**Comment by Tobschinski** [comment]
I'm sure there are existing exceptions. But how do you certainly know that Ragnaros should be vulnerable to frost damage?

**Comment by 249CAAFE40** [comment]
http://www.wowhead.com/npc=11502#comments

By eddm (2,190 – 6·18) on 2011/09/06 (Patch 4.2.2)  
It appears he's no longer immune to fire, did this today as an Enhancement Shaman, and recount shows no damage resisted, my previous times here, my lava lash and flame shock had been useless, but they seem to do full damage now. I don't recall seeing it in any patch notes though.

eddm on 2011/09/06 (Patch 4.2.2)
It also may be worth noting that he DOES still have negative frost resistance.

and elitist jerks http://forums.elitistjerks.com/topic/6635-frost-mage-spreadsheet/?p=145149

Not all mobs in MC are level 63, though. Also, a bunch of those mobs have negative Frost resist, like Firelords, Fire Spawns and Ragnaros.

**Comment by cala** [comment]
Fire resistance for these NPCs is now fixed. Closing then.
