### ISSUE TITLE
Duplicate Creature GUID 1882

### ISSUE THREAD

**Issue by 249CAAFE40** [classicdb/database#659]
Creature with guid 1882 shows up as an elemental in ironforge with the label of midsummer bonfire. In addition to having the wrong model, it appears to be a duplicate of creature 94910. All of these creatures have the same model, which isn't a bonfire, but I'm not sure why this one would even be showing up since it's not midsummer right now. Suggest removing it.

**Comment by Swater96** [comment]
Make sure GM mode is off, those shouldn't be visible for normal players. I agree that we should have a game event npc clean-up. I'm working on proper database support for the Elemental Invasion but I could work on other events too.

I've noticed some TBC event creatures and objects in the DB as well, this should be taken care of.

**Comment by ghost** [comment]
I can confirm those are constantly spawned. I think they should be tied to an event and only spawn during specific limited occasions.
