### ISSUE TITLE
Quest: A Rogues Deal

### ISSUE THREAD

**Issue by scotty0100** [classicdb/database#66]
Once you accept the second part of this quest from Calvin Montague where you have to kill him, the nearby Deathguard Elites assist you in killing him which shouldn't happen.

I noticed Calvin Montague's faction was 68 (Undercity), and the two Deathguard Elites nearby are 71 (Undercity) also.

Would changing Calvin's faction to 71 fix it?

**Comment by cala** [comment]
Thank you for this report. Updating faction would be my first guess but flags should be looked at also. This quest is more than probably handled by SD2 so there is something to look there also.

**Comment by cala** [comment]
After peering at SD2, changing Calvin's faction in DB will not work as SD2 assigns a new faction to him during the quest. I know of another quest doing the same and with no guards engaging combat. We should try to change Calvin's flags:

``` SQL
UPDATE `creature_template` SET `unit_flags` =  33536 WHERE `entry` = 6784;
```

**Comment by cala** [comment]
Added comments by @Tobschinski

> - nearby guards shouldn't assist you (if they defeat Calvin, which will most likely be the case, you will not be able to complete the quest)
> - it takes a long time to recognize the defeat of Calvin
> - Calvin does not use his rude emote after being defeated
