### ISSUE TITLE
Ironforge - Sognar Cliffbeard - missing equipment

### ISSUE THREAD

**Issue by Tobschinski** [classicdb/database#660]
[Sognar Cliffbeard](http://www.wowhead.com/npc=5124) in Ironforge should carry [Monster - Item, Mutton](http://www.wowhead.com/item=2196) (if I am not mistaken)

**Comment by Grz3s** [comment]
UPDATE creature_template SET EquipmentTemplateId = 85 WHERE entry = 5124;

**Comment by cala** [comment]
I was convinced to have already fixed this. Growing old does me no good. :/
I will push the fix soon.
