### ISSUE TITLE
Atiesh, Greatstaff of the Guardian - Karazhan Portal

### ISSUE THREAD

**Issue by ghost** [classicdb/database#664]
Currently there is no data in the database containing the gameobject for portal nor spell target position. Now I have not looked into this, and just assuming that this did exist during vanilla and was not just prep work from blizz to be added in TBC. As for the model of the portal I used, I used the Undercity model as I didn't not find one for Karazhan in the vanilla mpq's. But I am sure that at a later expansion (no clue to which xpac) there is one made for Karazhan. In any case here is code to have a working portal be created and clickable which teleports you in front of Karazhan (location based off videos I found but expansion is questionable in the videos).

INSERT INTO `gameobject_template` (`entry`, `type`, `displayId`, `name`, `faction`, `flags`, `size`, `data0`, `data1`, `data2`, `data3`, `data4`, `data5`, `data6`, `data7`, `data8`, `data9`, `data10`, `data11`, `data12`, `data13`, `data14`, `data15`, `data16`, `data17`, `data18`, `data19`, `data20`, `data21`, `data22`, `data23`, `mingold`, `maxgold`, `ScriptName`) VALUES (181146, 22, 4398, 'Portal to Karazhan', 115, 0, 1, 28147, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '');

INSERT INTO `spell_target_position` (`id`, `target_map`, `target_position_x`, `target_position_y`, `target_position_z`, `target_orientation`) VALUES (28147, 0, -11123.2, -2014.42, 47.09, 0.706859);

**Comment by evil-at-wow** [comment]
If I'm not mistaken, the portal is in TBC-DB and works. So if you need the data, you can have a look at TBC-DB.
