### ISSUE TITLE
Twilight Tablet Fragment

### ISSUE THREAD

**Issue by TheTrueAnimal** [classicdb/database#665]
You should get the item only by using gameobjects. Not by looting creatures.
Item: http://www.wowhead.com/item=20378

Comments:
http://wowdata.buffed.de/item/Quest/Zwielichtschrifttafelfragment-20378#comments
http://www.wowhead.com/item=20378#comments

Deletes item 20378 from all creatureloottemplates
DELETE FROM `creature_loot_template` WHERE `item` = 20378; 

Content Version: Classic DB version 1.4.1 'Toward the Fiery Heart'. For CMaNGOS z2525 and Scriptdev2 z2703 (update 0786_quest_template applied to mangos db)
Creature AI: ACID 1.12.x (Classic) for CMaNGOS-CLASSIC (1.12.X Client)

**Comment by Tobschinski** [comment]
Hello,
the comments on [wowhead.com](http://www.wowhead.com/item=20378#comments) state otherwise. Would you please look at it again?

**Comment by TheTrueAnimal** [comment]
Die liegen am Boden rum bei 24:11 und Umgebung, das sind keine drops, also wartet nicht vergeblich ^^  (translation: they're lying on the ground at 24:11 and around there, they're not dropped, don't wait forever for that to happen)

https://web.archive.org/web/20071027175846/http://wow.allakhazam.com/db/quest.html?wquest=8284

It seems like getting dropped by elementals is a bug that emerges with patch 3.3.5. Only the new source tells that.
(I'm really sorry for my bad englisch.)

**Comment by Tobschinski** [comment]
http://web.archive.org/web/20070315154609/http://www.thottbot.com/i20378
https://web.archive.org/web/20060720204038/http://wow.allakhazam.com/db/mob.html?wmob=11746

The fragments are listed as drops here.

**Comment by Tobschinski** [comment]
Still not sure if I should do something here.

**Comment by cala** [comment]
In my opinion, drop chance should be kept for the 3 NPCs having it. We have sources saying they should drop it though with a low rate.
However, the current drop chance in the DB is 100% (while being on the quest). It should be cut down to 5% to reflect percentages seen on archive website linked above (they say 1%, but they do not distinguish quest drop from normal drop, so 5% sounds good to me).
