### ISSUE TITLE
Bell of Dethmoora wrong german questtext

### ISSUE THREAD

**Issue by TheTrueAnimal** [classicdb/database#667]
The german text tells you to get 2 Elixir of Shadow Power instead of 10.
http://www.wowhead.com/quest=7626

UPDATE `locales_quest` SET `Objectives_loc3` = 'Bringt 10 Elixiere der Schattenmacht zu Gorzeeki Wildaug in die brennende Steppe.' WHERE `entry` = 7626;

**Comment by Metalica** [comment]
I don't think ClassicDB is in german. No offence meant offcourse.

**Comment by cala** [comment]
Metalica is right. Classic DB is a generic DB, local tables are not supported (and not even present in the repository). I suggest you contact someone from GMDB, assuming the project is still supported.
