### ISSUE TITLE
Quest: Hidden Enemies (5729)

### ISSUE THREAD

**Issue by scotty0100** [classicdb/database#67]
Quest: Hidden Enemies (5729) is bugged; once you accept it from Thrall it asks you to talk with Neeru Fireblade (3216), Neeru offers no gossip to finish this quest.

**Comment by cala** [comment]
Thank you. I'll look into it.

**Comment by cala** [comment]
Could you please try:

``` SQL
UPDATE `creature_template` SET `gossip_menu_id` = 3701 WHERE `entry` = 3216;
```

Relaunch server and tell me if quest can be completed.
