### ISSUE TITLE
Twilight Marauder & Morna bugs and fixes

### ISSUE THREAD

**Issue by Metalica** [classicdb/database#671]
Problems:
- Twilight Marauder and Morna dont dissmount once they are agrroed.
- Twilight Marauder has same skin as Morna, which is incorrect. Correct skin is: http://wow.zamimg.com/uploads/screenshots/normal/51417.jpg

Twilight Marauder skill Fixes:

UPDATE `creature_template` SET `AIName`='EventAI' WHERE (`Entry`='15542')

INSERT INTO `db`.`creature_ai_scripts` (`id`, `creature_id`, `event_type`, `event_inverse_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action1_type`, `action1_param1`, `action1_param2`, `action1_param3`, `action2_type`, `action2_param1`, `action2_param2`, `action2_param3`, `action3_type`, `action3_param1`, `action3_param2`, `action3_param3`, `comment`) VALUES ('1273790', '15542', '0', '0', '100', '1', '9000', '15000', '14000', '18000', '11', '23600', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', 'Twilight Marauder - Cast Piercing Howl');

INSERT INTO `db`.`creature_ai_scripts` (`id`, `creature_id`, `event_type`, `event_inverse_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action1_type`, `action1_param1`, `action1_param2`, `action1_param3`, `action2_type`, `action2_param1`, `action2_param2`, `action2_param3`, `action3_type`, `action3_param1`, `action3_param2`, `action3_param3`, `comment`) VALUES ('1273791', '15542', '2', '0', '100', '0', '30', '0', '0', '0', '11', '8599', '0', '1', '1', '-46', '0', '0', '0', '0', '0', '0', 'Twilight Marauder - Cast Enrage at 30% HP');

INSERT INTO `db`.`creature_ai_scripts` (`id`, `creature_id`, `event_type`, `event_inverse_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action1_type`, `action1_param1`, `action1_param2`, `action1_param3`, `action2_type`, `action2_param1`, `action2_param2`, `action2_param3`, `action3_type`, `action3_param1`, `action3_param2`, `action3_param3`, `comment`) VALUES ('1273792', '15542', '4', '0', '100', '2', '0', '0', '0', '0', '11', '22911', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', 'Twilight Marauder - Cast Charge on Aggro');

Twilight Marauder Morna Fixes:

UPDATE `creature_template` SET `AIName`='EventAI' WHERE (`Entry`='15541')

INSERT INTO `db`.`creature_ai_scripts` (`id`, `creature_id`, `event_type`, `event_inverse_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action1_type`, `action1_param1`, `action1_param2`, `action1_param3`, `action2_type`, `action2_param1`, `action2_param2`, `action2_param3`, `action3_type`, `action3_param1`, `action3_param2`, `action3_param3`, `comment`) VALUES ('1048991', '15541', '9', '5', '100', '1', '0', '5', '5000', '9000', '11', '15572', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', 'Twilight Marauder Morna - Cast Sunder Armor (Phase 1)');

INSERT INTO `db`.`creature_ai_scripts` (`id`, `creature_id`, `event_type`, `event_inverse_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action1_type`, `action1_param1`, `action1_param2`, `action1_param3`, `action2_type`, `action2_param1`, `action2_param2`, `action2_param3`, `action3_type`, `action3_param1`, `action3_param2`, `action3_param3`, `comment`) VALUES ('1048994', '15541', '9', '0', '100', '1', '0', '5', '9000', '14000', '11', '16856', '1', '1', '0', '0', '0', '0', '0', '0', '0', '0', 'Twilight Marauder Morna - Cast Mortal Strike');

INSERT INTO `db`.`creature_ai_scripts` (`id`, `creature_id`, `event_type`, `event_inverse_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action1_type`, `action1_param1`, `action1_param2`, `action1_param3`, `action2_type`, `action2_param1`, `action2_param2`, `action2_param3`, `action3_type`, `action3_param1`, `action3_param2`, `action3_param3`, `comment`) VALUES ('1048995', '15541', '0', '0', '100', '1', '9000', '15000', '14000', '18000', '11', '23600', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', 'Twilight Marauder Morna - Cast Piercing Howl');

INSERT INTO `db`.`creature_ai_scripts` (`id`, `creature_id`, `event_type`, `event_inverse_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action1_type`, `action1_param1`, `action1_param2`, `action1_param3`, `action2_type`, `action2_param1`, `action2_param2`, `action2_param3`, `action3_type`, `action3_param1`, `action3_param2`, `action3_param3`, `comment`) VALUES ('1048992', '15541', '24', '5', '100', '1', '15572', '5', '5000', '5000', '22', '2', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 'Twilight Marauder Morna - Set Phase 2 on Target Max Sunder Armor Aura Stack (Phase 1)');

INSERT INTO `db`.`creature_ai_scripts` (`id`, `creature_id`, `event_type`, `event_inverse_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action1_type`, `action1_param1`, `action1_param2`, `action1_param3`, `action2_type`, `action2_param1`, `action2_param2`, `action2_param3`, `action3_type`, `action3_param1`, `action3_param2`, `action3_param3`, `comment`) VALUES ('1048993', '15541', '28', '3', '100', '1', '15572', '1', '5000', '5000', '22', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 'Twilight Marauder Morna - Set Phase 1 on Target Missing Sunder Armor Aura Stack (Phase 2)');

**Comment by Swater96** [comment]
Getting syntax errors on this too :(

**Comment by Swater96** [comment]
Okay, to fix this one, add a ; to the end of the first two update query's

**Comment by cala** [comment]
The AI scripts part will be pushed to ACID repository within the day.
Thanks to all involved.
