### ISSUE TITLE
Prince Thunderaan fix

### ISSUE THREAD

**Issue by Metalica** [classicdb/database#673]
Fixes:
- Added 2 missing skills.
- Added missing say text on spawn.
  
  Reference for say text on spawn: http://www.wowwiki.com/Prince_Thunderaan

UPDATE `creature_template` SET `AIName`='EventAI' WHERE (`Entry`='14435')

INSERT INTO `db`.`creature_ai_texts` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `sound`, `type`, `language`, `emote`, `comment`) VALUES ('-1323', 'My power is discombobulatingly devastating! It is ludicrous that these mortals even attempt to enter my realm! ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '0', '0', '0', 'Prince Thunderaan');

UPDATE `db`.`creature_ai_scripts` SET `id`='1526091', `creature_id`='14435', `event_type`='0', `event_inverse_phase_mask`='0', `event_chance`='100', `event_flags`='1', `event_param1`='3000', `event_param2`='3000', `event_param3`='5000', `event_param4`='5000', `action1_type`='11', `action1_param1`='23011', `action1_param2`='4', `action1_param3`='0', `action2_type`='0', `action2_param1`='0', `action2_param2`='0', `action2_param3`='0', `action3_type`='0', `action3_param1`='0', `action3_param2`='0', `action3_param3`='0', `comment`='Prince Thunderaan - Cast Tears of the Wind Seeker' WHERE (`id`='1526091');

UPDATE `db`.`creature_ai_scripts` SET `id`='1526092', `creature_id`='14435', `event_type`='0', `event_inverse_phase_mask`='0', `event_chance`='100', `event_flags`='1', `event_param1`='9000', `event_param2`='13000', `event_param3`='16000', `event_param4`='20000', `action1_type`='11', `action1_param1`='23009', `action1_param2`='0', `action1_param3`='1', `action2_type`='0', `action2_param1`='0', `action2_param2`='0', `action2_param3`='0', `action3_type`='0', `action3_param1`='0', `action3_param2`='0', `action3_param3`='0', `comment`='Prince Thunderaan - Cast Tendrils of Air' WHERE (`id`='1526092');

UPDATE `db`.`creature_ai_scripts` SET `id`='1526093', `creature_id`='14435', `event_type`='1', `event_inverse_phase_mask`='0', `event_chance`='100', `event_flags`='0', `event_param1`='1000', `event_param2`='1000', `event_param3`='0', `event_param4`='0', `action1_type`='1', `action1_param1`='-1323', `action1_param2`='0', `action1_param3`='0', `action2_type`='0', `action2_param1`='0', `action2_param2`='0', `action2_param3`='0', `action3_type`='0', `action3_param1`='0', `action3_param2`='0', `action3_param3`='0', `comment`='Prince Thunderaan - Say on Spawn' WHERE (`id`='1526093');

**Comment by Swater96** [comment]
Tried to test this and I get a syntax error.

[SQL] UPDATE creature_template SET AIName='EventAI' WHERE (Entry='14435')

INSERT INTO creature_ai_texts (entry, content_default, content_loc1, content_loc2, content_loc3, content_loc4, content_loc5, content_loc6, content_loc7, content_loc8, sound, type, language, emote, comment) VALUES ('-1323', 'My power is discombobulatingly devastating! It is ludicrous that these mortals even attempt to enter my realm! ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '0', '0', '0', 'Prince Thunderaan');
[Err] 1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'INSERT INTO creature_ai_texts (entry, content_default, content_loc1, content_loc' at line 3

**Comment by Metalica** [comment]
After trying to update, i get: 

 INSERT INTO creature_ai_scripts (id, creature_id, event_type, event_inverse_phase_mask, event_chance, event_flags, event_param1, event_param2, event_param3, event_param4, action1_type, action1_param1, action1_param2, action1_param3, action2_type, action2_param1, action2_param2, action2_param3, action3_type, action3_param1, action3_param2, action3_param3, comment) VALUES ('1048992', '15541', '24', '5', '100', '1', '15572', '5', '5000', '5000', '22', '2', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 'Twilight Marauder Morna - Set Phase 2 on Target Max Sunder Armor Aura Stack (Phase 1)');

"1062 - Duplicate entry '1048992' for key 'PRIMARY'"

 So it seems the error is on your side some where :). 

 Edit: you got everthing up to date ?

**Comment by Swater96** [comment]
Yeah up to date core, scripts and db. Maybe someone else here can try it on their end before we add this into the repo.

**Comment by Schmoozerd** [comment]
You can only INSERT INTO for content that does not exist. (existing defined via key, in this case the first column "id" )

You should always provide the proper DELETE queries for a query. If you do so it should be ok.

> DELETE FROM creature_ai_scripts WHERE id=1048992;

**Comment by Metalica** [comment]
@Swater96 try @Schmoozerd idea and tell me how it goes.

**Comment by Swater96** [comment]
Here is my revised code. Although it runs, thunderaan does not use any abilities or aggro speech.

DELETE FROM creature_ai_scripts WHERE id=1526091;
DELETE FROM creature_ai_scripts WHERE id=1526092;
DELETE FROM creature_ai_scripts WHERE id=1526093;
DELETE FROM creature_ai_texts WHERE Entry='-1323';
UPDATE creature_template SET AIName='EventAI' WHERE (Entry='14435');
INSERT INTO creature_ai_texts (entry, content_default, content_loc1, content_loc2, content_loc3, content_loc4, content_loc5, content_loc6, content_loc7, content_loc8, sound, type, language, emote, comment) VALUES ('-1323', 'My power is discombobulatingly devastating! It is ludicrous that these mortals even attempt to enter my realm! ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '0', '0', '0', 'Prince Thunderaan');
UPDATE creature_ai_scripts SET id='1526091', creature_id='14435', event_type='0', event_inverse_phase_mask='0', event_chance='100', event_flags='1', event_param1='3000', event_param2='3000', event_param3='5000', event_param4='5000', action1_type='11', action1_param1='23011', action1_param2='4', action1_param3='0', action2_type='0', action2_param1='0', action2_param2='0', action2_param3='0', action3_type='0', action3_param1='0', action3_param2='0', action3_param3='0', comment='Prince Thunderaan - Cast Tears of the Wind Seeker' WHERE (id='1526091');
UPDATE creature_ai_scripts SET id='1526092', creature_id='14435', event_type='0', event_inverse_phase_mask='0', event_chance='100', event_flags='1', event_param1='9000', event_param2='13000', event_param3='16000', event_param4='20000', action1_type='11', action1_param1='23009', action1_param2='0', action1_param3='1', action2_type='0', action2_param1='0', action2_param2='0', action2_param3='0', action3_type='0', action3_param1='0', action3_param2='0', action3_param3='0', comment='Prince Thunderaan - Cast Tendrils of Air' WHERE (id='1526092');
UPDATE creature_ai_scripts SET id='1526093', creature_id='14435', event_type='1', event_inverse_phase_mask='0', event_chance='100', event_flags='0', event_param1='1000', event_param2='1000', event_param3='0', event_param4='0', action1_type='1', action1_param1='-1323', action1_param2='0', action1_param3='0', action2_type='0', action2_param1='0', action2_param2='0', action2_param3='0', action3_type='0', action3_param1='0', action3_param2='0', action3_param3='0', comment='Prince Thunderaan - Say on Spawn' WHERE (id='1526093');

**Comment by Swater96** [comment]
SELECT \* FROM `creature_ai_scripts` WHERE creature_id='14435'; returns no results either

**Comment by Swater96** [comment]
Ok ive got it. You need to use INSERT INTO statements. Here is the say text. Using this method the creature now properly will yell on aggro. This will need to be done for the spells too.

INSERT INTO `creature_ai_scripts` (`id`, `creature_id`, `event_type`, `event_param1`, `event_param2`, `action1_type`, `action1_param1`, `comment`) VALUES ('1526093', '14435', '1', '1000', '1000', '1', '-1323', 'Prince Thunderaan - Say on Spawn');

**Comment by Metalica** [comment]
Hehehe, glad you fixed it :+1:  I let those tiny details to cala, to sort them out :).

**Comment by cala** [comment]
Thank you for this report and data, I'll have a look at them before making a PR to ACID (this is ACID stuff).
But before, I'd like to know where do the timer values come from, please?

**Comment by Metalica** [comment]
Mostly taken from other skills as i didnt found any refence on net. Maybe if you find any reference you can fine tune it. Ground work is finished tho.

 Wind seeker was taken from moon fire ?
 Of air was taken from "knockback".
