### ISSUE TITLE
Serpentbloom is empty

### ISSUE THREAD

**Issue by TheTrueAnimal** [classicdb/database#674]
Serpentbloom does not always contain serpentblooms as it should.
http://www.wowhead.com/object=13891
http://www.wowhead.com/item=5339

UPDATE `gameobject_loot_template` SET `chanceorquestchance` = -100 WHERE `item` = 5339; 

Classic

**Comment by Sinoxan** [comment]
Quick check, does it drop it at all?  I was about to do a pull request for you but I can't find the loot template for this so UPDATE won't work.  Also, -100 is for a 100% from a quest relation but Serpentbloom still drops for you even if you aren't on the quest that you need it for.

**Comment by cala** [comment]
From the current state of the database, it has a 80% drop chance for player with the quest only. I agree it should be changed to 100% (and some other adjustements are needed). However, is it 100% for everyone or players on the quest only? We need sources to check if we need to change it from its current state.

**Comment by Sinoxan** [comment]
You don't have to be on the quest, I played Alliance so I wouldn't have been able to get the quest but I remember picking them anyway.  I see it now, I forgot how `gameobject_loot_template` worked.
