### ISSUE TITLE
Wrong PvP-reputation needed

### ISSUE THREAD

**Issue by TheTrueAnimal** [classicdb/database#675]
The following NPCs sell items that need wrong reputation:
http://www.wowhead.com/npc=14754  sells items that need silverwing reputation (should be warsong outriders)
http://www.wowhead.com/npc=15126  seels items that need silverwing reputation (should be Forsaken Defilers)

The following items do also need wrong reputation:
http://www.wowhead.com/item=17349
http://www.wowhead.com/item=17352

**Comment by cala** [comment]
Will be handled in https://github.com/classicdb/database/issues/819 . Thank you.
