### ISSUE TITLE
Wrong respawntime of Unfinished Painting

### ISSUE THREAD

**Issue by TheTrueAnimal** [classicdb/database#676]
The gameobject has a respawntime of 3 minutes. It should not despawn.
http://www.wowhead.com/object=177287
Source: https://www.youtube.com/watch?v=2Dm3YwxxJUo  (0:58) (From 2014 but normally GOBs in instances have no respawntimer)
Classic.

**Comment by time-out** [comment]
```
UPDATE `gameobject` SET `spawntimesecs` = '0' WHERE `id` = '177287';
```
