### ISSUE TITLE
Quest: A Taste of Flame (4024)

### ISSUE THREAD

**Issue by scotty0100** [classicdb/database#68]
Quest: A Taste of Flame (4024) is impossible to complete as when you use the Altered Black Dragonflight Molt (11231) on Bael'Gar's corpse (9016), it just eats the item and doesn't give you the Encased Fiery Essence (11230)

**Comment by cala** [comment]
I don't remember this quest but I guess which quest chain it is related to. I will look upon it in the coming weeks before my vacations. Thank you for reporting.

**Comment by cala** [comment]
It looks like this issue is related to the core: https://github.com/cmangos/issues/issues/274

**Comment by TheTrueAnimal** [comment]
@cala Have you already tested xfurrys fix?

**Comment by cala** [comment]
@evil-at-wow : I got your IRC message a bit late about this issue (see: https://github.com/cmangos/issues/issues/274 and https://github.com/cmangos/issues/issues/74 ). I ran the tests on Classic and got the same issue that the one you described:
- with the backported commit https://github.com/cmangos/mangos-classic/commit/d571ce8e84a2921fd08e80eaccb5008875770d54 if the player is close enough of the target (dead NPC), the spell is cast but no item is created in the inventory

**Comment by evil-at-wow** [comment]
This will be fixed once cmangos/mangos-wotlk@62d30ca5 is backported, which I plan to do this weekend. 

And the reason why this works in WoTLK is that the spell targets are reversed in WoTLK compared to TBC/Classic: (TARGET_SELF, TARGET_SCRIPT) vs (TARGET_SCRIPT, TARGET_SELF).

**Comment by cala** [comment]
Wonderful, thank you! :+1:

**Comment by cala** [comment]
Closed by: https://github.com/cmangos/mangos-classic/commit/b57116d97064ed6713d2098bb0d0aab38eb341a5
Thanks @evil-at-wow
