### ISSUE TITLE
Quest IDs: 7671, 7672, 7673, 7674 (epic mount replacement)

### ISSUE THREAD

**Issue by shnibble** [classicdb/database#680]
I noticed when starting one of these quests the quest text and required item (applicable mount) gossip page does not appear; it just skips directly to the rewards gossip text and items.

Whereas if you look at the similar quests 7664 and 7665, the proper text and requirement page appears when attempting to start either quest. I'm certain this is just a database fix but I couldn't find any existing issues reporting it. Maybe we just don't know what the quest text is supposed to say, hence why it was omitted?

**Comment by Swater96** [comment]
Im not sure if these are supposed to still be available. They were introduced in 1.4 to upgrade the unarmored mounts to armored, updated models. In the current state of 1.12, it isn't possible to attain unarmored mounts, so these quests are pretty obsolete.

**Comment by cala** [comment]
But if we think of people that have not logged between 1.4 and 1.12, they possibly still have a unarmored version of the mount, so the quests should be available for them.
But I agree that for CMaNGOS, they should be pretty useless.

Thus, this should be fixed in order to be blizz-like, but this is probably a low priority issue.

Thank you for reporting your first issue on Classic DB, @shnibble :smile:

**Comment by cala** [comment]
After a bit of research, I'm afraid finding the right texts will prove nearly impossible due to the very low number of people having completed the quests, especially at a time where very few tracking addons such as wowhead's were available.
It seems that only the raptor replacement quests have their texts set.

**Comment by cala** [comment]
Here is my suggestion to avoid having this issue opened for ever:
- adapt the raptor remplacement quest text for all quests
- prefix each replaced text with a [PH] tag (for PlaceHolder) to let user know this is not the right text (this tag is already used elsewhere in the database)

Does this sound good to you?

**Comment by Swater96** [comment]
That sounds good to me

**Comment by cala** [comment]
Here's my proposal (the first one is already in the database, I just moved it to the proper field):

``` SQL
-- STALLIONS
UPDATE `quest_template` SET `Details` = '', `RequestItemsText` =
'If you bring me your white stallion, I\'ll trade you for one from the new herd. The new horse will be just as fast as your old one, but have a different look to it. You can look at the swift steeds here to see what it will look like.'
WHERE `entry` = 7677;

UPDATE `quest_template` SET `Details` = '', `RequestItemsText` = 
'[PH] If you bring me your palomino, I\'ll trade it in for one from the new herd. The new horse will be just as fast as your old one, but have a different look to it. You can look at the swift steeds here to see what it will look like.'
WHERE `entry` = 7678;

-- MECHANOSTRIDERS
UPDATE `quest_template` SET `Details` = '', `RequestItemsText` = 
'[PH] If you bring me your old fast mechanostrider, I will trade it in for one from the new pack.   The new mechanostrider will be just as fast as your old one, but have a different look to it.   You can look at the swift mechanostriders we already have around the yard here to see what it will look like.'
WHERE `entry` IN (7675, 7676);

-- RAMS
UPDATE `quest_template` SET `Details` = '', `RequestItemsText` = 
'[PH] Ye bring me yer old ram, I will trade it in for one from the new pack!  The new ram will be just as fast as yer old one, but with a new look to him.   You can look at the swift rams here to see what ye will have to choose from.'
WHERE `entry` IN (7673, 7674);

-- SABERS
UPDATE `quest_template` SET `Details` = '', `RequestItemsText` = 
'[PH] If you bring me your old frostsaber, I will trade it in for one from the new pack.   The new swift saber will be just as fast as your old one, but have a different look to it.   You can look at the swift sabers we already have around the yard here to see what it will look like.'
WHERE `entry` = 7671;

UPDATE `quest_template` SET `Details` = '', `RequestItemsText` = 
'[PH] If you bring me your old nightsaber, I will trade it in for one from the new pack.   The new swift saber will be just as fast as your old one, but have a different look to it.   You can look at the swift sabers we already have around the yard here to see what it will look like.'
WHERE `entry` = 7672;
```

**Comment by cala** [comment]
Closed by https://github.com/classicdb/database/commit/edcefbb52cec247e00d71c0623059368eb3c84be
Thank you.
