### ISSUE TITLE
DM:N - Equipment

### ISSUE THREAD

**Issue by Tobschinski** [classicdb/database#685]
[Gordok Reaver](http://www.wowhead.com/npc=11450) should carry [Monster - Axe, 2H Horde Black War Axe](http://www.wowhead.com/item=17383)

[Gordok Bushwacker](http://www.wowhead.com/npc=14351) should carry [Monster - Mace2H, Horde Hammer A03 Dark](http://www.wowhead.com/item=14527)

~~[Gordok Brute](http://www.wowhead.com/npc=11441) should carry [Monster - Mace, Spiked Heavy](http://www.wowhead.com/item=3361)~~

~~[Stomper Kreeg](http://www.wowhead.com/npc=14322) should carry [Monster - Item, Tankard Dirty](http://www.wowhead.com/item=2704)~~

~~[Guard Mol'dar](http://www.wowhead.com/npc=14326) should carry [Monster - Axe, Horde Badass 01](http://www.wowhead.com/item=10611) and [Monster - Shield, Small Metal Damaged](http://www.wowhead.com/item=2052)~~

~~[Guard Fengus](http://www.wowhead.com/npc=14321) should carry [Monster - Axe, Metal Badass](http://www.wowhead.com/item=2183) and [Monster - Shield, Small Metal Damaged](http://www.wowhead.com/item=2052)~~

~~[Guard Slip'Kik](http://www.wowhead.com/npc=14323) should carry [Monster - Axe, One-Handed Double Axe](http://www.wowhead.com/item=5286) and [Monster - Shield, Large Wooden](http://www.wowhead.com/item=1985)~~

~~[Captain Kromcrush](http://www.wowhead.com/npc=14325) should carry [Monster - Axe, 2H Large Double Bladed](http://www.wowhead.com/item=5287)~~

~~[Cho'Rush the Observer](http://www.wowhead.com/npc=14324) should carry [Monster - Staff, Ornate Priest Staff](http://www.wowhead.com/item=2176)~~

**Comment by cala** [comment]
Thank you: I got them. I just need to test them before pushing the commit.

**Comment by Tobschinski** [comment]
Thanks Cala!

**Comment by Tobschinski** [comment]
If it helps you out just commit your stuff and I will check it.

**Comment by cala** [comment]
I'm currently away (holidays) but expect this to be pushed very soon. :)

**Comment by Tobschinski** [comment]
I'm sorry, I have to be annoying once more ...

> Gordok Reaver should carry Monster - Axe, 2H Horde Black War Axe
> 
> Gordok Bushwacker should carry Monster - Mace2H, Horde Hammer A03 Dark

**Comment by cala** [comment]
To be honest, I did not test the fix that I just pushed (no access to a server box before tomorrow), but there should be no problem as the equipment templates were already existing.

**Comment by Tobschinski** [comment]
Thank you very much, it works!
