### ISSUE TITLE
Spirestone Mystic skinnable

### ISSUE THREAD

**Issue by TheTrueAnimal** [classicdb/database#689]
Spirestone Mystics (orcs - humanoids) are skinnable.

https://web.archive.org/web/20060416002857/http://wow.allakhazam.com/db/mob.html?wmob=9198
http://www.wowhead.com/npc=9198

Classic Mangos

**Comment by Metalica** [comment]
UPDATE `creature_template` SET `SkinningLootId`='0' WHERE (`Entry`='9198')
