### ISSUE TITLE
Quest: Neeru Fireblade, Ak'Zeloth & The Demon Seed missing.

### ISSUE THREAD

**Issue by scotty0100** [classicdb/database#69]
Margoz (3208) does not offer Neeru Fireblade questline. 
Source: http://www.aowow.org/?quest=829

Quest: Neeru Fireblade (829) WoWHead: www.wowhead.com/quest=829
Quest: Ak'Zeloth (809) AoWoW: http://www.aowow.org/?quest=809 WoWHead: http://www.wowhead.com/quest=809
Quest: The Demon Seed (924) AoWoW: http://www.aowow.org/?quest=924 WoWHead: http://www.wowhead.com/quest=924

**Comment by cala** [comment]
Just to be sure: your saying that NPC 3208 should offer the quest 829 that leads to quests 809 and 924? Yet NPC does not offer the first quest. If you use ingame the command `.quest add 829` with only your character selected, are you able to do the quest chain as expected?

**Comment by cala** [comment]
After having a look at the database, I think the racial requirement for these quests is wrong. Could you please try:

``` SQL
UPDATE `quest_template` SET `RequiredRaces` = 178 WHERE  `entry` IN (829, 809, 924);
```

And relauch the server to see if it makes these quests available?

**Comment by cala** [comment]
Could you please tell me which race you were playing? :)

**Comment by scotty0100** [comment]
It was undead, but I looked in the database a bit further and can see Skull Rock is the pre requisite to unlock Neeru Fireblade quest, which I guess which is what threw me off. So I think this can be closed down now, sorry.

**Comment by cala** [comment]
Ok, I understand better. Racial requirements for these quests needed some clean up, nonetheless. Thank you for these reports. :)
