### ISSUE TITLE
Dire Maul - Gordok Reaver

### ISSUE THREAD

**Issue by Tobschinski** [classicdb/database#690]
[Gordok Reaver](https://wowhead.com/npc=11450) are totally missing from Dire Maul.

**Comment by Tobschinski** [comment]
I have all of them except for 2 spawns, but as these are no longer present on retail, I may need the help of the prime @evil-at-wow - if he can spare some time.

**Comment by Tobschinski** [comment]
Missing Reaver 1:
![reaver1](https://cloud.githubusercontent.com/assets/4753528/5601379/a79bfd86-92fb-11e4-8c13-6125eb20a48c.png)

Missing Reaver 2:
![reaver2](https://cloud.githubusercontent.com/assets/4753528/5601380/afe5cb20-92fb-11e4-9c27-9b928bf4e78e.png)

If this helps at all ...

**Comment by cala** [comment]
If we know where they should spawn, why don't we add them manually ? I don't think that 1 yard error in the spawn point accuracy would be a problem for such big NPCs.

**Comment by Tobschinski** [comment]
I can't help it, my OCD is ruining my life. : (

**Comment by evil-at-wow** [comment]
@Tobschinski I have some good offi data for the original Dire Maul North. The spawn points you're missing should be in there, so I'll check and report back.

@cala Oh noes! Perfection! We need absolute perfection!

**Comment by cala** [comment]
Then you don't mind that I eat pop corn while watching you looking for perfection about something released 10 years ago? :tongue:

**Comment by evil-at-wow** [comment]
I don't, as long as you don't mind eating pop corn for many years to come :wink:

**Comment by Tobschinski** [comment]
> @Tobschinski I have some good offi data for the original Dire Maul North. The spawn points you're missing should be in there, so I'll check and report back.

I was hoping for that, would be awesome!

**Comment by evil-at-wow** [comment]
Below is the data I promised earlier. I haven't run any serious analysis over multiple instances to detect any variations in spawns that need to be pooled for Dire Maul North, but at first glance most of the groups containing a Gordok Reaver seem fixed. The **Gordok Reaver spawns** in these groups are listed in the following  table, in the order you see them when you run through the instance (you can verify/compare with your data for the spawns that still exist, the ones you're missing are in bold):

| X | Y | Z | O | Where? |
| --- | --- | --- | --- | --- |
| 387.409 | 462.772 | -7.14894 | 2.68781 | Halls of Destruction, first bonfire |
| 419.015 | 538.269 | -18.26 | 0.488692 | Halls of Destruction, second bonfire |
| 530.206 | 600.875 | -25.3194 | 4.86947 | Below the ramp with Guard Slip'kik |
| 530.169 | 580.439 | -25.3194 | 1.41372 | Below the ramp with Guard Slip'kik |
| **541.695** | **582.741** | **-4.67144** | **5.67232** | **At the top of the ramp** |
| 593.228 | 565.12 | -4.67144 | 3.10669 | At the next ramp |
| **522.958** | **554.504** | **28.0006** | **2.19911** | **At the Gordok Inner Door, near the ramp** |
| 497.733 | 523.807 | 27.9982 | 1.64061 | Guarding the Gordok Inner Door |
| 484.101 | 523.808 | 27.9976 | 1.44862 | Guarding the Gordok Inner Door |
| 485.141 | 564.946 | 27.9951 | 3.21141 | At the Gordok Inner Door, near the braziers |
| 480.264 | 558.168 | 27.9953 | 1.85005 | At the Gordok Inner Door, near the braziers |
| 565.936 | 486.725 | 29.5475 | 4.2586 | At the bonfire before Captain Kromcrush |
| 559.22 | 477.314 | 29.5475 | 0.855211 | At the bonfire before Captain Kromcrush |

The three groups with Gordok Reavers and Gordok Captains at the end, after Captain Kromcrush, seem to have a varying composition. At least for several positions I've seen both a Gordok Reaver and a Gordok Captain in different instances, so these should probably be pooled with chances to be 100% accurate (a Gordok Captain seems far more likely than a Gordok Reaver, so just taking a guess here it could be 66%/33% but more analysis is required). I'm sure you know that I intend to respawn Dire Maul North somewhere in the future, so I'll take care of that when I get to it.

Finally, there are two more Gordok Reaver spawns when you fight Captain Kromcrush. They are both spawned at the same location with the same orientation before they attack your group:

| X | Y | Z | O |
| --- | --- | --- | --- |
| 556.869 | 481.557 | 29.6308 | 6.23827 |

Enjoy!

**Comment by Tobschinski** [comment]
Thank you very much, I was finally able to add them.

The groups in front of the King can have multiple variations, additions to the pooling-system are needed. I'll just use a static setup for now.

**Comment by evil-at-wow** [comment]
> The groups in front of the King can have multiple variations, additions to the pooling-system are needed.

Yeah, I ran into the limitations of the pooling system when respawning Dire Maul West. I've started working on the pooling/spawning system a bit. It'll take some time, but I'm sure we'll get there eventually. 

And I agree that a static setup is "good enough" for the time being - especially compared with the state we had until recently.
