### ISSUE TITLE
Finkle Einhorn

### ISSUE THREAD

**Issue by TheTrueAnimal** [classicdb/database#691]
The NPC should be spawned when you skin the Beast. At the moment he's automatically spawned when the Beast dies.

Finkle: http://www.wowhead.com/npc=10776
The Beast: http://www.wowhead.com/npc=10430
https://web.archive.org/web/20070812201411/http://wow.allakhazam.com/db/mob.html?wmob=10776

Classic.

**Comment by cala** [comment]
I think that we can't do that by DB and this should be handled by SD2. I suggest you open an issue on SD2 repository.
