### ISSUE TITLE
Investigate the Alchemist Shop

### ISSUE THREAD

**Issue by TheTrueAnimal** [classicdb/database#695]
When using the item no NPCs spawn.
Quest: http://www.wowhead.com/quest=1960
Item: http://www.wowhead.com/item=7308
NPC: http://www.wowhead.com/npc=6492
Quest for alliance: http://www.wowhead.com/quest=1920

Sources:
http://www.wowhead.com/quest=1960
https://www.youtube.com/watch?v=GVIDz5uz7s8
https://www.youtube.com/watch?v=lyyoE2-5GiQ
https://web.archive.org/web/20071018031619/http://wow.allakhazam.com/db/quest.html?wquest=1960

**Comment by Phatcat** [comment]
So I can imagine this one is done  since the other issue was closed.

**Comment by cala** [comment]
Yes, I thought it was already closed. Thanks!
