### ISSUE TITLE
Emberstrife

### ISSUE THREAD

**Issue by Metalica** [classicdb/database#699]
Quest:http://www.wowhead.com/quest=6570/emberstrife
NPC: http://www.wowhead.com/npc=10321/emberstrife#comments

 Problem: He does not give the item for the quest.

**Comment by cala** [comment]
Thank you for the report. Can you precise which item you are speaking of, please? I never did the Horde quest myself (I did the Alliance quest, several times though).

**Comment by cala** [comment]
As I said above, I never did that quest chain, so I tested it to see what happens:
- I started quest 6570 and used the provided item to get near Emberstrife.
- He gave me three quests (one dragon to kill for each).
- Once the three quests completed, he asked me to kill a fourth dragon.
- Once done, he gave me an item 16888 (Dull Drakefire Amulet).
- I brought the item to Rexxar that asked me to kill General Drakkisath in UBRS.

Aside from the fact that the spell in the first quest turns the player into a pig, while I assume it should be some kind of black dragonkin, everything seems logical. Can you tell me what is wrong and how it should be? Thank you.

**Comment by Metalica** [comment]
Emberstrife is part of Horde Onyxia quest chain: http://www.wowwiki.com/Onyxia%27s_Lair_attunement

 You will ge the meddalion from this quest:http://www.wowwiki.com/Quest:Emberstrife

 Medallion name: Amulet of Draconic Subversion (16787) / This items does not work properly.

 Edit: Sry for late response, but im i'll.

**Comment by cala** [comment]
No worries. :)
So we agree, the issue is when player uses item 16787 (Amulet of Draconic Subversion): players does not transform into a dragonkin like it should, but can still speak to Emberstrife.

**Comment by Metalica** [comment]
Agreed.

**Comment by Lumber-Jack-2** [comment]
npc=12536 the npc you should be morphed into - probably the modelid is wrong?
