### ISSUE TITLE
Game Object: Half-Buried Bottle in Stranglethorn Vale.

### ISSUE THREAD

**Issue by scotty0100** [classicdb/database#70]
Half Buried Bottle (Object: 2560) at the moment is dropping Raptor Loot and eggs.

http://www.aowow.org/?object=2560

I couldn't find any sources anywhere that say it can drop raptor items, I think the scrolls are more common.

The loot table needs a bit of a clean up.

**Comment by cala** [comment]
The whole loot table needs indeed a clean up and I'm slowly running through it as errors like this one are reported.
So, please, keep on reporting those, it helps a lot. Thank you! :+1:
