### ISSUE TITLE
Dire maul doors

### ISSUE THREAD

**Issue by Metalica** [classicdb/database#701]
Rogue with 300 Lockpicking is able to open the doors to Dire Maul North and West as well. 

Reference: http://web.archive.org/web/20061117164542/http://www.wowwiki.com/Dire_Maul

**Comment by cala** [comment]
Thank you for your report. I just tried on the DM:West entrance door (GO 177188, requiring the crescent key) and with Lockpicking (skill 633) set to 300, the door can be open. Same for DM:North Door (GO 177192). From my knowledge and your link, the other doors should not be lockpickable (aside from the library doors which are also working).

Can you tell us which GO are not working, please? You can use the command `.gobject near` to get the name and ID of gameobjects in a 10 yards radius.

**Comment by Metalica** [comment]
177192, 177188 - These should be opened with lockpick. If they do work (as seen by refence), report can be closed.

**Comment by cala** [comment]
Closing, thank you.
