### ISSUE TITLE
Dark Moon Faire Cannon Faulty

### ISSUE THREAD

**Issue by Patman64** [classicdb/database#703]
[Original post](https://github.com/cmangos/issues/issues/552)

> The DarkMoon faire Event, the cannon is meant to shoot you up into the air and you glide back down to the ground after you click on it. It is not working, instead when you click on it you turn into a demon for a few seconds... you never leave the ground.

**Comment by Lumber-Jack-2** [comment]
ahh yes - nice feature

a possible script which has to be modiefed can be found here: https://github.com/arcemu/arcemu/blame/master/src/scripts/src/MiscScripts/DarkmoonFaireObjects.cpp

for the german guys here i made a list for the important things some time ago:

1)Während es monatlichen Dunkelmondjahrmarktes gibt es auf den jeweiligen Eventplätzen ein spezielles Gameobject: Die [ Blastenheimer 5000 Ultra Kanone ](http://de.wowhead.com/object=186560// https://db.rising-gods.de/?object=180515).

2) Diese ist an folgendes Plätzen monatlich abwechselnd zu finden:

https://db.rising-gods.de/?object=180515 -> Wald von Elwynn (östlich es Marktes)
https://db.rising-gods.de/?object=186560 -> Shattrath (In der Nähe des Aufzugs)
https://db.rising-gods.de/?object=180452 -> Donnerfels ( Rechts neben dem Aufzug)

3) Neben dem Object steht der NPC Maxima Blastenheimer (https://db.rising-gods.de/?npc=15303)

4) Die Kanone ist für Spieler nutzbar. Wenn man mit der Maus über diese fährt wird ein "Zahnrad"
5) Nach dem "rechtsklicken" wird der Spieler in diese Kanone hineingeworfen und befindet sich für ca. 2 Sekunden in dieser.
6) Anschließend wird der Spieler im hohen Bogen in die Luft katapultiert und fliegt mit seinem Körper durch die Lüfte.
7) Während des Fluges erhält der Spieler den Buff: " Magische Flügel "(http://de.wowhead.com/spell=24742 // https://db.rising-gods.de/?spell=24742)
Damit kann der Spieler 18 Sek. Lang durch die Lüfte gleiten.
Die Animation des Buffs sind zwei große gelbe Flügel.
Bild: http://wow.zamimg.com/uploads/screenshots/normal/270496.jpg
8) Ziel ist das Treffen einer makierten Stelle. Diese Stelle befindet sich immer in einem See oder einem Fluss.
Bild: http://wow.zamimg.com/uploads/screenshots/normal/270496.jpg
9) Um in dem Ziel zu landen, muss man den Buff "Magische Flügel" aus seiner Buffleiste entfernen. Dadurch fliegt man nun nicht mehr mit verringerter Fallgeschwindigkeit, sondern fällt direkt zu Boden/in den Fluss/See.
10) Landet man nun, kann man entweder außerhalb hinfallen (und evtl. Sterben), oder aber man hat das makierte Ziel erreicht und erhält unterschiedliche Buffs:
11) Die Buffs:

```
Schlechter Schuss! (https://db.rising-gods.de/?spell=62179)
Knapp! (https://db.rising-gods.de/?spell=62175)
Ins Schwarze! ( https://db.rising-gods.de/?spell=62173)
```

Je nachdem wie Nah man an dem Ziel dran war, erhält man einen dieser Buffs
Die Buffs halten jeweils eine Stunde und verschiedene Texte sind bei den Buffs erkennbar
(z.B.: Ins Schwarze! - Sofort -Euer letzter Versuch an der Kanone wurde von einem Volltreffer gekrönt!)

Quelle: http://www.wowwiki.com/Blastenheimer_5000_Ultra_Cannon

Hier mal ein Video(vom Offi- Wotlk), wie das ganze aussehen sollte (nur Mulgore): https://www.youtube.com/watch?v=3HsnInYQvKY&hd=1
http://www.youtube.com/watch?feature=player_detailpage&v=tNfvEIYXrMg#t=67

FEHLER:
Bei uns funktioniert alles bis zu Punkt 4. Alles andere (Kanone besetzen / Flug / Buffs etc.) funktionieren auf dem RG-Liveserver nicht.

Hier ein Video,bei dem man sieht, wie es zur Zeit auf dem Server abläuft:
https://www.youtube.com/watch?v=MomDLo3PHZo&hd=1

Man kann deutlich erkennen, dass man die Kanone anklicken kann.
Jedoch passiert nach dem Anklicken nichts weiter.
Man wird lediglich für 5 Sekunden unsichtbar, kann sich in der Gegend bewegen, und wird nach den 5 Sekunden wieder sichtbar.

TrinityCore meinte dazu folgendes:
https://github.com/TrinityCore/TrinityCore/issues/2229 – (also eig nix :C )
Ein ähnliches Spielprinzip ist mir z.Z. nur von den Verwüstern bei Levi bekannt, was hier ja leider auch nicht funktioniert.

( PS: Neben der Goldverschwenderei, finde ich dieses Objekt mal wirklich interessant während des Dunkelmondjahrmaktes – Schade, dass es nicht funktioniert.)

**Comment by Tobschinski** [comment]
Guess you have to study German, Cala.

**Comment by Lumber-Jack-2** [comment]
the most important thing will be to find out how the apply of the buffs is handled, if you come closer to the circle-gameobjects in the near of the sea/lake/whatever

**Comment by Lumber-Jack-2** [comment]
okay i could convert this: http://pastebin.com/0gNG5cBn

My current problem: the spell kicks the player in ANY direction and not directly towards the lake.
Is there a possibility to relocate the position of the unit for this spell?

**Comment by cala** [comment]
Thanks for this patch. Can you tell us against which file it should be applied?
For the position, you can probably use `spell_target_position` in database.

**Comment by Lumber-Jack-2** [comment]
the problem is that this cannon has 3 spawnpoints and every portposition should be different. could be applied probably in the go_scripts file :D 

joschiwald reminded me to change:
player->CastSpell(player, 42867, true);
to
go->CastSpell(player, 42867, true);

and that works very well ^^

**Comment by killerwife** [comment]
Uhm one thing guys. From what I understand, 42867 was only used in TBC near shattrath. Also, what creature do those knockback spells target? Are there any dummy creatures in the DMF area? Because the cannon works the same as quests Test Flight: in TBC. I plan on implementing it on vengeance so when im done with it im gonna post the source. Tho I need to know what it should target first.

**Comment by cala** [comment]
Closed by https://github.com/cmangos/classic-db/commit/6053d376152353ca10d04070ecf5f289d32c268a
