### ISSUE TITLE
Booty Bay to Gnomeregan Transporter

### ISSUE THREAD

**Issue by Metalica** [classicdb/database#705]
The Transpolyporter [Object ID: 142172] for Booty Bay.

The Gnomeregan Train Depot Transpolyporter [Object ID: 142176] is also missing on PTR.

How it currently functions:

1) Horde player takes the quest Rig Wars [Quest ID: 2841] from Nogg NPC ID: 3412

2) Horde player speaks to Sovik [NPC ID: 3413] and accepts quest Chief Engineer Scooty [Quest ID: 2842]

3) Horde player completes quest Chief Engineer Scooty [Quest ID: 2842] and accepts quest Gnomer-goooone [Quest ID: 2843]

4) Horde player completes quest Gnomer-goooone [Quest ID: 2843] and receives Goblin Transponder [Item ID: 9173]

5) The Transpolyporter [Object ID: 142172] for Booty Bay is missing and the player is unable to continue.

How it should function:

1) Horde player takes the quest Rig Wars [Quest ID: 2841] from Nogg NPC ID: 3412

2) Horde player speaks to Sovik [NPC ID: 3413] and accepts quest Chief Engineer Scooty [Quest ID: 2842]

3) Horde player completes quest Chief Engineer Scooty [Quest ID: 2842] and accepts quest Gnomer-goooone [Quest ID: 2843]

4) Horde player completes quest Gnomer-goooone [Quest ID: 2843] and receives Goblin Transponder [Item ID: 9173]

5) Horde player uses the Transpolyporter [Object ID: 142172] situated in Booty Bay

6) Horde player is transported to Gnomeregan, Dun Morogh, appearing on the Gnomeregan Train Depot Transpolyporter [Object ID: 142176] next to the NPC Sprok [NPC ID: 8320]

Evidence:

Shows the position of the Gnomeregan Transpolyporter - http://www.atlasmod.com/phpBB3/viewtopic.php?f=6&t=991

The Booty Bay Transpolyporter in front of Chief Engineer Scooty - http://images3.wikia.nocookie.net/__cb20080729221426/wowwiki/images/7/73/Transpolyporter_BB.jpg

**Comment by cala** [comment]
Closed as now working as intented.
