### ISSUE TITLE
Graveyard's missing and/or broken

### ISSUE THREAD

**Issue by Metalica** [classicdb/database#706]
Horde Dun Morogh Graveyard missing. 

 Go ironforge as horde. Type .die and you are able to respawn in ironforge. Instead of at the Kharanos graveyard (which they correctly spawn at if they die in Ironforge).

 Horde Undercity Graveyard missing. 

Go Undercity as horde. Type .die and you are able to respawn in Undercity.

Darkshore graveyard:

 Horde I died and was deposited at the graveyard by Splintertree post. I know there is a graveyard right near the Bashal'aran ruins. I'm not sure if being Horde has to do with it but it is atleast a 20 minute run if you die at Tower of Althalaxx currently.

Hinterlands - Overlook Cliffs graveyard:

Alliance characters do not have access to the Overlook Cliffs graveyard when it should be available to both factions. Regardless of where an Alliance player dies, he/she will need to run back from the Aerie Peak graveyard.

Patch 1.5.0:

"A new graveyard has been added near the east coast of the Hinterlands at the Overlook Cliffs."

"The two Hinterlands graveyards are now using a system that will ensure that the spirits of dead characters go to the closest graveyard. "

http://www.wowwiki.com/Hinterlands#Patch_changes

"Sometimes, not ALWAYS BUG"

Sometimes when you die, for example in the caves before the Deadmines instance, you don't appear at the graveyard and have to run to your corpse, your ghost appears right next to your corpse and you wait 30 sec to respawn.

 Some more issues (if they work, ignore - posting just to make sure it's working).

Graveyard "Elwynn Forest, Eastvale Logging Camp" has to be assigned for Horde players, 
Graveyard "Elwynn Forest, Goldshire" has to be assigned for Alliance players.

**Comment by Lumber-Jack-2** [comment]
for the darkshorepart:

DELETE FROM `game_graveyard_zone` WHERE `id`=512 AND `ghost_zone`=148 AND `faction`=67;
UPDATE `game_graveyard_zone` SET `faction`=0 WHERE `id`=469 AND `ghost_zone`=148;

i hope this still can be used for mangos :D
