### ISSUE TITLE
Portals of the Legion

### ISSUE THREAD

**Issue by TheTrueAnimal** [classicdb/database#712]
You should use an item at the portals. They begin to glow as they should after the cast has completed but the NPC doesn't spawn. Because of this you can't complete the killquest. Thereafter the portals should despawn but they don't.

Quest: http://www.wowhead.com/quest=5581
Item: http://www.wowhead.com/item=14547
Portals: http://db.vanillagaming.org/?item=14547#unlocks
NPC: http://www.wowhead.com/npc=11937
Video: https://www.youtube.com/watch?v=IYmLOBbDVTE
https://www.youtube.com/watch?v=KAAajp3z_us

**Comment by trulynullified** [comment]
It seems there is database support for this already, but only for 1 of 10 gameobject's.

**Comment by ghost** [comment]
It seems there is already database support for this, but only for 1 of 10 gameobject's. This should allow all of the gameobject's to summon them now. (all the data is based off what was already existing)

DELETE FROM `dbscripts_on_go_template_use` WHERE `id` IN (177243,177365,177366,177367,177368,177369,177397,177398,177399,177400);
INSERT INTO `dbscripts_on_go_template_use` VALUES 
('177243', '0', '10', '11937', '60000', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 'Demon Portal - Summon Demon Portal Guardian'),
('177365', '0', '10', '11937', '60000', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 'Demon Portal - Summon Demon Portal Guardian'),
('177366', '0', '10', '11937', '60000', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 'Demon Portal - Summon Demon Portal Guardian'),
('177367', '0', '10', '11937', '60000', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 'Demon Portal - Summon Demon Portal Guardian'),
('177368', '0', '10', '11937', '60000', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 'Demon Portal - Summon Demon Portal Guardian'),
('177369', '0', '10', '11937', '60000', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 'Demon Portal - Summon Demon Portal Guardian'),
('177397', '0', '10', '11937', '60000', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 'Demon Portal - Summon Demon Portal Guardian'),
('177398', '0', '10', '11937', '60000', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 'Demon Portal - Summon Demon Portal Guardian'),
('177399', '0', '10', '11937', '60000', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 'Demon Portal - Summon Demon Portal Guardian'),
('177400', '0', '10', '11937', '60000', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 'Demon Portal - Summon Demon Portal Guardian');

**Comment by cala** [comment]
Thank you for the fix! I'll review it soon.

**Comment by yyhhrr** [comment]
trulynullified‘s fix was worked,but the portals is still respawn after you use the quest item.

**Comment by cala** [comment]
The portal despawn needs core support (currently, we cannot despawn a GO).
