### ISSUE TITLE
Rookery Hatcher doesn't open eggs

### ISSUE THREAD

**Issue by TheTrueAnimal** [classicdb/database#713]
Rookery Hatchers should open eggs but they don't.

http://www.wowhead.com/npc=10683
http://www.wowwiki.com/Solakar_Flamewreath
https://web.archive.org/web/20070228153148/http://wow.allakhazam.com/db/mob.html?wmob=10264

**Comment by cala** [comment]
Closed by: https://github.com/cmangos/mangos-classic/commit/9f9cb1f591a4dae2e99ede5b19540b1117037f84
