### ISSUE TITLE
Solakar Flamewreath

### ISSUE THREAD

**Issue by TheTrueAnimal** [classicdb/database#714]
Solakar doesn't use any abilities. I just found one video.
http://www.wowhead.com/npc=10264
https://www.youtube.com/watch?v=evgqtFJ7gl8
http://www.wowwiki.com/Solakar_Flamewreath

Classic.

**Comment by Tobschinski** [comment]
[Disturb Rookery Egg (FAST)](http://www.wowhead.com/spell=16556/disturb-rookery-egg-fast) (~8s)
[War Stomp](http://www.wowhead.com/spell=16727/war-stomp)  (~15s)
