### ISSUE TITLE
Magmus Blackrock Depths

### ISSUE THREAD

**Issue by TheTrueAnimal** [classicdb/database#715]
Bug:
- There should be flames only during fighting against magmus. At the moment there are also flames before the fight.

Magmus: NPC: http://www.wowhead.com/npc=9938
Ironhand Guardian: http://www.wowhead.com/npc=8982 (produces flames)
Spell: http://www.wowhead.com/spell=15529

Videos:
https://www.youtube.com/watch?v=tK46LmHyvFM (from 3:36 on)
https://www.youtube.com/watch?v=phBzWcCPgn0 (from 0:30 on)

**Comment by Tobschinski** [comment]
I'd like to suggest a SD2-solution here.

The Ironhand Guardians are never in-combat with any player. They just gain the mentioned spell if Magmus is. Correct me if I am wrong but I think SD2 seems to be the best solution here.

**Comment by cala** [comment]
I did this fight several time on retail, but did not test it with Classic DB. But I would agree with @Tobschinski 
I'll have a look at this : BRD issues are next on my list.

**Comment by evil-at-wow** [comment]
> There should be flames only during fighting against Magmus.

Unless this was changed in Classic or TBC, I disagree. I've been there about a hundred times or so, from early WoTLK to WoD, and the flames seem to activate the first time you aggro Magmus, and then keep going forever. In fact, in your second video you can see that the flames don't stop after Magmus is killed! I haven't found any pattern in what Guardian actives next, so it's probably random.

A few other observations I've done:
- If your group wipes on Magmus the first time, the flames keep going and will be active when you return, even before you pull Magmus again! So they are not reset like everything else (boss, doors that open again).
- Killing the Emperor or any other boss in the instance doesn't seem to stop the flames either.

**Comment by Tobschinski** [comment]
No, you are totally correct, I was just just pointing to the start of the event. The flames never stop once activated. I'm sorry for this.

**Comment by cala** [comment]
I looked at this. Currently, the NPCs are handled by ACID which makes them cast the spell randomly out of combat and in combat. The EVENT_T_TIMER_OOC is responsible for the fact that they are always casting even before engaging Magmus for the first time. This needs to be removed. 

But there is no way for those NPCs to know the current state of the encounter (not started, in progress, fail...) via ACID to make them cast the spell while simulating "in combat" mode. So, definitely a SD2 solution here. Thus, the whole ACID script needs to be removed.

I've written a small SD2 script that should do the trick, I will test it along with the Plugger script.

**Comment by Tobschinski** [comment]
I'll see if I can get proper timers for that spell.

**Comment by cala** [comment]
Thanks. Currently, I use the same than those in ACID.

**Comment by Tobschinski** [comment]
Yeah, I'm not happy with these. It's almost like they never drop that spell.

**Comment by Tobschinski** [comment]
Ironhand Guardian (8982)

---

Spell used on spawn is: `Stoned` (10255).

If you get in combat with Magmus, all of them drop `Stoned` and cast `Stoned - Channel Cast Visual` (15533). The cast lasts 3 second and can possibly be interrupted by `Gout of Flame` (15529). 
<sub><sup>(I don't know if this is intended or not, but it happens. I don't think anyone in Irvine cares as much as I would.)

`Gout of Flame` (x,x) | (x,x)

Oh boy, this is harder than expected.

**Comment by cala** [comment]
Seemingly fixed in https://github.com/scriptdev2/scriptdev2/pull/175/commits

**Comment by Ulduar** [comment]
Magmus on Aggro can SendAIEventAround - On Receive AI Event Iron Guardian can Set Phase One or two - On Phase One OOC Timer - cast spell. On Evade SendAiEventAround - Iron Guardian Set Phase 0 and all.

**Comment by cala** [comment]
All BRD related parts requiring SD2 are now scripted in this [pull request](https://github.com/scriptdev2/scriptdev2/pull/175) pending review and backport. So I'm closing this issue on the DB side. Thanks everyone for you contribution.
