### ISSUE TITLE
Freedom for All Creatures

### ISSUE THREAD

**Issue by TheTrueAnimal** [classicdb/database#717]
The NPC doesn't start walking and the quest fails after time has expired.

Quest: http://www.wowhead.com/quest=2969
NPC: http://www.wowhead.com/npc=7956
Video: https://www.youtube.com/watch?v=cbyKV88LfEg

**Comment by cala** [comment]
Closed by: https://github.com/cmangos/mangos-classic/commit/ed2057f9d910ad62702dcbe059ab7238c67ce130
