### ISSUE TITLE
The Spider God

### ISSUE THREAD

**Issue by TheTrueAnimal** [classicdb/database#718]
When you're on the quest you should be able to read a second page when clicking on the gameobject. A the moment there is no second page and you can't complete the quest.

Quest: http://www.wowhead.com/quest=2936
Object: http://www.wowhead.com/object=142715
http://wowpedia.org/Tablet_of_Theka

Classic.

**Comment by Lumber-Jack-2** [comment]
https://github.com/Tranquillien/TrinityCore-Gunship/blob/master/src/server/scripts/World/go_scripts.cpp#L859

**Comment by trimken** [comment]
Fix for quest 

SD2 -->  go_scripts.cpp

```
enum 
{
    GOSSIP_TABLE_THEKA = 1653,
    QUEST_SPIDER_GOD = 2936
};

    bool GossipHelloGO_table_theka(Player* pPlayer, GameObject* pGo) override 
    {
        if (pPlayer->GetQuestStatus(QUEST_SPIDER_GOD) == QUEST_STATUS_INCOMPLETE)
            pPlayer->AreaExploredOrEventHappens(QUEST_SPIDER_GOD);

        pPlayer->SEND_GOSSIP_MENU(GOSSIP_TABLE_THEKA, pGo->GetObjectGuid());

   return true;
    }
```

```
    pNewScript = new Script;
    pNewScript->Name = "go_table_theka";
    pNewScript->pGossipHelloGO =  &GossipHelloGO_table_theka;
    pNewScript->RegisterSelf();
```

Database

> UPDATE gameobject_template SET ScriptName='go_table_theka' WHERE entry=142715;

**Comment by cala** [comment]
Thank you both of you for these inputs (and sorry for my late reply).
