### ISSUE TITLE
Onu is meditating

### ISSUE THREAD

**Issue by TheTrueAnimal** [classicdb/database#719]
The quest is made to get an item with whichone you can talk to the npc if you lost the item. There is the blue question mark over its head and it offers you the quest but if you click on the red icon to complete the quest nothing happens and you don't get the item. You need it to start the next quest in chain.

Quest: http://www.wowhead.com/quest=961
NPC: http://www.wowhead.com/npc=3616
Item: http://aowow.wow-castle.de/?item=5251

**Comment by cala** [comment]
Thank you for the report. This is a core issue (see https://github.com/classicdb/database/issues/228)
I think that at least in Classic, the core does not handle properly quests with Method = 2 and specialflags = 1 (repeatable): currently, it seems to send the SMSG_QUESTGIVER_OFFER_REWARD opcode to client while player has not accepted the quest (not in quest log). Thus clicking on the "Complete" button does not send anything back from the client to the server.
