### ISSUE TITLE
Quest Lunar Fireworks

### ISSUE THREAD

**Issue by TheTrueAnimal** [classicdb/database#720]
You have to use some of the following items (8 rockets and 2 rocket clusters) near some firecrackers and firework launchers but it doesn't count.

Quest: http://www.wowhead.com/quest=8867
Items:
http://www.wowhead.com/item=21559/small-green-rocket
http://www.wowhead.com/item=21558/small-blue-rocket
http://www.wowhead.com/item=21557/small-red-rocket
http://www.wowhead.com/item=21576/red-rocket-cluster
http://www.wowhead.com/item=21574/green-rocket-cluster
http://www.wowhead.com/item=21571/blue-rocket-cluster
Cluster Launcher: 180869
Firework Launcher: 180868

**Comment by ghost** [comment]
This is what I came up with so far, but for whatever reason the Cluster Launcher gameobject's just doesn't seem to trigger the credit.. how ever if I use the cluster credit on the firework launcher it works.. Perhaps someone can take a look with fresh eyes.

DELETE FROM `dbscripts_on_go_template_use` WHERE `id` IN (180771,180850,180868,180772,180859,180869);
INSERT INTO `dbscripts_on_go_template_use` VALUES 
('180771', '0', '8', '15893', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 'Lunar Festival - Lunar Fireworks Fired Credit'),
('180850', '0', '8', '15893', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 'Lunar Festival - Lunar Fireworks Fired Credit'),
('180868', '0', '8', '15893', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 'Lunar Festival - Lunar Fireworks Fired Credit'),
('180772', '0', '8', '15894', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 'Lunar Festival - Lunar Fireworks Cluster Fired Credit'),
('180859', '0', '8', '15894', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 'Lunar Festival - Lunar Fireworks Cluster Fired Credit'),
('180869', '0', '8', '15894', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 'Lunar Festival - Lunar Fireworks Cluster Fired Credit');

**Comment by cala** [comment]
Moved to https://github.com/cmangos/issues/issues/1547

**Comment by Evilkiiller** [comment]
The Fix that Ghost Posted has only partially fixed the quest, the Fireworks Cluster Still wont show 1/2-2/2  the Lunar Fireworks do work however, Perhaps i am missing something?
