### ISSUE TITLE
Omen can't be summoned

### ISSUE THREAD

**Issue by TheTrueAnimal** [classicdb/database#721]
Omen can't be summoned because the launchers are missing so you can't use the rockets to summon him.

Quest Elune's Blessing: http://www.wowhead.com/quest=8868/elunes-blessing
Omen: http://www.wowhead.com/npc=15467
http://www.wowwiki.com/Omen
https://web.archive.org/web/20070629130555/http://thottbot.com/c15467

**Comment by cala** [comment]
Closed by https://github.com/cmangos/mangos-classic/commit/a8c1746646a88ef73c1989cc127d1efcdd902157
Thanks.
