### ISSUE TITLE
Small and Large Cluster Rocket Recipes

### ISSUE THREAD

**Issue by TheTrueAnimal** [classicdb/database#722]
The items are empty although they should consist recipes with a 100% dropchance.

Small Rocket Recipes: http://www.wowhead.com/item=21740
http://www.wowhead.com/item=21726/schematic-small-red-rocket
http://www.wowhead.com/item=21724/schematic-small-blue-rocket
http://www.wowhead.com/item=21725/schematic-small-green-rocket

Large Cluster Rocket Recipes: http://www.wowhead.com/item=21743/
http://www.wowhead.com/item=21735/schematic-large-red-rocket-cluster
http://www.wowhead.com/item=21733/schematic-large-blue-rocket-cluster
http://www.wowhead.com/item=21734/schematic-large-green-rocket-cluster

The Questtext is not shown completly so you can't see what they cost. I'm not sure if it's only a german bug.

**Comment by ghost** [comment]
The quest text seems fine for me (@http://i.imgur.com/B2bIyLN.jpg)

INSERT INTO `item_loot_template` VALUES 
('21740', '21724', '100', '0', '1', '1', '0'),
('21740', '21725', '100', '0', '1', '1', '0'),
('21740', '21726', '100', '0', '1', '1', '0'),
('21743', '21733', '100', '0', '1', '1', '0'),
('21743', '21734', '100', '0', '1', '1', '0'),
('21743', '21735', '100', '0', '1', '1', '0');

**Comment by cala** [comment]
Closed by https://github.com/classicdb/database/commit/f85ce33f9896c1602783703990a8bbe0228cfd80
