### ISSUE TITLE
Elune's Candle

### ISSUE THREAD

**Issue by TheTrueAnimal** [classicdb/database#723]
The items seems to have no effect.

http://www.wowhead.com/item=21713
http://www.wowwiki.com/Elune%27s_Candle

**Comment by Phatcat** [comment]
> Id: 26374
> Name: Elune's Candle
> Description: Shoots a firework at target.
> General info
> Category = 0, SpellIconId = 1, ActiveIconId = 0, SpellVisual = (0, 0)
> SpellFamilyName = SPELLFAMILY_GENERAL, SpellFamilyFlags = 0x0000000000000000
> SpellSchool = 0 (SPELL_SCHOOL_NORMAL)
> DamageClass = 0 (SPELL_DAMAGE_CLASS_NONE)
> PreventionType = 0 (SPELL_PREVENTION_TYPE_NONE)
> Attributes
> Attributes: 0x00040010 (SPELL_ATTR_UNK4, SPELL_ATTR_UNK18)
> AttributesEx1: 0x00080400 (SPELL_ATTR_EX_NO_INITIAL_AGGRO, SPELL_ATTR_EX_UNK19)
> Advanced info
> Spell Level = 0, BaseLevel 0, MaxLevel 0, MaxTargetLevel 0
> Category = 0
> DispelType = 0 (DISPEL_NONE)
> Mechanic = 0 (MECHANIC_NONE)
> SpellRange (Id 4) "Medium Range"
> MinRange = 0
> MaxRange = 30
> Speed: 12.00
> CastingTime (Id 1) = 0.00
> Interrupt Flags: 0x00000000, AuraIF 0x00000000, ChannelIF 0x00000000
> Chance = 101, charges - 0
> Effects
> Effect 0:
> Id: 3 (SPELL_EFFECT_DUMMY)
> BasePoints = 1
> Targets (25, 0) (TARGET_DUELVSPLAYER, NO_TARGET)
> Effect 1:
> NO EFFECT
> Effect 2:
> NO EFFECT

Looks like a missing dummy effect.

**Comment by Phatcat** [comment]
It looks like the dummy effect is supposed to then choose which spell to cast depending on target... or..? - I never heard of this world boss before or this candle, so someone has to tell me how this should function...

> Id: 26649
> Name: Elune's Candle
> Description: Shoots a firework at Omen's Left Hand.
> General info
> Category = 0, SpellIconId = 1, ActiveIconId = 0, SpellVisual = (7476, 0)
> SpellFamilyName = SPELLFAMILY_GENERAL, SpellFamilyFlags = 0x0000000000000000
> SpellSchool = 0 (SPELL_SCHOOL_NORMAL)
> DamageClass = 0 (SPELL_DAMAGE_CLASS_NONE)
> PreventionType = 0 (SPELL_PREVENTION_TYPE_NONE)
> Attributes
> Attributes: 0x00040000 (SPELL_ATTR_UNK18)
> AttributesEx1: 0x00000400 (SPELL_ATTR_EX_NO_INITIAL_AGGRO)
> Advanced info
> Spell Level = 0, BaseLevel 0, MaxLevel 0, MaxTargetLevel 0
> Category = 0
> DispelType = 0 (DISPEL_NONE)
> Mechanic = 0 (MECHANIC_NONE)
> SpellRange (Id 4) "Medium Range"
> MinRange = 0
> MaxRange = 30
> Speed: 12.00
> CastingTime (Id 1) = 0.00
> Interrupt Flags: 0x00000000, AuraIF 0x00000000, ChannelIF 0x00000000
> Chance = 101, charges - 0
> Effects
> Effect 0:
> Id: 2 (SPELL_EFFECT_SCHOOL_DAMAGE)
> BasePoints = 160 to 241
> Targets (25, 0) (TARGET_DUELVSPLAYER, NO_TARGET)
> Effect 1:
> NO EFFECT
> Effect 2:
> NO EFFECT
> 
> Id: 26625
> Name: Elune's Candle
> Description: Shoots a firework at Omen's Right Hand.
> General info
> Category = 0, SpellIconId = 1, ActiveIconId = 0, SpellVisual = (7471, 0)
> SpellFamilyName = SPELLFAMILY_GENERAL, SpellFamilyFlags = 0x0000000000000000
> SpellSchool = 0 (SPELL_SCHOOL_NORMAL)
> DamageClass = 0 (SPELL_DAMAGE_CLASS_NONE)
> PreventionType = 0 (SPELL_PREVENTION_TYPE_NONE)
> Attributes
> Attributes: 0x00040000 (SPELL_ATTR_UNK18)
> AttributesEx1: 0x00000400 (SPELL_ATTR_EX_NO_INITIAL_AGGRO)
> Advanced info
> Spell Level = 0, BaseLevel 0, MaxLevel 0, MaxTargetLevel 0
> Category = 0
> DispelType = 0 (DISPEL_NONE)
> Mechanic = 0 (MECHANIC_NONE)
> SpellRange (Id 4) "Medium Range"
> MinRange = 0
> MaxRange = 30
> Speed: 12.00
> CastingTime (Id 1) = 0.00
> Interrupt Flags: 0x00000000, AuraIF 0x00000000, ChannelIF 0x00000000
> Chance = 101, charges - 0
> Effects
> Effect 0:
> Id: 2 (SPELL_EFFECT_SCHOOL_DAMAGE)
> BasePoints = 160 to 241
> Targets (25, 0) (TARGET_DUELVSPLAYER, NO_TARGET)
> Effect 1:
> NO EFFECT
> Effect 2:
> NO EFFECT

and so on..

**Comment by cala** [comment]
Closed by https://github.com/cmangos/mangos-classic/commit/9711fc2329372e76f8d4740ffd9ed740fcb7a2d9
Thanks !
