### ISSUE TITLE
Elder's Moonstone

### ISSUE THREAD

**Issue by TheTrueAnimal** [classicdb/database#724]
The Elder's Moonstone doesn't show any light. You can select the area but nothing happens. The stone disappears.

http://www.wowhead.com/item=21745

**Comment by ghost** [comment]
From what I can tell, it only works if its not in a stack. Might be a core issue, or so.

**Comment by cala** [comment]
Elder's Moonstone are working fine for me. Like @trulynullified, I assume this is related to core not handling items that are both usable and stackable, though I remember a time in Classic (and maybe TBC) where it was already that way. So, it can also be a client limitation.
Anyway, not related to DB. Thank you.
