### ISSUE TITLE
Quest: Continued Threat

### ISSUE THREAD

**Issue by Tobschinski** [classicdb/database#726]
[Continued Threat](http://www.wowhead.com/quest=1428/deprecated-continued-threat) was reported as very time-consuming, maybe because of a lack of pooling. (just two spawns of Flesh Eaters)

**Comment by cala** [comment]
> Continued Threat was reported as very time-consuming

Was reported where and by whom if I may ask? This is the first time I hear of this quest as being broken.

**Comment by Tobschinski** [comment]
I don't remember his name, someone on IRC.

**Comment by cala** [comment]
Currently in DB: 
Marsh Inkspewer : 49 spawns, 0 in a pool (i.e. 49 are spawned)
Marsh Flesheater : 16 spawns, 0 in a pool (i.e. 16 are spawned)
Marsh Oracle : 13 spawns, , 0 in a pool (i.e. 13 are spawned)

That's a total of 78 NPCs, and every entry's spawns are above the required number of kills (10 per entry). I know that those NPCs are very scattered along the coast with some encampments very isolated and smalls. Maybe the original reporter was in one of those encampments and did not think there might be other spawn points further?

**Comment by Tobschinski** [comment]
As far as I remember there are just 2 flesheaters outside, the rest is in a cave. But I have yet to look at it.

**Comment by Tobschinski** [comment]
Nope, there are enough of them.

**Comment by cala** [comment]
Thank you for the feedback. It arrives right on time, I was about to import all spawns from all DBs into Classic DB in a few days. And then manually check which ones were duplicate or not. :+1:
