### ISSUE TITLE
High Inquisitor Whitemane

### ISSUE THREAD

**Issue by TheTrueAnimal** [classicdb/database#728]
How it should be: 
You kill Scarlet Commander Mograine and he dies. Whitemane comes through the door and attacks you. Once you get Whitemane to around 50% health, she'll sleep the entire party, resurrect Mograine, then heal herself. You have to kill Mograine the second time to get the loot.

Actual situation:
When Whitemane gets to 50% she sleeps the party but doesn't resurrect Mograine. You get the loot without killing him two times. It isn't possible to check if she also heals Mograine. 

http://www.wowhead.com/npc=3976/scarlet-commander-mograine#comments
http://www.wowhead.com/npc=3977/high-inquisitor-whitemane#comments

**Comment by cala** [comment]
Thank you for reporting.
This is a know bug in SD2 which was fixed recently on master branch (https://github.com/scriptdev2/scriptdev2/commit/a8dc9231f07fe59384514bc19939e2f5645613de) and is now waiting to be backported to Classic.
