### ISSUE TITLE
Gong-Event in Razorfen Downs

### ISSUE THREAD

**Issue by TheTrueAnimal** [classicdb/database#729]
When clicking on the gong, a wave of 8 Tomb Fiends should spawn. Clicking on it the second time sould spawn 4 Tomb Reavers and clicking on it the third time should spawn Tuten'kash. At the moment, the gong despawns and nothing happens.

Tomb Fiend: http://www.wowhead.com/npc=7349
Tomb Reaver: http://www.wowhead.com/npc=7351
Tuten'kash: http://www.wowhead.com/npc=7355/tutenkash
Gong: http://www.wowhead.com/object=148917
http://www.wowwiki.com/Tuten%27kash
http://www.hordeguides.de/Instanz/Classic/Boss/7355/Tutenkash/index.htm  (german)
https://www.youtube.com/watch?v=Dnnr0bqOgMA (here we can see 10 Tomb fiends)
https://web.archive.org/web/20070702040629/http://www.thottbot.com/c7355
https://web.archive.org/web/20070320014708/http://wow.allakhazam.com/db/mob.html?wmob=7355

**Comment by cala** [comment]
Thanks for the report.
This is SD2 stuff and I already ported it to SD2 a few days ago: https://github.com/scriptdev2/scriptdev2/commit/60d25551fa0320f18a6485c1211428cfeb4e6e7e
It is now waiting backport to Classic.
