### ISSUE TITLE
Empty chamber general drakkisath at UBRS

### ISSUE THREAD

**Issue by stan84** [classicdb/database#73]
The general's chamber is empty, only boss and 2 guards are  there. Missing 4 pack of mobs.
1 stand opposite enterance
2 stand at corner left side of enterance
3 stand at farest corner of chamber.
4 patroling chamber

Standing packs contains:
1x rage talon  Captain 10371
 1x rage talon fire tongue 10372
2x blackhand assasin 
1x blackhand iron guard

Patrol has also:
Rage Talon Dragonspawn
blackhand elite

**Comment by Schmoozerd** [comment]
you can pick the spawning positions and mobs from here: http://paste2.org/1xKYs7sp

**Comment by cala** [comment]
Thank you for the report. It is a long time since I tested UBRS and it would definitely need a look at.

@Schmoozerd thank you for the spawns, I guess from the SpawnMask/PhaseMask that the they come from UDB. I understand that I will only pick spawns from the missing NPC, but can you tell me how this query was generated, please? Because it seems to insert some creatures outside of UBRS (map = 0) while they are definitely related to the instance. Unless, I'm mistaken (which is a possibility). Thanks! :)

**Comment by Schmoozerd** [comment]
This is the content that somebody saw when he entered BRS from map0 on retail 335 at some point.

**Comment by cala** [comment]
Ah yes, NPCs on the other side of the portal before zoning in. I did not thing of that. Thanks for clarifying.

**Comment by cala** [comment]
@Schmoozerd sorry to bother you again about this one: I'm currently adding the missing NPCs and many of them with map = 0 can not be visible unless players go through instance portal (which have an area trigger) and even venture a bit into the dungeon (example: creature 9096 - Rage Talon Dragonspawn is only visible after opening the door leading to what is called UBRS part of the instance). Thus, these spawns on map 0 will never be displayed for the players as they will be teleported to map 229 before even reaching them...
So I wonder what is the purpose of adding them and what was the purpose for blizz to send data of them to client (as they were sniffed)?

**Comment by Schmoozerd** [comment]
hmm, are you sure they should be spawned on map 0 (eastern-kingdoms)??
Because once you enter the portal you are on a new map (BRS) -- and you won't get any information on any spawn of map 0 at all.

*confused

**Comment by cala** [comment]
I think they should not be spawned on map 0. But in the link you pasted above (http://paste2.org/1xKYs7sp), the query inserts those NPCs on map 0. Hence my question. :)

If you think this is a mistake in the query you linked, I can add them manually later to the proper map (BRS map = 229).

**Comment by Schmoozerd** [comment]
i have actually no idea :)

I don't work with the parser's sql output, so i do not know whether this is really correct :/
Also poke @crackm to this -- i don't know which parser version i used there, but there is an error

@cala At least one ((9818, 0, 1, 1, 151.1029, ...) of the spawns "on map 0" must be on 229 -- so i would assume all of them are there actually and this parser is (oh wonder) crap again ..

Btw - you will notice the different likely on the coordinates as well.
Real spawns on map 0 like (9043, 0, 1, 1, -7572.68, -1302.691, 245.5374, 1.358267, 120, 0, 0), are in the x coords around -7500 -- this would be way outside BRS map ;)

**Comment by cala** [comment]
Thank you for confirming my thoughts. 
Yes, I was betting on the coordinates values to distinguish which creatures should be manually spawned on map 229 instead of 0. :)
