### ISSUE TITLE
Pusillin just doing autohit

### ISSUE THREAD

**Issue by TheTrueAnimal** [classicdb/database#731]
When Pusillin gets hostile he just uses autohit.

NPC: http://www.wowhead.com/npc=14354

Sources:
https://www.youtube.com/watch?v=88Y7CQ6hVFI (7:30)
https://www.youtube.com/watch?v=-Ar1GBKbCC0 (9:00)
https://www.youtube.com/watch?v=M3_6Z0V9YaE (8:20)

**Comment by Schmoozerd** [comment]
he is scripted with EventAI - maybe you missed something when installing.

**Comment by cala** [comment]
The current ACID repositories (Classic/TBC/WOTLK) have no entries for this NPC, just a comment line:

``` SQL
-- Pusillin (14354) - WILL BE SCRIPTED IN C++    
```

Maybe the EventAI for this NPC was never merged?

**Comment by Schmoozerd** [comment]
Edit: Ah, sorry, i got him confused with somebody else.

**Comment by Schmoozerd** [comment]
Hmm, Pussilin-Event is scripted with DB-Scripting.
The script (UDB-Updatepack 406) ends with the gossip option triggering

```
(570905,1,0,0,0,0,0,0,2000005464,0,0,0,0,0,0,0,''), -- "Say hello to my little friends!" 
(570905,3,10,13276,120000,0,0,0,0,0,0,0,14.7965,-696.322,-12.6426,4.4823,'summon - Wildspawn Imp'),
(570905,3,10,13276,120000,0,0,0,0,0,0,0,18.8891,-697.389,-12.6426,4.35271,'summon - Wildspawn Imp'),
(570905,3,10,13276,120000,0,0,0,0,0,0,0,21.4274,-700.227,-12.6426,4.06997,'summon - Wildspawn Imp'),
(570905,3,10,13276,120000,0,0,0,0,0,0,0,22.2017,-705.459,-12.6426,3.48092,'summon - Wildspawn Imp'),
(570905,4,15,22735,0,0,0,0,0,0,0,0,0,0,0,0,'TRANSFORM'),
(570905,4,22,90,0x01,0,0,0,0,0,0,0,0,0,0,0,'set DemonFaction');
```

As far as i know there is nothing special in his combat remaining, hence i think using EventAI for this encounter should be perfectly fine!

**Comment by cala** [comment]
As you already noticed, the event for this NPC is handled by DBscripts since UDB 406 (I think this is Xfurry's work). I backported it to Classic DB and evil@wow did the same thing to TBC-DB.

I also agree that the combat part does not require the mighty powers of SD2. :smile: 

I will write the script and push it to ACID repo soon.

**Comment by Grz3s** [comment]
``` quote
As you already noticed, the event for this NPC is handled by DBscripts since UDB 406 (I think this is Xfurry's work). I backported it to Classic DB and evil@wow did the same thing to TBC-DB.
```

you can easy check who made this script... checking "whois" name above it... in UDB406_updatepack. 
;)

**Comment by cala** [comment]
Pull request done to ACID: https://github.com/ACID-Scripts/WOTLK/pull/21
