### ISSUE TITLE
Arcane Torrent doesn't use AOE

### ISSUE THREAD

**Issue by TheTrueAnimal** [classicdb/database#732]
Arcane Torrents don't use their AOE.

http://www.wowhead.com/npc=14399/arcane-torrent#comments
https://web.archive.org/web/20071109180807/http://wow.allakhazam.com/db/mob.html?wmob=14399
Video: https://www.youtube.com/watch?v=WfYPbr8hYuo  (16:20, 19:20, 19:55)

**Comment by cala** [comment]
Thanks for the report, but after testing this: the NPCs do cast Lightning Cloud. I suggest you check that your ACID is correctly installed. Closing here.
