### ISSUE TITLE
Quest: 40 Tickets - Schematic: Steam Tonk Controller ...

### ISSUE THREAD

**Issue by Tobschinski** [classicdb/database#733]
does not exist.

http://www.wowhead.com/quest=9249/40-tickets-schematic-steam-tonk-controller

**Comment by Tobschinski** [comment]
Adding missing items .... hurts ... a lot ...

**Comment by cala** [comment]
Only the first time.

Not all DBs have the same sniff, even for the creature/gameobject/item templates. No shame to have missing templates and add them later.

**Comment by Tobschinski** [comment]
not available for players until patch 2.0
