### ISSUE TITLE
Ambassador Flamelash

### ISSUE THREAD

**Issue by TheTrueAnimal** [classicdb/database#735]
Ambassador Flamelash doesn't get the buff from his adds and they don't despawn after giving him the buff.

http://www.wowhead.com/npc=9156/ambassador-flamelash#comments
http://www.wowhead.com/npc=9178/burning-spirit

https://web.archive.org/web/20070127125448/http://wow.allakhazam.com/db/mob.html?wmob=9156
https://www.youtube.com/watch?v=d_T-eh_P1SI (new, seems like the buff has been taken away my one character)

**Comment by Tobschinski** [comment]
For further improvements, you have to wait for a back-port to happen, the encounter was recently changed in https://github.com/scriptdev2/scriptdev2/commit/848f3543cf3cf4cebc80eea53dc1dc0326b1ab10
