### ISSUE TITLE
Mor Grayhoof is (not) there

### ISSUE THREAD

**Issue by TheTrueAnimal** [classicdb/database#738]
Using the Brazier of Invocation summons Mor Grayhoof who should attack players with several spells.
At the moment there is something the spawns, but nobody can see it. The log tells, something unknown is hitting you with 1-2 damage. 

http://www.wowhead.com/item=22057/brazier-of-invocation#comments
http://www.wowhead.com/npc=16080/mor-grayhoof#comments
http://www.wowwiki.com/Mor_Grayhoof
https://www.youtube.com/watch?v=08M1EuTR7eY
https://www.youtube.com/watch?v=tO20DFYAnXQ

**Comment by cala** [comment]
Thank you for the report. I know this is tricky at first, but the issue is related to ACID and should be reported there (https://github.com/ACID-scripts). Likely, the NPC trigger for Mor Grayhoof is missing its AI (the other triggers seem fine).
