### ISSUE TITLE
Thornlings don't use abilitie

### ISSUE THREAD

**Issue by TheTrueAnimal** [classicdb/database#741]
When you summon this NPC, it should stand there, grow in 2 phases and use an AOW. At the moment it just follows the summoner.

NPC: http://de.wowhead.com/npc=14362 
Video: https://www.youtube.com/watch?v=yVxtEFUVDRo
Source: http://de.wowhead.com/item=18297

**Comment by Tobschinski** [comment]
15:37:55.640 - Spawn (Scale 1)
15:37:57.672 - Scale 2
15:37:57.859 - %s begins to grow!
15:38:00.906 - Scale 3
15:38:01.109 - "%s continues to grow!"
15:38:04.140 - Scale 4
15:38:04.140 - Spellcast: 22781
15:38:04.328 - %s has grown to full size!

**Comment by cala** [comment]
Thanks! :)

**Comment by Tobschinski** [comment]
They cannot move, by the way.

**Comment by Phatcat** [comment]
With pets and guardians being able to use eventai this might be solvable now.

**Comment by cala** [comment]
I'm not sure we can change the scale of a creature through EventAI. I have to check.

**Comment by Tobschinski** [comment]
Spell 22788 is super close to 22781 and 22792

**Comment by Tobschinski** [comment]
and 22786 & 22787

**Comment by cala** [comment]
Closed by https://github.com/cmangos/classic-db/commit/67b33f8271ca609f231ffa304684a9af171eab21
