### ISSUE TITLE
Mantles of the dawn

### ISSUE THREAD

**Issue by TheTrueAnimal** [classicdb/database#742]
You should have to make two quests to be able to buy some items from three vendors. At the moment you can buy the items without having made the quests.

Vendors:
http://www.wowhead.com/npc=10856 
http://www.wowhead.com/npc=10857 
http://www.wowhead.com/npc=11536 

Quests:
http://www.wowhead.com/quest=5507/mantles-of-the-dawn (comment 2)
http://www.wowhead.com/quest=5521/chromatic-mantle-of-the-dawn 
http://www.wowhead.com/quest=5504/mantles-of-the-dawn 
http://www.wowhead.com/quest=5517/chromatic-mantle-of-the-dawn 

http://wowpedia.org/Quest:Mantles_of_the_Dawn [^]
http://wowpedia.org/Quest:Chromatic_Mantle_of_the_Dawn [^]

**Comment by ghost** [comment]
I based condition id's off items/quests feel free to change them if need be. I noticed the Chromatic Mantle of the Dawn quests were set to repeatable which is incorrect. Also I noticed you could complete all 3 versions of the quest when you should only be able to complete one version so I added the quests to their own exclusive groups.

INSERT INTO `conditions` VALUES 
('5513', '8', '5513', '0'),
('5507', '8', '5507', '0'),
('5504', '8', '5504', '0'),
('18169', '-2', '5513', '5507'),
('18170', '-2', '5504', '18169'),
('5524', '8', '5524', '0'),
('5521', '8', '5521', '0'),
('5517', '8', '5517', '0'),
('18172', '-2', '5524', '5521'),
('18173', '-2', '5517', '18172');
UPDATE `npc_vendor` SET `condition_id` = '18170' WHERE `item` IN (18169,18170,18171,18172,18173);
UPDATE `npc_vendor` SET `condition_id` = '18173' WHERE `item` = '18182';
UPDATE `quest_template` SET `ExclusiveGroup` = '5504' WHERE `entry` IN (5504,5507,5513);
UPDATE `quest_template` SET `ExclusiveGroup` = '5517', `SpecialFlags` = '0' WHERE `entry` IN (5517,5521,5524);

**Comment by cala** [comment]
Thanks for the report and thanks @trulynullified for providing a fix. It will be reviewed soon.
