### ISSUE TITLE
Signet of Expertise

### ISSUE THREAD

**Issue by TheTrueAnimal** [classicdb/database#743]
When you use the Signet of Expertise it sould create a Hammer of Expertise. The signet has a cooldown of 3 hours and the hammer lasts for 1 hour. 

Bugs:
The signet disappears when you use it.
You don't get the hammer.

http://www.wowhead.com/item=8703/signet-of-expertise
http://www.wowhead.com/item=8708/hammer-of-expertise

**Comment by ghost** [comment]
Make sure you are up to date with all of the updates, as it works fine for me.

**Comment by cala** [comment]
> The signet disappears when you use it.

I guess it was equipped on the character instead. This item is a trinket: it must be equipped to work.

Closing here, the item works as intended. Thank you.
