### ISSUE TITLE
Scum Covered Bag

### ISSUE THREAD

**Issue by TheTrueAnimal** [classicdb/database#745]
The bag is often empty. It seems like the droprate of its loot is too low. I didn't find any source that they should sometimes be empty.

http://www.wowhead.com/item=20767/scum-covered-bag#contains
https://web.archive.org/web/20070526051550/http://www.thottbot.com/i20767
https://web.archive.org/web/20071204063513/http://wow.allakhazam.com/db/item.html?witem=20767

**Comment by cala** [comment]
Fixed in https://github.com/classicdb/database/commit/edcefbb52cec247e00d71c0623059368eb3c84be
Thank you.
