### ISSUE TITLE
Scarshield Infiltrator / Vaelan

### ISSUE THREAD

**Issue by TheTrueAnimal** [classicdb/database#748]
The Scarshield Infiltrator doesn't morph into Vaelan any more when you're on the right quests. It once worked correctly but got broken again.

Vaelan: http://www.wowhead.com/npc=10296/acride
https://github.com/classicdb/database/issues/411

**Comment by cala** [comment]
Please, check that you have ACID properly installed. This NPC is handled by ACID.

**Comment by TheTrueAnimal** [comment]
Our ACID seems to be okay. A few months ago the quests worked as it should but since a few weeks the npc doesn't morph.

**Comment by cala** [comment]
This is a core issue: the eventAI code used by this script was broken in a recent backport: 
https://github.com/cmangos/mangos-classic/commit/c4ee504db3f0519cc0e2a34b341ccbcb2d1c9302
Waiting for a fix.

**Comment by cala** [comment]
Fixed by https://github.com/cmangos/mangos-classic/commit/c9f0dee2b65f706490bb59e634cd3520fff024b1
