### ISSUE TITLE
Seal of Ascension

### ISSUE THREAD

**Issue by TheTrueAnimal** [classicdb/database#752]
When you mindcontrol the dragon for the quest and try to use its spells, it always says, that the pet is infight and you can't do the quest.

Dragon: http://www.wowhead.com/npc=10321/emberstrife
Quest: http://www.wowhead.com/quest=4743/seal-of-ascension
Video: https://www.youtube.com/watch?v=HRL5jk-8aag

**Comment by scotty0100** [comment]
Just found this bug as well. As well as the issue mentioned above some other notes about this - currently Orb of Draconic Energy can be cast whenever, should only be usable under 10% HP. He should also emote at <10% HP to say Emberstrife's will falters.

**Comment by cala** [comment]
This will probably require a mix of DB and ACID (possibly SD2, but I doubt it).
How TC did it: https://github.com/TrinityCore/TrinityCore/issues/15021

**Comment by cala** [comment]
Closed by https://github.com/cmangos/mangos-classic/commit/bd1e0da20f7ceba0f6b3ddc7afab7dfd0c65c0ec
