### ISSUE TITLE
[BUG] Ancient Petrified Leaf Quest and stave-of-the-ancients Quest 1.12.1 

### ISSUE THREAD

**Issue by e46ad** [classicdb/database#754]
Quest http://www.wowhead.com/item=18703/ancient-petrified-leaf Is bugged i can't find the npc below i did this quest in vanilla myself and something is not correct with it.

http://www.wowhead.com/npc=14524/vartrus-the-ancient

I don't see vartrus-the-ancient in game i have the Leaf from molten core, I've been to the place he is suppose to spawn when on the quest but his not there, I had to spawn him with a GM command to be able to see him and advance to the next stage of the quest he give's 

 http://www.wowhead.com/quest=7636/stave-of-the-ancients

I see each Npc in game but they don't have the required scripts or npc text they should show, I can talk to them but they will just Say good day My Character Name, And some of them have custom text but no trigger to start the encounter and kill the creature for the Head's that are a required item for the Bow and Staff,

Latest Git pull of Cmangos latest DB and Core 1.12.1,

there my be an available fix but i might of missed them or not seen the updates ? 

I tired this on a admin/gm account and a normal players account, each time same results,

Thanks for reading.

**Comment by Lumber-Jack-2** [comment]
https://github.com/scriptdev2/scriptdev2/blob/master/sql/updates/r3070_mangos.sql
https://github.com/scriptdev2/scriptdev2/blob/master/scripts/world/areatrigger_scripts.cpp#L369

**Comment by cala** [comment]
The NPC providing the quest is handled by SD2 and is working (player has to stand on the little hill). 
The three demons were indeed not working when I tested them last week. We need to investigate if this can be fixed by DB or needs SD2 also.

**Comment by shnibble** [comment]
I think this was fixed but not for SD2-Classic. I opened an issue on SD2 awhile ago to resolve the ancients spawning: https://github.com/scriptdev2/scriptdev2-classic/issues/33.

Commit 3070 on SD2 closed the issue but if you are using SD2-Classic, none of those changes would be implemented I don't think.

**Comment by cala** [comment]
Closed in March 2018 via SD2.
