### ISSUE TITLE
[server crash]Quest 667 can't complete

### ISSUE THREAD

**Issue by yyhhrr** [classicdb/database#757]
The issue appearred again.When first wave end，the server crashed.
but if you delete dbscripts_on_quest_start
this line:
dbscripts_on_quest_start (id, delay, command, datalong, datalong2, buddy_entry, search_radius, data_flags, dataint, dataint2, dataint3, dataint4, x, y, z, o, comments) VALUES('667','50','34','317','667','0','0','0','0','0','0','0','0','0','0','0','Stop script if player is dead or out of range');
and
dbscripts_on_quest_start (id, delay, command, datalong, datalong2, buddy_entry, search_radius, data_flags, dataint, dataint2, dataint3, dataint4, x, y, z, o, comments) VALUES('667','50','34','318','667','0','0','0','0','0','0','0','0','0','0','0','Stop script if npc is dead');
the quest can complete.
I found all the dbscripts_on_quest_start table command=34 lead the server crashed.I'm not sure this is db issue.Anyone can reproduce this issue?(core version c2652)

**Comment by cala** [comment]
Thanks for reporting. This is a core issue. See: https://github.com/cmangos/issues/issues/591
