### ISSUE TITLE
Calling in the Reserves, XP reward fix

### ISSUE THREAD

**Issue by Swater96** [classicdb/database#758]
This quest does not give the right xp reward to players.

UPDATE `quest_template` SET `RewMoneyMaxLevel`='1150' WHERE (`entry`='5881')

Sources: Master Guide, and https://youtu.be/XAHWk939VlQ?t=16m41s

**Comment by Tobschinski** [comment]
Hello Sir, the quest is rewarded with 1150 experience on my end.
690 / 0.6 = 1150

> QuestLevel <= 60: XP = RewMoneyMaxLevel / 0.6
> https://github.com/cmangos/issues/wiki/Quest_template

**Comment by Tobschinski** [comment]
I just woke up, if I didn't see something obvious, please respond back.

**Comment by Swater96** [comment]
You're completely right. Thank you for the formula. Basically what i'm doing is going through the Joana's guide quests and making sure every one gives the proper xp.
