### ISSUE TITLE
NPC Text. Grelin Whitebeard

### ISSUE THREAD

**Issue by danielsreichenbach** [classicdb/database#759]
The current NPC text presented for Grelin Whitebeard aka creature template 786 is wrong.

The correct text is

> Greetings, $glad : lass;. I''m Grelin Whitebeard. I''m here to examine the threat posed by the growing numbers of trolls in Coldridge Valley. What have I found? It''s a bit troubling...

Source: [the web archives](http://web.archive.org/web/20050219010534/http://wow.allakhazam.com/db/mob.html?wmob=786)

**Comment by cala** [comment]
Thank you for this report and providing the right text.
