### ISSUE TITLE
BWL - Missing Equipment

### ISSUE THREAD

**Issue by Tobschinski** [classicdb/database#760]
[Blackwing Guardsman](http://www.wowhead.com/npc=14456/blackwing-guardsman) should carry [Monster - Axe, 2H Horde Black War Axe](http://www.wowhead.com/item=17383)
[Grethok the Controller](http://www.wowhead.com/npc=12557/grethok-the-controller) should carry [Monster - Staff, Ornate Jeweled Staff - Blue High Blue Glow](http://www.wowhead.com/item=18122)

[Blackwing Mage](http://www.wowhead.com/npc=12420/blackwing-mage) should carry [Monster - Staff, Ornate Jeweled Staff - Purple Low Purple Glow](http://www.wowhead.com/item=14837/monster-staff-ornate-jeweled-staff-purple-low-purple-glow)
[Blackwing Legionnaire](http://www.wowhead.com/npc=12416/blackwing-legionnaire) should carry [Monster - Axe, 2H Horde Black War Axe](http://www.wowhead.com/item=17383/monster-axe-2h-horde-black-war-axe)
Blackwing Warlock should carry 12959
Blackwing Spellbinder should carry 13705
Blackwing Taskmaster should carry 18123

[Death Talon Dragonspawn](http://www.wowhead.com/npc=12422/death-talon-dragonspawn) should carry [Monster - Axe, 2H Rev. Bearded Single Bladed - Red](http://www.wowhead.com/item=12285/monster-axe-2h-rev-bearded-single-bladed-red)
Death Talon Captain should carry 13150
Death Talon Flamescale should carry 13631
Death Talon Wyrmkin should carry 13050
Death Talon Seether should carry 6224
Death Talon Hatcher should carry 11383
Death Talon Overseer should carry 3432
Death Talon Wyrmguard should carry 5597

Broodlord Lashlayer 12403
Blue / Green / Bronze / Black / Red Drakonoids should carry 3432
Chromatic Drakonid should carry 12403

Blackwing Technician 2717 + 3757
Enraged Felguard 12889

**Comment by Tobschinski** [comment]
Not it!

**Comment by Tobschinski** [comment]
update

**Comment by cala** [comment]
Basically, almost all NPCs are missing their equipment if I understand it. Alright, I'm on it (and that should motivate me to write the wiki entry about that wonderful magic). :wink:

**Comment by cala** [comment]
I don't have a server at hand so I can't test it right now, but the following code should do the trick.
If this fix is OK for you, I'll push it tonight.

``` SQL
-- Fixed missing equipment of various NPCs in Blackwing Lair and Onyxia Lair
-- Thanks Tobschinski for reporting and researching. This closes #760 and closes #762 
UPDATE `creature_template` SET `EquipmentTemplateId` = 2164 WHERE `Entry` IN (14456, 12416); -- Blackwing Guardsman, Blackwing Legionnaire
UPDATE `creature_template` SET `EquipmentTemplateId` = 1427 WHERE `Entry` = 12557; -- Grethok the Controller
UPDATE `creature_template` SET `EquipmentTemplateId` = 1371 WHERE `Entry` = 12420; -- Blackwing Mage
UPDATE `creature_template` SET `EquipmentTemplateId` = 1003 WHERE `Entry` = 12459; -- Blackwing Warlock
UPDATE `creature_template` SET `EquipmentTemplateId` = 1845 WHERE `Entry` = 12457; -- Blackwing Spellbinder
UPDATE `creature_template` SET `EquipmentTemplateId` = 1428 WHERE `Entry` = 12458; -- Blackwing Taskmaster
UPDATE `creature_template` SET `EquipmentTemplateId` = 1872 WHERE `Entry` = 12422; -- Death Talon Dragonspawn
UPDATE `creature_template` SET `EquipmentTemplateId` = 1742 WHERE `Entry` = 12467; -- Death Talon Captain
UPDATE `creature_template` SET `EquipmentTemplateId` = 155 WHERE `Entry` = 12464; -- Death Talon Seether
UPDATE `creature_template` SET `EquipmentTemplateId` = 417 WHERE `Entry` IN (12461, 14261, 14262, 14263, 14264, 14265); -- Death Talon Overseer, Blue/Green/Bronze/Red/Black Drakonid
UPDATE `creature_template` SET `EquipmentTemplateId` = 2415 WHERE `Entry` IN (12017, 14302); -- Broodlord Lashlayer, Chromatic Drakonid
UPDATE `creature_template` SET `EquipmentTemplateId` = 1184 WHERE `Entry` = 14101; -- Enraged Felguard

SET @ENTRY := 2422;

DELETE FROM `creature_equip_template_raw` WHERE `entry` BETWEEN @ENTRY AND @ENTRY + 4;
INSERT INTO `creature_equip_template_raw` VALUES
(@ENTRY, 18388, 0, 0, 33490434, 0, 0, 529, 0, 0), -- lance
(@ENTRY + 1, 20300, 0, 0, 50268674, 0, 0, 529, 0, 0), -- 2H staff
(@ENTRY + 2, 19673, 0, 0, 50267138, 0, 0, 781, 0, 0), -- one hand mace
(@ENTRY + 3, 8376, 0, 0, 33488898, 0, 0, 1037, 0, 0), -- one hand big sword
(@ENTRY + 4, 6529, 6530, 0, 50266116, 50266116, 0, 1815, 1815, 0); -- bottle right and left hand

UPDATE `creature_template` SET `EquipmentTemplateId` = @ENTRY WHERE `Entry` IN (12463, 12129); -- Death Talon Flamescale, Onyxian Warder
UPDATE `creature_template` SET `EquipmentTemplateId` = @ENTRY + 1 WHERE `Entry` = 12465; -- Death Talon Wyrmkin
UPDATE `creature_template` SET `EquipmentTemplateId` = @ENTRY + 2 WHERE `Entry` = 12468; -- Death Talon Hatcher
UPDATE `creature_template` SET `EquipmentTemplateId` = @ENTRY + 3 WHERE `Entry` = 12460; -- Death Talon Wyrmguard
UPDATE `creature_template` SET `EquipmentTemplateId` = @ENTRY + 4 WHERE `Entry` = 13996; -- Blackwing Technician
```

**Comment by Tobschinski** [comment]
I think it's dark magic, I don't know if I wanna get involved ...

But thank you very much, I'll test it right away.

**Comment by Tobschinski** [comment]
Nicely done, Cala-san!

**Comment by cala** [comment]
I don't think it counts as dark magic as long as you don't send prayers to C'Thun, Yogg'Saron or Mephisto when you sacrifice the goat, black chicken and the new born in order to get the right SQL code.
