### ISSUE TITLE
[Hunter] Aimed Shot has no cast bar

### ISSUE THREAD

**Issue by MarcoPolo87** [classicdb/database#768]
As originally posted on the cmangos issues tracker ( https://github.com/cmangos/issues/issues/691 ).

When using the Hunter ability "Aimed Shot," the Cast Bar does not appear while the ability/spell is "casting." After checking old youtube videos, Aimed shot did display a cast bar in Vanilla prior to the release of TBC. I can not confirm if the "Cast Bar" was visible in every patch from Launch.

I am not sure if this would be labeled as a "content error" (classic DB) or a "server error" (mangos core DB).

Classic DB version 1.5.0 'The Great Swimming Pool'. For core z2656 and SD2 z2734
ACID 1.12.x (Classic) for CMaNGOS-CLASSIC (1.12.X Client)
required_z2621_s2263_12823_04_mangos_creature

**Comment by cala** [comment]
Thank you for this report. However, I highly doubt this could be fixed via DB and I think this is best to stick to the issue you opened in core repos.
