### ISSUE TITLE
Blackhoof Cages - Dustwallow Marsh (Bluefen) [With SQL Fix]

### ISSUE THREAD

**Issue by scotty0100** [classicdb/database#773]
There are several 'floating' Blackhoof Cages & a floating Campfire within the Bluefen area.

I spent a while aligning the Z axis of these - after about 45 minutes of doing this. I realized that the Blackhoof Village was added in patch 2.3.0 and we can probably just delete them. >:(

Just so that my 45 minutes of work is not for nothing, below will be re positioning SQL and deletion SQL. Just in case TBC, or WotLK need the correct Z axis locations..

Source for deletion for classic: 
http://www.wowhead.com/item=33061/grimtotem-key#comments (Added 2.3)
http://wowwiki.wikia.com/Blackhoof_Village

Re Position Z Axis TBC+:

```
/* Blackhoof Cages */

UPDATE gameobject SET position_z='34.94023' WHERE guid='11183';

UPDATE gameobject SET position_z='34.98740' WHERE guid='11184';

UPDATE gameobject SET position_z='34.18050' WHERE guid='11185';

UPDATE gameobject SET position_z='34.74039' WHERE guid='11707';

UPDATE gameobject SET position_z='32.67097' WHERE guid='11708';

UPDATE gameobject SET position_z='33.74427' WHERE guid='11710';

UPDATE gameobject SET position_z='32.46579' WHERE guid='11719';

/* Burning Embers */

UPDATE gameobject SET position_z='33.14332' WHERE guid='7633';
```

Deletion SQL for Classic:

```
/* Blackhoof Cages */

DELETE FROM gameobject WHERE guid IN (11183,11184,11185,11707,11708,11710,11719);

/* Burning Embers */

DELETE FROM gameobject WHERE guid='7633';
```

**Comment by cala** [comment]
Thanks for the issue and fix.
Dustwallow Marsh was remade in TBC (including some map changes). So, chances are good that the Z values you fixed were correct in TBC and WotLK.
The delete however are OK ! :+1:
