### ISSUE TITLE
Quest - Jail Break! [BRD] - [Partial Fix]

### ISSUE THREAD

**Issue by scotty0100** [classicdb/database#774]
Quest: Jail Break inside BRD has a minor bug in it.

When Marshal Windsor gets his armor, he spawns as a new NPC that is neutral and not friendly, making him vulnerable to PC AOE Attacks/Spells.

I also noticed the run speed of the new NPC is almost double of the previous one, but as I don't really know if this should be the case that fix is not included..but it's also worth looking into..I could not find any video proof of him walking faster after he gets his armor.

Marshal Reginald Windsor;below fixes his faction and flags to be like the other NPC:

```
UPDATE `creature_template` SET `FactionAlliance`='534', `FactionHorde`='534' WHERE (`Entry`='9682');

UPDATE `creature_template` SET `UnitFlags`='320', `CreatureTypeFlags`='4096' WHERE (`Entry`='9682');
```

This makes him friendly & now also assists the player on NPCs.

However I can not get this NPC to attack NPCs in his path as the previous one did. I couldn't find where that would be set in creature_template?

**Comment by evil-at-wow** [comment]
> I couldn't find where that would be set in creature_template?

NPCs fight stuff 'automatically' based on the factions involved and the relations between them. So if he's not attacking other NPCs but should do so, it most likely means at least one of the factions involved is wrong.

**Comment by cala** [comment]
This quest is handled by SD2, so chances are good that flags/factions are changed there and that DB values are not really used (at least not all of them).
I did not look at the script, so I can't be sure of this though.

It may be best to open an issue in SD2 repo for this.

**Comment by scotty0100** [comment]
From what I can remember when I looked at the script it literally just spawns a new NPC.

'Marshal Windsor' was the original NPC. Then once he gets his armor, the script then replaces him with another npc called 'Marshal Reginald Windsor', which has different faction etc to the original NPC.

I don't think this NPC is spawned elsewhere, so I think it can be done either DB or SD2.

**Comment by Tobschinski** [comment]
FACTION_ESCORT_A_NEUTRAL_ACTIVE     = 231

Try this one.
