### ISSUE TITLE
NPC - Grimtotem Naturalists

### ISSUE THREAD

**Issue by scotty0100** [classicdb/database#775]
Map & Area: Feralas - Grimtotem Compound
How to replicate the bug: engage a naturalist
What happens: they tend to stand still while you kill them
What should happen: They should attack back.

Possible buggy creature_ai_scripts?

**Comment by cala** [comment]
Thank you for reporting. This is an AI script error that prevent it from attacking. I suggest you report it to ACID repository instead.
