### ISSUE TITLE
Possible duplicates in the Manufactory

### ISSUE THREAD

**Issue by Tobschinski** [classicdb/database#776]
These marked creatures do no longer exist, but I don't know if they have been around in earlier version. 
There are patrolling creatures colliding with them, that could be a sign for duplicates.

![duplicate2](https://cloud.githubusercontent.com/assets/4753528/8297522/a2f27c3a-195e-11e5-936f-ae4dd2c30086.png)

GUIDs: 47255, 47258, 90593

**Comment by Tobschinski** [comment]
![duplicate1](https://cloud.githubusercontent.com/assets/4753528/8297625/6c8f8998-195f-11e5-9211-29100beb6ec6.png)

GUIDs: 47295, 90594, 90813

**Comment by Tobschinski** [comment]
They do not seem to exist in https://youtu.be/3mIkmIdpEW4?t=96 (or are elsewhere) but there's another creature at https://youtu.be/3mIkmIdpEW4?t=102 that is not existing in our DB (next to the red barrel).

Missing pat?

**Comment by evil-at-wow** [comment]
I think my earliest set of BRD data is taken early during WoTLK (patch 3.0.3). I'll check later.

**Comment by cala** [comment]
I don't remember groups with so many NPCs in BRD (at least in that part). Either they are duplicate from a patrol (happens often) as you suggested, or they are from an alternate spawned group sniffed from a first run, mixed the currently spawned group sniffed from the "current" run (also happens sometimes).

I think we can safely remove them unless @evil-at-wow find something in his data. :)

**Comment by evil-at-wow** [comment]
Note: I took the liberty to correct the title of this issue, because I started checking the wrong data! The screenshots are taken in The Manufactory, and not the Halls of Crafting as the title originally said.

That said, here's the verdict after checking some data captured with version 3.0.3:
- The three spawns on the first screenshot do _exist_, but in reality they are patrols that go a fairly long way, so it is very unlikely to see them in a state like on the screenshot (all three close together). That 'other creature that does not exist in our DB, near the red barrel' is actually one of these three, but in a different position along the path. And you don't see the other two in the video because they are patrolling elsewhere at that moment in time. 
- At first sight I counted no less than six patrolling NPCs in The Manufactory. Three of them no longer seems to exist according to a quick comparison with some MoP (5.4.1) data - those could be the three spawns mentioned above.
- The three spawns on the second screenshot do _exist_ as well! So yes, at least in my first BRD run in 3.0.3 there were a total of eight spawns in that corner! No wonder we were trying to avoid that corner as the plague in the good old times!
- Unsurprisingly, many spawn points can be either a Weapon Technician or a Doomforge Arcanasmith (or Ragereaver Golem/Wrath Hammer Construct for the golem spawns), but I suggest we ignore that for now until we have a better system in place in the core that allows us to easily do this without having to create a bunch of pools...
- I have not checked the actual ClassicDB data, but I had a quick look ingame on my TBC server. Most spawns match my 3.0.3 data perfectly, but some are really off, and I didn't see any patrols either. Most likely this matches the ClassicDB data, so I'll clean up the parsed data and post all spawn coordinates and waypoints. That way, you can update and correct as needed.

**Comment by cala** [comment]
Thank you @evil-at-wow for this very detail feedback. Once again, I'll be happy to see your parsed data to fix this. You are some kind of gold mine :)

Regarding the corner you want to avoid like the plague, I'm afraid you had to clean it up one moment or another because Argelmach is supposed to aggro the whole Manufactory when engaged.

**Comment by cala** [comment]
Kindly bump to our ever-busy @evil-at-wow about the spawn points/waypoints for these patrols. :)

**Comment by evil-at-wow** [comment]
@cala I didn't forget, but our ever-busy evil was cursing at failing hardware for the past week...

Anyway, let's post some data! The following list are static spawns, meaning the NPCs that spawn there do not move (not even random movement). The NPCs I'll mention are the ones I've actually observed for these spawns (in five runs), so they are not guaranteed to be an exhaustive list. Each table is listed roughly clockwise, starting at your left as you enter the Manufactory.

A Weapon Technician or a Doomforge Arcanasmith:

| x | y | z | o |  |
| --- | --- | --- | --- | --- |
| 759.862 | 58.2598 | -53.6085 | 3.9619 |  |
| 756.804 | 55.0023 | -53.5866 | 0.715585 |  |
| 756.6 | 52.5513 | -53.5831 | 3.90954 |  |
| 760.166 | 55.6209 | -53.6182 | 3.24631 |  |
| <br> |  |  |  |  |
| 809.952 | 49.7623 | -53.559 | 1.22173 | Yes, that's inside a table! |
| 804.537 | 50.8482 | -53.5804 | 0.139626 |  |
| <br> |  |  |  |  |
| 786.798 | -42.1107 | -53.6505 | 0.366519 |  |
| 793.538 | -34.395 | -53.631 | 5.28835 |  |

A Doomforge Arcanasmith:

| x | y | z | o |  |
| --- | --- | --- | --- | --- |
| 759.628 | 61.429 | -53.5742 | 3.21141 | Weapon Technician also possible? |

A Weapon Technician:

| x | y | z | o |  |
| --- | --- | --- | --- | --- |
| 755.346 | 51.0896 | -53.57 | 1.0472 |  |
| 755.999 | 61.6141 | -53.5721 | 6.21337 |  |
| 757.366 | 59.5952 | -53.5933 | 0.837758 |  |
| <br> |  |  |  |  |
| 778.728 | 42.3766 | -53.6518 | 2.19911 |  |
| 776.288 | 43.6711 | -53.6518 | 0.418879 |  |
| 781.008 | 46.79 | -53.6518 | 3.52557 |  |
| 778.715 | 47.5265 | -53.6518 | 4.7822 |  |
| <br> |  |  |  |  |
| 791.143 | -40.9252 | -53.6506 | 3.85718 |  |
| 787.464 | -40.3752 | -53.6493 | 5.23599 |  |
| <br> |  |  |  |  |
| 806.096 | 54.2448 | -53.5767 | 5.48033 | Doomforge Arcanasmith also possible? |
| <br> |  |  |  |  |
| 794.78 | -35.9308 | -53.6368 | 2.04204 | Doomforge Arcanasmith also possible? |

A Ragereaver Golem or a Wrath Hammer Construct:

| x | y | z | o |
| --- | --- | --- | --- |
| 779.212 | 44.9612 | -53.6518 | 3.19395 |
| 807.141 | 52.1214 | -53.5713 | 3.1765 |
| 789.356 | -42.4263 | -53.6514 | 1.95477 |

The Golem Lord Argelmach group:

| x | y | z | o |  |
| --- | --- | --- | --- | --- |
| 846.801 | 16.2806 | -53.6395 | 3.14159 | Golem Lord Argelmach |
| 851.842 | 13.2664 | -53.6419 | 2.28638 | Ragereaver Golem |
| 856.701 | 17.871 | -53.6308 | 2.53073 | Wrath Hammer Construct |

Then it gets more interesting. On the right side, there are golems, but their position can vary. I've seen four spawn points only for all of them. If you'd put them on the minimap, you could say they are the corners of a square. It looks like each point can spawn either a Ragereaver Golem or a Wrath Hammer Construct.

| x | y | z | o |  |
| --- | --- | --- | --- | --- |
| 794.549 | 2.11547 | -53.6519 | 3.28122 | NW |
| 793.348 | -9.29995 | -53.6518 | 3.07178 | NE |
| 780.244 | -9.44037 | -53.6513 | 1.72788 | SE |
| 779.154 | 1.81084 | -53.6518 | 0.0174533 | SW |

Analyzing my limited amount of data, exactly two points are taken out of this set of four, to spawn two NPCs, so you'll need to pool these. In my limited amount of data (five runs), one point was always 'north' and one was always 'south', but this might well be a wrong conclusion.

Around these two golems are also two Weapon Technician NPCs. These two have random movement. The annoying thing here is that the Manufactory is probably too far from the instance's entrance, so I looks like I didn't capture the actual spawns. All I got is random movement positions that vary slightly each run. So I guess Tobschinski needs to go kill them, then camp them for two hours so they respawn, and see where they spawn! :smiling_imp:

**Comment by evil-at-wow** [comment]
What follows are the waypoints for the six patrols, as my parser currently spits them out. In an earlier and similar post with the waypoints for a Dark Keeper, Tobschinski remarked that my data is 'wrong' in the sense that it sometimes lacks orientations. I believe this is indeed true (see third and fourth table), but I'll just post what I have now.

Once again, I believe I didn't capture the actual spawns, so I can't tell where the patrols actually spawn. But I do believe the waypoints are complete. The wait times I'm listing are what I've actually observed in my sniffs, give or take a few seconds maximum (so 20 seconds could actually be gap of 21.8 seconds between the packets). So a 20-50 range could still be betwen 20 and 60 in reality.

I believe these three patrols are the ones still present today:

| point | x | y | z |  |
| --- | --- | --- | --- | --- |
| 1 | 803.859 | 12.9567 | -53.6615 |  |
| 2 | 803.332 | 36.0541 | -53.6688 |  |
| 3 | 788.064 | 46.9496 | -53.7332 |  |
| 4 | 773.939 | 57.1793 | -53.7083 |  |
| 5 | 762.993 | 50.4319 | -53.7269 |  |
| 6 | 761.421 | 29.3542 | -53.6321 |  |
| 7 | 762.968 | 9.71107 | -53.701 |  |
| 8 | 769.319 | -3.63559 | -53.7241 |  |
| 9 | 777.615 | -18.1981 | -53.7212 |  |
| 10 | 792.493 | -18.6761 | -53.6741 |  |
| 11 | 802.697 | -9.92748 | -53.6707 |  |

| point | x | y | z |  |
| --- | --- | --- | --- | --- |
| 1 | 762.349 | 41.594 | -53.7146 |  |
| 2 | 799.356 | 43.3486 | -53.6921 |  |
| 3 | 803.831 | 32.7512 | -53.6365 |  |
| 4 | 799.356 | 43.3486 | -53.6921 |  |
| 5 | 762.349 | 41.594 | -53.7146 |  |
| 6 | 761.201 | 22.3508 | -53.6527 |  |
| 7 | 777.259 | 21.7293 | -53.6562 |  |
| 8 | 781.122 | 8.1129 | -53.6999 |  |
| 9 | 798.227 | 7.70171 | -53.6888 |  |
| 10 | 802.456 | -8.26351 | -53.6719 |  |
| 11 | 795.791 | -21.864 | -53.6543 |  |
| 12 | 813.282 | -40.8431 | -53.746 |  |
| 13 | 795.791 | -21.864 | -53.6543 |  |
| 14 | 802.456 | -8.26351 | -53.6719 |  |
| 15 | 798.227 | 7.70171 | -53.6888 |  |
| 16 | 781.122 | 8.1129 | -53.6999 |  |
| 17 | 777.259 | 21.7293 | -53.6562 |  |
| 18 | 761.201 | 22.3508 | -53.6527 |  |

| point | x | y | z |  |
| --- | --- | --- | --- | --- |
| 1 | 782.138 | -45.6668 | -53.7721 |  |
| 2 | 778.198 | -33.9222 | -53.7311 |  |
| 3 | 783.974 | -27.3003 | -53.6742 |  |
| 4 | 762.94 | 8.65715 | -53.71 |  |
| 5 | 761.041 | 41.1992 | -53.7038 |  |
| 6 | 753.723 | 41.7996 | -53.6441 | Wait for 20-60 seconds. |
| 7 | 764.597 | 45.6037 | -53.7352 |  |
| 8 | 774.852 | 60.0696 | -53.6795 |  |
| 9 | 774.852 | 60.0696 | -53.6795 | NPC turns -missing orientation! Also wait for 5 seconds. |
| 10 | 784.549 | 54.0242 | -53.7352 |  |
| 11 | 785.148 | 35.8518 | -53.6995 |  |
| 12 | 776.289 | 27.4625 | -53.6255 | Wait for 20 seconds. |
| 13 | 776.729 | 26.9007 | -53.6282 |  |
| 14 | 783.783 | 14.001 | -53.6906 |  |
| 15 | 786.595 | -12.3495 | -53.7113 |  |
| 16 | 784.733 | -32.3172 | -53.7235 |  |
| 17 | 784.662 | -39.4896 | -53.7492 |  |
| 18 | 781.288 | -46.3105 | -53.7746 | Wait for 20-50 seconds. |

And these three no longer exist. I would be very surprised if these didn't spawn at one of the book shelves though, so you might want to change the order.

| point | x | y | z |  |
| --- | --- | --- | --- | --- |
| 1 | 792.438 | 45.7173 | -53.7176 |  |
| 2 | 795.405 | 38.8804 | -53.6981 |  |
| 3 | 800.774 | 35.1317 | -53.6755 |  |
| 4 | 800.455 | 27.8962 | -53.6365 |  |
| 5 | 800.281 | 15.0601 | -53.6782 |  |
| 6 | 804.687 | -0.79423 | -53.6417 |  |
| 7 | 809.65 | -1.35354 | -53.5894 | Wait for 40 seconds. |
| 8 | 808.37 | -0.974017 | -53.6027 |  |
| 9 | 798.703 | -14.2282 | -53.6685 |  |
| 10 | 785.097 | -22.9216 | -53.6839 |  |
| 11 | 778.349 | -26.1744 | -53.6948 | Wait for 30 seconds. |
| 12 | 779.015 | -25.8711 | -53.6937 |  |
| 13 | 770.726 | -10.8395 | -53.731 |  |
| 14 | 765.311 | 6.20587 | -53.7134 |  |
| 15 | 763.947 | 21.5177 | -53.6724 |  |
| 16 | 777.62 | 24.3637 | -53.6415 |  |
| 17 | 787.35 | 36.6482 | -53.6692 |  |
| 18 | 790.302 | 56.138 | -53.7397 |  |
| 19 | 791.537 | 60.003 | -53.6842 | Wait for 15 seconds. |
| 20 | 790.544 | 58.6389 | -53.6977 |  |
| 21 | 791.594 | 46.1057 | -53.7208 |  |
| 22 | 791.594 | 46.1057 | -53.7208 | Missing orientation! Wait for 30 seconds. |

| point | x | y | z |  |
| --- | --- | --- | --- | --- |
| 1 | 773.925 | 3.11658 | -53.7172 |  |
| 3 | 774.192 | -10.6106 | -53.7327 |  |
| 4 | 786.545 | -21.9167 | -53.6825 |  |
| 5 | 785.527 | -33.0789 | -53.726 |  |
| 6 | 789.237 | -36.13 | -53.7359 |  |
| 7 | 785.527 | -33.0789 | -53.726 |  |
| 8 | 786.545 | -21.9167 | -53.6825 |  |
| 9 | 774.192 | -10.6106 | -53.7327 |  |
| 10 | 773.925 | 3.11658 | -53.7172 |  |
| 11 | 781.98 | 7.79252 | -53.6991 |  |
| 12 | 783.496 | 44.9433 | -53.7352 |  |
| 13 | 784.57 | 58.7309 | -53.6953 |  |
| 14 | 783.496 | 44.9433 | -53.7352 |  |
| 15 | 781.98 | 7.79252 | -53.6991 |  |

| point | x | y | z |  |
| --- | --- | --- | --- | --- |
| 1 | 811.87 | -25.2166 | -53.6904 |  |
| 2 | 796.794 | -14.5872 | -53.6733 |  |
| 3 | 803.802 | -5.47762 | -53.6552 |  |
| 4 | 800.327 | 11.2513 | -53.6704 |  |
| 5 | 803.43 | 28.3222 | -53.6365 |  |
| 6 | 803.879 | 39.4262 | -53.672 |  |
| 7 | 810.038 | 40.6187 | -53.6542 | Wait for 30-50 seconds. |
| 8 | 809.069 | 40.2641 | -53.6568 |  |
| 9 | 801.317 | 31.8698 | -53.6365 |  |
| 10 | 796.212 | 24.2951 | -53.6492 |  |
| 11 | 780.355 | 12.836 | -53.6862 |  |
| 12 | 774.289 | 3.12628 | -53.7185 |  |
| 13 | 758.585 | 1.25146 | -53.714 | Wait for 20-60 seconds. |
| 14 | 768.231 | 0.35128 | -53.72 |  |
| 15 | 775.579 | -15.6753 | -53.7378 |  |
| 16 | 791.5 | -26.4753 | -53.7006 | Wait for 20 seconds. |
| 17 | 791.093 | -26.4291 | -53.7006 |  |
| 18 | 795.717 | -22.4336 | -53.6528 |  |
| 19 | 812.793 | -25.571 | -53.6914 | Wait for 30-60 seconds. |

Enjoy!

**Comment by cala** [comment]
>  I didn't forget, but our ever-busy evil was cursing at failing hardware for the past week

You have all my sympathy. I hate when this happens to me.

Thank you very much for all those data!! I'll translate them into DB queries soon, hopefully next week. :+1:

**Comment by Tobschinski** [comment]
Nice one, thanks a lot.

**Comment by evil-at-wow** [comment]
In just realized I forgot to mention a few things last night!
- It's always good to know the source of data, if only to avoid any confusion or doubt: this is data from version 3.0.3, build 9183.
- I've seen the patrols above in my data as either a Weapon Technician or a Doomforge Arcanasmith, _except_ for two of them, which I've only seen as Weapon Technicians (the second and fifth one). As usual, that's not a guarantee that a Doomforge Arcanasmith isn't possible for those two patrols, but it becomes somewhat unlikely after seeing five Weapon Technicians in a row.
