### ISSUE TITLE
AT-Script 1786 is missing

### ISSUE THREAD

**Issue by Tobschinski** [classicdb/database#777]
If triggered, two Anvilrage Guardsman will spawn on both sides and move towards the middle of the bridge.

**Comment by Tobschinski** [comment]
Spawns:
Guardsman 1 - X: 642.3660 Y: -274.5155 Z: -43.10918 O: 0.4712389
Guardsman 2 - X: 740.1137 Y: -283.3448 Z: -42.75082 O: 2.8623400

---

Waypoints:
Guardsman 1 - 685.8903 Y: -279.7297 Z: -43.19436
Guardsman 2 - will constantly move towards Guardsman 1

---

Guardsman 1 will yell on spawn:
Language: Universal
Target: Triggering PC
Text: You can't hide from us.  Prepare to burn!

---

Both, Guardsman 1 and 2 will switch to random movement (r 1) if they reach their destination. Both will always evade to their new position if engaged in combat and not to their initial spawn-point.

**Comment by Tobschinski** [comment]
https://github.com/classicdb/database/commit/c7d92ba36bdd334390ea79d391190e3e85891416

**Comment by cala** [comment]
Currently scripting it in SD2.

**Comment by Tobschinski** [comment]
I failed hard when I wanted to move their spawn-point.

**Comment by cala** [comment]
That's also where I'm struggling: they move back to their original spawn-point and I did not find a way to change their contact point yet.

**Comment by Tobschinski** [comment]
They are also linked by the way. Both will attack if you engage one.

**Comment by cala** [comment]
Pull request for this: https://github.com/scriptdev2/scriptdev2/pull/175/

**Comment by cala** [comment]
All BRD related parts requiring SD2 are now scripted in this [pull request](https://github.com/scriptdev2/scriptdev2/pull/175) pending review and backport. So I'm closing this issue on the DB side. Thank you very much for your help.
