### ISSUE TITLE
Missing creatures: Portal Seeker (Blasted Lands)

### ISSUE THREAD

**Issue by Neotmiren** [classicdb/database#779]
They are the only source of `Pattern: Heavy Scorpid Vest` (10% drop chance)

``` sql
INSERT INTO creature (id,map,position_x,position_y,position_z,orientation,spawntimesecs,spawndist,curhealth,curmana,MovementType) VALUES
(5981, 0, -11500, -3041, -1,    0.619, 430, 6, 2131, 0, 1),
(5981, 0, -11444, -3038, 1.239, 5.285, 430, 7, 2131, 0, 1),
(5981, 0, -11397, -2926, 3.257, 4.305, 430, 6, 2131, 0, 1),
(5981, 0, -11381, -3013, -4,    3.849, 430, 6, 2131, 0, 1),
(5981, 0, -11371, -2856, 4.901, 4.067, 430, 6, 2131, 0, 1),
(5981, 0, -11359, -2797, 5.421, 4.76,  430, 7, 2131, 0, 1),
(5981, 0, -11352, -2755, 7.84,  3.888, 430, 6, 2131, 0, 1),
(5981, 0, -11331, -2986, 3.603, 2.103, 430, 7, 2131, 0, 1);
```

Source:  SDB (DB from Classic time)

**Comment by cala** [comment]
Is this Silvermoon DB?

**Comment by Neotmiren** [comment]
I think no. It is very old DB. It has no data related to TBC at all (MangosZero / Classis DB has). I can upload it somewhere if you are interested.

**Comment by cala** [comment]
I would appreciate this, please. :)

**Comment by Neotmiren** [comment]
Searching by file name "SDB_0.6.1", I managed to find existing download location
http://filebeam.com/04e6e7a86d0369553a14792277abc27b

Notice its upload date. Thanks to filebeam.com service, which keeps such files (barely dowloaded frequently) for more than 8 years.

**Comment by cala** [comment]
Thank you for this link. It looks very useful.
I checked from an old source and your data seems quite ok. I just need to ensure that there are no duplicate amongst those 8 spawns (pathing NPC sniffed twice and counted as two different ones).

**Comment by cala** [comment]
After looking at the position of the eight spawns above, it is very likely that they are in fact eight waypoints of a single patrolling NPCs (circular patrol). Also, comments here and there tend to suggest there was only one NPC back in Classic.
So, I would go with one patrolling NPC.

**Comment by Neotmiren** [comment]
Yes, this seems to be a single creature. I read "Portal Seekers can be found in the Blasted Lands" in wowwiki at first and after that not even considered other variants.
