### ISSUE TITLE
Ubrs - bonfires at enterance to Beast lair

### ISSUE THREAD

**Issue by stan84** [classicdb/database#78]
There should be a 6 orcbonfires in a row at enterance to Beast lair in UBRS. 
3 bigger and 3 bit smaller, gameobjects #126312 and #126313 could be used for this.
Both gobject has same scale i prpose change one to 1.2 or 1.
Dont know their certain xyz coords, i saw them in reatil and old YT movies.  

something like that http://imageshack.com/a/img94/179/9qnm.jpg, fast placed by hand

**Comment by cala** [comment]
Thank you for this report, I remember those bonefires.
