### ISSUE TITLE
Cliff Giant / Land Walker collision (Feralas)

### ISSUE THREAD

**Issue by Neotmiren** [classicdb/database#781]
``` sql
DELETE FROM creature WHERE guid=51697 AND id=5358; -- this Cliff Giant #51697 has the same coordinates as Land Walker #51692
```

**Comment by cala** [comment]
Thanks.
I would remove both of them: they really look like manually added spawns (no movement, same orientation, too close of other spawns...)

**Comment by Neotmiren** [comment]
Yes, it may seem strange... but considering sequential numbering of GUIDs in range 51684..51704 for Cliff Giants and Land Walkers they do not look as manually added.

**Comment by cala** [comment]
I agree with you it is strange, but sequential numbers on GUIDs can come from many things related to DB management like sorting guids out, auto-population of an area based on several mix-sources (sniffs + manual work and I assume this is what happened here)...

In my opinion, both of them should be removed. Usually, still/idle hostile NPCs in the world are either "named"/involved in something specific or wandering NPCs that are missing their WP. Those are obviously not named or specific and I found nowhere trace of patrolling giants in the area. Plus, they are overlapping with nearby NPCs with random movement. Hence the removal suggestion.
