### ISSUE TITLE
Missing Midsummer Festival gameobjects

### ISSUE THREAD

**Issue by Neotmiren** [classicdb/database#784]
These objects are required for one of Midsummer quests and should have fixed ID numbers.

``` sql
INSERT IGNORE gameobject (guid, id, map, position_x, position_y, position_z, orientation, rotation0, rotation1, rotation2, rotation3, spawntimesecs, animprogress, state) VALUES
 (39794, 181561, 1, 1916.99, -2033.11, 103.89, 2.76462, 0, 0, 0.982289, 0.187372, 600, 100, 1),   -- Flame of Ashenvale
 (39795, 181560, 1, -914.339, -3347.22, 94.7678, 1.81427, 0, 0, 0.787742, 0.616005, 600, 100, 1), -- Flame of the Barrens
 (39796, 181563, 1, 4364.96, 229.192, 53.5103, 5.93761, 0, 0, 0.171929, -0.985109, 600, 100, 1),  -- Flame of Darkshore
 (39797, 181562, 1, 636.417, 336.333, 52.0252, 3.31442, 0, 0, 0.996269, -0.0863062, 600, 100, 1), -- Flame of Stonetalon
 (55203, 181564, 0, -281.426, 1171.33, 63.6401, 5.26475, 0, 0, 0.487494, -0.873126, 600, 100, 1), -- Flame of Silverpine
 (55204, 181565, 0, -11277, 1853.95, 40.1741, 5.94853, 0, 0, 0.166548, -0.986033, 600, 100, 1),   -- Flame of Westfall
 (55205, 181566, 0, -345.467, -668.955, 55.2845, 3.07144, 0, 0, 0.999385, 0.0350691, 600, 100, 1),-- Flame of Hillsbrad
 (55206, 181567, 0, -2622.55, -2504.01, 82.8143, 3.15764, 0, 0, 0.999968, -0.00802358, 600, 100, 1); -- Flame of the Wetlands

INSERT IGNORE game_event_gameobject (guid,event) VALUES (39794,1),(39795,1),(39796,1),(39797,1),(55203,1),(55204,1),(55205,1),(55206,1);
```

**Comment by cala** [comment]
Poke @Zingzah who is working right now on Midsummer Festival for Classic. That could interest him.

**Comment by Neotmiren** [comment]
@Zingzah: To make sure, there are coordinates of locations of all Midsummer Flames in the times of Classic.
http://wowwiki.wikia.com/Midsummer_Fire_Festival?oldid=631273

**Comment by Zingzah** [comment]
Thanks for the spot Neot.  Your first post looks very much like sniff data.  It's something I've been asking for in the forums about Midsummer with no takers atm.  I prefer actual data over best/closest guesses which is how I'm placing npcs/objects from screenshots.  Wowwiki coordinates give a general area but is far too imprecise for the accuracy and lack additional information such as orientation.  If you have sniff data I would love some retail info on npcs/objects associated with the event.

**Comment by Neotmiren** [comment]
It is not likely that someone has sniffs from a few weeks of Summer 2006. The data above is taken from later TBC/WotLK databases (sniffs/client WDB cache). Such data should be correct if its coordinates are identical to wowwiki (but I did not check numbers, only text description of locations). Maybe it is possible to extract more valid Classic data from YTDB or UDB.

GUIDs of green "Flame of ..." gameobjects correspond to ones in quest_template table. Notice that Classic DB quest_template data seems to be of earlier origin (from Classic time).

The only Classic time database I have - SDB (Silver DataBase) does not have Midsummer Festival event gameobjects (Alliance/Horde Bonfire, Flame of ...).

It would be nice to have NPC and Quest structure fully implemented, even not being 100% sure about precise coordinates and orientations (which could be corrected later at any time).

**Comment by cala** [comment]
Closed by https://github.com/classicdb/database/commit/5f438d9952e558dd0eb77a9f57549167917b464b
Thanks both of you! :+1:
