### ISSUE TITLE
Mining Nodes overlapping

### ISSUE THREAD

**Issue by scotty0100** [classicdb/database#789]
In the cave at the back entrance to Uldaman, there are 2 mine spawn points that EACH spawn Iron, Silver, Truesilver, Gold, and Mithril at the same time. (5 mines overlapping each other, at once, in two locations.)

**Comment by cala** [comment]
Closed in https://github.com/classicdb/database/commit/4dc8e13020f63b9427fd08c49dfd5c3ef2bdc3c5
Thank you. :+1:
