### ISSUE TITLE
War Master Voone no weapon

### ISSUE THREAD

**Issue by stan84** [classicdb/database#79]
War Master Voone in LBRS is unarmed, should have 2 axes 22319

INSERT INTO `mangos`.`creature_equip_template_raw` (`entry`, `equipmodel1`, `equipmodel2`, `equipmodel3`, `equipinfo1`, `equipinfo2`, `equipinfo3`, `equipslot1`, `equipslot2`, `equipslot3`) VALUES ('967', '22319', '22319', '0', '33488898', '33488898', '0', '781', '781', '0');

UPDATE `mangos`.`creature_template` SET `equipment_id`='967' WHERE `entry`='9237';

**Comment by cala** [comment]
Thank you, I'll test this soon(tm).
