### ISSUE TITLE
Class Paladin - Classlevelstats

### ISSUE THREAD

**Issue by Tobschinski** [classicdb/database#791]
Redo the armor for all paladins, it does not seem to be correct.

**Comment by Tobschinski** [comment]
e.g. The most common armor value for 63 paladins is 3795 - the basearmor in the classlevelstats-table is 4637

**Comment by cala** [comment]
Closed I'm afraid the problem is bigger than expected at first. See my answer in #790 
I close this issue to focus the discussion on the other one.
