### ISSUE TITLE
missing creature_template

### ISSUE THREAD

**Issue by Tobschinski** [classicdb/database#792]
1849 - Dreadwhisper 
~~? - Maggosh~~

investigate further ...

**Comment by cala** [comment]
Dreadwhisper is in every DB but Classic DB. Weird.
Maggosh is possibly a renamed NPC (ring a bell in my head).

**Comment by Tobschinski** [comment]
I'm just dumb, Maggosh is Magosh, a level 21 trogg.

**Comment by cala** [comment]
Below is the entry (stats for Classic):

``` SQL
DELETE FROM `creature_template` WHERE `Entry` = 1849;
INSERT INTO `creature_template` VALUES
(1849, 'Dreadwhisper', '', 58, 58, 4629, 0, 35, 35, 1, 0, 6, 3, 3, 0, 0, 0, 0, 0, 0, 1.2, 1.14286, 1, 4, 1.35, 1, 1, 1, 1, 1, 3876, 3876, 0, 0, 100, 132, 69, 101, 3457, 242, 25, 2000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8388624, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '');
```

I could not find any data of his spawn point. However, it is still present in the game and wowhead has map and screenshot for it that should allow us to spawn him with an acceptable accuracy:
http://www.wowhead.com/npc=1849/dreadwhisper#map
http://www.wowhead.com/npc=1849/dreadwhisper#screenshots:id=243137

**Comment by Tobschinski** [comment]
If he's still at the same spot, I will have a look at him.

**Comment by Tobschinski** [comment]
Faction is 21.

Position: X: 1753.88 Y: -2335.215 Z: 59.89574
Orientation: 2.373648

Since there is absolutely no info about this guy anywhere, I start to believe he was part of the Scourge Invasion and came back with Cataclysm, or was never ingame before.

I know of other rares that never made it into the game pre 4.0, http://www.wowhead.com/npc=62/gug-fatcandle - https://twitter.com/Muffinus/status/454377272774893569

**Comment by cala** [comment]
He is referenced in the master guide but indeed unknown to me though I spent a lot of time in the Plaguelands, farming Argent Dawn reputation. Also, archives show him only on test realm:
http://web.archive.org/web/20070509133014/http://wow.allakhazam.com/dyn/mobs/rare.html

I'm also more and more thinking that only its template should be added...
