### ISSUE TITLE
BRD Arena - Trash

### ISSUE THREAD

**Issue by Tobschinski** [classicdb/database#793]
Waves:
2 \* 2 - Deep Stinger
2 \* 3 - Cave Creeper
2 \* 3 - Burrowing Thundersnout
2 \* 4 - Dredge Worm
2 \* 5 - Dark Screecher
2 \* 7 - Borer Beetle

-> prob. wrong models
-> diff timers
-> correct spawnpos

**Comment by cala** [comment]
The rest of this issue will require SD2 update.

**Comment by Tobschinski** [comment]
I still have to verify if these models were used ...

| name | model 1 | model 2 | model 3 | model 4 |
| --- | --- | --- | --- | --- |
| Deep Stinger | 7347 | 3247 | 2489 | 0 |
| Dark Screecher | 1955 | 1954 | 0 | 0 |
| Burrowing Thundersnout | 8184 | 9033 | 3005 | 2194 |
| Dredge Worm | 8182 | 9030 | 9031 | 9032 |
| Cave Creeper | 8014 | 909 | 821 | 520 |
| Borer Beetle | 7470 | 9354 | 9028 | 9029 |

**Comment by Tobschinski** [comment]
It is mandatory to add two more fields to creature_template. Alternating gender models must not be used.

**Comment by cala** [comment]
You mean that those NPCs are all spawned as male in retail even though they are using 4 different model types?

**Comment by Tobschinski** [comment]
I do not even know. I just don't know how I could store 4 ids without touching other creatures. These models are used elsewhere.

**Comment by cala** [comment]
You said yesterday that you already have a core update for this. If you do a pull request to core repository, I can merge it and we will then proceed to the DB structure update.

**Comment by Tobschinski** [comment]
https://github.com/Tobschinski/Classic-Core/commit/ea5df337baf9cffc50ed599b0a9f29c4f853775f

**Comment by cala** [comment]
Thank you. I'll merge it this WE. :+1:

**Comment by cala** [comment]
The correct number of NPCs per wave is handled in: https://github.com/cala/scriptdev2/commit/6e7eaaff4b50357b864166a3edcd83c740c28601 which is part of the currently open PR for SD2 regarding Blackrock Depths.

**Comment by cala** [comment]
Your update is merged in core and DB repository! :+1:

**Comment by Tobschinski** [comment]
Each of these groups have individual waypoints, but there is no efficient way to do this ...

**Comment by cala** [comment]
Aside from hardcoding them in SD2, I don't see how either.

**Comment by cala** [comment]
I updated the spawn points and number of NPCs per wave according to your data.
However, they have still the same timer and spawn point. Changing them could be possible but would require much more changes in the script and I don't know if this would be really noticeable (at least worst the effort). Thank you for your help.

All BRD related parts requiring SD2 are now scripted in this [pull request](https://github.com/scriptdev2/scriptdev2/pull/175) pending review and backport. So I'm closing this issue on the DB side.
