### ISSUE TITLE
Non-swimming jerky movemement of creatures in water

### ISSUE THREAD

**Issue by Neotmiren** [classicdb/database#795]
There are at least two water-only creatures unable to swim properly that should be fixed: Rippa (rare, Stranglethorn Vale) and Canal Frenzy.

Moreover, it seems that Swimming Flag for WoW client (unit_flags|32768) should be set to almost all creatures with IhnabitType&2 bit set.

Here is what I use now:

``` sql
UPDATE creature_template SET unit_flags=unit_flags|32768 WHERE (InhabitType&2)!=0 AND NOT type IN (5) AND not family IN (8);
```

Crabs and Giants are excluded here. Setting this flag to them leads to different animation in case of crabs and crawlers (they start to swim, not crawl), and no animation at all in case of giants. Should be there some other exclusions?

Swimming flag must also be supported in the core, in Random Movement Generator. Water-tolerant creatures (InhabitType&2) must be differentiated by (unit_flags&32768) into two cases:

1) they use 3D movement in water.
2) they use 2D movement at the bottom of waterbody.

Changes to the core should be very simple. I already implemented it in my version of Classic Core: giants and crabs walk, other creatures swim.

**Comment by cala** [comment]
poke @cyberium about the core part since this is him who remade recently the random movement generator.

**Comment by cyberium** [comment]
> Changes to the core should be very simple. I already implemented it in my version of Classic Core: giants and crabs walk, other creatures swim.

@Neotmiren did you made any Pull request then?

**Comment by Neotmiren** [comment]
I worked only with Classic code and it has become quite different from raw CMangos (many things fixed/implemented/tweaked for single player multiclass). In this case, I did not apply Random Movement Generator patch from repository, but had made another version of Random Movement code... and fixed some related issues: if I remember correctly, current CMangos Random Movement should have bug with low water levels: check creatures in Swamp of Sorrows (in "water canals").

**Comment by cyberium** [comment]
Do you have more information about UnitFlags 32768? What its purpose exactly.

**Comment by Neotmiren** [comment]
It seems very simple. With this flag set Classic Client switches to swimming visual animation type when creature enters water.

Not all creatures have swimming animation implemented. Sea Giants have not, for example. Crabs have, but only crab pets should use it, probably.
