### ISSUE TITLE
Missing creature_linking for Moon Priestess Amara

### ISSUE THREAD

**Issue by Muehe** [classicdb/database#799]
[Moon Priestess Amara](http://db.vanillagaming.org/?npc=2151) (GUID 46394) should be followed by [Huntress Nhemai](http://db.vanillagaming.org/?npc=10604) (GUID 46414) and [Huntress Yaeliura](http://db.vanillagaming.org/?npc=10606) (GUID 46416). Right now they have individual waypoint movement, which desyncs the group when Amara is stoping to give/accept her quest.

**Comment by yankellch** [comment]
and the position now also wrong,Moon Priestess Amara (GUID 46394)  should in the middle leading the way.

**Comment by Tobschinski** [comment]
ManGOS lacks support for moving formations, they will sooner or later be out of sync either way, sadly.

**Comment by Muehe** [comment]
This doesn't really look good, but at least the Huntresses follow correctly instead of walking on their own:

``` sql
UPDATE creature SET MovementType = 0 WHERE guid IN (46414, 46416);
DELETE FROM creature_linking WHERE guid IN (46394, 46414, 46416);
INSERT INTO creature_linking  VALUES (46414, 46394, 515); -- AGGRO_ON_AGGRO, TO_AGGRO_ON_AGGRO, FOLLOW
INSERT INTO creature_linking  VALUES (46416, 46394, 515); -- AGGRO_ON_AGGRO, TO_AGGRO_ON_AGGRO, FOLLOW
```

Wasn't there an issue/a forum discussion about patrol formations? I think that's a seperate problem.

**Comment by cala** [comment]
There is a forum discussion about it IIRC. Patrols/formations are core stuff, so even if it looks ugly after some time, I think this is not DB mission to compensate for the lack of a core feature.

Currently formations are handle this way : slave tries to keep the same angle/position from master than the one it had a spawn. However, since paths are obviously different and speed is constant, they slowly move out of sync.

One solution I thought of but never tried to implement is to check the first and second derivative of the NPC distance from master and depending on the sign of each, make the slave NPC stop, walk or run. Obviously, some threshold parameter would also be used here in order to decide when to switch the modes.

**Comment by Muehe** [comment]
This solution seems to work quite well:

``` sql
-- Set CREATURE_FLAG_EXTRA_ACTIVE for the patrol
UPDATE creature_template SET ExtraFlags = 4096 WHERE entry IN (2151, 10604, 10606);

-- Updated Spawn positions
UPDATE creature SET position_x = '9847.158203', position_y = '1033.056885', position_z = '1304.841553', orientation = '1.598161' WHERE guid = '46394';
UPDATE creature SET position_x = '9848.743164', position_y = '1030.924561', position_z = '1304.877075', orientation = '1.598161' WHERE guid = '46416';
UPDATE creature SET position_x = '9844.817383', position_y = '1030.817139', position_z = '1304.843262', orientation = '1.598161' WHERE guid = '46414';

-- Link patrol together
UPDATE creature SET MovementType = 0 WHERE guid IN (46414, 46416);
DELETE FROM creature_linking WHERE guid IN (46394, 46414, 46416);
INSERT INTO creature_linking  VALUES (46414, 46394, 515); -- AGGRO_ON_AGGRO, TO_AGGRO_ON_AGGRO, FOLLOW
INSERT INTO creature_linking  VALUES (46416, 46394, 515); -- AGGRO_ON_AGGRO, TO_AGGRO_ON_AGGRO, FOLLOW

-- Set new Waypoints, with 1 or 2 minute waittime on turning points
DELETE FROM creature_movement WHERE id IN (46394, 46414, 46416);
DELETE FROM creature_movement_template WHERE entry IN (2151, 10604, 10606);
INSERT INTO creature_movement_template (entry, point, position_x, position_y, position_z, orientation, waittime, script_id) VALUES
(2151,1,9848.04,1041.22,1304.85,100,0,0),
(2151,2,9858.52,1069.36,1307.46,100,0,0),
(2151,3,9875.29,1083.34,1308.01,100,0,0),
(2151,4,9882.02,1097.79,1307.99,100,0,0),
(2151,5,9883.15,1111.71,1307.96,100,0,0),
(2151,6,9890,1120.49,1307.86,100,0,0),
(2151,7,9907.28,1132.35,1307.9,100,0,0),
(2151,8,9914.82,1147.38,1307.86,100,0,0),
(2151,9,9918.2,1163.74,1307.88,100,0,0),
(2151,10,9916.63,1182.79,1308.02,100,0,0),
(2151,11,9911.21,1195.08,1308.58,100,0,0),
(2151,12,9909.48,1204.53,1308.46,100,0,0),
(2151,13,9911.23,1216.3,1307.86,100,0,0),
(2151,14,9922.35,1235.1,1307.82,100,0,0),
(2151,15,9930.69,1241.98,1307.91,100,0,0),
(2151,16,9939.68,1245.05,1307.84,100,0,0),
(2151,17,9950.57,1245.9,1307.82,100,0,0),
(2151,18,9974.05,1243.7,1307.86,100,0,0),
(2151,19,9986.35,1244.66,1307.86,100,0,0),
(2151,20,9996.67,1249.89,1307.86,100,0,0),
(2151,21,10004.9,1258.47,1307.86,100,0,0),
(2151,22,10019.9,1280.59,1307.57,100,60000,0),
(2151,23,10004.9,1258.47,1307.86,100,0,0),
(2151,24,9996.67,1249.89,1307.86,100,0,0),
(2151,25,9986.35,1244.66,1307.86,100,0,0),
(2151,26,9974.05,1243.7,1307.86,100,0,0),
(2151,27,9950.57,1245.9,1307.82,100,0,0),
(2151,28,9939.68,1245.05,1307.84,100,0,0),
(2151,29,9930.69,1241.98,1307.91,100,0,0),
(2151,30,9922.35,1235.1,1307.82,100,0,0),
(2151,31,9911.23,1216.3,1307.86,100,0,0),
(2151,32,9909.48,1204.53,1308.46,100,0,0),
(2151,33,9911.21,1195.08,1308.58,100,0,0),
(2151,34,9916.63,1182.79,1308.02,100,0,0),
(2151,35,9918.2,1163.74,1307.88,100,0,0),
(2151,36,9914.82,1147.38,1307.86,100,0,0),
(2151,37,9907.28,1132.35,1307.9,100,0,0),
(2151,38,9890,1120.49,1307.86,100,0,0),
(2151,39,9883.15,1111.71,1307.96,100,0,0),
(2151,40,9882.02,1097.79,1307.99,100,0,0),
(2151,41,9875.29,1083.34,1308.01,100,0,0),
(2151,42,9858.52,1069.36,1307.46,100,0,0),
(2151,43,9848.04,1041.22,1304.85,100,0,0),
(2151,44,9847.16,1033.06,1304.84,100,120000,0);


```

Pros:
- Better waypoints (no weird movement, like moving up and down rapidly)
- Behave as group
- "Proper" formation

Cons:
- Waittimes are guesswork
- Start and spawn points are guesswork
- Not sure if ExtraFlags are needed, from my understanding they keep the patrol from splitting up or stoping when no players are nearby.

**Comment by cala** [comment]
Tested in-game and this looks indeed nice. :+1: 

> - Waittimes are guesswork
> - Start and spawn points are guesswork

I don't know if this patrol still exist on live servers, (almost) correct values would then be easy to check. Your version looks good to me, I would have said that start point should be closer to Dolanaar, but I may be wrong.

> - Not sure if ExtraFlags are needed, from my understanding they keep the patrol from splitting up or stoping when no players are nearby.

This extra flag is used to make creatures active at server startup even if no players are on the map. This is may be useful for NPCs with long paths like the Forsaken Courrier or the Crimson Courier but here, I don't think it would bring a real advantage given the short patrol path.

**Comment by Muehe** [comment]
Not sure on this but I think I have read that the patrol got removed somewhere. 

Also I seem to remember the patrol splitting up when ExtraFlags wasn't set, but couldn't reproduce afterwards. The point where the patrol waits in front of the village is a complete guess, so it could really have been closer. The one where it turns back is basically the same as before, with a little adjustment for formation.
