### ISSUE TITLE
Quest 8460 rewards too much XP

### ISSUE THREAD

**Issue by cala** [classicdb/database#8]
The quest "Timbermaw Ally" works except it grants 63,000exp instead of what I assume should be 6,300exp. I just completed it using the build I built tonight from the repository, so this is a current stable build, not testing.

_original report by [The-Great-Sephiroth](https://github.com/The-Great-Sephiroth)_

**Comment by cala** [comment]
Submitted fix by Evildead666: https://github.com/Evildead666/database/commit/ca937eb1a3197ebaccf496f27b75d39bbead9c6a

Also concern two other quests:

> Correcting xp of quests 8460, 8464, 8485, was 10x to high

**Comment by cala** [comment]
Fixed in rev [0142] https://github.com/classicdb/database/commit/c252b03ea5c6ea0d78218c316fcd48344594fee6

**Comment by Schmoozerd** [comment]
Btw, you can automatically close issues with writing into the commit message " close #XX or " fix #xx "

Full list: https://help.github.com/articles/closing-issues-via-commit-messages
