### ISSUE TITLE
Awbee UBRS

### ISSUE THREAD

**Issue by stan84** [classicdb/database#80]
Awbee Small dragon is nearly death always was on the ground, not flying

INSERT INTO `mangos`.`creature_template_addon` (`entry`, `mount`, `bytes1`, `b2_0_sheath`, `b2_1_flags`, `emote`, `moveflags`) VALUES ('10740', '0', '7', '0', '0', '0', '0');

**Comment by cala** [comment]
Though we should be happy that Awbee is getting better, thank you for this report, I'll look at it.
