### ISSUE TITLE
Naxxramas - Living Posion

### ISSUE THREAD

**Issue by Tobschinski** [classicdb/database#804]
I don't think the database can handle these type of spawns. Pop some and they will quickly go out of sync, because they re-spawn.

Something else must constantly spawn these type of creatures.

**Comment by cala** [comment]
When I did it using DBscripts long ago, my SD2 skills were close to zero.
Would I have to redo it now, I would definitely use SD2 instead, mostly for the reason you describe.
So, I'll redo it later in SD2, thanks.

**Comment by Tobschinski** [comment]
spawnpos

|  | t | x | y | z | (o) |
| --- | --- | --- | --- | --- | --- |
| A | 21:39:46.081 | 3128.507 | -3131.873 | 294.0651 | (4.725505) |
| B | 21:39:46.081 | 3151.084 | -3137.727 | 294.0628 | (4.456693) |
| C | 21:39:46.081 | 3169.601 | -3146.016 | 294.0564 | (4.244928) |

next wave - 21:39:50.824
next wave - 21:39:55.987
next wave - 21:40:01.229
next wave - 21:40:06.486
next wave - 21:40:11.743

That's roughly once per 5s!

**Comment by Tobschinski** [comment]
waypoints

|  | x | y | z |
| --- | --- | --- | --- |
| A | 3128.614 | -3140.014 | 294.0628 |
| A | 3128.709 | -3157.404 | 293.3238 |

|  | x | y | z |
| --- | --- | --- | --- |
| B | 3150.380 | -3140.421 | 294.0628 |
| B | 3145.881 | -3158.563 | 293.3216 |

|  | x | y | z |
| --- | --- | --- | --- |
| C | 3167.571 | -3150.038 | 294.0628 |
| C | 3157.736 | -3164.859 | 293.2874 |

**Comment by Tobschinski** [comment]
PH

**Comment by cala** [comment]
I'm about to fix this. So, that's basically 3 paths of 3 waypoints each? With a spawn at one end every five seconds?

**Comment by Tobschinski** [comment]
No?! Naxxramas is the first raid in WotLK, why would you implement that for vanilla, idiot!

**Comment by cala** [comment]
Please master, don't whip me again. I'll be good. I was so sure that you like undead and frost thingies that I wanted to bring it back to vanilla, like some kind of vanilla ice cream. Everyone loves vanilla ice cream.

**Comment by cala** [comment]
Vanilla. Frozen. Blobs.
I promise, I deliver.
![Vanilla Frozen Blobs](http://revel.in/wp-content/uploads/2015/10/Vanilla_Cocoa_Sauce.jpg)
