### ISSUE TITLE
Stave of the Ancients -*

### ISSUE THREAD

**Issue by Kelzior** [classicdb/database#806]
https://db.valkyrie-wow.org/?quest=7636

Simone the Inconspicuous (Seductress) is untargetable, so you cannot summon the "Seductress".

same for the other mobs required for the quest.

(Klinfran the Crazed.

Solenor the Slayer.

Artorius the Doombringer.)

https://www.youtube.com/watch?v=xlRSZXbdu_4
https://www.youtube.com/watch?v=sxZzBXsM900

**Comment by cala** [comment]
Duplicate issue of https://github.com/classicdb/database/issues/754 
Closing here. Thanks.
