### ISSUE TITLE
LBRS female version of Scarshield Legion creatures.

### ISSUE THREAD

**Issue by stan84** [classicdb/database#81]
In creature_template table there is only male versions of :

Scarshield Legionaire - entry 9097,creature should also have other gender in modelid_2 = 9857.

Scarshield Acolyte - entry 9045,  Modelid_2 = 9853;

Scarshield Spellbinder - entry 9098, modelid_2= 9863

blackhand veteran entry 9819, modelid_2 = 9896

**Comment by cala** [comment]
Thank you. I'll fix this soon.

**Comment by cala** [comment]
Tried yesterday and tonight: the creature above never spawn as female. The only scarshield orc spawing sometimes with a female model is the scarshield warlock. I think the cause might be somewhere else.
