### ISSUE TITLE
Stratholme - Postmaster Malown

### ISSUE THREAD

**Issue by Tobschinski** [classicdb/database#812]
... carries item 12751

... uses spell 3417 - Thrash

**Comment by Tobschinski** [comment]
Bannok Grimaxe - 7612

**Comment by Tobschinski** [comment]
Sandarr Dunereaver - 10612

**Comment by cala** [comment]
Is this a checklist of NPCs missing their equipment?
~~If so, I thought to have fixed Sandarr Dunereaver long ago. But I might be wrong.~~ I am wrong.

**Comment by Tobschinski** [comment]
Yo, I just trash everything in here I notice while doing other things.

**Comment by Tobschinski** [comment]
Something different: Obsidian Nullifier should not carry any items. For some reason, they have a mace equipped.

**Comment by cala** [comment]
I know that your _love_ of the `creature_equip_template_raw` table is even deeper than mine. Do you want me to handle these NPCs?

**Comment by Tobschinski** [comment]
I would do it myself, but I have to look at my cat. Maybe he is doing something funny I have to record to put it on youtube. 

So yes, please do it.

**Comment by cyberium** [comment]
OMG poor cat :(

**Comment by cala** [comment]
This cat will be famous! The first Dortmund supporter cat in pink pyjamas on the Internet !

**Comment by Tobschinski** [comment]
Yo Caladin, did you do the health multiplier for Myzrael? When did she got nerfed?

**Comment by cala** [comment]
The health/mana multipliers for Myzrael are ok. I already did them some time ago after a long search in the deep places of the interweb to find reliable values for her HP/mana (and I also found _things_ I do not want to remember in such places). Her damage stats are probably wrong, though. Her AI is also wrong, but I need Cyberium to finish and release its nice pet patch first before pushing the correct AI.

I remember Myzrael being nerfed twice : somewhere in TBC she had her stats and AI scripts modified without real notification in the patch log. And later her level was reduced.

**Comment by Tobschinski** [comment]
http://web.archive.org/web/20060509125052/http://wow.allakhazam.com/db/mob.html?wmob=2755

Look at the image, she was 50. Maybe that nerf happened prior to patch 1.12 went live?

**Comment by cala** [comment]
Yes, I remember that, it was at the beginning of Vanilla. If I remember correctly, I also found traces that the whole quest chain (including Fozruk and the other elite giant) were changed during Vanilla resulting in a fixed level for Myzrael in late 2006.
However, as usual, if one provides sources stating otherwise, I'm always open to reconsider.

**Comment by Tobschinski** [comment]
Meh, not worth my time to dig deeper. You are safe for now ...

**Comment by cala** [comment]
I dug deeper for you and it seems I found our answer in a post from December 2005 stating that her level was seemingly now a fix 44:
http://web.archive.org/web/20071027094845/http://wow.allakhazam.com/db/quest.html?wquest=656;page=1;howmany=50#113579380414109

**Comment by Tobschinski** [comment]
But when did the hp nerf happen?

**Comment by cala** [comment]
Possibly in 2.3 but I never checked that for sure.

I'm too lazy to look for those sources again, but I remember finding 2 different sources of late 2006 stating that Myzrael had around 11k HP and that she was lvl 44 (as confirmed above). They are the values in the actual DB, I just took the liberty to fix the rounding error.

**Comment by cala** [comment]
@Tobschinski the use of Trash for Postermaster Malown is only for Classic ? Or for TBC/WotLK also?
(to know if I make a PR to all ACID or only one).

**Comment by Tobschinski** [comment]
Nah, I don't see a reason to remove Thrash in later expansions, he is still using it in Wod.

**Comment by cala** [comment]
Ok. Thanks!
