### ISSUE TITLE
Gnomeregan - Dark Iron Ambassador

### ISSUE THREAD

**Issue by Tobschinski** [classicdb/database#815]
[Dark Iron Ambassador](http://wowhead.com/npc=6228) carries [Monster - Staff, Ornate Mage Staff](http://wowhead.com/item=2177)

**Comment by Tobschinski** [comment]
Not it!

**Comment by cala** [comment]
_Cala uses dark powers of the Scourge:_

``` SQL
UPDATE `creature_template` SET `EquipmentTemplateId` = 97 WHERE `Entry` = 6228;
```

Not tested yet, I'll try it this WE. But if you check it first, feel free to push it.

**Comment by Tobschinski** [comment]
It's Friday 2pm, weekend. Why didn't you test this yet!??

**Comment by cala** [comment]
Because I'm not a lazy student, I'm just a lazy salaryman who needs to pretend he is working.
