### ISSUE TITLE
ACID

### ISSUE THREAD

**Issue by Tobschinski** [classicdb/database#816]
...

**Comment by Tobschinski** [comment]
Roloch
https://github.com/classicdb/database/commit/65c683e5dbe035745c2c056205c855e37686349b

**Comment by cala** [comment]
I already made a PR to ACID for that, since I know how much you love it. :p 
https://github.com/ACID-Scripts/Classic/pull/41

**Comment by Tobschinski** [comment]
I have exams coming soon, just in case ...

**Comment by cala** [comment]
Good luck with that. Go quick finish them so you can again push ten commits a day! Quick!

**Comment by cala** [comment]
I was granted push rights to ACID this WE. If you want them to, I can do some lobbying to X-Savior. In the meantime, I will merge in a timely manner every PR you will made there or port myself any AI updates you may do here.
