### ISSUE TITLE
Warrior Quest "The Summoning" can't be done.

### ISSUE THREAD

**Issue by RichardGe** [classicdb/database#818]
The NPC  "Cyclonian"  ( ID = 6239 )  is not summoned by "Bath'rah the Windwatcher"

![asup_wow1](https://cloud.githubusercontent.com/assets/2279126/13196887/c52dd92e-d7dc-11e5-8f03-744137962f62.png)
![asup_wow2](https://cloud.githubusercontent.com/assets/2279126/13196888/c52fc338-d7dc-11e5-8378-b40da2aed69f.png)
![asup_wow3](https://cloud.githubusercontent.com/assets/2279126/13196889/c53586b0-d7dc-11e5-96b9-1874b031fba7.png)

**Comment by cala** [comment]
Thank you for your report. I'm surprised: I remember doing this quest twice and it was working aside from a minor visual effect on the NPC movement that should now be fixed. Are you sure all of the required items are in the player inventory and none in the bank ?

**Comment by RichardGe** [comment]
AFAIK, you don't need any items.

Here is a full script to reproduce it fast :
- Create an admin Alliance warrior
- _.character level characterName 40_
- _.go xyz -8689 323 113 0_     <--- go to warrior master
- speak with Wu Shen , and Take quest "The Islander"
- _.go zonexy 68.6 49.0 17_     <---- go to Fray Island
- speak with Klannoc Macleod
- step on the grate.
- _.die_  command on all the enemies
- speek again with Klannoc, receive the reward and take quest "The Windwatcher"

Note that the skin of the reward "Path of the Berserker" is bad :
![wowbad1](https://cloud.githubusercontent.com/assets/2279126/13197500/ac984954-d7ef-11e5-9e79-45df73e05dde.png)
- _.go zonexy 80 66 36_   <--- go to Bath'rah the Winwatcher
- complete "The Windwatcher"
- take "Cyclonian"
- add the needed items :
  _.additem "Liferoot"_                x8
  .additem "Bloodscalp Tusk"       x30
  .additem "Essence of the Exile"    x1
- complete "Cyclonian"
- take "The Summoning"

**Comment by RichardGe** [comment]
Note that my server is using ClassicDB_1_6_z2683.sql
and I'm using  cmangos 0.12.3

**Comment by cala** [comment]
Thanks for those details.
I looked at all the scripts for this quest in the DB and they look OK. So, I need to do it by myself to see what is wrong now that was previously OK. Does the NPC start casting at least?

Note that to avoid having to redo the whole quest line, you can juste use the `.quest remove quest_id`, `.quest complete quest_id` and `.quest add quest_id` commands with the following IDs:
- 1712 for Cyclonian
- 1713 for The Summoning

**Comment by RichardGe** [comment]
thanks for the .quest info.

Here are more screenshots of the summoning :
- I see the message "Bath'rah the Winwatcher begins a spell of summoning"
- a spell effect is visible

![wow1](https://cloud.githubusercontent.com/assets/2279126/13226947/74cb031c-d994-11e5-8072-9bc058c0b7e7.png)
![wow2](https://cloud.githubusercontent.com/assets/2279126/13226945/74c99284-d994-11e5-8f07-31c90a57793e.png)
![wow3](https://cloud.githubusercontent.com/assets/2279126/13226948/74cf611e-d994-11e5-81c6-25635d340045.png)
![wow4](https://cloud.githubusercontent.com/assets/2279126/13226949/74cfd2c0-d994-11e5-9d9d-247afc9533dc.png)
![wow5](https://cloud.githubusercontent.com/assets/2279126/13226946/74c98dd4-d994-11e5-9c60-712e43cee93b.png)

**Comment by cala** [comment]
Ok. Thanks to your screenshots, I understand what is going on. The script here is very old and no longer working with some changes made to the movement system last year. I will write an updated version soon.

**Comment by RichardGe** [comment]
:+1:
