### ISSUE TITLE
Missing groups LBRS 

### ISSUE THREAD

**Issue by stan84** [classicdb/database#82]
Some Scarshield Legion groups missing at enterance

1st.  5 orcs Legionaire just at start, 2 orcs are sitting on each side, 1 walking from roasted pig to cooking table. exactly like on pic http://imageshack.com/a/img687/2649/j0va.jpg 
1.  in small rooms there are packs of orcs 1 acolyte, 1 legionaire, 1 spellbinder. (legionaire is always sitting on the ground, casters emotes and laugh- but dont know how to do this - custom emote script ? ) example http://imageshack.com/a/img822/3753/1u77.jpg
2. missing group at way to LBRS,  scarshield raider 9258 with 2 worgs 9416. and 1 acolyte, 1 legionaire, 1 warlock. example http://imageshack.com/a/img834/2183/dvb7.jpg
3. missing group at hordemar city,  scarshield raider 9258 with 2 worgs 9416. and  1 legionaire, 1 warlock . example http://imageshack.com/a/img5/7673/rcs3.jpg

About 3-4 patroling groups is missing too, but dont know their route - not reporting as issue.

**Comment by cala** [comment]
Thank you for all these reports. I have opened a dedicated milestone to Blackrock Spire, regrouping all of them. It will take time to fix everything.
We are working on backporting many data from UDB, including missing spawns from Blackrock Spire and they should fix some of these.
