### ISSUE TITLE
Naming the next release

### ISSUE THREAD

**Issue by cala** [classicdb/database#820]
Poke @evil-at-wow and @Tobschinski : many things were fixed since the last release of Classic DB: lots of pathing, spawns and stats by Tobschinski, many quests, scripts fixes, a few instance fixes by myself, some backports from UDB and two nice PR by Zingzah.

**About naming**
So, I'd like to make a new release and I would like to request your suggestion/opinion in naming and tagging this release. Usually, I choose a name that is related to the major changes that release was about (and that is usually the name of the milestone closed by the release): "The Dread Citadel" for the release with the rework of Naxxramas, "Shadowforge City" for the one with the rework of BRD.
Here, there is no associated milestone nor major topic addressed, so we could go for a more free name like when I used "High Elves, Thaurissan and Necromancers in a Swimming Pool".
If for this naming you have any suggestion, wish, idea... Please, say so!

**About tagging**
Current version is 1.6.0. I don't think (but this is debatable as I'm not even sure myself) that there is enough major content change to switch to 1.7.0, so we stay in the same minor version number and this should just be a patch change. Given the high number of fixes since the last release (and some are quite big fixes), I think we could go for 1.6.5. But again, I would like to hear your opinion on the matter.
[Semantic versioning rules](http://semver.org/) though its use was made rather freely for now because Classic DB is a content database not a real API/software.

**Comment by evil-at-wow** [comment]
Let me start by saying that you should have the final say here. I may provide some useful data every now and then, but let's be fair: my overall contribution to this project is still quite limited, especially compared to yours and Tobschinski's.

Version wise, I think 1.6.5 might be a good compromise between 1.7.0 where people might expect to find more major changes and 1.6.1 which sounds like a small update with a handful of fixes. But to be honest, I can live with 1.6.1 or 1.7.0 as well. In the end, that's just a version number, and what matters most is the set of actual changes and fixes. As long as it's clear that this is an update/upgrade people will be happy.

Which brings us to the most difficult part: a (code) name. I'm actually terrible at coming up with good names (I'm sure I could have had another level 100 character in the time it has taken me to come up with the names of all my characters!). So I'll leave that to Tobschinski and you. If you're really, really lacking inspiration too, you can always go for something silly like "Box of Assorted Parts". But that's not really a suggestion, as I'm sure you can find something better.

**Comment by Zingzah** [comment]
How about a variation on the saying "A Change is as good as a holiday" i.e. A Stat Change is as good as a Midsummer Holiday (In the Wailing Caverns) This incorporates the various stat changes, midsummer rework and the Wailing Cavern changes.  Just an idea.

**Comment by Tobschinski** [comment]
+1 for "Still no pet patch from @Cyberium"

**Comment by cala** [comment]
What about: 1.6.5 "The Wailing Pet, The MidSummer Joy and all that sort of things"?

**Comment by cala** [comment]
Closed by https://github.com/classicdb/database/commit/a2bff2576a69fa069a6eb2f301c7a06113858cfa

**Comment by Tobschinski** [comment]
Ehm, you forgot to mock Cyberium.

**Comment by cala** [comment]
I would love to, but he plays gnome. That's enough bad fortune for any man.
