### ISSUE TITLE
LRBS - Missing patrols

### ISSUE THREAD

**Issue by cala** [classicdb/database#822]
Most if not all patrols are missing in LBRS

**Comment by cala** [comment]
This probably results in some duplicate NPCs (same patrol seen at several places).

**Comment by Tobschinski** [comment]
The whole LBRS dungeon was done by hand, resulting in badly positioned and missing spawns.
Since lots of groups got removed with 4.0, only something very evil can help us out here ...

I can only do some patrols ...

**Comment by cala** [comment]
That sounds like manual (evil) adding based on videos and screenshots. I'm not fan of it but like it is said in my country: "Faute de grives, on mange des merles".

**Comment by cala** [comment]
@Tobschinski I'm calling for your incredibly good memory here. I'm working on the patrols and I have conflicting sources about the spawns in LBRS. Do you remember a big nerf in LBRS **during Classic** ? I mean some small groups of mobs (usually 1 - 2 NPCs per group, 3 max) being removed.
It would have occurred some time between April and August 2006 (before patch 1.12 for sure).

**Comment by Tobschinski** [comment]
Patch 1.6 removed several spawns from dungeons, but no idea if LBRS was one of them. Can you link both videos?

**Comment by cala** [comment]
The two most relevant I have:
- 1st one: no real date, comments said it was taken in mid-2006 but it may be before https://www.youtube.com/watch?v=BsRO1NRDUI4 it has more spawns on the Firebrand Legion part than the second one
- 2nd one: posted on August the 21th 2006 (1 day before patch 1.12 release), it shows the same part of Firebrand Legion and many spawns are no longer there and those spawns are confirmed by more videos from Classic, TBC and WotLK https://www.youtube.com/watch?v=7Bo8vzKaKZg

The question is about the Bloodaxe Legion part: there are very few old footages of that part. The first videos is one of those and the quality is really poor (low res, high speed…). I need to know how much I can trust what I can see/guess from this video or if I need to find another one.

**Comment by Tobschinski** [comment]
It is nothing unusual that groups sometimes have 1 less spawn, even if they are patrolling. I noticed that in Stratholme and the Blackrock Depths. But I can't explain the spawns in your video. They don't fit in at all. They aren't static like the rest of the spawns in that area. It almost looks like they were summoned.

**Comment by Phatcat** [comment]
Dunno if you can use any of these;
https://www.youtube.com/watch?v=nUED5cXa-Wk (+ https://www.youtube.com/watch?v=vr8bA68_9Z8)

**Comment by cala** [comment]
> But I can't explain the spawns in your video. They don't fit in at all. They aren't static like the rest of the spawns in that area. It almost looks like they were summoned.

That's also what I thought and I saw them nowhere else. It's almost like if they were added manually and I am thinking that either this video was made in mid 2005 (and not 2006 as claimed) either it was made on a private server and posted as a retail one. Moreover, I saw no more videos with those spawns.
Long story short: I think I will disregard this video as a source.

@Phatcat Thanks for the videos. They were not in my (long, very looooong) list but they are compliant with my other sources.

**Comment by Phatcat** [comment]
Yeah, they weren't there in mid 2006 either; https://www.youtube.com/watch?v=wcA8O_dRLy0

**Comment by Lumber-Jack-2** [comment]
realted: 
https://github.com/classicdb/database/commit/70d1fec769ffcbfe62c01c5e6d03b812da5f6222
https://github.com/classicdb/database/commit/9bdf057a9a30c52c627b81060ac7b3eeb0cd9f00

**Comment by cala** [comment]
Finally closed by https://github.com/cmangos/classic-db/commit/612367ab2978798a439b43dad555ba01ad4e3979 and https://github.com/cmangos/classic-db/commit/f18f02e22b3600459be72170996e717c00f4a643
