### ISSUE TITLE
BUG BRD Arena

### ISSUE THREAD

**Issue by kokiwixx** [classicdb/database#824]
Hello,
[puu.sh/nX83q/fa8be82562.jpg](url)
![ss 2016-03-28 at 07 33 09](https://cloud.githubusercontent.com/assets/18122752/14084802/e24c71f2-f51c-11e5-9d45-fdc244ddb809.jpg)

Npc : High Justice Grimstone
Bug : Not move and not event arena
Server :
![ss 2016-03-28 at 07 37 59](https://cloud.githubusercontent.com/assets/18122752/14084793/d486020e-f51c-11e5-9c0e-e3d85e1851b0.jpg)

Plz help me

**Comment by cala** [comment]
Hello,

I will have a look at it. Did you use GM mode at some time?

**Comment by kokiwixx** [comment]
my server is open to the public, nobody can activate a event arena.

**Comment by Lumber-Jack-2** [comment]
@kokiwixx:
type: .gm off
then run into the middle of the arena
then the event should start

**Comment by Tobschinski** [comment]
The event did start, the NPC is there (and hostile).

He just doesn't know where to move (looks like he is doing some random movement, because he faces the wall).

**Comment by cala** [comment]
I agree with @Tobschinski : if the NPC is spawned, then SD2 is activated and the trigger in the middle of the arena started the event. Though, the NPC seems to not move. Why?
I tested the event a few minutes ago and it did start and work as intended. So I'm afraid it will be hard to spot what is wrong here.
@kokiwixx could you look into your SD2 log and server log files to see if there is an error related to the event, please?

**Comment by cala** [comment]
I'm still unable to reproduce the issue. Without further feedback, I'm afraid I will close it.

**Comment by Vanillafanatic** [comment]
Works fine for me on the latest build. Even the D1 upgrade flag worked. (I didn't see a chest spawn to loot for the d1though, but I just rushed the kill with .damage cmd, must check fully later when time.)

**Comment by cala** [comment]
Without further feedback, I'm closing this issue.
