### ISSUE TITLE
[Quest] In Search of Menara Voidrender

### ISSUE THREAD

**Issue by Muehe** [classicdb/database#825]
There are four quests with this name, two for Horde (4736, 4739) and two for Alliance (4737,4738). The latter have an ExclusiveGroup set, the former don't. Guess that is wrong, as all four quests have 1796 as NextQuestInChain. Fix:

``` sql
UPDATE quest_template SET ExclusiveGroup = 4737 WHERE entry IN (4736, 4739);
```

**Comment by cala** [comment]
Good catch. :+1:
