### ISSUE TITLE
Two Seal of Righteousness

### ISSUE THREAD

**Issue by katz1** [classicdb/database#834]
While doing the first quests with a human paladin, I ended up receiving two Rank 1 Seal of Righteousness spells. The only difference between the two seems to be an extra line in the tooltip, describing the effect of Judgement:

"Unleashing this Seal's energy energy will cause..."

I guess the one with the simpler tooltip should have been removed.

**Comment by katz1** [comment]
A bit more info on the subject.

This is the spell the paladin starts with: http://db.vanillagaming.org/?spell=20154
And this is the one received later: http://db.vanillagaming.org/?spell=21084

I am not entirely sure when the latter one is learned, either after the first quest (http://db.vanillagaming.org/?quest=3101) or after learning the Judgement skill (http://db.vanillagaming.org/?spell=20271).

**Comment by Phatcat** [comment]
Actually, you didn't get it while leveling, you had it to begin with. It seems that the paladin starts with both.

It seems we indeed need to remove the one with the longer discription, and reintroduce it when the player learns judgment, then removing the one with the shorter from the player.

**Comment by Xentr0** [comment]
I looked into this a bit and as far as I can see it is pretty easy to let people start out with the simpler tooltip version, however there is nothing built in (again, as far as I saw) that would teach players judgement and seal of righteousness with the larger tooltip and then replace that new version with the old one. I don't think this can be fixed just on the database side.

**Comment by cala** [comment]
Is this a DB issue? I've seen seemingly related PRs on core and I wonder if it is relevant to let that issue open here? Just asking. :)

**Comment by Phatcat** [comment]
Í have new info on this one ;)
https://github.com/cmangos/wotlk-db/issues/8 -> https://www.youtube.com/watch?v=7Whduw2cLEE (watch in 0.25 speed); at 2:24

Seal of righteousness should be available from the trainer even though you have it;
buying it should change the tooltip (2:29 vs 2:31)

**Comment by Phatcat** [comment]
@cala yes, this is a db issue as the paladin should only know the one with the shorter tooltip on creation, and then from level 2 the trainer should have seal of righteousness rank 1 available (even though you already have it, it should however add on the functionality of the spell.) - This is all db side.

**Comment by Grz3s** [comment]
https://github.com/cmangos/wotlk-db/commit/fb054ace41efd10ccf3e2f28a6c812e961e9d7b4

**Comment by cala** [comment]
Closed by https://github.com/cmangos/classic-db/commit/ba7f9d2f52aa1e5cce559ed025504b3b9e4d6036 Thanks @Phatcat and @Grz3s !
