### ISSUE TITLE
Duplicities in DB

### ISSUE THREAD

**Issue by killerwife** [classicdb/database#841]
Not sure about classic, but try running this query:

select a.guid,b.guid,a.id,b.id,a.position_x,b.position_x,a.position_y,b.position_y , a.position_z,b.position_z , a.orientation,b.orientation , a.map , b.map from creature a join creature b on (a.id=b.id and a.position_x=b.position_x and a.position_y=b.position_y and a.position_z=b.position_z and a.orientation=b.orientation and a.map = b.map and a.guid<>b.guid) where not exists(select d.guid from game_event_creature d where a.guid=d.guid or b.guid=d.guid);

We discovered some duplicities in our TBC DB branch and also in UDB so i thought you might wanna try it (i dont have classic on my local)

**Comment by cala** [comment]
Thank you for this suggestion. It seems we love so much bats in Classic DB that we even duplicate them ! ;)

I'll fix those. Thanks!
