### ISSUE TITLE
Reinforcing Redridge quest chain

### ISSUE THREAD

**Issue by Muehe** [classicdb/database#842]
This fixes a quest chain starting in Lakeshire. Without the fix all three stages of the chain can be started at once by Magistrate Solomon.

``` sql
-- fix for quest chain SELECT * FROM quest_template WHERE Title LIKE ("%Messenger to%");
UPDATE quest_template SET PrevQuestId = 121 WHERE entry = 143;
UPDATE quest_template SET PrevQuestId = 144 WHERE entry = 145;
```

Sources:
http://wowwiki.wikia.com/wiki/Reinforcing_Redridge_quest_chain?oldid=1256047
Quest text.

Note: Quest text suggests NextQuestInChain doesn't need to be set, but not sure. If it is set and player level is <18, then the last part (Messenger to Darkshire) is offered but doesn't go into quest log upon accepting. It could be set for the middle part (... to Westfall) without danger, as it has the same MinLevel as the first part (... to Stormwind).

``` sql
-- UPDATE quest_template SET NextQuestInChain = 143 WHERE entry = 121;
-- UPDATE quest_template SET NextQuestInChain = 145 WHERE entry = 144;
```

**Comment by cala** [comment]
:+1:
