### ISSUE TITLE
Fel Cone drops

### ISSUE THREAD

**Issue by Muehe** [classicdb/database#857]
[Fel Cone drops](http://db.vanillagaming.org/?object=1673) some reagents. Seems wrong. I think inventory of reagant merchant [Alyssa Eva](http://db.vanillagaming.org/?npc=1673) got added, cause they have the same ID.

``` sql
DELETE FROM gameobject_loot_template WHERE entry = 1701 AND ChanceOrQuestChance > 0;
```

**Comment by cala** [comment]
Thanks! :+1: 
By the way, I got your PM but did not took the time to properly reply to it yet.

**Comment by Muehe** [comment]
No problem, thanks for commiting!

**Comment by Muehe** [comment]
No problem, thanks for commiting!

Btw. gameobject ID is 1673, 1701 is the loot group (no idea why, nothing else uses it).
