### ISSUE TITLE
Missing Stockades jailbreak event?

### ISSUE THREAD

**Issue by Phatcat** [classicdb/database#859]
http://wow.gamepedia.com/Stormwind_Stockade_(original)#Notes.2C_Tips.2C_.26_Additional_Info

> Sometimes a group of Defias Rioters will come from the instance and attack the Guards and other players. They won't survive that long and it only lasts for about 5–10 seconds.

**Comment by Phatcat** [comment]
And there it was, latest entry -.-

**Comment by Lumber-Jack-2** [comment]
so the event is already scripted?

**Comment by Phatcat** [comment]
It looks to be in classic db at least;

line 453677 in the classic 'full db' file.

> (61,'2010-12-31 23:58:00','2020-12-30 23:00:00',30,10,0,'Stormwind City - Stockades Jail Break');

**Comment by Lumber-Jack-2** [comment]
kk
