### ISSUE TITLE
Multiple mining nodes in 1 spot

### ISSUE THREAD

**Issue by Zooke** [classicdb/database#862]
![capture](https://cloud.githubusercontent.com/assets/19142330/16228024/43686906-37ac-11e6-8865-03ae038fcf1c.PNG)

**Comment by cala** [comment]
Thanks.

**Comment by dagochen** [comment]
Is there any way to do this kind of fix for all fishing nodes without having to write 100000 inserts?

**Comment by Tobschinski** [comment]
Well, you can try and let the core do some zone-wide pooling or something like that...
