### ISSUE TITLE
7:XT marked neutral (yellow) but aggressive.

### ISSUE THREAD

**Issue by Zooke** [classicdb/database#863]
As the title, npc:14224 7:XT looks neutral, but attacks on sight.
Playing Human Pally.

**Comment by cala** [comment]
I'm surprised by this one. Does Azuregos also attack you on sight ? `.go creature id 6109`
Did you try with another character?

**Comment by Zooke** [comment]
I'll test a range of characters / mobs in a few hours time.

**Comment by Zooke** [comment]
> > Does Azuregos also attack you on sight ?

Good call with Azuregos, that revealed a different issue. #866 
Ok, found the issue, Corrupted Ashbringer makes neutral mobs aggressive.
Intended behaviour ? I thought it was just the argent dawn and scarlet crusade it affected.

**Comment by cala** [comment]
Yes, this intended. The aura applied by the sword causes NPCs to react and for neutral ones this means attacking. I'm closing the issue. Thanks.
