### ISSUE TITLE
Azuregos Mark Of Frost removable.

### ISSUE THREAD

**Issue by Zooke** [classicdb/database#866]
You can remove the Mark of Frost by clicking it. Obviously it should be considered a debuff rather than a buff.

**Comment by cala** [comment]
I assume you were not in GM mode? :)

**Comment by Zooke** [comment]
> I assume you were not in GM mode? :)

Lol, I had to recheck to be 100%, but this is definitely a bug, the buff appears at the top of the screen instead of lower down like debuffs normally do.

**Comment by cala** [comment]
It was a core issue. Now fixed along with Mark of Nature which had the same behaviour.
