### ISSUE TITLE
Cinder Bracers (Midsummer reward) must have 3 charges and limited duration

### ISSUE THREAD

**Issue by Neotmiren** [classicdb/database#868]
``` sql
UPDATE item_template SET spellcharges_1=-3, duration=14*24*60*60 WHERE entry=23379 AND spellcharges_1=-1 AND duration=0;
```

http://www.wowhead.com/item=23379/cinder-bracers
http://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-guides/1275-midsummer-fire-festival-print.html

And thanks to @Zingzah. I never did Midsummer quests and now walking through them for the first time. Good and appropriate event, in contrast to "Hallow's End" that seems tasteless / not fit to the World of Warcraft / one of vulgar pop-culture references which spoil World of Warcraft.

**Comment by Zingzah** [comment]
Thanks for the positive feedback and the spot on the bracers.  The event is looking pretty good with only a few minor fixes needed. I'm hoping at some point to add the fireworks extravaganza which ends/is part of this one and a few of the other seasonal events (Lunar, New Years)

**Comment by Neotmiren** [comment]
One more thing: duration for Cinder Bracers and Burning Blossom should be realtime duration. Currently it is /played time duration.

``` sql
UPDATE item_template SET ExtraFlags=2 WHERE entry IN (23247, 23379);
```

@Zingzah - it would be very nice to have events working in Classic. They add variety and it is interesting to compare differences between Classic and later stages (TBC, WotLK).
