### ISSUE TITLE
Too high drop chance for Pattern: Robe of Winter Night from Cobalt Mageweaver (Winterspring)

### ISSUE THREAD

**Issue by Neotmiren** [classicdb/database#873]
61% for rare recipe is nonsense, at least in Classic. Even current wowhead.com chance is about 30%.

At the end of 2004 it was 0.56%
http://web.archive.org/web/20050218155006/http://wow.allakhazam.com/db/item.html?witem=14493

Later data shows 1.22%
http://web.archive.org/web/20060720200616/http://wow.allakhazam.com/db/mob.html?wmob=7437

Maybe it should be around 4% considering this is BoP recipe (cannot be bought from auction and therefore should not be too low chance).

There is also issue of missing EventAI for Cobalt Mageweaver, which is very bad, because this creature is also the source of Schematic: Arcanite Dragonling and Recipe: Greater Arcane Protection Potion.

**Comment by Phatcat** [comment]
I would say a 2% chance makes more sense given those numbers; especially considering the playerbase in 2006 compared to 2004.

**Comment by cala** [comment]
The Cobalt Mageweaver AI was added in https://github.com/ACID-Scripts/Classic/commit/2b5d2b20e95b589719b64157e7530cee6c7e5117 along with the AI for the two other Cobalt blue dragons in the area that were missing it.
