### ISSUE TITLE
Extra misplaced Thuzadin Acolyte (Stratholme)

### ISSUE THREAD

**Issue by Neotmiren** [classicdb/database#875]
There are 3 groups, 5 Thuzadin Acolytes each, but 16 guids in DB. This one should be deleted probably. The position is bad and in client it falls (visually) onto the floor level under Stratholme.

``` sql
DELETE FROM creature WHERE guid=53267 AND map=329 AND ROUND(position_x)=3930 AND ROUND(position_y)=-3674;
```

**Comment by Tobschinski** [comment]
This Acolyte does indeed exist on the retail servers and is the one that's yelling whenever you clear out Ziggurats in Stratholme.
