### ISSUE TITLE
All quests "Darkmoon *** Deck" must be repeatable (Darkmoon Faire)

### ISSUE THREAD

**Issue by Neotmiren** [classicdb/database#876]
``` sql
UPDATE quest_template SET SpecialFlags=SpecialFlags|1 WHERE entry IN (7907,7929,7927,7928);
```

And another minor issue: Professor Thaddeus Paleo has gossip about non-Classic decks from TBC/WotLK.
http://wowwiki.wikia.com/wiki/Darkmoon_Faire_(old)?oldid=365700

**Comment by cala** [comment]
Thanks. Gossip is fixed in https://github.com/classicdb/database/commit/ce66a224962b1524ad4e4d1fe70827be83dc5c0b
I already had it on my list.
