### ISSUE TITLE
Premature completion of some escort quests

### ISSUE THREAD

**Issue by Neotmiren** [classicdb/database#878]
They become completed immediately after accepting, without actual escort done.

``` sql
UPDATE quest_template SET SpecialFlags=SpecialFlags|2 WHERE entry IN (1560, 4261, 5203);
```

**Comment by Phatcat** [comment]
Man, you are on a roll! Nice work!

**Comment by cala** [comment]
Thanks for the issues reports and provided fixes. :+1: 
I pushed some of them today. I need to look at/test a bit more the others, like the demons spawns near the Dark Portal, for example.
