### ISSUE TITLE
Improved Wing Clip procs in a wrong way

### ISSUE THREAD

**Issue by Neotmiren** [classicdb/database#880]
For me this talent immobilizes the player sometimes!

This issue should probably come to core repository, but not 100% sure about it (I use heavily modified version of core; for me it works) so I post it here for @cala to check it.

``` sql
REPLACE spell_proc_event SET entry=19228, SpellFamilyName=9, SpellFamilyMask0=64, SpellFamilyMask1=64, SpellFamilyMask2=64
```

**Comment by cala** [comment]
Hi,

I was testing this today and I'm unable to reproduce the issue on the current core. So, I'm closing this issue but I keep your fix in mind in case I was just extra-lucky. Thanks !
