### ISSUE TITLE
Some creatures cannot cast Shoot in EventAI because they have no ranged weapon (equipment_id=0)

### ISSUE THREAD

**Issue by Neotmiren** [classicdb/database#883]
Magister Hawkhelm (rare - Azshara), Thauris Balgarr (rare - Burning Steppes) Murloc Scout, Isalien, Malgen Longspear

**Comment by cala** [comment]
Note for later:

| Name | Entry | Slot 1 | Slot 2 | Slot 3 |
| --- | --- | --- | --- | --- |
| Magister Hawkhelm | 6647 | 1983 | 0 | 13147 |
| Thauris Balgarr | 8978 | 5281 | 0 | 2552 |
| Murloc Scout | 578 | - | - | - |
| Isalien | 16097 | 18122 | 0 | 5259 |
| Malgen Longspear | 16052 | 3433 | 0 | 5259 |

**Comment by cala** [comment]
It seems that Murloc Scout (ID 578) does not wield equipment...

**Comment by cala** [comment]
@Neotmiren : we have currently no AI set for Malgen Longspear, so even with equipment set, he won't cast shoot, unless you can provide me the spell IDs as you seem to have them, please.

**Comment by Neotmiren** [comment]
As for Malgen Longspear, now I see he belongs to EventAI ported from PSDB (about 200 creatures in addition to ACID):

``` sql
(1605201, 16052, 2, 0, 100, 3, 25, 0, 15300, 22900, 11, 15503, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Malgen Longspear - Cast Drink Healing Potion When Below 25% HP'),
(1605202, 16052, 0, 0, 80, 3, 3000, 5500, 15000, 15000, 11, 27632, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Malgen Longspear - Cast Aimed Shot'),
(1605203, 16052, 0, 0, 80, 3, 5500, 5500, 11000, 11000, 11, 27634, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Malgen Longspear - Cast Concussive Shot'),
(1605204, 16052, 0, 0, 80, 3, 3000, 5500, 15000, 15000, 11, 18651, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Malgen Longspear - Cast Multi-Shot'),
(1605205, 16052, 0, 0, 80, 3, 3000, 5500, 13000, 18000, 11, 27633, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Malgen Longspear - Cast Wing Clip'),
(1605206, 16052, 0, 0, 100, 2, 0, 0, 0, 0, 21, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Malgen Longspear - Stop Movement on Aggro'),
(1605207, 16052, 4, 0, 100, 2, 0, 0, 0, 0, 11, 16100, 1, 0, 22, 6, 0, 0, 0, 0, 0, 0, 'Malgen Longspear - Cast Shoot and Set Phase 1 on Aggro'),
(1605208, 16052, 0, 6, 100, 3, 2200, 4700, 2200, 4700, 11, 16100, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Malgen Longspear - Cast Shoot (Phase 1)'),
(1605209, 16052, 9, 6, 100, 3, 20, 100, 0, 0, 21, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Malgen Longspear - Start Movement at 20 Yards (Phase 1)'),
(1605210, 16052, 9, 6, 100, 3, 6, 10, 0, 0, 21, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Malgen Longspear - Stop Movement at 10 Yards (Phase 1)'),
(1605211, 16052, 9, 6, 100, 3, 0, 5, 0, 0, 21, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Malgen Longspear - Start Movement at 5 Yards (Phase 1)'),
(1605212, 16052, 2, 0, 100, 2, 15, 0, 0, 0, 22, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Malgen Longspear - Set Phase 2 at 15% HP'),
(1605213, 16052, 2, 5, 100, 2, 15, 0, 0, 0, 21, 1, 0, 0, 25, 0, 0, 0, 1, -47, 0, 0, 'Malgen Longspear - Start Movement and Flee at 15% HP (Phase 2)'),
```

For Murloc Scout in Redridge Mountains I use spear equipment (as temporary fix) and it starts throw spears properly:

``` sql
UPDATE creature_template SET equipment_id=1754 WHERE entry=578 AND equipment_id=0;
```

**Comment by cala** [comment]
Thank you! :+1: 
I'm leaving for three weeks of holidays today. I'll handle this when I return as I won't have access to a computer during that time (and barely access to my emails).

Poke @cyberium @Tobschinski @Phatcat @evil-at-wow @Grz3s @xfurry so they read this and know they won't be able to get in touch with me for a while.

See you later. :smile:

**Comment by Tobschinski** [comment]
(1/2) https://github.com/classicdb/database/commit/668e758368d5366185ddd687e506a656434b50e7
(2/2) https://github.com/classicdb/database/commit/9f7f769d05a732d6d8c4a0342cbdb1f65ae43a14
