### ISSUE TITLE
Non-elite creatures in Stratholme and Scholomance should stop yielding Reputation after Honored with Argent Dawn

### ISSUE THREAD

**Issue by Neotmiren** [classicdb/database#884]
"Non-elite monsters (except Neutral Shadowmages) stop giving reputation at Honored. Elite monsters stop at Revered"
http://wowwiki.wikia.com/Argent_Dawn?oldid=324107

``` sql
DELETE FROM creature_onkill_reputation WHERE creature_id=10582; -- remove Dog (Freewind Post)

UPDATE creature_onkill_reputation SET MaxStanding1=4 WHERE creature_id IN (10481,10485,10482,10391,10390,10399,10480) AND RewOnKillRepFaction1=529 AND MaxStanding1=5; -- Stop after Honored

UPDATE creature_onkill_reputation SET MaxStanding1=5 WHERE creature_id=8550 AND RewOnKillRepFaction1=529 AND MaxStanding1=4; -- Prolong until Revered
```

**Comment by Phatcat** [comment]
> DELETE FROM creature_onkill_reputation WHERE creature_id=10582; -- remove Dog (Freewind Post)

Why should this mob not reward any rep at all anymore?

**Comment by Neotmiren** [comment]
Do you think there should be some amount of Argent Dawn reputation for level 1 Dog in Thousand Needles?

**Comment by Phatcat** [comment]
so you group in an unrelated mob without giving any info on it basically, without mentioning it in your pr either, and so when I ask about it, not to offend, but to be enlightened, i do not wish to be met with such hostility. I never said the change was wrong nor even hinted at it.

> Please, do not ask about trivialities when could easily find answers yourself.

you must not understand how pr'ing works.. youre proposing a change; it is your job to provide info, not anyone else.

**Comment by Neotmiren** [comment]
Do not take offence. I have no jobs here, not interested in development scene by itself (just playing now and making quick fixes), and practically have no gains from posting here (using heavily modified core, dynamically modified DB via php script, totally different building scheme and thus having absolutely no problems with making any private fixes/changes).

**Comment by Phatcat** [comment]
Frankly, I do not care for your circumstances; you do not get special treatment, not by me, especially not considering that elitist behaviour right there.

Do you think we others have a job here?

So you think you are bringing us gifts and we should be thanking you on our hands and knees? If not why are you too important to even list your own data, or you think it makes more sense having EVERYONE who wishes to check it out look it up himself; like thats not a waste of other peoples time.

**Comment by Neotmiren** [comment]
I believe there is no significant "wasting time" for developers of DB, and that unexperienced peoples should learn how to find elementary information quickly. If you have another view - well, just do not address me. And I always try to make essential points clear, so there is no ground for accusations.

**Comment by Phatcat** [comment]
Let me break it down for you since you seem to not want to get it;

when you are doing obscure changes, and yes, changes are obscure when they are neither commented (properly) nor provided any info in the PR, then you are, as I already said, expecting every single interested person to look it up for themselves. Let's say it takes 1 minute to look up; let's say 5 people find interest in your change and have to look it up, that's 5 min of developers time used to look it up, while you could have merely mentioned it initially, or spend that 1 min yourself when I asked, which you also did. this is not about teaching people to look up stuff in the db, because you do not even explain to people how to look up stuff, now do you?

When you do something UNRELATED, you better document it, especially upon request, if this is a problem for you, then you should consider if you wanna bother with this every time you do this; because I very well do. This is a principle for me, and I ain't going nowhere, get used to me addressing you.

**Comment by Phatcat** [comment]
I don't know why you're confused, cala, all I did was ask him explain one of his changes that I felt was not properly documented and both of you view that as being offensive?

**Comment by cala** [comment]
Thread moderated. Let's focus on the issue reported here.
If one want to discuss the various approaches in contributing, I think the CMaNGOS forums are a more suitable place.

**Comment by Phatcat** [comment]
I can respect that.

**Comment by Tobschinski** [comment]
Is 

```
UPDATE creature_onkill_reputation SET MaxStanding1=4 WHERE creature_id IN (10481,10485,10482,10391,10390,10399,10480) AND RewOnKillRepFaction1=529 AND MaxStanding1=5; -- Stop after Honored
```

correct?

> 5 reputation for killing any elite undead and **most non-elites** in Scholomance and Stratholme (stops at Revered).

**Comment by Neotmiren** [comment]
Not sure about this "most non-elites" part. It seems like wowwiki formally contradicts to itself within the same page. Yes, the first quote could be badly formulated and be related to non-instanced non-elite only. So I agree this sql part could be not correct and thus should not be applied.

My reason to notice this subject was practical easiness to AoE grind reputation from non-elite creatures at the entrance of Stratholme (repeatedly resetting instance). Too easy for Classic, compared to grinding reputation with other factions.

**Comment by Tobschinski** [comment]
https://github.com/classicdb/database/commit/43d05f667384d06b55a5d4b6b2148d8deeb33849
