### ISSUE TITLE
Mechanical Yeti (quest reward) must have 3 charges

### ISSUE THREAD

**Issue by Neotmiren** [classicdb/database#885]
http://web.archive.org/web/20061026001132/http://wow.allakhazam.com/db/item.html?witem=15778

``` sql
UPDATE item_template SET spellcharges_1=-3 WHERE entry=15778 AND spellcharges_1=-1;
```

**Comment by Tobschinski** [comment]
https://github.com/classicdb/database/commit/edad197fe690c70370b540e7ab8a64fd979050ec
