### ISSUE TITLE
TBC quest category "Battleground" (-25) did not exist in Classic

### ISSUE THREAD

**Issue by Neotmiren** [classicdb/database#886]
allakhazam shows Ironforge/Orgrimmar categories instead

``` sql
UPDATE quest_template SET ZoneOrSort=1537 WHERE entry IN (8371,8385) AND ZoneOrSort=-25; -- Category: Ironforge
UPDATE quest_template SET ZoneOrSort=1637 WHERE entry IN (8367,8388) AND ZoneOrSort=-25; -- Category: Orgrimmar
```

**Comment by Phatcat** [comment]
Shouldn't the quests be associated with the zones they belong to; in the case of vanilla: WSG, ZB or AV, depending on the quest content?

What quests exactly are these if you happened to look them up?

**Comment by dagochen** [comment]
These are the quests where you have to collect 3 marks of each battleground.

**Comment by Phatcat** [comment]
Alright, in that case if/org makes sense

**Comment by Tobschinski** [comment]
https://github.com/classicdb/database/commit/4c3a3e50f71f8f16be1ad9fe53a3e9c475a7dc27
