### ISSUE TITLE
Stranglethorn cats should sleep at night

### ISSUE THREAD

**Issue by Phatcat** [classicdb/database#889]
~~Filled with ghouls.~~

~~Yeah, I don't know when these got added but it wasn't in vanilla, I can say that at least. It's supposed to be greater fleshrippers in vanilla.~~

Unrelated.

**Comment by dagochen** [comment]
And only at night ;)

**Comment by cala** [comment]
The ghouls are spawned at night. The fleshrippers at day. Start/stop the Nights event and you should see the switch. :)

Sorry for the short and delayed answers: I have only my mobile and little signal here.

**Comment by Phatcat** [comment]
I'm pretty sure I've never seen any ghouls there at all, ever. I may be wrong, but I did run quite a few Deadmines runs. You 100% sure they're supposed to be there in vanilla? - if you are then just close this issue =)

**Comment by dagochen** [comment]
Cala is right, can confirm it. We did this for the german server i am working for. Together with a lot of other events which only occur in the night (like sleeping tigers and panthers in stranglethorn).  Maybe I can find some evidence on that in our bugtracker.

**Comment by cala** [comment]
> sleeping tigers and panthers in stranglethorn

I have those on my list also but I am missing the right aura spell ID for proper implementation.

**Comment by Phatcat** [comment]
Something like this one?

Id: 25148
Name: Sleep Visual DND
General info
Category = 0, SpellIconId = 157, ActiveIconId = 0, SpellVisual = (5645, 0)
SpellFamilyName = SPELLFAMILY_GENERAL, SpellFamilyFlags = 0x0000000000000000
SpellSchool = 0 (SPELL_SCHOOL_NORMAL)
DamageClass = 0 (SPELL_DAMAGE_CLASS_NONE)
PreventionType = 0 (SPELL_PREVENTION_TYPE_NONE)
Attributes
AttributesEx1: 0x10000400 (SPELL_ATTR_EX_NO_INITIAL_AGGRO, SPELL_ATTR_EX_UNK28)
AttributesEx2: 0x00000004 (SPELL_ATTR_EX2_CANT_REFLECTED)
Advanced info
Spell Level = 0, BaseLevel 0, MaxLevel 0, MaxTargetLevel 0
Category = 0
DispelType = 0 (DISPEL_NONE)
Mechanic = 0 (MECHANIC_NONE)
SpellRange (Id 13) "Anywhere"
MinRange = 0
MaxRange = 50000
CastingTime (Id 1) = 0.00
Duration: ID (21) -1, 0, -1
Interrupt Flags: 0x00000000, AuraIF 0x00000000, ChannelIF 0x00000000
Chance = 101, charges - 0
Effects
Effect 0:
Id: 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 1
Targets (1, 0) (TARGET_SELF, NO_TARGET)
Aura Id 4 (SPELL_AURA_DUMMY), value = 1, misc = 0 (0), periodic = 0
Effect 1:
NO EFFECT
Effect 2:
NO EFFECT

**Comment by Phatcat** [comment]
This one also looks sorta related looking at the attributes.

~~Id: 20373
Name: Tag: Sleep
General info
Category = 0, SpellIconId = 157, ActiveIconId = 0, SpellVisual = (5645, 0)
SpellFamilyName = SPELLFAMILY_GENERAL, SpellFamilyFlags = 0x0000000000000000
SpellSchool = 0 (SPELL_SCHOOL_NORMAL)
DamageClass = 0 (SPELL_DAMAGE_CLASS_NONE)
PreventionType = 0 (SPELL_PREVENTION_TYPE_NONE)
Attributes
AttributesEx1: 0x04000400 (SPELL_ATTR_EX_NO_INITIAL_AGGRO, SPELL_ATTR_EX_UNK26)
AttributesEx2: 0x00000004 (SPELL_ATTR_EX2_CANT_REFLECTED)
Advanced info
Spell Level = 0, BaseLevel 0, MaxLevel 0, MaxTargetLevel 0
Category = 0
DispelType = 8 (DISPEL_SPE_NPC_ONLY)
Mechanic = 0 (MECHANIC_NONE)
SpellRange (Id 13) "Anywhere"
MinRange = 0
MaxRange = 50000
CastingTime (Id 1) = 0.00
Duration: ID (21) -1, 0, -1
Interrupt Flags: 0x00000000, AuraIF 0x00000000, ChannelIF 0x00000000
Chance = 101, charges - 0
Effects
Effect 0:
Id: 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 1
Targets (25, 0) (TARGET_DUELVSPLAYER, NO_TARGET)
Aura Id 4 (SPELL_AURA_DUMMY), value = 1, misc = 0 (0), periodic = 0
Effect 1:
NO EFFECT
Effect 2:
NO EFFECT~~

**Comment by cala** [comment]
Yes, there are several of them, basically with a 5, 10, 20 sec or permanent duration. I just don't know which one to use exactly.

**Comment by dagochen** [comment]
perma i think, and wake them up if night-event is ending?

**Comment by Phatcat** [comment]
Well, I did look through the dbc some, and these are the only ones to make sense in this regard to be honest. And the second one I've posted seems off with targeting and stuff. I'd very much like to believe it's the first one I listed from QSW.

**Comment by cala** [comment]
Okay, then I'll add it when I come back.

**Comment by Phatcat** [comment]
Well, if I could do something helpful like test it in some way let me know.

**Comment by cala** [comment]
Self-assigned, re-open and edited title to match new context. :)

**Comment by Phatcat** [comment]
Hah, nice way to turn a faulty issue ticket around ;D

**Comment by Tobschinski** [comment]
I've been to STV past midnight but couldn't caught any cat sleeping. Maybe I was unlucky, maybe that was removed ...

By the way ... aren't cats nocturnal?

**Comment by Phatcat** [comment]
I think cala meant that they still need to be done.

**Comment by dagochen** [comment]
Yeah they were sleeping at night in classic and yes, @Tobschinski  is right, cats are nocturnal, which makes this feature a little bit "wrong". But still, looks so cute when they sleep!

**Comment by Phatcat** [comment]
Yeah it does, they used to throw off green z's if I don't remember incorrectly.

**Comment by Tobschinski** [comment]
I'll try again tonight ...

**Comment by Phatcat** [comment]
Also, can't blame Blizzard for making cats sleep at night, they were just following disney : https://www.youtube.com/watch?v=Gn4jmvwgtoE :p

**Comment by Phatcat** [comment]
Hmmm... Watching Joana's Videos in the stranglethorn parts shows no sleeping cats in stranglethorn, day or night. either the videos were recorded before it was added (or after it was removed..) or it only applied to a select few mobs.. or we may be remembering stuff wrong..

**Comment by cala** [comment]
I read/heard about those sleeping cats but if I saw them in retail, I have no memory of it. So, I can only do guesses here. Maybe that was a feature that was added/removed during Classic or later, maybe the feature was periodic: cats had periodic or scripted aura that make them sleep small amounts of time during the night but not 100% of the time, or maybe we remember wrong. 

@dagochen : by any chance do you have some materials/data/sources you used when you did these cats on your server, please?

**Comment by dagochen** [comment]
I was not participating in that feature at all. But I can investigate and try to find something about it.

**Comment by cala** [comment]
That would be very kind, please.

**Comment by cala** [comment]
Poke @dagochen about this, please. I was still unable to find anything about this and I'm considering closing this issue unless we get some data.
Maybe @Phatcat saw something in the Joana leveling videos he is currently watching, but I assume it would have report here if that was the case.

**Comment by dagochen** [comment]
Got no evidence on that issue. All I could find is the aura which we applied.

**Comment by Phatcat** [comment]
gonna have to point to my earlier comment: I was not able to find any sleeping cats in joanas videos.

**Comment by Phatcat** [comment]
Yeah, going to close this until someone finds some actual proof for this, this issue is all over the place and without any actual merit.
