### ISSUE TITLE
Summer in christmas

### ISSUE THREAD

**Issue by killerwife** [classicdb/database#891]
https://gist.github.com/Xinito/8b37a6b385a7c2aa087ec38f015e66dd

https://gist.github.com/killerwife/d421dd58940aa1fe3e556ee1fb6f3af1

@cala these are my latest changes done to the classic world on voa, I thought you might want them

Initially I thought there would be more, but @Xinito stopped coming online.

**Comment by dagochen** [comment]
https://gist.github.com/Xinito/8b37a6b385a7c2aa087ec38f015e66dd#file-db-sql-L33
Looks strange? "7743 0"? 

Btw: How to find all this chests in a particular zone/area?

**Comment by killerwife** [comment]
Yeah, thats a typo i fixed in our repo since then :D 
Well, he did it by hand.

**Comment by dagochen** [comment]
He searched all chests by hand?! wtf...how long ....how much work... :D _cheer_

**Comment by killerwife** [comment]
2-3 days, what u have here, he tped around the world to coordinates from DB
Still is far from finished, but hey, better than nothing.

**Comment by cala** [comment]
Thank you.
One question: how was calculated the mask in the query below, compared to the one that is currently in the DB, please?

``` SQL
DELETE FROM spell_proc_event WHERE entry in(14186,14190,14193,14194,14195); -- seal fate
INSERT INTO spell_proc_event VALUES
('14186', '0', '8', '9672066312', '9672066312', '9672066312', '0', '2', '0', '0', '0');
```

**Comment by killerwife** [comment]
I did more of those, but it was one of the following:
1. taken from wotlk spell.dbc where they are inside
2. took old flags and added missing spell family flags based on my voa jira bug reports and/or personal research

**Comment by cala** [comment]
Thanks.

**Comment by cala** [comment]
Closing as everything has since be ported/added to Classic DB.
