### ISSUE TITLE
BRD missing weapons fixes 

### ISSUE THREAD

**Issue by Metalica** [classicdb/database#893]
Black Rock Depths:
Snokh Blackspine:
Added missing 2h staff.
Malgen Longspear:
Added missing 2h spear.
Added missing bow.
Gorosh the dervish:
Added missing 2x 1h axes.
Korv:
Added missing shield.
Added missing 1h mace.
Rotfang:
Added missing 2x 1h daggers.
Va'jashni:
Added missing 2h staff
Volida:
Added missing 2h staff
Rezznik:
Added missing Shield.
Added missinh 1h mace.

INSERT INTO `creature_equip_template` VALUES (3019, 2226, 0, 0);
INSERT INTO `creature_equip_template` VALUES (3020, 13055, 0, 20663);
INSERT INTO `creature_equip_template` VALUES (3021, 6738, 6738, 0);
INSERT INTO `creature_equip_template` VALUES (3022, 13349, 9661, 0);
INSERT INTO `creature_equip_template` VALUES (3023, 13368, 10750, 0);
INSERT INTO `creature_equip_template` VALUES (3024, 15854, 0, 0);
INSERT INTO `creature_equip_template` VALUES (3025, 11932, 0, 0);
INSERT INTO `creature_equip_template` VALUES (3026, 17003, 17718, 0);

**Comment by Tobschinski** [comment]
No longer needed because of https://github.com/classicdb/database/commit/850362e3a5098cc5e9cb8b8823b7a1b0d4fa40af

But thank you.
