### ISSUE TITLE
Deadmines: bosses not linked

### ISSUE THREAD

**Issue by Metalica** [classicdb/database#894]
Rhahk'Zor was not linked to 2 Defias Watchman guards.

 INSERT INTO `world`.`creature_linking_template` (`entry`, `map`, `master_entry`, `flag`, `search_range`) VALUES ('1725', '36', '644', '1', '10');

Sneed's Shredder and Sneed was not linked to Goblin Woodcarver (whole room must agroo).

INSERT INTO `world`.`creature_linking_template` (`entry`, `map`, `master_entry`, `flag`, `search_range`) VALUES ('641', '36', '642', '1', '40');

INSERT INTO `world`.`creature_linking_template` (`entry`, `map`, `master_entry`, `flag`, `search_range`) VALUES ('642', '36', '641', '1', '40');

**Comment by Tobschinski** [comment]
This is correct for Rhak'Zor, afaik, he's not directly linked to both Watchman, they just assist if they are close to each other.

https://youtu.be/Y1_jBM9Jkpk?t=55
https://youtu.be/ds3IeOs1Nbk

**Comment by dagochen** [comment]
Combat Info
Rhahk'Zor provides a fairly straightforward fight. The only "trick" to this fight is the pull. Just wait til he walks farther away from the two Defias mobs, and then pull.

http://wowwiki.wikia.com/wiki/Rhahk%27Zor?oldid=337540

**Comment by Metalica** [comment]
HM.... then i got wrong info. this can be closed.
