### ISSUE TITLE
Respawn creature @bug

### ISSUE THREAD

**Issue by DescCore** [classicdb/database#895]
Hello developers classicdb, check please table creature column's spawn , all npc spawn 25 sec

**Comment by Tobschinski** [comment]
I don't have this issue.

**Comment by cala** [comment]
There was no such issue when I left two weeks ago and I could not find any change in the recent updates that could explain this. Could you confirm that clean install has this issue ?

**Comment by Tobschinski** [comment]
I checked again, this issue is on your end, reset your db.
