### ISSUE TITLE
Venture Co. Enforcer & Overseer & Boss Copperplug

### ISSUE THREAD

**Issue by impowski** [classicdb/database#898]
You need to fix drop rate of loot item 5097 in creature_loot_template. Because drop rate to this item should be 100% and in DB it's set to negative value.

**Comment by dagochen** [comment]
http://web.archive.org/web/20070105155301/http://wow.allakhazam.com/db/item.html?witem=5097
Low drop chance but comments say something different...?

**Comment by impowski** [comment]
@dagochen According to this one I guess http://db.vanillagaming.org/?item=5097

**Comment by dagochen** [comment]
Negative value in database says it is a quest drop. That should be fine I guess. They question now is: 100% or 2% or maybe something between? Some of the comments say it drops on first mob, which leads into direction of 100% chance. Others say they needed to kill about 20, which leads towards 5% or so? Any other sources on that?

**Comment by impowski** [comment]
@dagochen according to wowhead it around 6% but it was patched in 3.0.2

**Comment by Phatcat** [comment]
The thing about reading the percentage rates for quest items in particular from websites like that is you have to consider a few factors:
- Was the mob added with the quest? If not, then the percentage displayed will be slightly higher due to the period where the mob was killed with no quest drop.
- How common was it for people to stumble upon this quest mob and kill him without being on said quest? - if it is even possible to meet/kill him without being on the quest? - this is once again going to factor into the actual drop rate.

**Comment by dagochen** [comment]
Yeah thats true phatcat. But still the comments....they are not influenced by that factors and are completely different. One says it dropped from first mob, other says he needed about 20... i would guess the drop on first mob was lucky, while the other guy was very unlucky and the correct drop chance might be between ...?

I know its offtopic, but I once had a "ClassicWoWResearcher". A little program you could find old database entrys on nearly any wow database and filter by date, expansion, item creature quest ids....? If anyone has got it, please tell me where to get it^^

**Comment by Phatcat** [comment]
Also there is the consideration that blizzard may have fine-tuned (changed) some drop rates during the game's life, which makes it next to impossible for us to ever be sure.

It would sound like it going by the comments, wouldn't it?

Furthermore, looking at the level span of the mob itself; http://web.archive.org/web/20070105182651/http://wow.allakhazam.com/db/mob.html?wmob=9336 would indicate that he changed during vanilla.

This actually used to drop off of other mobs:

http://web.archive.org/web/20040825131632/http://wow.allakhazam.com/db/quest.html?wquest=896

> Retrieve the Cats Eye Emerald from one of the Venture Co. Overseers or Enforcers for Wharfmaster Dizzywig at Ratchet.

http://web.archive.org/web/20041110233551/http://wow.allakhazam.com/db/item.html?witem=5097

> Dropped By:
> The Barrens
> Venture Co. Enforcer (16 - 17)  Venture Co. Overseer (17 - 18)

Now that was 2004, let's look in 2007:

> Retrieve the Cats Eye Emerald from one of the Venture Co. Overseers or Enforcers for Wharfmaster Dizzywig at Ratchet.

How they never bothered to update the quest text properly to reflect that it now only dropped from one particular mob is beyond me

http://web.archive.org/web/20070105155301/http://wow.allakhazam.com/db/item.html?witem=5097

> 2.34% chance to drop. (6,295 in 269,391) Dropped By:
> The Barrens
> Boss Copperplug (14 - 22) 0.83% (6,649)

Let's go back a bit and check in 2005:

http://web.archive.org/web/20050219233349/http://wow.allakhazam.com/db/item.html?witem=5097

> Dropped By:
> The Barrens
> Boss Copperplug (19) 0.65% (7)  Venture Co. Enforcer (16 - 17) 2.26% (855)
> Venture Co. Overseer (17 - 18) 2.24% (596)

Looking at the quest text which reads:

"Word from the river dock here is that one of the miners in the Venture Company's Boulder Lode mine just northeast of here discovered an emerald the size of your fist."

it would very much indicate that the drop chance is not 100% on this, no, but rather low (5 - 10% perhaps)

All we can really do is make educated guesses...

**Comment by Phatcat** [comment]
The comments are influenced by the human factor, though, a factor far worse.

You can never be entirely sure for someone not to be exaggeraging, to be trolling, to be writing out of false memory (usually people didn't sit on forum boards while playing the game, so almost all comments are written post-fact, sometimes days or weeks after experiencing the thing being commented on) or simply to be outright lying. I am not saying comments don't contain useful information or that bogus comments can't be spotted, or that good comments can't be used as points of reference, but all comments always have to be taken with a grain of salt. All info has to, even sniffs.
