### ISSUE TITLE
Bonus armor items

### ISSUE THREAD

**Issue by killerwife** [classicdb/database#900]
Recently we discovered items that have bonus armor account for bonus armor twice, because Armor column contains not only BASE_ARMOR but also BONUS_ARMOR. Fix is following:

UPDATE item_template SET armor= armor-ArmorDamageModifier WHERE ArmorDamageModifier>0 AND armor >= ArmorDamageModifier;
(the where are failsaves)

I would advise you to check your db. Such item includes Blackskull shield. @cala

**Comment by cala** [comment]
Thank you for sharing this info :+1: . This is not needed for Classic though as there is no `ArmorDamageModifier` column in the `item_template` table.

**Comment by killerwife** [comment]
I would just like to let you know, that it was correct and core was wrong. I forgot to clean my cache and now have to implement it properly by removing it from core instead. My bad :/
