### ISSUE TITLE
Firebrand Invoker (Entry 9262)

### ISSUE THREAD

**Issue by Phatcat** [classicdb/database#903]
~~Firebrand Invokers should NOT cast a fire AoE in vanilla (at least not out of combat); that they currently do this on cmangos makes the soloing of smolderweb as a druid impossible.~~

https://www.youtube.com/watch?v=vr8bA68_9Z8
0:47
The invokers that are stood around (and the other orcs as well maybe) should be doing /talk animation now and then, like they're having a conversation with the others.
Edit: watching other videos, I havn't caught on to any other orc or even firebrand invoker for that matter, who does anything besides either standing still or wandering around; it could seem that that one fire invoker is the only one who should do /talk animation (and he should, every video from late vanilla shows this)

**Comment by Phatcat** [comment]
Also on cmangos all the mobs are just stood around staticly, while a few of them, not many, but a few, should 'wander' between groups, creating a bit of 'life' to the scene. (also forces druids/rogues who are stealthing through to step up their game)

**Comment by Tobschinski** [comment]
https://github.com/ACID-Scripts/Classic/commit/3e2a6bc51eb2c909b083b35a431bdd97c7995687

**Comment by Phatcat** [comment]
okay, I havn't updated ACID in a bit I see.. :+1:

**Comment by cala** [comment]
Closed by https://github.com/cmangos/classic-db/commit/f18f02e22b3600459be72170996e717c00f4a643
