### ISSUE TITLE
Call Guards on Hostile LOS

### ISSUE THREAD

**Issue by dagochen** [classicdb/database#912]
Hey,

i am not sure about this, so this issue is more for research than to get it fixed. Did npcs in the main cities like stormwind summon/call guards if they saw hostile players in LOS? Currently this is not supported in the db or core, but i found something like that in an old database. So my question is: Was it removed from classicdb? And if, on purpose or by accident and based on what sources? How did NPCs behave in classic?
Did they call/summon guards?

I was told to poke @cala with this.

Hope you can help me,
greets

**Comment by cala** [comment]
The answer is yes and no. The scripts are supposed to be here in ACID, but they are wrong and possibly not working. I have on my list to check and fix all of them. This is the same issue that one reported in https://github.com/classicdb/database/issues/860 so I'm closing this one.
Thank you for reporting. :+1:

**Comment by dagochen** [comment]
I couldn't find the scripts at all to be honest^^ Maybe I searched in the wrong place?
