### ISSUE TITLE
InstallFullDB.sh error: mangos_spell_chain update applied twice

### ISSUE THREAD

**Issue by katz1** [classicdb/database#913]
If I use the InstallFullDB script with the core update path set, then the script fails with:
```
Append core update z2687_01_mangos_spell_chain.sql to database mangos
ERROR 1054 (42S22) at line 1: Unknown column 'required_z2685_01_mangos_event_linkedto' in 'db_version'
```

The db_version column is already set to 'required_z2685_01_mangos_event_linkedto' by the update in classicdb: 1470_z2687_01_mangos_spell_chain.sql
Removing mangos-classic\sql\updates\mangos\z2687_01_mangos_spell_chain.sql will make the script work for me.

I already mentioned this issue in a comment some time ago (https://github.com/cmangos/mangos-classic/commit/fe8daa7e7aeb63642055958c9a96ad5a39e4200a), but it might be a problem on my end if nobody reported it ever since?

**Comment by Phatcat** [comment]
Hey man. you are not on the right db anymore, we moved repos about a month ago; https://github.com/cmangos/classic-db
All 3 main databases are now a part of the cmangos organization. ACID has also been merged with the database projects.

Running the full db from the new rpo should run you no trouble =)

**Comment by katz1** [comment]
Ah, and I was starting to wonder why is this repo so inactive.
Thanks :)
