### ISSUE TITLE
Quest issue: Freedom for All Creatures

### ISSUE THREAD

**Issue by Digicode** [classicdb/database#914]
Looking in src/scripts/kalimdor/feralala.cpp I do not see an entry for this quest or the relevant NPC.
When starting the quest, the timer does begin, but the NPC you are supposed to escort (Kindal Moonweaver) does not move.

Interacting with this NPC again will trigger a quest completion dialogue, but nothing actually happens when you hit the 'complete quest' button.

trigger data from server log:

WORLD: Received opcode CMSG_QUESTGIVER_CHOOSE_REWARD - for Player Tester (Guid:
 1) to Creature (Entry: 7956 Guid: 50005), quest = 2969, reward = 0
WORLD: Sent SMSG_QUESTGIVER_OFFER_REWARD NPCGuid = Creature (Entry: 7956 Guid: 5
0005), questid = 2969

**Comment by cala** [comment]
Greetings,

Thank you for this report. This issue has already been reported [here](https://github.com/classicdb/database/issues/717). It needs to be scripted somehow.

By the way, the development of Classic DB has been moved to http://github.com/cmangos/classic-db/
I'm closing this issue then. Thanks again.
