### ISSUE TITLE
"Lilith the Lithe" npc gives 2 same quests

### ISSUE THREAD

**Issue by RichardGe** [classicdb/database#915]
Lilith the Lithe (npc 11191) gives 2 same quests: 5305 & 8869.
those quests have the same title : "Sweet Serenity".
the only difference is that 1 is for blacksmith only, and the other is for everyone.
I think we should only keep 1.
db.vanillagaming.org says that the good one is 5305 and the 8869 doesn't exist.

**Comment by Lumber-Jack-2** [comment]
only http://wotlk.openwow.com/quest=5305 should be available to my mind
