### ISSUE TITLE
Quest - The People's Militia

### ISSUE THREAD

**Issue by M2us** [classicdb/database#917]
Quest - The People's Militia id 14

Objectives:
kill 15 Defias Highwaymen

but mob name is Defias Highwayman
^___^

**Comment by Lumber-Jack-2** [comment]
men is the plural of man

1 man, but 15 men

https://www.quora.com/What-is-difference-between-men-and-man

**Comment by cala** [comment]
I agree with Rushor: the quest description indeed use the plural version of the NPC name.
http://www.wowhead.com/quest=14/the-peoples-militia
Thank both of you.
