### ISSUE TITLE
Outdoors chests are not in pools

### ISSUE THREAD

**Issue by cala** [classicdb/database#93]
The chests in the outdoor areas should be in pools, each one containing 3 to 4 chests.

**Comment by Neotmiren** [comment]
Are you sure about pools of chests? What is the source of such information? (I think it was difficult
to surely test this in original Classic with lots of players looting chests). And with all existing chest
gameobjects in DB I actually do not rememeber places with "too many chests in one area" what could
make impression of missing pooling. Possibly if there were more chest gameobjects, pooling could
be reasonable.

**Comment by cala** [comment]
Closed: no longer relevant since the update of chest respawn times a few months ago.
